### ISSUE TITLE
External Avatars  javascript Can not resize proportionally

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#1050]
hi,

select "Resize with JavaScript" set avatar size 100x100 

problem, SMF 2.1: http://s17.postimg.org/in7pg35jj/smf21_avatar.png

no problem, SMF 2.0.6: http://s28.postimg.org/tvotgctgt/smf206_avatar.png

**Comment by Arantor** [comment]
Except that's how the code works normally anyway. It starts out by forcing those values on the server because the server doesn't know how big it is, and then resizes on the client once the image has been loaded (this is how SMF has done it for a decade)

That would suggest you have an error in the JavaScript on your page causing it to not work. Check for JS errors.

**Comment by Arantor** [comment]
Can you provide a link to your test site? (I can't debug this without more information...)

**Comment by gevv** [comment]
sorry :(  localhost wamp server

**Comment by Arantor** [comment]
In which case can you check for JavaScript errors please?

**Comment by gevv** [comment]
I tried it again no problem (restart wamp server, clean cache)
