### ISSUE TITLE
blank message name?

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1066]
http://www.simplemachines.org/community/index.php?action=profile;area=showposts;u=83023

this user has somehow created 2 messages without text in the subject line. this means that the subject link does not show up in the message. should we not allow blank text like this in the subject?

the source shows

`<a href="http://www.simplemachines.org/community/index.php?topic=201161.msg3413450#msg3413450"> </a>
<a href="http://www.simplemachines.org/community/index.php?topic=455983.msg3648216#msg3648216"> </a>`

but when viewing the post you cant see the link at all

**Comment by LiroyvH** [comment]
This was handled, but apparently not fixed :P, on the community as well:
http://www.simplemachines.org/community/index.php?topic=400012.0

Quoting Arantor:
"What has happened is that the subject has at some point been replaced with a space encoded as a numeric entity ( )

IIRC this would not be caught by the check made in Post.php against the subject being empty since the trim() operation would not be done on entities. I can't remember what processing is done prior to that trim(), though, as there is a htmlspecialchars() or $smcFunc['htmlspecialchars'] call. I don't have access to the source right now to view, but the order of operations, and the details of them, may be important."

**Comment by Arantor** [comment]
And the issues mentioned there are still, IIRC, an issue with respect to quick reply vs post form handling of entities.

**Comment by AngelinaBelle** [comment]
Is there still an issue with spaces being converted to entities that are not trimmed, so the check
 For blank subject line doesn't realize there are no non-white space characters in the subject?
