### ISSUE TITLE
2005 end date on subscriptions

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1167]
This is one that has been kicking around but never properly investigated.

"Since then I've gotten three one-year subscriptions and the End Date and Time for each one has automatically been set to December 31, 2005. (Yes, you read that date correctly!) Bug?"

And similar such messages - where the end date is always 2005. I've never been able to reproduce it myself but it firmly needs investigating.

**Comment by igirisjin** [comment]
I have mentioned this several times on SMF and never had a successful subscription set up (all 2005) in the last 3 year (with about 250 subscriptions a year). A few pending ones but not many recently.
Krash on SMF(action=profile;u=271166) had a look on my site and tested it with paypal and came to the conclusion that my settings were ok but for some reason the callback wasn't working. I never got a reply from Paypal to say if the call back was being blocked, and never got a proper reply from Bluehost either. Its ok saying it can't be reproduced but most of us are using cheap hosting rather than our own servers.
Just my last cents worth on this - hope it gets sorted.
Maybe there should be some log for this to confirm the call back happened or not.
Surely SMF can afford a months hosting with a few of the big companies to test (reproduce) this.

**Comment by Arantor** [comment]
Thing is I don't get why it's giving you an end date of 2005... the only place I can find 2005 in the code is during manual setup of a subscription... I'd expect pending if the IPN couldn't reach your site, but not the 2005 thing.

**Comment by Ant59** [comment]
Managed to reproduce the bug. Having trouble finding it's source though. I can tell that $endtime is getting set to 0, since it's shown as 0 in the database. For some reason though, it doesn't seem that subscriptions.php is even calling addSubscription(), because it refuses to throw an error even if I drastically ruin the syntax of the ManagePaid.php. I cannot work out the link here.

**Comment by Ant59** [comment]
The reason it displays as 2005 (and not 1970) is because the template only displays the years from 2005 to 2030:

```
for ($year = 2005; $year <= 2030; $year++)
```

**Comment by Ant59** [comment]
Seems that the PayPal subscription class cannot handle the following IPN response:

```
    [txn_type] => subscr_signup
    [subscr_id] => ...
    [last_name] => Account
    [residence_country] => UK
    [mc_currency] => GBP
    [item_name] => Test Subscription
    [business] => ...
    [recurring] => 1
    [verify_sign] => ...
    [payer_status] => verified
    [test_ipn] => 1
    [payer_email] => ...
    [first_name] => Test
    [receiver_email] => ...
    [payer_id] => ...
    [reattempt] => 1
    [item_number] => 1+2
    [subscr_date] => 01:39:05 Apr 29, 2014 PDT
    [charset] => windows-1252
    [notify_version] => 3.8
    [period3] => 1 M
    [mc_amount3] => 10.00
    [ipn_track_id] => ...

```

(private info redacted with '...')

PayPal sends that initial response when producing a recurring subscription. Without knowing how SMF wants this to function, I cannot progress. Can one of the project maintainers please shine some light on this issue?

**Comment by igirisjin** [comment]
It was suggested before that this was a server related problem but I have recently changed host and still 100% failure with subscriptions (all 2005 finished). Bluehost to Westhost (supposed to be better). I wonder if the SMF options could affect this. My only guess (as I'm not a coder) is something maybe related to SMF server time and offset time settings - could this affect how it handles the time?

**Comment by Spuds** [comment]
> PayPal sends that initial response when producing a recurring subscription. Without knowing how SMF wants this to function, I cannot progress. Can one of the project maintainers please shine some light on this issue?

Not a maintainer, but to my knowledge the [txn_type] => subscr_signup is not supposed to be processed .

The IPN response of subscr_signup is sent when a member FIRST signs up for a subscription, and should only be sent when the payment is successful or does not fail.  However the one to be processed is  [txn_type] => subscr_payment as that is the payment verification response sent for EVERY verified payment.

For a first subscription both of those responses will be sent, in no particular order, and in quick succession.  Now one could trust that the IPN documentation is correct (cough) and add the ability to process subscr_signup to the isSubscription() method but its really not the transaction type that says its a true verified payment.

**Comment by Arantor** [comment]
(Also not a maintainer) The above is what subscriptions.php seems to suggest:

```
    // subscr_signup: This IPN response (txn_type) is sent only the first time the user signs up for a subscription.
    // It then does not fire in any event later. This response is received somewhere before or after the first payment of
    // subscription is received (txn_type=subscr_payment) which is what we do process
```

I know I fixed up most of the other remaining txn_types to be at least recognised even if there is no specific action to be carried out (e.g. subscr_eot requires no action from SMF's perspective but it _is_ recognised), but subscr_signup seems like it shouldn't actually be processed. I had hoped that Krash had played with it by now and seen if the updates had resolved most of the outstanding issues...

Note that #1169 is still open in the event that subscr_signup should be handled...

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
