### ISSUE TITLE
Custom Profile Field Checkbox 'No Default' Option

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1176]
## **Old Bug Report**

When you create a radio button custom profile field it requires that you select one of the options as the default value, there should be a 'No Default' option instead of having to set one of the selectable options as the default value.

**Comment by Oldiesmann** [comment]
Two things...

First, I've never seen an example of having radio buttons where you don't have one in a group selected. Secondly, once a radio button in the group is selected, it is not possible to un-select it (e.g. set things back to "no button in the group is selected"). Also, the HTML5 spec says that having a group of radio buttons with none selected by default is "poor user interface" (http://www.w3.org/html/wg/drafts/html/CR/forms.html#concept-input-required).

**Comment by Arantor** [comment]
Except that the underlying point is still valid: you cannot create a radio box or a select box where no default value is given, forcing the user to select something.

**Comment by Xarcell** [comment]
Not a bug.

**Comment by Arantor** [comment]
Valid issue.

**Comment by Xarcell** [comment]
I must mis-understand the problem then.

**Comment by Oldiesmann** [comment]
I'm lost as well. Why is it a problem to force people to select something for a radio button or select box?

**Comment by Arantor** [comment]
The problem is you can't. Right now there is no way when creating a custom field to have a 'no default' option where the users of the site who are filling in a custom field have to explicitly make a choice.

Let me give you an illustrated example, maybe that will help. Create a field, called SMF version, for representing what version of SMF you're using. You include everything from SMF 1.0 through to 2.1 Alpha. You want users to fill that in. Under the current setup it is not possible to have a field that forces a user to pick one. You have to pick a default value for it, which means either you create an extra value 'I don't know/not specified' or you put in a default of any one version on the list. Neither of these is ideal because neither represents the real state of play.

**Comment by Xarcell** [comment]
Ok I understand now. I always assumed when creating radio buttons a default value had to always be selected. This is not the case? So the goal for SMF would be to allow a "No default" option for radio buttons, so that the user will be forced to select a value to proceed, rather than just letting the user ignore it and the admin created default value always getting selected(eg: I don't know).

**Comment by PhuriousGeorge** [comment]
What about utilizing a warning fader/in-page red box (similar to the PM not for support warning) whenever the 'I don't know/not specified' field is selected? That way, we let them know we're not pleased with their selection, but don't fall into the 'poor practice' zone.

Or, possibly better - what about swapping the radio buttons for a drop-down? This is generally where I see multiple-choice, required answers to be fulfilled.

**Comment by Arantor** [comment]
The point is you STILL can't specify that either with the current setup...

**Comment by Arantor** [comment]
There is also a side consequence that currently required fields can be bypassed as per http://www.simplemachines.org/community/index.php?topic=487295.0

**Comment by MissAllSunday** [comment]
The more I look into this the more I don't see the point on adding it, sure a problem exists but whoever uses the combination of required/choices has a design flaw or could solve their issues by having a default value. 

Adding a whole new parameter to an already convulsive feature just to satisfy a few isolated cases doesn't seem like enough reason for me so unless an OS paladin knight with some actual code comes here with a PR, this won't be solved.

Edit, oh, and before the usual ranters come here and rant about this, take a look at yourselves and all the real issues you didn't fix, thank you.
