### ISSUE TITLE
Calendar Events Missing Additonal Options

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1178]
## **Old Bug Report**

Description below taken from original bug report.

This bug applys to non-admin users with "additional options" permssions such as announce topics or upload attachments. I am running 1.1.10 and there are several boards configured with different permssions.

Creating a event/topic by following the link from the calendar page results in the user only having the additional options "return to this topic" and "Don't use smileys".

What I think should happen is whatever permissions the user has on the board given in the option "Default board to post events in: " should be applied.

This is the link from the calendar with missing permissions:

```
index.php?action=calendar;sa=post;month=12;year=2009
```

If I change the link manually it has correct permissions:

```
index.php?action=calendar;sa=post;month=12;year=2009;board=7
```

This is the link from "link to calendar" button with correct permissions:

```
index.php?action=post;calendar;msg=87;topic=57.0
```

Option discussed to resolve was, to use a Javascript to determine the selected board and show/hide the attachments part depending if the user is allowed to post attachments in the selected board and ignore the attachments if the user doesn't have the permission to post attachments in the selected board.

**Comment by Sesquipedalian** [comment]
> Option discussed to resolve was, to use a Javascript to determine the selected board and show/hide the attachments part depending if the user is allowed to post attachments in the selected board and ignore the attachments if the user doesn't have the permission to post attachments in the selected board.

The basic idea is good, but it might be trickier to implement than expected. Turning off and hiding checkboxes is easy enough, so handling the basic post options is not a problem. But dealing with the attachments will be much more complicated.

To illustrate, consider this scenario:

1. The user has permission to create events and add attachments in board 1
2. The user has permission to create events, but not to add attachments, in board 2
3. The user selects board 1 as the destination board in which to post her event. Since she can add attachments in board 1, SMF allows her to add some attachments to the event's post.
4. The user decides to change the destination board for the event to board 2...

Now the question is, what should we do with the attachments the user already uploaded? Should we delete her attachments immediately? Should we hide the attachments interface from her but keep the attachments themselves in case she changes her mind? If we do the latter, how and when do we make sure that her attachments do not get posted on board 2?

Since the attachments system is pretty complex, I'd like to hear what @MissAllSunday thinks about this.

**Comment by Sesquipedalian** [comment]
At this point, here's the situation with this:

Suppose that Joe is a non-admin user who has permission to create events and who has permission to post attachments in Board 1 but not in Board 2.

# If the admin option to allow events that are not attached to posts is enabled

1) Joe clicks the "Post Event" button on the calendar, enters the event info, and then activates the option to post the event in a board and selects Board 1. 
2) Joe clicks the post button and is redirected to the post authoring page for Board 1. 
3) Since Joe has permission to add attachments in Board 1, attachment options are shown to him at the bottom of the posting page. But he is _also_  still shown the option to change which board to create the post in. 
4) Joe adds an attachment, but then selects Board 2 in the "Post in" select menu before clicking the "Post" button.
5) A new topic is created in Board 2 for Joe's event **with the attachment**.

Clearly, we need to do a final permissions check (probably in `Post2()`) to ensure that the post can't be made if it has attachments when the user doesn't have permission to post attachments.

# If the admin option to allow events that are not attached to posts is disabled

1) Joe clicks the "Post Event" button on the calendar as before, and is taken to the post authoring page where he must enter the topic and event info, including selecting the board in which to post the topic.
2) Joe is not given any option to add attachments, even though he has permission to add them on at least one of the boards available in the "Post in" select menu.

In this case, we probably should show Joe the interface to upload some attachments, because he does have permission to do so for at least some of the available boards.

# What to do?

1) On the post authoring page, if the "Post in" select menu is shown in the event options section, we should check Joe's permissions for each of the listed boards. If he has permission to upload attachments on any of those boards, we should show him the attachment upload UI.
2) Whenever a post is made with attachments, we should always do a final permissions check before creating the topic to make sure Joe is allowed to post attachments on the board in question. If not, we should refuse to make the post and instead send him back to the post authoring page with an error message.

**Comment by frandominguezl** [comment]
Any updates on this, @Sesquipedalian ? :P

**Comment by Sesquipedalian** [comment]
None to speak of at the moment. :)

**Comment by Sesquipedalian** [comment]
Upon investigation, this has turned out to be two distinct bugs. So I am going to close this and create separate issues (and PRs) for each bug.
