### ISSUE TITLE
BBCode parsing has trouble with urls containing braces

### ISSUE THREAD

**Issue by shmax** [SimpleMachines/SMF#1187]
The following url, when pasted into a SMF forum post, will hopelessly confuse the bbcode parser (this url was taken from the address bar while browsing around in Firefox, which has the unusual behavior of decoding urls):

http://www.example.com/products?q[filters][toyline]=3533

I don't understand why this should be an issue, as it does not have any valid bbcode markup in it (no closing tags). This is using SMF 2.0.2.

**Comment by Arantor** [comment]
Of course it's an issue. You can have self-closed tags in SMF, for example the [br] or [hr] tags.

But consider the complexity of what this is getting into - this is really a shortcut to:

```
[url=http://www.example.com/products?q[filters][toyline]=3533]http://www.example.com/products?q[filters][toyline]=3533[/url]
```

Which is now bbcode within bbcode, and it's going to be aiming for the earliest closing brace by definition. You're probably thinking of other systems that explicitly rely on closing tags for a regular expression, a system SMF moved away from after it was proven to be a vulnerability vector, of the ReDoS kind where you create regular expressions that force the parser to backtrace repeatedly until you exceed the backtrack limit causing execution to stop - do that in a few posts and suddenly you can have a miniature denial of service.

(The fact you're using a version that's 4 security patches behind is, on this occasion, not a relevant factor)

EDIT: Other systems use quotes to get around this, but we can't exactly do that without breaking links and whatnot in existing posts.

**Comment by shmax** [comment]
Fair enough, but given that SMF knows what the valid bbcode tags are ([b],[img],[url], and such, as well as custom ones), why does it get so easily fooled by "tags" that really aren't? Are there custom self-closed tags? It seems like the parsing could be bolstered a bit to make some better guesses about what are meant to be tags, and what aren't.

**Comment by Arantor** [comment]
Except that doing so would 1) slow down the slowest part of SMF even more and 2) potentially create a vulnerability in itself.

If it were to test for all known tags, every time this comes up, that's fine until you start dealing with nested tags. It would not be hard to create a case where it would end up hitting the time limits on most servers because it's wound itself so deeply in trying to match things (which is really why it was rewritten not to use regular expressions in the first place)

The only really safe way I can see of doing this is rewriting the tag on post saving, to convert it into a URL encoded form in the expanded type I mentioned - which would solve it but would also screw it up for editing purposes. Or we do the quotes thing, and have the upgrader rewrite potentially every single post (which, given that we have installations into the multi-million posts to support, would be a nightmare)

Interestingly enough I did try this same experiment with other forum systems, with some interesting results, especially the ones that have WYSIWYG editors to play with. (Also, I am not sure how the WYSIWYG editor in 2.1 will deal with this; it's a new editor, not the one 2.0 had)

**Comment by shmax** [comment]
Hmm. Well, in this case, my extra tags occur inside a string that would pass a regex for a url. Perhaps strings that validate as urls could be excluded from bbcode parsing.

**Comment by shmax** [comment]
By the way, what were your findings with the other forum systems? Did any of them manage to evade the brace trap?

**Comment by Arantor** [comment]
They have some interesting behaviour. A couple of them broke the URL at the opening brace, figuring it wasn't even a valid URL character. A couple of them decided to silently convert them to URL encoded (which made editing fun) but XenForo was the most weird. If I posted it in the rich editor bare, it worked. If I posted it with bbcode, it didn't parse the bbcode but left the link present (which appears to be a Redactor bug, though I didn't try it with the very current XF version so that might be a related but fixed bug)

As for strings that validate as URLs... where? Outside bbcode? Doesn't happen - because the bare URLs get converted to url bbcode before anything interesting happens. Inside bbcode? Then the link would be broken.

Here's the fundamental problem: a character that is necessary for bbcode is inside the bbcode. It'd be like if you dealt with:

```
<a href="domain.com/<something>">
```

because you have < and > inside the HTML... where is it supposed to stop? (And before we get into the 'it's quoted' argument, HTML doesn't _require_ the quotes. Only XHTML requires them, HTML4 and SGML before it do not, HTML5 does not either but strongly recommends it last I saw that part of the spec)

EDIT: Github does not like my invalid HTML example. Not just SMF!

**Comment by shmax** [comment]
I have a fix I'd like to test. Is there a unit test for this function, or anything like that?

**Comment by Arantor** [comment]
There were unit tests, years ago, don't think they have worked in years either (not that they've ever been published anywhere anyway)

**Comment by Arantor** [comment]
Also ref: http://www.simplemachines.org/community/index.php?topic=381285.0

**Comment by shmax** [comment]
Aha. So I put my fix on hold to work on some other things; I came to the realization that even if I got it working perfectly (and managed to convince you folks to merge the change) this is probably going to be an issue for all the other forum packages out there. I think I'm going to research changing my url format (to use dots instead of braces, for example), before I continue arguing with parse_bbc.
