### ISSUE TITLE
GM allowed manage board, can see disallowed board in manageboard

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1196]
## *\* Old Bug Report **

Original Bug Report:

In group permission I allowed Global Moderator to manage boards.

In my forum there is one board with Allowed Groups all unticked, which means every group including Global Moderator is not allowed to see this board.

When a GM goes to manageboard, he can see that disallowed board listed. Which means he can click modify and tick Global Moderator in Allowed Groups. After which he can enter the disallowed board.

---

If a board's Allowed Groups has disallowed a Membergroup, even when that group is allowed to manage board in Membergroup permission, it should not see this board in manageboard list.

**Comment by Arantor** [comment]
Perhaps we could disable the tickboxes for those groups that it would not be applicable for?

**Comment by ghost** [comment]
Should they be disabled or hidden the groups that the GM doesn't have access to as they could start asking why can't I access this and that board etc.?

**Comment by Arantor** [comment]
No, that's not what I'm saying. From the edit-board page, you get a list of groups that can access that board which is how you control access. But for the groups that have manage-board permissions, there's no point making it an option to configure those boards because their permissions override.

For example, let's say Global Moderator has Manage Boards. There is no point offering the tickbox to the GM group for access to a board because their management permission overrides that. So we might as well just display it as a disabled-but-checked tickbox to indicate that access is already given and not able to be overridden.

**Comment by Arantor** [comment]
OK, so I think I'm OK with how this is now. We'll reopen it if a message does need to be added.
