### ISSUE TITLE
Option to allow admins to use IPv4 instead of forcing IPv6 use

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1271]
Just a suggestion to add an internal option to allow admins to use IPv4 addresses instead of IPv6 if there host is setup to use IPv6 and the forum admin has no control over it, inet_ntop() would be one way to implement it.

**Comment by Arantor** [comment]
For what benefit, exactly? If you're supporting IPv6 you need to do it everywhere, and all of IPv4 is already contained within a subset of IPv6 meaning that it's still, ultimately, IPv6 anyway.

Everything after that is just display, and if it's already clearly inside IPv4's subset, display it as IPv4 and if you input an IP address, check which format it's in before attaching it elsewhere.

**Comment by Oldiesmann** [comment]
There's also the very real issue of what happens when, at some point in the future, someone visits the forum with an IPv6 address which cannot be represented in IPv4 format. According to Wikipedia, there are approximately 4.3x10<sup>9</sup> IPv4 addresses, compared with 3.8x10<sup>38</sup> IPv6 addresses. If you force the use of IPv4, then you will have problems when IPv6 becomes the standard and IPv4 is phased out. This isn't likely to happen in the near future, but we have to be ready, which is why we're implementing IPv6 support now rather than waiting for it to be necessary.

**Comment by Arantor** [comment]
There have already been instances of spambots attacking from IPv6 addresses knowing full well their targets cannot block them with IP bans.

I still see no reason to turn off IPv6 in favour of IPv4. But if I'm missing something please do tell me - but as it stands I cannot see why we would.
