### ISSUE TITLE
Post Preview on MessageIndex Settings

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1283]
I find this bit odd, since we have;
- Show post previews on the message index 
- When using post previews, show the text of the first post

those settings at Current Theme, and this (which also the most important and the master setting for this feature is under Post Settings); 
- Maximum length of last/first post preview (0 to disable)

My suggestion is remove the "Show post previews on the message index" setting and move "Maximum length of last/first post preview (0 to disable)" to Current Theme. :paw_prints:

**Comment by Oldiesmann** [comment]
I think max length should remain a global setting. The only reason I can see the first two being theme settings is that there's always a possibility some themes might not support it, but it would definitely make more sense to have them all in one place.

**Comment by XinYenFon** [comment]
But if you don't enable it from Current Theme there is no point for other setting(s)

**Comment by Oldiesmann** [comment]
I'm assuming the reason it's in Current Theme is because there's a possibility that a given theme might not support that feature (and, technically, it is a theme-related feature), but there's also the fact that some users might not want that feature I guess. I'd much rather just have everything in one area as a global setting though (such as Board Settings, which makes a bit more sense than Post Settings).
