### ISSUE TITLE
Board index / birthdays showing coloured names

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1291]
We have the online list which shows coloured names, and we have the calendar showing birthdays in the same area, except they don't have colours.

I think it should display the colours of membergroup names there, use bold for buddies rather than 'today's birthdays' and instead have a small birthday cake icon for today's birthdays.

**Comment by Xarcell** [comment]
I can't say I'm fond of using various colors because they tend to conflict with a theme design. 

Really, a class should be added to the user's names and not inline styles, so that designer's can define it within the index.css; which makes good in custom themes.

I agree with using Bold for buddies.

**Comment by Arantor** [comment]
Well, using bold for buddies will bring it into line with Who's Online.

As for the colours thing, does the admin's right to pick colours override a designer's choice? Because that's what we're talking about here. And last I checked there's no way to get colours set in the database by the admin into the index.css file without some kind of preparser.

**Comment by Xarcell** [comment]
I was merely suggesting instead of the admin user source looking like this:

"a href="http://localhost/smf-2/index.php?action=profile;u=1" style="color: #FF0000;">Xarcell</a"

Why not make it look like this: 

a href="http://localhost/smf-2/index.php?action=profile;u=1" class="online-admin">Xarcell</a

This would eliminate the admin setting: "Admin > Membergroups > Edit Membergroups > Color in online list".

By doing it this way, you can have a nicer color variations determined by the designer, instead of using a set color across all themes which sometimes stick out like a sore thumb.

Only a suggestion.

**Comment by Arantor** [comment]
Yes, I realise that. That is a popular setting, a lot of people like it and want us to expand - not curtail - it.

**Comment by Xarcell** [comment]
It's your decision Arantor, doesn't really matter to me either way.

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
