### ISSUE TITLE
postgresql 9.1 modified_reason error , Database Error: ERROR:  null value in column "modified_reason" violates not-null constraint

### ISSUE THREAD

**Issue by tinoest** [SimpleMachines/SMF#1304]
I just needed to amend the db to have the following as default ''; This was from a clean install so I'm guessing its missing in the install.sql files.

**Comment by Arantor** [comment]
Is this happening during the installer itself or afterwards?

**Comment by Oldiesmann** [comment]
I didn't realize PostgreSQL allowed default values for varchar columns (MySQL doesn't). Where are you getting this error?

**Comment by Arantor** [comment]
Eh? MySQL is fine with default values on varchar, it's only the large block objects (text, blob and so on), even on the smf_messages table (where this is), there is a default explicitly set for icon (which is a varchar)...

I'm thinking this needs to be changed in the installer and upgrader because the other code expects to be able to insert a null value there and get the table default.

**Comment by Oldiesmann** [comment]
For some reason I was thinking MySQL didn't, since many varchar columns in SMF don't have default values specified in Postgres, even when they do in MySQL (admin_info_files for example).
