### ISSUE TITLE
Merge Watch this topic & Watch

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1320]
Hai,

Today i saw new enchantment for the topic systematic and as far as i can see there is an upcoming notify (aka user-tagging) system coming and i think we should take GitHub model in this like they use in repos (Not Watching / Watching / ...)

Our model can be;
- Not Watching (You get notification only when you mentioned)
- Watching without mails (You get notification only via Alerts area)
- Watching with mails (You get notifications via Alerts area & mails)
- Ignoring (You'll not get any mail or alert even when you mentioned)

**Comment by Oldiesmann** [comment]
The mention thing is already set up that way (or at least will be if/when it gets finished). I would like to see some sort of merger between "unwatched topics" and what was previously called notifications since "notify" has been changed to "Watch this topic" - we now have two different things with almost identical descriptions which will really confuse people.

**Comment by Oldiesmann** [comment]
After thinking this over more I think it's better to just rename "watched topics" (again) to "ignored topics". I think it would be too confusing to try and merge the features.

**Comment by ChainyEO** [comment]
So, "Watch topic" = the old "Notify" (receive notification by email)?

"Ignore topic" would mean "Exclude the topic from Unread Topics"? 

EDIT: I deleted my comments about "Ignore Boards" as I think I misunderstood it...

**Comment by Oldiesmann** [comment]
Yeah, that's how it would work.

**Comment by AngelinaBelle** [comment]
-- notify button has disappeared, so txt ends to change at bottom of watched topics and watchd boards in profile
-- watch and follow are used interchangeably in txt-- should pick one term for watching/following topics or boards

Need to create one interface that covers option to "stop telling me about replies to my posts" and "watch/I watch this topic", because we cannot have
![image](https://cloud.githubusercontent.com/assets/3267025/3341970/9895ed78-f88d-11e3-95dc-89991ead7006.jpg)

**Comment by XinYenFon** [comment]
Well if anyone wonders how it needs to be done, Arantor already did it :P

http://i.imgur.com/nT9IRSF.jpg (I hope he don't mind me putting this here).

**Comment by XinYenFon** [comment]
why you closed this? I'm bit confused.

**Comment by live627** [comment]
the duplicate button is already gone, which is what this issue is about, no?

**Comment by XinYenFon** [comment]
nope... and this has nothing with Alerts :)

**Comment by Dragooon** [comment]
This needs to be fixed before beta 1, it's way too confusing.

**Comment by XinYenFon** [comment]
Confusing in which way, you need to remove all settings related to both feature (because you don't need them anymore), and remove all user side settings as well. After doing that little clean-up :P;
- Ignore (Disregard/Ignore) will be the one option, even you get mention in that topic you don't get notified (via PM or Alerts or Mail)
- Not Watching (Default), you'll get notified but only if you get mentioned.
- Watching, you'll get notified if you get mentioned or new post made under that topic.
