### ISSUE TITLE
Negative years old

### ISSUE THREAD

**Issue by mcblaber** [SimpleMachines/SMF#1322]
Versions Affected: SMF2.1 / SMF2.0

For some odd reason you are able to set your birthday in the future.
![screen shot 2014-01-28 at 9 53 35 pm](https://f.cloud.github.com/assets/3847907/2026360/a517ccbe-8890-11e3-96a7-71b2b216cf1f.png)

 We should throw some kind of error if you input an unrealistic birthdate.

**Comment by matthew-kerle** [comment]
Or ideally the birthdate field would be select boxes, like Intuitive Age.

**Comment by mcblaber** [comment]
Even better.

**Comment by Arantor** [comment]
Meh.

**Comment by illori** [comment]
i dont really see it as an issue... some people like to feel a few thousand years older then they are 

if the admin does not like an age a person put it, up to them to get it fixed.

**Comment by Oldiesmann** [comment]
I don't see much of an issue with minimal date validation (making sure that the birthday is not in the future at least, and possibly making sure they're not younger than the minimum age if registration is set to reject people younger than a set age), but select boxes are a pain because they limit you to a specific range of years, and we'd also have to deal with the "year is optional" thing (SMF allows you to enter "0004" as the year if you don't want the forum displaying your exact age).

**Comment by matthew-kerle** [comment]
That's why you add an option for not wanting to pick if something is optional. And really? Populating the years is easy.

**Comment by Xarcell** [comment]
You could just make it so that if date is equal to or greater than current date, reject.

Some people put in future dates because they sometimes represent a company or project that hasn't been released yet(most likely set for that future date).

SMF should allow the registration of companies, organizations, or groups of people rather than forcing them to register as a individuals. How to address this properly, I am unsure.

Perhaps allow multiple individual user's to login that company user account, decided by the company account creator. Company domain email(no free email services) should be required to help try to prevent over-use or abuse of feature.

So in the company profile, you would have the company name, then a list of user's within that company. When posting as the company, you would show company name then under that the username logged into that company account to make that post.

Although, I know this is just asking too much ATM from SMF.

**Comment by Arantor** [comment]
Some people put in future dates when the forum is for sci-fi role playing. I've seen forums with members' birthdays starting in the year 2600... the whole validation thing has been discussed numerous times in the past.

I'm really not a fan of selectboxes where you populate it with best part of 100 options. It's not actually that friendly for the user - the funny part is that the most efficient way to actually use them is to type in the year anyway.

**Comment by Oldiesmann** [comment]
Also, now that we're going with HTML5, we can probably change the input type to "date" which will display calendar-popup things in some browsers (though I'm not sure how many currently support it - Chrome does, but I don't know if others do).

**Comment by jdarwood007** [comment]
One of the reasons we don't do this is because some forums, such as role playing ones, do use this.

I seem to recall we had an option at one time controlling the user age limits, but none the less since I don't see it.  I think that is something we could setup to solve this nicely.

**Comment by illori** [comment]
would that allow a user to select the month/day and not the year as they can now?

**Comment by Oldiesmann** [comment]
If we do the HTML5 thing, they could do everything just like they can now. The calendar selection thing is optional just as it is on other sites that use similar functionality (through jQuery, ASP .NET, etc.).

**Comment by Arantor** [comment]
With one exception, though. The date picker stuff relies on knowing the year to know whether to display Feb 29th or not. We explicitly do not want to rely on entering the year.

**Comment by Arantor** [comment]
Perhaps the simplest solution is to simply hide the age if it's negative or more than something like 125 or so...?

**Comment by illori** [comment]
and what if the user just wants their birthdate to be known and not the year and you are forcing them to enter the year now?

**Comment by Arantor** [comment]
That's exactly it if the date input gets used.

**Comment by illori** [comment]
then i would say this would be a regression and many would not be happy [users not the admin] so few may actually speak up about it.

**Comment by Arantor** [comment]
That's why I suggested not touching things and just hiding the age if it's 'out of bounds' rather than the more complex suggestions being thrown about.

**Comment by XinYenFon** [comment]
This may come weird to some people but, tbh negative age is also valid for RP forums... People can have -2 -1 years, unborn and waiting the day their day come etc... Yes this is bit weird but still some usability (unless there is issue with coding side or risk etc...)

**Comment by live627** [comment]
@Antes Both @Arantor and @jdarwood007 brought that up.
