### ISSUE TITLE
Group Moderator Can View All Membergroups

### ISSUE THREAD

**Issue by Xarcell** [SimpleMachines/SMF#1340]
I consider this an undesirable effect. Not a bug, and a low priority, but wanted to point it out.

The thing I noticed was I have a user that I made moderator of a membergroup. When this user goes to the moderation center, he can see ALL membergroups, even if the group is set to private or protected. What if the admin wants to keep some membergroups private, especially custom ones?

I think from the moderation center, the moderator should only see the groups he is in, and can moderate.

**Comment by Arantor** [comment]
Going _where_ in the moderation center exactly?

**Comment by Xarcell** [comment]
Moderation Center > Members & Groups > View Membergroups

Sorry about that. I had originally wrote more than what you see, but I went back and deleted a paragraph, which had the path to the issue in it. I forgot to add it back in at the bottom before posting.

**Comment by Arantor** [comment]
Private and protected do not have anything to do with group visibility; the admin group is both a private and protected group. Private means it cannot be requested or joined freely, or based on a post count group. Protected means that it cannot be added to, or removed from, someone's account unless they are in that group themselves. For example, to add group 1 to someone, you must be in group 1 yourself. There were circumstances where, before this was introduced in the 2.0 RC phase, where you could manage membergroups and add people to groups inappropriately.

**Comment by Xarcell** [comment]
@Arantor your not making much sense, what does that have to do with this issue? I'm thinking now you've gotten the membergroup two issues mixed up. Which could explain the confusion between us.

**Comment by Arantor** [comment]
Not at all. On the contrary, you're the one that I'm sure is confused.

>  he can see ALL membergroups, even if the group is set to private or protected. 

The group being set to private or protected will not, and SHOULD NOT, affect its visibility in this page, because a group's visibility is nothing to do with its status as private or protected.

As explained, a group being set to private from the group's configuration screen is about how one gets into the group. As explained, a group being set to protected is about who can grant that group to others. Neither of these will affect whether the group will be seen in the page in question BECAUSE THEY'RE NOT SUPPOSED TO.

The only option that SHOULD is the option entitled Visibility in the membergroups page, whose options are: Visible, Visible - Apart from in group key, and Invisible. Groups marked invisible, clearly, should not show up except to 1) admins, 2) people with manage-membergroups or 3) moderators of those groups. Groups marked visible (except for group key) is a different story because potentially this option has wider ramifications (if you turn on membergroup listing in the footer, like it is on sm.org, the default destination of that link is to the action=groups page which is borrowing heavily from this routine)

So, in other words, you're the one confused by what you think the options are doing vs what they actually do, meanwhile I'm trying to explain why things you think are relevant are not relevant, and clearly I am again confusing you by explaining to you what is relevant when you think it is not. Perhaps in future you should not try to second guess what you think is important in making bug reports and instead answer the question when further information is requested, rather than going off on a tangent because you think it is relevant.

I'm sorry to snap at you but this is immensely frustrating trying to sift out the relevant detail to actually fix these things when I have to wade through a lot of irrelevance - and confusion - to get to the answer. It's not like I don't have literally hundreds of other bugs to investigate or anything...

**Comment by Xarcell** [comment]
Looks like I'm getting in the way here. I have no problem backing off.

**Comment by Arantor** [comment]
After extensively re-testing how SMF works, visibility is indeed completely controlled by the Visibility option, groups marked Invisible or Visible (apart from group key) are not shown to groups even in the page you're referring to, and groups that are invisible are indeed shown as expected to their moderators.

In short: this is not a bug, this is working exactly as designed as I tried to explain (twice). It would be wise to ensure you understand how the system is supposed to work before stating there is an issue with how it works in future.

**Comment by Xarcell** [comment]
@Arantor as I said in my first post, this is not a bug. Merely suggesting an improvement. You like it the way it is, that's fine. Was only a suggestion.

**Comment by Arantor** [comment]
No, there's no improvement to be made because you misunderstand how things are supposed to work!

I have two groups on my test board, Test Hidden and Test Hidden 2, both are set to INVISIBLE (and both are private, just to appease your confusion). I have a user who is set to be the moderator of Test Hidden 2. This user account only sees Test Hidden 2 because the account is a moderator of it. This account does not see Test Hidden: because it's invisible. If I removed this user from being moderator of Test Hidden, they see neither group.

As I have said multiple times, visibility is implemented, working just fine. It's not my fault that you're not configuring it properly, using the option specifically provided for the reason provided.

**Comment by Xarcell** [comment]
@Arantor Your absolutely right. I never noticed or understood the "Visibility" parameter until now.

Sorry for wasting everyone's time. I reckon the best thing for me to do is stay out of it. I'm done.
