### ISSUE TITLE
Fatal error: Call to undefined function cache_put_data() 

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1376]
Fatal error: Call to undefined function cache_put_data() in ***/Sources/Subs.php on line 476

This happens on upgrade.php on first load, when i refresh the page - error gone and i can upgrade my site without any error.

**Comment by Oldiesmann** [comment]
That's a weird one. That function is defined in Load.php, which is also pulled in around the same time as Subs.php. Load.php is pulled in after Subs.php, but no actual functions are called in between the time Subs.php is loaded and Load.php is loaded.

**Comment by Arantor** [comment]
Load.php only gets loaded under some circumstances, whereas Subs.php will always be loaded, cf.

```
// Are we going to be mimic'ing SSI at this point?
if (isset($_GET['ssi']))
{
    require_once($sourcedir . '/Subs.php');
    require_once($sourcedir . '/Errors.php');
    require_once($sourcedir . '/Logging.php');
    require_once($sourcedir . '/Load.php');
    require_once($sourcedir . '/Security.php');
    require_once($sourcedir . '/Subs-Package.php');

    loadUserSettings();
    loadPermissions();
}

// All the non-SSI stuff.
if (!function_exists('ip2range'))
    require_once($sourcedir . '/Subs.php');
```

So Subs.php should always be loaded but there's a better than average chance Load.php will not. Just beware the inline copy of clean_cache in the upgrader if you do go down and include Load.php at that point by checking if function_exists('cache_put_data')

**Comment by Oldiesmann** [comment]
Ah. I missed that if statement. Thanks for pointing that out.

Looking into this further, the cache_put_data call is part of the updateSettings function. That function is only called in two specific situations: if the custom avatar directory isn't already defined and if you're on MySQL 5.0.50 or 5.0.51 (to fix an issue with "GROUP BY" apparently).

Since we won't always need Load.php, it may just be better to only include that if it's needed rather than all the time.

**Comment by Arantor** [comment]
The custom avatar directory will not be defined in the vast bulk of upgrades.

**Comment by Arantor** [comment]
(didn't mean to close it)
