### ISSUE TITLE
If all boards are ignored, recent posts has some issues

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1378]
action=recent adheres to ignored boards rules, which is handy if you want to ignore some boards and still keep up with what's going on. But if you ignore all boards, you get no messages - but there's no indication of 'no messages' like there is in an empty board.

Additionally, the page index for that doesn't work properly since it's not basing it off the number of possible messages, but off the forum total. If you have all boards ignored with at least 100 posts in the forum (seemingly regardless of whether you _could_ see them or not), you will get a page index of 1 2 ... 10 as you might expect, but of course none of them _do_ anything.

**Comment by Oldiesmann** [comment]
For "action=recent", it seems SMF doesn't even pay attention to whether or not you've ignored a board - it simply shows up to 100 most recent posts from all boards that you can see based on the query string parameters (specified category, specific boards, single board).

However, I did find a couple of issues:

If you specify a category, single board or list of boards in the URL, redirection boards are not taken into account when determining how many recent posts are in the boards matching those parameters for pagination purposes. This can lead to more pages being displayed than actually necessary. In this same situation (one of the parameters above specified), posts from the recycling bin board are not excluded (they're only excluded if you're viewing all recent posts).

Also, there's this "todo" notice before the code that generates page links for "action=recent" with no boards/category specified: `// @todo This isn't accurate because we ignore the recycle bin.`

The solution there would be to figure out how many posts are in the recycling board and subtract that from $modSettings['totalMessages'].

I haven't looked at the "unread" options yet so there may still be an issue with ignored boards in that situation.

There is definitely a problem with the page index generation though, as not specifying any board/category parameters causes it to assume you can either see all posts or at least 100 posts (if there are more than 100 posts on the board). This will cause problems in many situations.

**Comment by Arantor** [comment]
Trust me, it does. I have been using action=recent for a very long time on sm.org and it ignores all the boards I marked ignore. It is through marking all boards on ignore that I discovered this behaviour. I do not use recent with a board or category specifier, merely the overall list, and that list certainly exhibits the behaviour I describe. If I didn't genuinely think it worked that way I would not have reported it as such.

And I also reported the determination aspect in my original report... that's what the second paragraph mentions. Perhaps next time I should file each report as a single paragraph.

Also note that while action=recent does indeed support board and category subsets, nowhere is there actually a link to these - except when you're already there (in which case it populates the linktree and page index properly)... so there is no way a user would know they are even there, unless they were specifically told about it, while action=recent is linked from the board index.

**Comment by Oldiesmann** [comment]
Sorry about that. I guess I should have read things more closely.

As far as the ignored boards - it's possible the issue on my test board was due to caching. On simplemachines.org, it's because ignored boards aren't taken into account when specifying a particular category (or, for that matter, when specifying one or more particular boards, but it makes sense in that situation to overlook ignored boards).

I'm also thinking it might be best to exclude ignored boards and the recycling board when viewing recent posts for a particular category.

**Comment by Arantor** [comment]
Except, again, behaviour for categories and board(s) is separate to the main behaviour. This report concerns the main behaviour: the one users actually see and interact with because ;c= and ;b= aren't documented anywhere that I'm aware of except in the code, it's certainly not linked anywhere, so they will never see it, and never realise or notice it is awry. The main recent behaviour can be observed in normal use, not with URL manipulation or using hidden features.

Also, you don't need to count(id_msg), just query the boards table and use the values in there, which should be faster.
