### ISSUE TITLE
Cannot report user without a post

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1383]
As per http://dev.simplemachines.org/mantis/view.php?id=5008

If a user has a signature or other spam things without a post, there is no formal way to report them.

While this can certainly be mitigated for Google purposes (limiting signatures etc. to > 0 posts through the permissions system, plus limiting profiles to members only), there's still no way to do it.

**Comment by Xarcell** [comment]
The love of God I would love to see an option to report a user without post. It's not just signatures that can be offending, but the user-name or any profile fields as well.

**Comment by Oldiesmann** [comment]
How do we want to handle permissions for this? Do we just want to send it to anyone who can edit any part of the profile (excluding of course the person whose profile we're reporting), or should it just be limited to those with the "admin_forum" permission?

For simplicity, I'm just going to have a simple form where you enter why you're reporting it (just like we have for reported posts), but I'd like to know who should actually get the report before I figure out how to handle this (most likely via hacking the existing report functionality).

**Comment by MissAllSunday** [comment]
mmm, I was looking at this myself, I was thinking to expand the moderation section to add a brand new section since re-using the existing one isn't going to be possible without some major changes.

As for who can see it, thats a good question, we cannot really let local moderators to see it since this shouldn't need to be tied up with any topic, perhaps yet another permission or just go safe and let global moderators and admins been the only ones who can see reported users

**Comment by Oldiesmann** [comment]
The problem is there is no single permission (other than admin_forum) which gives you permission to edit most of the parts of the profile which could be abused (avatar, personal text, custom title, signature, website and location basically).

The way I see it, we have three options:
1. Keep it simple and send it only to those with admin_forum.
2. Keep it simple and send it to anyone with any of the assorted permissions needed to edit parts of the profile (assuming that if they have one they probably have most of them).
3. Make it a bit more complicated and allow the user to choose what part of the profile they're reporting, at which point we can reliably figure out who has permission to fix that.

The thing is though, I've never seen a forum where users other than the admins have the ability to edit users' profiles, so I don't know how common it is. It might be worth asking the community here.

There are really two stages to this:
1. Modify SMF code appropriately to allow reporting of profiles and storing those reports somewhere.
2. Figure out when and where to display those reports. The mod center sounds like a good place (new area of course), and I was thinking it would also be good to be able to access all reports about a profile from the Track User section so you can more easily notice potentially problematic members.
