### ISSUE TITLE
Admin Approvals doesn't include under-age approvals

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1385]
On my test site, for example, I have 17 accounts pending approval, 2 of which are under age accounts, but only 15 shows up in the menu (x) counter. Not session or cache related, either.

**Comment by Xarcell** [comment]
Shouldn't under-age registrations be rejected automatically? Or are you talking about registration with parents approval(not even sure if SMF has this option)?

**Comment by Arantor** [comment]
Um... no... parents approval has been a function of SMF for some years, this is about the situation where the admin has enabled them and so on.

**Comment by Oldiesmann** [comment]
This has already been fixed in 2.1. ViewMembers handles members with an "is_activated" value of 5 (which is set if they're awaiting approval because of COPPA restrictions), and when I tested it on my board, it worked properly (I went in and set "is_activated" to 5 for my Oldiesmann3 account and it shows as awaiting approval in the admin center).

**Comment by Arantor** [comment]
I thought I turned off notifications for Github, guess not. Thing is, that isn't what the bug report was about. If you think it's fixed, by all means close it but the situation I described was from 2.1 where I had 17 unapproved accounts in admin but the _main menu_ (not in the admin panel) only told me there were 15.

**Comment by Oldiesmann** [comment]
I misread it then. I was under the impression that this was occurring in the admin center. I will look into it further and see what I can figure out.
