### ISSUE TITLE
Number of unapproved items should be indicated in the moderate menu?

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1387]
We indicate the number of members etc. waiting for approval with (x) numbers in the menus. It would be neat to do that for the items pending approval but the trick is doing it without there being a huge performance hit in so doing, because it's not a single universal value for each user. It's not even a single universal value for any given amount of groups because of board level moderation (so it's a per _user_ thing)... maybe storable in the mod cache?

Or maybe let it go but it would be useful to indicate if it is at all feasible to do.

**Comment by Xarcell** [comment]
Indicators are your friend, but your server's enemy. I would love to see this if it doesn't have a huge performance impact. Then again, how big if an impact can it have if their are only a few moderators?

**Comment by Oldiesmann** [comment]
If we can do it without a huge performance hit, I'm all for it. Storing it in the mod cache would probably be the best option.

**Comment by MissAllSunday** [comment]
oops, got the wrong issue .___.   anyway, I'm looking at this too.

**Comment by MissAllSunday** [comment]
meh, got the wrong issue...

anyway, I have no idea what kind of unapproved items should be displayed.

**Comment by Oldiesmann** [comment]
Pretty much anything that the current user can approve (except of course account deletions since that's mostly an admin thing and not tied to the moderation center) - group requests, posts, topics and attachments.

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.

**Comment by MissAllSunday** [comment]
I remember I did fix this but I can't find the branch but even if I did it won't be a clean merge anyway.

**Comment by Sesquipedalian** [comment]
Do you have any memory of what you did to fix it, @MissAllSunday?

**Comment by MissAllSunday** [comment]
Since this was on a per user basis I remember I was toying with the idea of collecting each notification in an array and store it on a cache item using the member id as part of the key:  unapproved_stuff_. $user_info['id']  and then attach it to the menu entry after the menu cache call.

My plan was to either get the cache entry and redone it with the new elements or inject it directly using the shady cache functions no one knows about 👅

**Comment by jdarwood007** [comment]
@MissAllSunday 
Is this something still feasible for 2.1, or for a later date?

**Comment by MissAllSunday** [comment]
It is, kinda, we just need to make sure we inject the number of items after the menu cache gets called. Will take a look over the weekend

**Comment by MissAllSunday** [comment]
So, turns out it is not that simple... in order to fire up an event when someone post an unapproved topic/msg you need to get a list of users who have the permission to approve stuff, this is more complicated that it looks. It is pretty easy to get it when you're checking the current user ($user_info) but it becomes quite cumbersome to do so when you want to get a list of users, ie: usersAllowedTo('post_unapproved_replies_any')

Will have to mess around with a heavy and full of joins query, thing is, I don't really know which permissions granted the user privileges to approve stuff.

**Comment by Sesquipedalian** [comment]
Based on @MissAllSunday's last comment, this is best left for SMF 3.0.
