### ISSUE TITLE
Severely curtail send-forum-email functionality

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1403]
There is no need for users to send email to each other through the forum. They have the PM system for that.

There is one, and only one, remaining use for it: for contacting since-deleted-authors (or guest authors) of posts where only the email address will be available. Checks should be added to the EmailUser function to ensure that the owner of a post (which is how it is primarily done) is a guest, and that no direct-to-user-id option remains.

As far as limiting contact of guest posters goes, that could be a permission or it could be pulled from admin_forum or moderate_forum to avoid spamming in general.

Ref: http://www.simplemachines.org/community/index.php?topic=508995.0

**Comment by Xarcell** [comment]
Is this very small feature really worth the work though? I mean, if a user deletes his/her own account, I would think in most cases he/she would not want to be contacted by anyone from the community anyway.

**Comment by Arantor** [comment]
So you're saying that if the admin wants to contact someone to try and work it out, they're forced to trawl through the database to obtain the email address? Good luck explaining that to people.

**Comment by Xarcell** [comment]
Never thought of it that way.

**Comment by Oldiesmann** [comment]
Thinking about this some more, is there any reason why we need to allow non-admins to contact guest posters through the forum?

The reason I'm asking is that in order to handle #1383, I have to modify the Report To Moderator feature, which is in the same file as the "Email User" function. If I do that, then we end up having a function to report users in a file called "SendTopic.php" (though the old "email a user through their profile" functionality went through the same file for whatever reason). If we don't need to allow non-admins to email guests through the forum, then we can completely kill the EmailUser function and rename SendTopics.php to something more descriptive of what it does.
