### ISSUE TITLE
Favicons In Various Sizes

### ISSUE THREAD

**Issue by Xarcell** [SimpleMachines/SMF#1422]
I'm looking to maybe tackle this, but I need feedback from the developer team as how best to approach this. Currently there is no way to make all browsers/OS's work with the favicon and various sizes properly.

So what are the priorities? What do we want to support and not support?

Here is a research article for common problems and various sizes needed: http://realfavicongenerator.net/faq#why_so_many_files

**Comment by Oldiesmann** [comment]
At the most just a favicon.ico and assorted sizes of apple-touch-icon.png for the latest/most common iOS devices should be enough. I ran that favicon checker thing at the site you linked to on several major websites (Bing, Yahoo, Google, Microsoft, Apple and TechCrunch) and most only had favicon.ico, with a few also having the Apple touch icon (although in those cases the script still said several recommended sizes were missing). Nobody had Windows 8 icons, nor did anyone have browserconfig.xml. The fact that Microsoft doesn't have them is a good indicator that they probably aren't needed.

It might be best to ask in the community about this though to see if anyone else knows more about this stuff, rather than just taking advice from a single website.

**Comment by Xarcell** [comment]
I'm not longer contributing to the SMF project.
