### ISSUE TITLE
Additional permissions for topic visibility

### ISSUE THREAD

**Issue by Zer0-One** [SimpleMachines/SMF#1506]
I'd like to request that permissions be added to optionally restrict a user's ability to view topics on a given board. Preventing a user from looking at topics that aren't his own would come in handy on a board that was meant for private conversations between regular users and staff/moderators. A permission like this currently exists for polls, but not topics in general.

**Comment by tekkla** [comment]
This would be really cool!

**Comment by XinYenFon** [comment]
I don't think it fits for core product but nice idea for a modification.

**Comment by Zer0-One** [comment]
@Antes why not? I think it makes sense to have the most flexible set of permissions available to you out of the box.

**Comment by XinYenFon** [comment]
I think i misunderstand it, you don't mean specific topic, you mean as board permission... Sorry i mixed it. I remember we discussed it in somewhere (probably private), I also like to see this feature, i see some usability. Last word still comes from our developers unless someone come and write it for SMF.

**Comment by Oldiesmann** [comment]
While it would be useful on some boards, it's a pain to implement due to the large amount of code we'd need to modify for this - news feeds, recent/unread posts/topics, the thing where you can view all posts/topics by a user, etc. In some cases we could simply tack the info on to "query_see_board" (so just assume you can't see the board if you can't view other users' posts in that board), but we'd still have to modify other areas to account for only showing posts that you can see in a particular board, which gets really complicated. If someone can write it up, I'll be glad to take a look at it, but with the limited dev power we have right now (myself and MissAllSunday plus assorted team members helping out here and there), I don't see this becoming a core feature anytime soon.

**Comment by Arantor** [comment]
Not to mention a non-trivial performance bottleneck that gets added at the same time.
