### ISSUE TITLE
Internal admin settings do not adhere to limits

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1569]
Some settings that are int or float also declare min/max values. While these may be enforced through the front end, these are never enforced in the back end.

saveDBSettings needs to validate and clamp the values within ranges if appropriate.

**Comment by NanoSector** [comment]
Looking into this.

**Comment by Oldiesmann** [comment]
Looking into this further, I definitely see where the confusion was coming from. SMF expects many items to be at a specific location within the array (even if they're optional), while some other things simply need to be set. However, if you don't specify some of the optional things while specifying the ones that simply need to be set, you may run into weird problems. So, this means in many cases you need to specify values for things you're not using (input size, helptext, etc.) just to specify values for other optional things you ARE using.

While we can sort of work around this for 2.1 (continue the "expect some optional things to always be there if other optional things are there" thing that we're currently doing), it leads to all sorts of confusion and is rather messy, plus it means we need more code than necessary.

I think the best solution at this point is to rewrite all the config var arrays to make everything use text keys ('type', 'value', 'name', etc.) instead of relying on things to always be at specific locations. This will make the code easier to read (someone won't have to go digging for a comment that explains what goes where) and also mean we won't have to specify values for optional things when we don't want to use them.

**Comment by Oldiesmann** [comment]
After further investigation, it looks like I somewhat misunderstood how PHP handles arrays. However, it's still confusing because $array[4] will be the 5th item in the array that doesn't have a specific key associated with it - meaning it won't always be the 5th item overall. This still means things are going to be horribly confusing if we have some items with text keys and others that use numeric keys/indices.
