### ISSUE TITLE
ISO-8859-1 vs Windows-1252

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#1717]
If you run my SMF 2.1 test board through the W3 validator, it complains " Bad value text/html; charset=ISO-8859-1 for attribute content on element meta: iso-8859-1 is not a preferred encoding name. The preferred label for this encoding is windows-1252.".

The reasoning for this is explained here (thanks to Illori for this link): http://w3-org.9356.n7.nabble.com/VE-html5-Character-Set-ISO-8859-1-vs-windows-1252-td250039.html

I know that new installs will be using UTF-8 by default, but for existing installs, should we change to Windows-1252 instead of ISO-8859-1, or is this something we should just ignore?

**Comment by Oldiesmann** [comment]
@Arantor do you have anything to add to this?

**Comment by Arantor** [comment]
That's kind of the problem, though... it isn't just a simple change. For a lot of things, you can just safely change it on the front end and not worry about it because for a large swathe of ISO-8859-1, it's identical in meaning to Win-1252 anyway. It's only that block from 128 to 159 where there have different meanings and changing one to the other is suddenly problematic on all kinds of levels, especially when you're dealing with user input.

As much as I'd be all for correctness, I'm also very mindful of the practicalities of retesting and securing all forms. I'd argue that if they actually cared about it, the recommendation would be a conversion to UTF-8, and for those that don't care, to leave it be.

**Comment by Oldiesmann** [comment]
Sounds good to me. Thanks for your input :)
