### ISSUE TITLE
Use autoloading

### ISSUE THREAD

**Issue by Daniel15** [SimpleMachines/SMF#1720]
It's 2014, nobody manually requires PHP files any more.
`spl_autoload_register` FTW.

**Comment by live627** [comment]
Um, yeah, but  how well does that work in procedural code?

**Comment by Daniel15** [comment]
Well, converting to proper OOP would be a good prerequisite :)

There's ways to autoload functions but they're not as straightforward and require a build step (creating a mapping of function name to the file that defines it). Ideally you'd have a build step for classes too, to build a cache so you don't need to dynamically look for the file every time.

**Comment by Dragooon** [comment]
Either way isn't ideal IMO, we don't have enough resources or time to go full OOP and I'd rather not define a function map

**Comment by Arantor** [comment]
Which is why you do it with 3.0 and a full workover to go OOP. I've been saying this for some time but no-one else seemed to want to listen. :tongue: (Also, some people feel it's LAZY to go and use autoloading and it shouldn't be used, but the same people also have terribly selective hearing)

**Comment by Dragooon** [comment]
Well, yeah. When we go into a proper OOP rewrite this is practically a no brainer.

**Comment by Daniel15** [comment]
Along with getting away from the NIH mentality and reinventing things like database abstraction and UTF-8 handling :P

@Arantor I'd love to hear arguments like that. Autoloading makes things extremely efficient and you get it for free with Composer.

**Comment by Arantor** [comment]
@Daniel15 The person who doesn't like autoloading because it makes programmers lazy is also of the mindset that class names should have no more than 5 letters wherever possible, has one major class in their system that has just two letters in its name, that 'sources' was too long a folder name for the SMF sources folder. And yet feels that autoloading is lazy-inducing. Waste of time going down that road.

The NIH mentality in SMF is actually quasi understandable - to a point. For regular users of SMF, things like Composer are a pain because you can't leverage them in an ideal fashion. Same with things like using PDO, it'd be great but impractical if hosts don't have it. As for the DB abstraction I really do quite like the overall abstraction and the way queries get parameterised, because I find it's so much more readable to have named parameters than the ? binding normally seen in such libraries. But it's hardly a deal-breaker. (Much more of an issue is decoupling error handling from the query setup)

**Comment by Daniel15** [comment]
The DB layer should use classes and proper polymorphism at least :)

And by "use Composer" I meant to use it during development. For release versions you could pre-bundle everything, users don't have to know about Composer. Would need to think about handling autoload of plugins in an extensible way though, and dependencies introduced by plugins. The whole plugin architecture needs reworking. Manually editing files is not scalable.

Ideally someone (or a group of people) needs to figure out the architecture of a modern PHP-based forum system before even writing a line of code. It's definitely challenging in terms of doing things the 'right' way vs being able to run on terrible shared hosts. Every modern PHP framework is doing things the 'right' way by using built-in functionality like PDO, mbstring and mcrypt these days so as their usage increases, shared hosts are going to have to adapt eventually otherwise they'll get to a point where they'll be unable to run any modern PHP apps.

**Comment by Arantor** [comment]
@Daniel15 You're preaching to the converted here, and yes, rethinking plugin architecture is nothing new to me... I already did it once. Not ideally in hindsight but I already did it once and ditched file edits back then too.

The problem is, none of it matters. Not enough people with the skills care enough to sit down, design it and build it because too many people don't want to consider change. Not even more modest change than a full scale rewrite.
