### ISSUE TITLE
Info Center

### ISSUE THREAD

**Issue by Morsyl** [SimpleMachines/SMF#1772]
I noticed when viewing on my phone (Galaxy Nexus, using either Android's default browser or Chrome) that the data in the Info Center on the Board Index doesn't load, unless I press the arrow twice, once to "hide" (what isn't there) and again to unhide.

**Comment by XinYenFon** [comment]
Interesting your first point (double tap) is a known and done by me (you know info_center served as uncollapsed by default) but I don't see any problem hiding it again on my Lumia (IE-mobile).

**Comment by Morsyl** [comment]
Ummm, sorry, but I'm afraid I don't quite follow you, being new to this and all....

**Comment by XinYenFon** [comment]
beg my pardon, i misunderstand you. better to remove hide option on small screens, I actually did that for better UX but seems better i left it out.

**Comment by Morsyl** [comment]
Ah, all good. So does this mean the info center is always there or always gone from now on, on small screens?

**Comment by XinYenFon** [comment]
yea we did that for small screens at start but seems its looking like a bug to end user better to leave it to end user.

**Comment by AngelinaBelle** [comment]
Initially Hidden is fine.
The problem is this:
1) Info center is hidden.  "upshrink" icon ^ is visible
2) tap upshrink icon ^ 
3) info center is hidden.  "unhide" icon v is visible
4) tap v icon
5) info center is visible.

---

The correct behavior would be:
1) info center is hidden.  "unhide" icon v is visible
2) tap v icon
3) see the info center.  "upshrink" icon ^ is visible.
4) tap ^ icon
5) info center is not visible.  "unhide" icon v is visible again.
