### ISSUE TITLE
Change registration (COPPA/Terms)

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1778]
I was reading http://dev.simplemachines.org/mantis/view.php?id=2318, and got this small idea how about we remove the Terms & Rules thing and  COPPA extra pages from registration and add them as checkbox to the page with link (either pop or new page redirect). We already have Rules page (;sa=rules) and we can add COPPA part to it if enabled. This also requires adding birthday field to registration page.

**Comment by Oldiesmann** [comment]
Why would we want to remove those pages?

Adding the birthdate to the registration page is doable, but it's a pain because of the whole "three fields" thing (even though SMF does store all three as a single date - the reason for three separate fields is that we make the year optional rather than having a checkbox that says "hide my age" or something like that).

**Comment by XinYenFon** [comment]
I'm closing this now, and something for --SMF3.0
