### ISSUE TITLE
Tokens and edit others profiles

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#182]
- end the admin session (since we can now, it's easier :P)
- edit someone else's profile
- save
- insert the admin password
- token verification failed

**Comment by smguy9** [comment]
I added false parameter in Profile.php@line 461 to validateToken function, and it worked without any problem. But I'm not sure if it creates a security issue or not.

**Comment by emanuele45** [comment]
As far as I can see, adding the false simply makes useless the token.
false is used in case you want to grab the token in return from the function, but not during validation.

At the moment the only solution I have in mind is to change Profile.php to:

```
    if (isset($security_checks['validate']))
    {
        if ($security_checks['validateToken'])
        {
            createToken($token_name, $token_type);
            $_POST[$context[$token_name . '_token_var']] = $context[$token_name . '_token'];
        }
        validateSession();
    }
```

But it's rather ugly...I think.

Maybe @Norv, or @jdarwood007 have another idea.

**Comment by wsabransky** [comment]
In a sense, this seems just like the anti-CSRF logic is doing its job, since the reason the "token verification failed" message is being displayed is that the token is no longer present in the user request after the re-authentication happens. Although @emanuele45 's proposed fix does solve the problem, it seems like it's just generating a new token at the login, and this would make the token for the original request useless. One potential solution, without changing the security logic at all, could be to have the re-authentication form display a hidden field for any tokens that are in the request data when the call to render the password form takes place. Another solution could be to just redirect the user back to the original form after the login (potentially substituting all of the new data).

This does all beg the question of whether the current token design is best. I'm unsure why per-session tokens aren't more than sufficient for the level of security needed here. I could see how per-form tokens could be useful, but single use tokens seem like they're overkill. On top of issues like this one, another downfall of single-use tokens is not being able to submit a form more than once, which can easily break navigation. I wasn't around when the token logic was decided on, though, so there may very well have been a good reason for the single-use design.

**Comment by Krashsite** [comment]
Getting token verification errors in ACP when creating new board (once - board created suiccessfully), and registering new member (twice - had to start over from ACP menu).  Haven't been able to duplicate the first one, but can duplicate the registration error as follows:
- Admin -> Register new member
- Fill out registration with no email address 
- 'An Error Has Occurred - Please enter a valid email address.'
- Back 
- Fill out registration with email address
- 'An Error Has Occurred - Token verification failed'
- Back
- Repeats error

Have to return to Admin -> Register new member to complete registration.

**Comment by matthew-kerle** [comment]
Thanks for posting what you've found thus far.

@wsabransky any luck on resolving this? It'd be awesome to see a PR from you :)

**Comment by illori** [comment]
@krashsite anytime you use the back button in the admin panel in 2.1 you will get a token verification failed message. you can no longer go back and re-submit the same form again, it has to be filled out again from scratch.

**Comment by Krashsite** [comment]
That being the case, then the 'Back' button below the error message should reinitialize the form, not take you back to a dead end.

**Comment by Oldiesmann** [comment]
The above commit/PR will resolve this issue - rather than using javascript:history.go(-1) for the back button, it now uses javascript:document.location=document.referrer which sends them to whatever URL referred them there. Before I close this issue though I wanted to see if anyone had a better solution. It also might look better if we create a new JS function for that instead so we can do javascript:goBack() or something similar.

**Comment by illori** [comment]
we cant close this issue as it is actually 2 issues. the first one being not solved yet.

**Comment by emanuele45** [comment]
Yep, your fixes the token verification failed page (and probably the session verification failed), though it doesn't change anything when adminLogin is used.

**Comment by Oldiesmann** [comment]
Didn't see that first issue. Sorry.

After spending some time digging through the code and doing some debugging, I found the problem here. The token that it's failing to validate is the one for modifying the profile.

Sources/Profile.php, lines 462-470:

```
// Now the context is setup have we got any security checks to carry out additional to that above?
if (isset($security_checks['validateToken']))
    validateToken($token_name, $token_type);
if (isset($security_checks['session']))
    checkSession($security_checks['session']);
if (isset($security_checks['validate']))
    validateSession();
if (isset($security_checks['permission']))
    isAllowedTo($security_checks['permission']);
```

The problem here is that validateSession is called after the token has already been validated, so when we try to validate that same token again after the admin logs in, it no longer exists. Changing the order of the security checks (calling validateSession before calling validateToken) fixes the issue.

**Comment by illori** [comment]
cool, glad to see a resolution to the main issue here. have you made a PR on that? i can test it out tomorrow.

**Comment by matthew-kerle** [comment]
Yes, that is the issue that @wsabransky was coming up with. However, he was also thinking about improving on the token system a little bit. Great to finally see a fix for this though, either way.

**Comment by matthew-kerle** [comment]
Can we close this now then, @Oldiesmann ?

**Comment by illori** [comment]
he meant to close this but it put the merge against the wrong issue 128 instead of 182, go ahead and close it.

**Comment by Oldiesmann** [comment]
Closing this since it's fully fixed.
