### ISSUE TITLE
gender none icon used in profile

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1889]
it is confusing that the gender icon in the profile for the none option is the same as when the user is online. it should be something else so we can see it is different from others used elsewhere in the UI.

also most may not understand what the alt text "none" means as there is nothing in that area to tell that it is the persons gender.

**Comment by MissAllSunday** [comment]
Thats because there isn't a gender_None class defined, the same will happen with any other custom options the user might implement, we can add one for the None option but we cannot possible know which other options an user might add.

As for the title, it seems redundant to add Gender:  since the icon kinda already tells you its the  user's gender.

For the None option I suggest adding 
.gender_None
{
background:none;
}

Since theres really no good way to represent a "none" gender with an image.

Or hijack the code and remove printing the icon altogether if the "None" option was selected.

**Comment by illori** [comment]
would a question mark work? i have seen that before.

**Comment by MissAllSunday** [comment]
That would be more like "I don't want to tell you"  or "Undefined"  rather than "None".

**Comment by illori** [comment]
maybe we should rename none, as it is basically i dont want to tell you right now. if i dont want to know as male or female, i have to pick none instead of i dont want to tell you.

**Comment by MissAllSunday** [comment]
Tecnically none and "I don't want to tell you" should be separate options because None actually is a valid gender  but  we will be entering on the same debate we had before about "defining genders" and we will reach the same conclusion, that is best to leave the default behavior as vanillas as possible.

So yeah, change the "none" option to something like "disabled"  or something that suggest the user specifically don't want to show it and make the change to not show it if the "disabled" option was chosen.

**Comment by illori** [comment]
sounds like a good compromise to me.

**Comment by XinYenFon** [comment]
They are customizable so I think that won't be a big problem for site admins to change stuff around. But bigger problem is, they are CSS related, so if forum admin adds a new sex, like new_sex its class becoming "gender_new_sex" and since its not defined in CSS, it shows on icon.

**Comment by MissAllSunday** [comment]
Only the default ones are css, any new custom ones could be added like a normal img tag.  The user needs to upload an image with the same name as the option and use a valid path to that image

**Comment by illori** [comment]
looks like they would all be css.

```
<span class=" generic_icons gender_{INPUT}" title="{INPUT}"></span>
```

**Comment by MissAllSunday** [comment]
oh, yeah :(

well, thats a problem then :P

**Comment by MissAllSunday** [comment]
mmm, we can either revert back to use single images or post somewhere a detailed guide on how to add new gender options

**Comment by illori** [comment]
i think an option of both may be useful... a how to on the css method but doing it with inline html would be easier for most admin to understand.

**Comment by XinYenFon** [comment]
I vote for second. Its not a big deal really. CSS better. I can write the guide about that. Which also gives me chance to make Irisado suffer... but those are details :paw_prints:

**Comment by MissAllSunday** [comment]
TBH I prefer to keep it all css, I can foresee quite a few questions about this but as long as we have a guide and a quick link like we have for "how to add buttons on 2.0" for example, we can pull this up.

As a fallback, we can have a single image for female and for male on /Themes/default/images/  that way if the user changes the default input for something like 

<img src="{DEFAULT_IMAGES_URL}/{INPUT}.png" alt="{INPUT}" />

the image will still be show,

**Comment by illori** [comment]
sounds good to me, i can work with irisado when we get closer to 2.1 release on converting this to css doc on the wiki if that is what is wanted
