### ISSUE TITLE
Undefined Index(es)

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1904]
- [x] 8: Undefined index: avatar

Sources/Subs-BoardIndex.php
Line: 318 
- [ ] 8: Undefined index: id_attach

Themes/default/GenericMenu.template.php (edit_options sub template - eval?)
Line: 2891
- [ ] 8: Undefined index: alerts_no_unread

Themes/default/GenericMenu.template.php (alerts_popup sub template - eval?)
Line: 145
- [ ] 8: Undefined index: all_alerts

Themes/default/GenericMenu.template.php (alerts_popup sub template - eval?)
Line: 99 
- [ ] 8: Undefined index: alert_settings

Themes/default/GenericMenu.template.php (alerts_popup sub template - eval?)
Line: 96
- [ ] 8: Undefined index: mark_alerts_read

Themes/default/GenericMenu.template.php (alerts_popup sub template - eval?)
Line: 95
- [x] 8: Undefined index: image_proxy_secret

Sources/ManageServer.php
Line: 966 
- [x] 8: Undefined index: image_proxy_maxsize

Sources/ManageServer.php
Line: 970

**Comment by live627** [comment]
Turn eval off.

**Comment by Oldiesmann** [comment]
Those last two occur because $_POST['image_proxy_secret'] and $_POST['image_proxy_maxsize'] aren't set when the SSL setting is disabled.

On a related note, I also got these errors when saving settings from that page:
Undefined offset: 2
Sources/ManageServer.php
Line: 1030

array_keys() expects parameter 1 to be array, null given
Sources/ManageServer.php
Line: 1030

in_array() expects parameter 2 to be array, null given
Sources/ManageServer.php
Line: 1030
