### ISSUE TITLE
Errors related to mentions and alerts?

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1941]
Type of error: Cron
8: Undefined offset: 1  http://angelinabelle.meximas.com/p4/cron.php  
CreatePost-Notify.php
Line: 335
Line: 322

Type of error: General
8: Uninitialized string offset: 7   http://angelinabelle.meximas.com/p4/index.php?action=post2;start=0;msg=11;f2e30ffca0=8d9862f25e1363d4870be82c809a794b;board=1    File: Mentions.php
Line: 191

**Comment by Oldiesmann** [comment]
What line of cron.php did that first error occur on?

The two errors in CreatePost-Notify.php indicate that there is no entry in $prefs for that particular member. That needs to have a default value set, or at least return if $prefs[$id] is empty.

The error in Mentions.php is because we're doing `trim($char[$k - 1])` but the string in question is less than 8 characters long. I'm not entirely sure what's being done there though. @Dragooon should know though.

**Comment by AngelinaBelle** [comment]
Cron.php is the url.  The error is in CreatePostNotify.pho -- there is no line number given for cron.php

<hr/>

If you want to give me a diagnostic version of cron.php with some debugging statements, I'll be happy to test it. I can even make you admin on my free host test site, in case you aren't seeing these errors on your test install.

**Comment by Oldiesmann** [comment]
I'll look into it further tomorrow and see if I can find anything.

**Comment by AngelinaBelle** [comment]
I will be available again monday

**Comment by Oldiesmann** [comment]
I'm thinking the cron.php error might be related to this line:
`if (substr($sourcedir, 0, 1) == '.' && substr($sourcedir, 1, 1) != '.')`

However, I don't know why we'd ever have a setup where there's an empty directory that doesn't have a ".." in it.

I'll commit a fix for the CreatePost-Notify.php errors in a minute. Still don't know what's going on with the Mentions.php error though.
