### ISSUE TITLE
Errors after Creating Topic

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1980]
- Type of error: Critical
- The database value you're trying to insert does not exist: id_member Function: insertMentions
- /Sources/Mentions.php - Line: 93 
- http://next.mmobrowser.com/cron.php

---
- Type of error: Cron
- 8: Undefined index: id
- /tasks/CreatePost-Notify.php
- Line: 44 
- http://next.mmobrowser.com/cron.php

**Comment by NanoSector** [comment]
Can't reproduce.

**Comment by Oldiesmann** [comment]
Doing a bit of a backtrace on this, I cannot figure out how this could ever happen. It means that there's no "id" in the posterOptions array passed to the background task, but sendNotifications in Subs-Post.php specifically sets this to $user_info['id'], which again should always be set (it's 0 for guests). The database error from Mentions.php is related because $posterOptions['id'] is passed as the id_member parameter to insertMentions there.

**Comment by AngelinaBelle** [comment]
Eppur si muove

**Comment by XinYenFon** [comment]
You can reproduce this issue with;

1) Mention someone in a topic
2) Visit that topic as Guest.

**Comment by MissAllSunday** [comment]
Can you still reproduce this?

**Comment by XinYenFon** [comment]
Unfortunately yes

**Comment by Oldiesmann** [comment]
I'm still not sure what's going on here...

The createPost function specifically sets $posterOptions['id'] to 0 if it's empty. There is absolutely no reason why $posterOptions['id'] should not be set there.

**Comment by XinYenFon** [comment]
Those errors are generated from cron.php as Guest... and only when people are only (:confused:)
