### ISSUE TITLE
Some things render differently in preview and in display.template.php

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1996]
![image](https://cloud.githubusercontent.com/assets/3267025/3430319/4185adae-0060-11e4-88f7-859b9778d626.jpg)
![image](https://cloud.githubusercontent.com/assets/3267025/3430320/418c2bd4-0060-11e4-82da-bf0740f13422.jpg)

**Comment by Oldiesmann** [comment]
What's the actual source code for that topic after the post has been made? It's possible SMF is stripping out the object/embed tags.

**Comment by AngelinaBelle** [comment]
nope.  nothing stripped from the page html

**Comment by Oldiesmann** [comment]
I have no idea why this would be happening if the HTML from the post is the same.

**Comment by AngelinaBelle** [comment]
I was assuming some wrapper is causing different CSS styling?

**Comment by Oldiesmann** [comment]
Just tested this in Firefox and can't reproduce it, though I didn't try embedding the verification audio - just the one piano2.wav file. I tried both the HTML5 method (audio tag) and the object method (as shown in your screenshot there) and both items showed up the same after posting as they did in the preview. It might be related to whatever plugin is set to handle wav files for your computer (on mine it's Quicktime, though the audio tag uses a player built-in to the browser rather than a third-party plugin).

**Comment by AngelinaBelle** [comment]
Funny that it renders differently in preview than after save.
Not a high priority.
Not worth investigating further?
Tag "can't fix"?

**Comment by Oldiesmann** [comment]
I'll try it with a few more browsers and see what I can come up with. It works as expected in Firefox at least.

**Comment by AngelinaBelle** [comment]
You can view this at Antes' site, for convenience.
I suspect "can't fix" because I don't know why it looks different, either.
