### ISSUE TITLE
Timezone (user setting) not using PHP

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#2024]
This is bit confusing and this list seems bit missing, admin panel has Server Timezone and using (http://www.php.net/manual/en/timezones.php), newly added Timezone setting for users lacking lots of places and time-saving (+1/-1) option.

**Comment by live627** [comment]
So you'd rather complicate it more by adding three billion options?

**Comment by XinYenFon** [comment]
I rather call it incomplete...

**Comment by Oldiesmann** [comment]
The timezone list thing is a tough call. If we present the user with the same list as the admin, it could get confusing due to the large number of options and the fact that you have multiple names for the same timezone. However, it might be easier for users if they see something they're more familiar with rather than what we're currently using for them.

We do need to have something to handle DST as well - even something as simple as a checkbox that decreases the user's time offset by one hour. It's not the best method (and may not always work properly, since for instance British Summer Time ends a week earlier than DST), but it's probably simpler than trying to figure it out ourselves.

**Comment by illori** [comment]
the checkbox may not really be needed, if the server changes the time correctly the user should never really need to change the time settings manually.

**Comment by live627** [comment]
> We do need to have something to handle DST as well - even something as
> simple as a checkbox that decreases the user's time offset by one hour.
> It's not the best method (and may not always work properly, since for
> instance British Summer Time ends a week earlier than DST), but it's
> probably simpler than trying to figure it out ourselves.

I already told you the code already does that.
