### ISSUE TITLE
Do not emulate

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#2029]
Current package manager can emulate down to 1.0 (didn't tried with 1.0 Alpha 1 alike things) but it shouldn't be emulating down of SMF 2.0 RC3 (or 2 can't really remember in which RC Curve introduced).

**Comment by tekkla** [comment]
Does it makes sense to offer release candidates for emulation?

**Comment by Oldiesmann** [comment]
Yes, because some mod authors will make mods for beta/RC versions then either abandon them or fail to update them to make SMF aware that they're compatible with newer versions.

**Comment by illori** [comment]
but we should still limit how far down in emulation it attempts, we know mods for 1.1 and below will not work in 2.1 as they dont work in 2.0. even setting it to stop the auto emulation attempts at 2.0 would not be a bad idea since users can still manually emulate.

**Comment by XinYenFon** [comment]
It should be SMF 2.0 RC3+

**Comment by tekkla** [comment]
All over the world IT professionals are teaching to the "noobs" that beta/RC versions are NOT for use on live systems. Even you as SMF team are telling this to your users. I can imagine why you ignore your own advice with the emulation support for RCs, but it is some kind of weird inconsistency. :)

**Comment by XinYenFon** [comment]
Main problem, license - we can't edit the package for users if the mod license doesn't allow it. So either SMF needs to emulate that version, or users needs to give up on that modification.

Its true that we never recommend our users to use Alpha/Beta/RC builds, but we can't block them either. Personally if a person knows php/smf s/he can run Beta/RC builds very well, that also helps us, also I want to remind, in this beta/rc stage(s), we are not just testing core functions/theme -- we are also adding new background things (new hooks/classes), mod authors needs to test them as well. This sometimes ends with an author creating new mod or updating his/her to new version. As you can understand we are spending hour personal time here (as well as you/mod authors), so its very normal to all of us to leave SMF one day -- for some this dings to beta/rc period, so they leave their mods as well. We are encouraging our mod authors to choose open source license but still its up to them to decide which license they want to put to their mods. This small emulation trick saves all to some problem(s).

I hope this will clear your mind bit and removes the inconsistency from the situation :)

**Comment by tekkla** [comment]
No one talked about altering code from others. Or did I? What you say is what I meant with: "I can imagine why..." Does not change inconsistency at all. Never mind me asking. :)

**Comment by Arantor** [comment]
Which is funny since there's even a file available which lists the versions that can be autosuggested to the user... why not use that since it's already available to you?

**Comment by BitFros7y** [comment]
Correct me if im wrong but emulation system was introduced because smf used direct file modifications for extension of core (and it was a quick fix). If that is the case than emulation system is not even needed for SMF 2.1, or later as SMF will use hooks to provide extensions to the software. And please, i beg you not to mention Backward Compatibility. If you want something to be done right way than drop everything that is done wrong way.

**Comment by XinYenFon** [comment]
Not really, SMF 2.0 also has hooks, SMF 2.1 has A LOT more... But still emulation needed for some cases we listed above. I'm 100% sure in SMF 2.1 there will be some file edit mods.

Think about an author made modification for SMF 2.1 Beta X, and left the community, lets say that mod only uses hooks. In SMF 2.1 RC X that modification won't be recognized by Package Manager, it needs to emulate to SMF 2.1 Beta X.

**Comment by live627** [comment]
> drop everything that is done wrong way.

if only it were that easy...

**Comment by Arantor** [comment]
You can do an awful lot with pure hooks if you are extremely clever. Even some of the most vicious and unpleasant mods can be done with hooks... including things that theoretically shouldn't even be possible because the hooks don't exist. For example, the unread/unread replies page doesn't have a hook in 2.0 to add anything before or after the main list. This was, however, not even remotely a problem in SimpleDesk. A little bit of light tweaking and pre-empting actions as well as adding template layers, job done. It does get more complex if you're doing things like replacing PHPSESSID and pretty URLs type code, but even that is completely possible without file edits (as has been demonstrated before), but it really does require some serious understanding of SMF and how to abuse what you're given.

Going hook only presents technical challenges to current mindsets, and to my mind you're still missing half the infrastructure to make hook-only editing work, so raw edits (and by extension versioning) are realistically going to continue to be a problem. Unless the plan is to limit 3PD to a ridiculous level because going hook only is a barrier to entry that too many new modders will not be able to get over, even assuming it's even possible. I see recent 2.0 mods that could only be done in 2.1 with hooks only under very specific and extreme conditions that I believe only a handful of people would be able to make happen (and not the original modders)

I'd love a hook only approach but more hooks and more facilities are going to be required to do that, which SMF will not be able to support without a redesign of larger components or even a complete rebuild of the entire theme system in the worst possible case; adding new things in is not a significant hurdle even when there aren't existing facilities, but altering what's already there is significantly more complex.
