### ISSUE TITLE
All theme files not copied over

### ISSUE THREAD

**Issue by JP1981** [SimpleMachines/SMF#203]
Creating a copy of default theme through ACP does not copy all relative css files or the relative paths are not found resulting in Admin & Post bit being messed up.

Example:  admin.css & jquery.sceditor.css

**Comment by ghost** [comment]
Thank you for your report JP1981 :)

Yes indeed, it doesn't copy all the new files that were added. This is intended as some files are called from the default theme by default (aka non-theme files). However, since now admin.css is a standalone file, it should be included in the files to copy array:

$to_copy = array('/index.php', '/index.template.php', '/css/index.css', '/css/rtl.css', '/scripts/theme.js');

Will look into this.
