### ISSUE TITLE
Double permission settings

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#2080]
Mentions has a permission setting on the settings page but also in the Permissions panel. I don't think we need the former.

**Comment by live627** [comment]
A few other permissions are also doubled like that. I think the inline permissions are more accessible.

**Comment by NanoSector** [comment]
I think it just fragments the admin panel. Permissions should IMO be in a central place.

Even then, the permissions shattered through the ACP don't take any/own into account.

**Comment by Dragooon** [comment]
It is to provide easier access to the permissions for relevant area so that
admins don't miss them, and mentions/likes don't have any/own to take into
account.

**Comment by illori** [comment]
i really dont see an issue doing this. if anything were to change maybe a link back to the permissions page so the admin knows they can set more permissions there as well.

**Comment by Arantor** [comment]
This is most notable for the calendar, actually.

I'm not against the idea of duplicating options across the admin panel to where they are relevant like that, despite my usual minimalistic style simply because the permissions area is somewhat more complex.

Unfortunately permissions _must_ be declared to the permissions area (but with a bit of magic you can expose them through inline-permissions in settings pages and keep them invisible in the main settings pages)
