### ISSUE TITLE
warning preview

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2147]
if sending a warning message to a user clicking on the preview button seems to do nothing at all.

**Comment by Oldiesmann** [comment]
This is due to leftover code from 2.0 that didn't get removed when that area was rewritten.

In 2.0, there were two divs - one for those without JS (which showed a select list with warning levels and their effect) and one for those with JS (which shows the fancy slider thingy). When the page loads, the non-JS div and preview button are hidden with JS while the fancier one is shown.

In 2.1, the code to hide the preview button and switch which div is visible is still there, but there is no "warningdiv1" or "warningdiv2" any longer - the warning slider isn't shown in a div and there is no div to show a select list for those who don't have JS enabled.

There are a couple ways we can fix this:
1. Just remove the remaining old code
2. Rework the changes in 2.1 to still include an option for those who don't have JS enabled.

The question here is whether it's still worth supporting users who don't have JavaScript enabled. I can't even find any statistics about it.

**Comment by live627** [comment]
1

**Comment by Oldiesmann** [comment]
While investigating #2149, I found that clicking the preview button is supposed to do something (albeit via AJAX), so I think the first option is our best. Still not entirely sure why clicking that button has no effect (possibly because of the other error), but will look into that as well.
