### ISSUE TITLE
blank im fields after save

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2149]
if you fill in the fields for AOL, ICQ etc in the forum profile and click change profile then return to the forum profile page, you will find the fields empty.

this also applies to the location field, i dont see any related errors in the error log.

my 2 custom profile fields seem to save just fine.

**Comment by illori** [comment]
seems this upgraded install is not showing the error if the input does not validate with the default regex

**Comment by Oldiesmann** [comment]
Even so, it shouldn't even be trying to validate those fields if they're blank because they're not required.

**Comment by Oldiesmann** [comment]
Quick update for those who haven't been following along.

First, I fixed the issue with fields being validated when they shouldn't be by deleting and recreating them. I'm not sure what that did, but it seems to have fixed the issues I was having with that.

Second, after some debugging, I found out why the error box wasn't being shown. It's due to sloppy coding within the JavaScript for previewing signatures and counting how many characters you've used. Long story short, the code to count characters hides that box if it's visible and your signature isn't too long.

There are some other issues with that code that need to be handled as well, but as I have limited time right now, I will go ahead and fix this issue and commit a separate fix to properly address the other problems.
