### ISSUE TITLE
Dropdown menus: mouseover or click?

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#2189]
The new section in the top-left corner (Username/My Messages/Alerts) requires a click to open each dropdown menu. This contrasts with the rest of the forum, where a mouseover opens up the dropdown menu (eg. the Main Menu, the Admin and Moderation Center etc). 

Perhaps it would be better to use one or the other method, but not both?

**Comment by illori** [comment]
if we had the top menu work on mouseover instead of click it could add more stress to the server as it would be calling the alerts stuff more times then needed.

**Comment by Arantor** [comment]
Which is why there are done on click, precisely because of performance concerns; other menus do not require potentially multiple database queries, which is why they are done as AJAX loads rather than having the data available every single page load.

In any case, on click behaviour has been demonstrated time and time again as being better from a usability standpoint, not to mention consistent between platforms.

I don't understand why this has to be discussed, I was under the impression this debate had already been had multiple times before and each time the same behaviour (go click menus everywhere) was decided upon.

**Comment by XinYenFon** [comment]
Also mobile :) click to open is better for mobile devices, we gonna do something similar for main menu as well...

**Comment by BitFros7y** [comment]
1. As said above, they are trying to avoid unnecessary requests to server. (It wont add stress on server as SMF is very lightweight, but from other point of view, these kind of optimizations are the reason why its so lightweight)
2. They are friendly with touch screens.
3. Some people like to fix header (or parts like menu's and avatars) so that its easy to jump from page to page, and click toggle menu's are way better than a dropdown in these case.

Im sure that everyone agree with these facts (As many people already said these things) and that its a good choice, so there is no need to change anything.

**Comment by smfbigguy** [comment]
Leave things as they are now. All the menu's work fine.

**Comment by ChainyEO** [comment]
@qICEp 

The point is that click menus are only being used in the section at the top left-hand corner at the moment. The rest of the forum uses mouseover. So apparently there is a need to change something.

**Comment by XinYenFon** [comment]
I give you a simple answer @ChainyEO : No.

**Comment by ChainyEO** [comment]
@Antes

No to what? You seem to be in favour of click menus:

> Also mobile :) click to open is better for mobile devices, we gonna do something similar for main menu as well...

**Comment by ChainyEO** [comment]
According to the comments above, there are good reasons to have click menus in the section at the top left-hand corner (Username/My Messages/Alerts). So perhaps it would be good to use click menus for the rest of the forum for the sake of consistency. This is why I don't understand the comments about there being no need for change (as we currently have a lot of mouseover menus).

**Comment by Oldiesmann** [comment]
If we go "click to open" everywhere, how do we handle the current situation where the item you hover over to open the menu is a link as well?

**Comment by XinYenFon** [comment]
SuperFish working fine with iOS afaik @AngelinaBelle said, so we just need to adapt that fix to WP/Android (I don't have android device), afaik there is a fix for WP7 IE10 in SuperFish but WP8 (IE10/11) not working well. So we don't need to rewrite the menu for this version, we just need to fix some device issues (and some styling for mobile -small screen-).

Also compatibility issue reported here: https://github.com/joeldbirch/superfish/issues/121

**Comment by smfbigguy** [comment]
There is a good reason for having things like this then that is good enough for me really. All works good I think.

**Comment by XinYenFon** [comment]
Seems, superfish working good on Android as well, (probably on IE9/10 WP7) problem here, after reading report linked above, WP8/WP8.1 and IE10/11 is not defined in SuperFish. So this is not SMF side problem :)

**Comment by Arantor** [comment]
Consistency is a wonderful thing to have. It makes everything feel coherent and as though it was designed to be that way rather than being thrown together.

**Comment by Oldiesmann** [comment]
I'm fine if we do click to open, but we'll have to rewrite a bunch of menus and such in order to do so.

**Comment by Xarcell** [comment]
+1 click to open everywhere. 
+1 to get rid of superfish. 
+1 to make the on-click menus without javascript.

**Comment by XinYenFon** [comment]
tbh I don't want to stall SMF 2.1 for this. SuperFish working very well, we'll change things in SMF 3.0

**Comment by Arantor** [comment]
> +1 to make the on-click menus without javascript.

HOW?

**Comment by live627** [comment]
Using :active? I'm also wondering.

**Comment by Xarcell** [comment]
There are 4 ways that I know of, but each having their pro's and cons. 2 of which that will work in IE8+.   So those are the two that I focus on. I'm currently trying something a little newer with :focus, by re-visiting it. I'll know you know if I make progress with it. Probably end up replacing the css only drop menu I use on my current sites.

Ways To Do It:
1.| Using a hidden checkbox, my preferred method because it's great to use with PHP.
2.| Using CSS2 :focus.
3.| using CSS3 :target
4.| Using CCS3 transitions.

I whipped something up here using :focus, but it's far from perfect, but I just started working on it: earlier  then stopped to take my daughter to the doctor to have her cast removed: http://codepen.io/anon/pen/iuhtn

You can see my first hidden checkbox attempt on a site I made as a true horizontal layout blogger theme for my site last year. Unfortunately it was scrapped because of horizontal scrolling issues in IE Touch. The menu should be still be responsive(haven't messed with it in awhile, did some experiments that broke some things, but you should get the idea.). Anyway, by resizing your browser you can see how I tried to implement what I call "transitional design", basically switching from vertical to horizontal depending on orientation or device used: http://xarcellstudios.blogspot.com/

What I put together back in April of this year, but didn't finished. It was another hidden checkbox menu(no-js). It has it quirks, but it's 100% fixable. I've been tied up with branding and photography past couple of months: http://www.xarcell-studios.com/

Please don't make fun of my sites. I know they are empty and not working well. I know the code is messy, but I prefer to work live. I've just been too busy with clients to address the issues on my site or stock it with content.

**Comment by Arantor** [comment]
Well, there's two things to consider. Firstly, IE8+ is still (as I understand it) the target baseline, so anything that doesn't work with IE8 is automatically off the table.

Secondly, accessibility. Which of these methods support keyboard navigation? Screenreaders? These are serious considerations.

**Comment by Xarcell** [comment]
The hidden checkbox method as seen in my site designs and the :focus method would work. These should suit all needs and accessibility, but some of the cons are additional HTML(which I don't care about, but others would). So I'm still trying to accomplish the menu task with :focus and without the additional HTML that would allow the CSS to be reusable by other scripts/plugins. I just updated the :focus method to have transition effect in codepen.  It's not perfect, but I'm still working on it. I've run into an issue with :focus children in sub-sub-menu items: http://codepen.io/anon/pen/iuhtn . I'm not sure if I can get around that, but if I find a way it would be golden.

However, if used for something like SMF, the :focus method would work great for css-only overlays/modals and menus, spoilers, etc, but things that needed to be saved; that would have to use the hidden checkbox method, which would require additional HTML(there is just no way around it). Board Categories come to mind.

Back when I was planning to fork SMF(but not anymore), I wanted to try to make it work without JS(except admin areas). I even had a method for modal fullscreen popups that are CSS only and work in IE8. Only thing I absolutely had no way of replacing was the post editor. Which just would end up being just a plain textarea and that wouldn't be appealing to the majority.

**Comment by Arantor** [comment]
Yes but where does any of that leave users with accessibility concerns?

Foregoing JS is really not the deal it used to be. (And even users with accessibility concerns don't use JS-free browsers)

**Comment by Xarcell** [comment]
Sorry, but I don't quite understand what you mean by accessibility concerns. 

As far as I know it works in IE8+ and all modern desktop browsers and recently all mobile browsers, even opera mini. It's an onclick dropdown menu in HTML & CSS2, but it should be fully tested.

I prefer it not just because it's js-free, but because it's less code and more flexible in terms of making it responsive and getting the design you want. Javascript restricts responsive design unless you add yet another Javascript plugin to accommodate. It's crazy to see 20+ javascript files being loaded into a webpage nowadays(check out popular WP themes on themeforest.net).  I'm more of a fan of server-side Javascript rather than client-side. So I'm just expressing what I would like to see and trying to answer your questions. Obviously this isn't for everyone because it's not common practice. Give it another 2-3 years to see if it catches on  or wait until the toggle state proposal is approved in CSS3.

I reckon I just don't have a good answer for you. Only my thoughts.

**Comment by Xarcell** [comment]
I found this 2 year old article that might answer some of your questions: http://tympanus.net/codrops/2012/12/17/css-click-events/

There are hundreds of other articles using more modern techniques, but none that I can find that cover all the various methods.

**Comment by Arantor** [comment]
Accessibility: making sure it works with people who use screen readers, or keyboard for navigation and things like that. There's a whole raft of other stuff that goes with it, mind, but that's where it starts.

:active should theoretically trigger when an element has focus by way of the keyboard, for example.

**Comment by Xarcell** [comment]
You can use tabindex attribute for keyboard navigation I believe, hidden or not. I don't know anything about screen readers though.

**Comment by Arantor** [comment]
The problem with tabindexes is that you have to bear in mind forms that _also_ have tabindexes.

**Comment by BitFros7y** [comment]
Remind me why do we try to complicate things?

**Comment by Arantor** [comment]
Because 1) not excluding a surprising part of the user base is important and 2) we have seen SMF in use on governmental websites that are required by law not to discriminate against disabled users. SMF has, historically, shown itself to be good with disabled users in general.

I see no real benefit to going no-JS in the menu except for the sheer 'look at me' value it generates. But if it is legitimately better for usability and accessibility, I could be persuaded.

Right now, though, there are better options for accessibility by employing click to open that actually responds properly to keyboard events (which, IIRC, the original menus did indeed to that), though I suspect the profile/PM/alerts menu I added would not (but because I'm no accessibility expert and because they do strange and special things like fetching content AJAXively anyway)

**Comment by Xarcell** [comment]
@qICEp 

If referring to me, then I merely voiced my opinion and answered questions about that opinion. By no means has anyone decided to implement non-js onclick events. This probably should have been discussed elsewhere.

If your referring to the originally question at hand, I think this is something that should be addressed IMO. I thought the SMF team agreed on onclick not hover events, and there is lack of consistency here that was pointed out.

**Comment by BitFros7y** [comment]
Actually i was referring to whole discussion above...Get rid of superfish, implement on click, dont use JS...I actually agree with On Click, specially because of touch devices but why would we do all that? Why not just use JS and go with easy way to use and implement, also we can implement some fallbacks for certain devices... You guys try to complicate things thats just not worth it...half of the themes will override your menu...

**Comment by Xarcell** [comment]
Again, no one is saying the dev team is going non-js. It was merely a discussion, bouncing ideas around and such. I don't see how it "complicates things" and "worth" what? There's no harm to anyone or the software. There's no unnecessary or unproductive work time involved. No one is being made to do anything.

I learned from this discussion, that while I can prove you can do onclick menus without javascript, accessibility is a major concern as Arantor pointed out to me. So now I'm going to explore more on screen-readers and such to see if I can overcome that obstacle. It definitely "worth" it to me, because it was a learning experience for me.

Not to mention if anyone else has the same idea(non-js), they can see this discussion and it'll be known to them that it's not an option at this time.

**Comment by Arantor** [comment]
> You guys try to complicate things thats just not worth it...half of the themes will override your menu...

Not _all_ of us. I don't like complicating things without a very sound reason. I can't speak for the team though.

**Comment by XinYenFon** [comment]
Last time i tried to get rid of SuperFish, menu was working perfectly on desktop. Not the mention SuperFish is very good with mobile phones with its latest update its working well with all major mobile OS(es) (Android/iOS/WP). Afaik some Android phones needs HoverIntent to work (which also inside SMF).

There will be some work for 3rd level menus for mobile but I don't expect major change from now on for this issue.

:focus not working with iOS (Safari), and party with mobileIE - never ever used :target so I stay away from that for now as well.

Thank you for your contributions.
