### ISSUE TITLE
Alerts and Notifications: confusing settings

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#2196]
- Why do we have two names for what seems to be the same thing (Alerts and Notifications)?. At first, I was thinking that the difference was that Alerts are via the new section in the top left-hand corner, with notifications continuing to be the traditional system of receiving emails. But then in the preferences for alerts, I can select to receive them via emails...
- What's the difference between the setting "Turn notification on when you post or reply to a topic." (in the General Settings) and "Follow topics I reply to" in the Alerts preferences? 
- The wording of this option confuses me: "When a topic I follow gets a reply, I normally want to know via..." Why "normally"? Will this option not always work? The same goes for the next option: "When a board I follow gets a topic, I normally want to know via..."

**Comment by Dragooon** [comment]
1. Mostly confusing leftover stuff, they're supposed to be the same
2. Ugh.....probably none, needs to be removed I guess
3. Choice of words I guess, I'm not sure if there would be any circumstances when they're not alerted for a reply/new topic.

**Comment by Arantor** [comment]
Mostly it was about not having finished the rewrite. I am very concerned that it has taken 6 months for this to be even noticed.

The reason for 'normally' is because the intention was that you would 'normally' want to follow the behaviour but you might set it otherwise for individual topics. E.g. normally have it set to send you one of the alerts, but for occasional topics it might send you an email instead. That certainly was the intention before it was very clear that any ideas I might have had were far too controversial and progressive.

**Comment by Dragooon** [comment]
Ohh right, there is code internally that would allow having per-board/per-topic preferences to alerts and emails but the UI was never completed.

**Comment by illori** [comment]
this was mentioned not long ago here https://github.com/SimpleMachines/SMF2.1/issues/1766#issuecomment-51715128

**Comment by Oldiesmann** [comment]
We need to decide what we're going to do with the remaining "old" settings (PM settings for instance) and get that cleaned up. I'd like to have as much of the alerts stuff done as possible by Beta 1. I realize betas are partly supposed to be buggy, but given that it's been 6+ months since alerts were implemented, I don't think it would look good to release a beta with the system unfinished.

**Comment by illori** [comment]
it seems the setting for email for pm's received has been fixed/moved at some point in the last month or so.

**Comment by Dragooon** [comment]
This has been mostly taken care with recent PRs
