### ISSUE TITLE
show bbc/collapse additional post options

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2218]
why do we have the option to not show the bbc buttons? why would we not want the additional post options collapsed by default? at least the show bbc buttons option should be removed. it is on the post settings page in 2.1 admin.

**Comment by live627** [comment]
> why do we have the option to not show the bbc buttons

I remember someone raised hell when I removed that. I'm of the opinion that the BBC buttons should always be visible.

No further comments from me on this one. >.<

**Comment by Arantor** [comment]
There's two quite separate issues here, and it's kind of bothering me that they've been lumped together, but anyway.

The show bbc button... as far as I'm concerned there is no good reason to hide them. If you don't want bbc, don't use bbc and turn the whole shebang off. If you want bbc, have the buttons and be done with it. The option to hide the buttons only should just disappear. Simplify the code, improve the user experience.

Truly sane defaults don't need to be options.

As for the other matter, regarding additional post options, there's two sub-aspects to that. On the one hand, I can see the validity of keeping them collapsible because too much presented to the user is probably a bad thing. Which means, in my mind, the question is not 'do we always show everything (and remove the choice)' but much more 'do we re-evaluate the current default'

I can see the wisdom of both sides to collapsing it, but in all honesty what I'd suggest is that if you're going to have it open by default, a rethink of the amount of stuff under the collapse would be in order. Too much stuff at once is a serious usability issue, and hiding a lot of that stuff in general is not a bad thing, whilst keeping it accessible for the (minority, in theory) times in which you need those things.

**Comment by illori** [comment]
i would rather keep the additional options to have the collapse option by default and no option to leave it open all the time.

**Comment by Arantor** [comment]
On what grounds? I'd argue that it depends on the community to a point; while many options is daunting, there's nothing more daunting than trying to do something and not having any obvious idea where to start with it.

**Comment by XinYenFon** [comment]
Hmm, actually that's not the option we are talking @live627 :P, I think removing hiding bbc setting is better. But I still in favor of keeping the collapse setting.
