### ISSUE TITLE
Paid Subscriptions menu item always available, even if paid subscriptions aren't available

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#2229]
As the title says, when you click the button http://i.imgur.com/40oRh46.png you get this message:
Sorry, the admin has not yet finished setting up paid subscriptions. Please check back later.

**Comment by illori** [comment]
cant duplicate this. if i disable paid subs on the settings tab it does not show up in the profile at all.

**Comment by live627** [comment]
I can

**Comment by illori** [comment]
then you have paid subs enabled but not fully configured? it has been like this in 2.0 as well.

maybe we should make it more apparent that the email address is required although the text under it says you can leave it blank.

**Comment by live627** [comment]
> then you have paid subs enabled but not fully configured?

yes

**Comment by Arantor** [comment]
Except that you can't predicate it based on that.

There is no way to indicate in the profile area menu that paid subs are configured properly, because it would have to contact each of the payment processors currently installed (just because PayPal is the only one currently available does not mean it is the only one that could conceivably be available) to see if there is at least one configured and ready to go.

**Comment by Oldiesmann** [comment]
Does it still show up in the profile if you haven't defined any subscriptions? We can handle that situation pretty easily at least.

**Comment by illori** [comment]
yes

**Comment by Oldiesmann** [comment]
Ok. That should be pretty easy to work around then.

**Comment by illori** [comment]
actually, it gives you a different message if you enter your email address...

"You haven't set up any subscriptions yet. "

**Comment by Oldiesmann** [comment]
Yeah, we can handle that one. The other error message only occurs if there are no valid payment gateways (either no gateways were found or none of them have a "form" defined in their fetchGatewayFields method). Hiding the menu item when there are no active subscriptions should prevent users from getting that message in most cases as well (since it's not likely there will be subscriptions defined if there aren't any valid gateways).
