### ISSUE TITLE
Calendar Stats Plural

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#2326]
Of german language is holidays = Feiertage. 
$txt['calendar_prompt'] = 'Holidays';

In the Calendar view, the plural is incorrect:
![calendar-german-plural](https://cloud.githubusercontent.com/assets/2753863/4267916/60d3432a-3ca5-11e4-825b-fd651d1f6ff8.PNG)

In the calendar week view, the plural is correctly
![calendar_week-german-plural](https://cloud.githubusercontent.com/assets/2753863/4267922/7ff90140-3ca5-11e4-8a9b-b7cf3bb08826.PNG)

**Comment by illori** [comment]
same issue basically as #2020

but maybe having different strings in each place here may fix the issue

**Comment by Oldiesmann** [comment]
This is one of those things that we really can't fix easily. We can fix it for "1" vs "more than 1", but that may not be correct in all languages. I think this, along with what's mentioned in #2020, is something we'll just have to live with for 2.1. Trying to fix it for every language gets unnecessarily complicated and makes the code more bloated since we have to add conditionals and such for each language that doesn't follow a standard convention.

**Comment by ChainyEO** [comment]
In this particular case, the problem seems to be that one string is being used for two places, one of which requires the singular, and the other requires the plural. So, this could probably be solved by having two separate strings, one for the singular and one for the plural. 

Even with two strings, in the month view (as shown in the first image above), there would have to be some kind of condition, whereby the plural is shown if more than one holiday is shown on that particular day.

I think this particular case is solvable. It doesn't seem as complicated as some of the other issues we've come across for the plural.

**Comment by ChainyEO** [comment]
@Oldiesmann 

This particular case can indeed be solved by the simple fix of "1" vs "more than 1". The words are standalone, not part of a sentence, so the simple fix would be enough for _all_ languages.

**Comment by Oldiesmann** [comment]
If we use singular there, then it's wrong in the case of multiple holidays on the same day (not likely, but it could happen - especially on international forums where the admins wish to acknowledge holidays in countries other than the US as well).

**Comment by NanoSector** [comment]
What about Feiertage: (note the : )
That makes the sentence a list, where it doesn't matter whether singular vs plural is used if only one item is available.

**Comment by NanoSector** [comment]
Bump?

**Comment by Oldiesmann** [comment]
Adding a colon there is probably our best bet. I'm a little hesitant though because I don't know if it's used that way in all languages or just most of them. The best option is probably to do it in CSS since that same string is likely used in multiple places.
