### ISSUE TITLE
improper use of closure

### ISSUE THREAD

**Issue by Underdog-01** [SimpleMachines/SMF#2427]
Oldiesmann,

  I already wrote a fix for this a little while ago yet you reverted it with this PR:
https://github.com/SimpleMachines/SMF2.1/pull/2418

The code you have there is not working properly and I do not believe you are using the closure correctly.
Using the concerned function to filter a string containing single quotes (apostrophes) throws an error.
As far as I have read from the documentation on anonymous closure functions, you can't put more than one variable within the brackets and other variables to be used in the function must be within the 'use' language construct. 
ref.
http://php.net/manual/en/functions.anonymous.php

Imo do not always pay attention to the user examples below the actual docs whereas those have to be tested for yourself because sometimes people post wrong use of code in error. This is the way I interpret those docs and of course have used closures often. None the less the code you posted there causes an error and needs to be fixed.

Regards.

**Comment by Oldiesmann** [comment]
There is a difference between function parameters and the variables passed via "use". Your change caused "undefined variable" errors (see #2412), since those variables are supposed to be function parameters and are not defined outside that function. That's why it was reverted. There is nothing that prevents you from having anonymous functions with multiple parameters either. In fact, there are three other instances of this behavior in the same file (see 'strpos', 'substr' and 'truncate' for $smcFunc).

What error is being generated now?

**Comment by Underdog-01** [comment]
Interesting, I did not think that was the proper syntax.
My apologies as I read the error I was seeing incorrectly and it is not related to those changes.
The issue I was seeing in the past from that area of code prior to either of us adjusting it is not occurring any more.

I believe the issue I am seeing now is somehow related to changes in the un_htmlspecialchars function whereas certain characters are not being converted properly. I will close this report and either file another report with the proper reference else post a PR for fixes/changes.

The issue I now see occurs when un_htmlspecialchars is used on a string and then using eval() to execute said string (ie. Simple Portal preview block). Imo the un_htmlspecialchars should be converting all html entities to their applicable literal characters but it is not. 
Regards.

**Comment by Underdog-01** [comment]
Here is the PR reference:
https://github.com/SimpleMachines/SMF2.1/pull/2429
