### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#2450]
I'm getting some validation errors in several parts of my test board.
- Admin (main page)
  Line 599, Column 33: Element object is missing one or more of the following attributes: data, type.
  `<object id="quick_search">`
  Line 600, Column 137: Element form not allowed as child of element object in this context. (Suppressing further errors from this subtree.)
  …ion=admin;area=search" method="post" accept-charset="UTF-8" class="floatright">

**Comment by XinYenFon** [comment]
I think you are not on the latest build, please update your build :) I did some changes with https://github.com/SimpleMachines/SMF2.1/pull/2425

**Comment by margarett** [comment]
Ups, sorry :tongue: 

Yet, there are still errors...
- MessageIndex:
  Line 276, Column 57: Duplicate ID notify_dropdown.
  `<div id="notify_dropdown" class="top_menu dropmenu">`
- Display:
  Line 380, Column 57: Duplicate ID notify_dropdown.
  `<div id="notify_dropdown" class="top_menu dropmenu">`

And in Admin, the same errors about quick search are still there...

**Comment by XinYenFon** [comment]
Yes I'm aware that, to open drop-menu we need JS, and that JS snip using ID part to do its job :) Oh can you please also remove the errors you are not getting anymore, so I can track them easily. thanks ^^

**Comment by margarett** [comment]
Done ;)

**Comment by Oldiesmann** [comment]
Couldn't we just use a CSS class for those instead of duplicating the ID?

**Comment by Oldiesmann** [comment]
The object issue was fixed with #2454, and the rest of this has now been fixed with #2457. Further investigation into the issue revealed that the ID for the dropdowns wasn't even being used anywhere. The JS for updating the button text (when selecting an item from the notifications list) wasn't working either because it was referencing an element with an ID of "button_strip_notify" rather than one with that class...
