### ISSUE TITLE
Eval injection findings

### ISSUE THREAD

**Issue by kpawloski** [SimpleMachines/SMF#2494]
One of the sites I work with is using SMF and recently has been being static analysis on their code. Since SMF is wrapped into the site as apart of their forums, the SMF code ends up being analyzed by the scan. Anyways, two files are being flagged for potential eval injection. (Duplicate code)

register.template.php
$field['options'] = eval($field['options']);

profile.template.php
$field['options'] = eval($field['options']);

Just wanted to pass this along to have a set of eyes verify that the input is sanitized prior to it getting to that eval line.

**Comment by Arantor** [comment]
Firstly, the input for those functions is not sanitised because it is not user-facing.

The definitions for these things can be found inside Profile-Modify.php where it defines a function in a string to be called during the templates to get the data for them. This is, therefore not a security matter.

Secondly, this is the repository for 2.1 - not 2.0. 2.1 has quite different code using closures instead of evaluated strings. If you find issues with 2.0 please report them to simplemachines.org rather than here to avoid confusing matters; 2.0 is not presently on Github and being reported here may end up serving to delay any resolution that might be required rather than expediting it. (Since issues reported here are assumed to be 2.1 rather than 2.0 issues and since this does not affect 2.1, it would logically just be closed, and action if it had been required for 2.0 might not have occurred. Fortunately in this case, no action is required.)

**Comment by kpawloski** [comment]
Thanks for the clarification!
