### ISSUE TITLE
More bugs...

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#2516]
Local cookie don't work, because the CHECK value from template POST returns always FALSE

**Comment by MissAllSunday** [comment]
Where exactly does this happen? Do you mean the post.template or any _POST request?

**Comment by live627** [comment]
Looks like it stems from SMF  trying to be smart https://github.com/SimpleMachines/SMF2.1/blob/354f8c1893c1f442deba64e38c7ba8b6c74bed76/other/install.php#L1172

**Comment by sbulen** [comment]
I think there are two separate issues raised in this thread:

(1) The OP points out that local cookies don't work.    I do not think this is the case anymore, I can choose local on or off in the ACP, and inspecting the cookies, with local ON, the forum path is properly represented, and with local OFF, there is no subfolder noted in the cookie.  So, the ACP works, and as near as I can tell, the local cookie setting is doing exactly what it is supposed to do.  (Note when testing: clear browser cookies after modifying the local cookie setting in the ACP so you don't use the old, now-bogus cookie, or bad things happen...  Which may have been the original problem.)

I'm pretty sure there is no action required here.  

(2) As live627 points out, the installer logic for choosing default settings for cookies is wonky.  The pregmatch is seriously screwed up, and even if it gets fixed, the subsequent logic seems questionable to me...   The upshot is that I believe the installer will end up setting both the local & global cookie settings to FALSE most, if not all, of the time.   This will mean no subfolder support & no subdomain support upon install, the settings must be manually set.

To address, we can either fix the pregmatch, or, simply delete this logic and allow the settings to remain FALSE upon install.

**Comment by Sesquipedalian** [comment]
Maybe we could just ask the admin during install whether they want local or global cookies?

**Comment by sbulen** [comment]
Reading the code, it appears 2.0 uses the exact same logic upon install...  I.e., it seems to be low priority.

Between asking users for more info during install, or, fixing the default logic, my sense is to fix the default logic.  It would be more friendly, and will probably be less error prone.  

So, my input is to keep this open & low priority, with the recommended solution being to enhance & test the default logic in the installer.

**Comment by sbulen** [comment]
I'll be submitting a PR for this over the next couple of days.  Regarding the 2 issues noted above:

(1) Setting Local cookies appears to have been resolved at some point.    Unless someone find a way to reproduce the initial issue, there will be no action taken.

(2) Regarding the wonky installer logic...   

- The existing logic looks for a subdomain in $boardurl, and attempts to set globalCookies if found.  Three issues: (A) due to a problem with the preg_match, it never detects a subdomain, (B) it should mirror the ACP logic and also set globalCookiesDomain with the top-level-domain (TLD) but it does not, & (C) it is hard-coded to only recognize certain subdomains (e.g., forum, community, board) which is an unnecessary constraint, and worse, will not work for non-english languages.  All 3 issues will be addressed.
- The existing logic looks for a subfolder in $boardurl, and attempts to set localCookies if found.  Due to an issue with the preg_match here, it will ONLY find sub-sub-folders (e.g., mysite.com/myboard will not be detected, but mysite.com/myboard/smf will be).  This will be addressed.

**Comment by sbulen** [comment]
PR #4340 submitted.
