### ISSUE TITLE
Modal in PM Button

### ISSUE THREAD

**Issue by apiweb** [SimpleMachines/SMF#2549]
I think it would be interesting if the Private Message button in a topic, open a Modal, with the form to sending the message, instead of opening a new page.
Thus, it would be faster and more practical to contact other users. For the user would not need to load a new page to send.
In addition to not have to leave the current page.

**Comment by XinYenFon** [comment]
I like this idea, but unfortunately feature requests must go [Feature Request](http://www.simplemachines.org/community/index.php?board=3.0) page.

**Comment by Arantor** [comment]
Strongly disagree, the dev time required to this simply does not justify the benefit IMO.

**Comment by live627** [comment]
How different would this be from the login popup?

**Comment by apiweb** [comment]
I'm sorry Arantor, but disagree completely.
What may not be worth it to you, you might consider for others.
Today, we have many people accessing the mobile phone, tablet, etc ... Reduce the loading of a page, it is a great go forward.
With this suggestion, people click on the button, open the modal, send message, and return the discussion, without even having to leave the topic page, continuing the discussion.

If the SMF provide any API, or implement some modal library, I can develop this modal, and make a PullRequest.

**Comment by Arantor** [comment]
@live627: The login form had to be modified non-trivially to achieve this.

Here's the problem, though, @apiweb - doing this requires a rewrite of large parts of the PM code, because of the way the workflow works (how, exactly, would previewing work in your mentality?) not to mention the various asset loading that has been rewritten since 2.0... you'd end up rewriting the PM code to make it work - and make sure you don't break it in the meanwhile for normal use.

This is far more work than you give it credit for - it is not just having the modal library (though SMF does have its own facility for this in 2.1)

**Comment by live627** [comment]
Seems best to not do this for 2.1.
