### ISSUE TITLE
avatars

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#2573]
Just wanted to ask...is it really necessary to have two avatars in the same location. I would like to maybe bring up the idea of the small one being removed. 
![avatar](https://cloud.githubusercontent.com/assets/3620111/5326681/447f0478-7cf3-11e4-8c50-adc78fa5c510.png)

**Comment by smfbigguy** [comment]
If there has been discussion on this already and it is set in gold the way it is well, that's fine to. It was just a suggestion. :)

**Comment by Oldiesmann** [comment]
I don't know that there's a specific reason for it being in both places. It was only in the mini profile first, then only next to the username. This is apparently a compromise to please both sides. Since a template edit can remove it from either place, I don't think it's worth trying to keep it in only one spot.

**Comment by smfbigguy** [comment]
Ok, no problem, thanks for posting. :)
