### ISSUE TITLE
Errors on install a new language

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#2607]
A lot of errors came up from the Subs-Package.php on install a new language...

file_exists() expects parameter 1 to be a valid path, string given (line 185)
is_dir() expects parameter 1 to be a valid path, string given (line 1729)

Feline

**Comment by Oldiesmann** [comment]
This is going to be a tough one to debug, but it would help to know exactly what was passed to file_exists() there (the second error is due to the mkTree() call on line 186 of Subs-Package.php). Can you provide the package you're trying to install? I think it will be a bit easier to debug if I do it on my own board where I can compare the info passed to those functions with the actual paths.

**Comment by MissAllSunday** [comment]
I believe this is related to the changes on the packager manager and handling zip files, still need to debug this further to really know whats going on.

**Comment by Oldiesmann** [comment]
Add `log_error('Destination: ' . $destination . '/' . $context['file'], 'debug');` on line 184 of that file to see what's being passed to those two functions.

**Comment by Oldiesmann** [comment]
Anyone have any updates on this? If not I'll go grab a language pack from the language editor and test it myself when I get a chance.
