### ISSUE TITLE
upgrade.php run doesn't save old date/time format setting correctly

### ISSUE THREAD

**Issue by bperry921** [SimpleMachines/SMF#2715]
I've noticed that an upgrade.php run doesn't keep the old set of "date/time" formatting setup properly, it keeps lopping off the last few characters where i put the :%S, it keeps the front ones fine where i added %a, however...

**Comment by Oldiesmann** [comment]
What specific format string are you using? The upgrade script shouldn't be messing with that setting at all.

**Comment by bperry921** [comment]
All I know is every time I run upgrade.php, I have to go back and add the last part of the string I normally use, which is %a, %b %d, %Y, %H:%M:%S, it always truncates the characters after %M...

**Comment by Oldiesmann** [comment]
Did some digging and see what's going on. We changed the default time format in 2.1 (replacing the full month name with abbreviated month name and dropping seconds), and someone decided that we should do the same for the time format on the update as well. I'm not sure why, and I'll remove the code since we have no way of knowing whether the user wanted the current time format to be that way and the current method messes up other formats as well.
