### ISSUE TITLE
duplicate settings? notify of items awaiting approval

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2778]
in the moderation center there is under settings notify of items awaiting approval and a similar setting in the profile under notifications When an unapproved topic is created

i think the option in the moderation panel should be removed.

seems no other settings on that page so maybe remove it?

**Comment by live627** [comment]
Looks like that is for the weekly digest.

**Comment by illori** [comment]
It was not in 2.0 if it is in 2.1 the name should be changed.

**Comment by illori** [comment]
if it is a digest, it does not seem to send out a digest. i have many topics still waiting approval and no digest being sent out.

**Comment by margarett** [comment]
I don't really know if that is used anywhere, really...
That updates mod_prefs in smf_members but looking at it throughout the code, I don't really understand what it does... It's mentioned in Scheduled Tasks and GroupReq-Notify.php but I really don't see how it's used...

**Comment by illori** [comment]
i dont think it is used, it should be replaced with the feature listed in the notifications area of your profile.

i guess if we remove this "feature" it would also solve https://github.com/SimpleMachines/SMF2.1/issues/1156

**Comment by illori** [comment]
FYI, i do have the box checked and topics awaiting approval. the scheduled task fails to send the email that anything is waiting approval.

**Comment by jdarwood007** [comment]
@illori I don't see any options under the moderation center settings.  This looks closable now?

There isn't any settings to display, but I would leave it incase mods add any.

**Comment by illori** [comment]
If it has been moved then close this. I can't check right now.

**Comment by SychO9** [comment]
@jdarwood007 it hasen't been removed, you just have to enable post moderation

https://github.com/SimpleMachines/SMF2.1/blob/05ee2be48cbbe1a8e23c18b96568d9494206318d/Themes/default/ModerationCenter.template.php#L506-L524

**Comment by illori** [comment]
Reopened

**Comment by jdarwood007** [comment]
Your right.  I didn't check the code just saw it empty.

**Comment by Sesquipedalian** [comment]
From what I can tell, this is not so much a duplicate setting as it is an obsolete setting to control what appears to be an obsolete system of sending out notifications to moderators about items needing approval.

Unless I am understanding things wrongly, the addition of the `ApprovePost_Notify_Background` task in #2739 rendered the old system for sending out such notifications (using `scheduled_approval_notification()` and the approval_queue table) obsolete and redundant. But the old system was never removed from the codebase. Assuming that I am correct in my understanding, removing that setting in the moderation centre should be part of ripping out all that code as well as the approval_queue table and the related columns in the members table.

**Comment by betonkamil** [comment]
First of all you say rc 1 bitin rc 2

**Comment by Sesquipedalian** [comment]
@live627, would you mind if I assign this one to you? 

As I said in my comment above, it appears that what is really going on here is that your addition of the `ApprovePost_Notify_Background` task in #2739 created a new system for sending out notifications about posts that needed approval, but the old system has not been dismantled and removed yet. (The confusing setting in the Moderation centre is merely a component of the old system.)

Ideally, I'd like:

1. All four types of "approval needed" notifications (post, topic, attachment, and event) to use background tasks. Currently, only the post and topic ones use background tasks, while the attachment and events ones only use the old method (i.e. using `scheduled_approval_notification()` and the approval_queue table).
2. The `scheduled_approval_notification()` and the approval_queue table to be removed.
3. The setting in the Moderation centre that this issue report was originally complaining about to be either turned into an alternative UI for the same setting that can be accessed via the main notifications settings area in the user's profile, or simply removed.

I ask if you're willing to take this because you've done work in this area in the past, whereas I would need to spend a while making sure I was completely up to speed on all of this before I could even start working on changes. It's probably much more efficient to let you take point on this.

**Comment by live627** [comment]
I'm now looking into this and `approval_queue` also does attachments. I'll probably need to write a new background task for handling those... lest they be lost.

**Comment by live627** [comment]
Ohh, I may want to keep the table because it provides a nice list of unapproved posts within the moderation center. Otherwise all of that will just be buried in alerts.

**Comment by Sesquipedalian** [comment]
Thanks for taking it.
