### ISSUE TITLE
removing ban triggers not logged

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#284]
Adding a ban trigger is logged, removing one is not.

Full report:
http://www.simplemachines.org/community/index.php?topic=495656.0

**Comment by Oldiesmann** [comment]
Started looking into this, and it's going to be a bit of a pain in my opinion.

When you go to delete bans/triggers, SMF just deletes them based on the IDs passed to the function.

To fix this, there are two options that I can think of:
1. Find a way to pass all the info about each trigger in $_POST (hidden input fields maybe?)
2. Run a query to get all the data.

Once we have all the data we need, we simply load it up into an array, pass it off to validateTriggers (since that will handle the log info for us), and log it like the other functions do. After that it's a simple matter of tweaking the code for the log to handle removal of bans.

**Comment by emanuele45** [comment]
At the moment I don't remember what is logged adding the ban, but I suppose that if you can pass the data by POSTing then you can retrieve them after the POST...no?

**Comment by Oldiesmann** [comment]
Yes, the IDs of the ban items we're deleting are passed from the form, so we'd just need to pull all the info and create a nice array akin to that returned by validateTokens(), then pass the log info off to the log function. After that it's just a few minor code tweaks to handle removal of bans.

**Comment by Oldiesmann** [comment]
Before I start to work on getting this fixed, is there a way we can pass all the details via hidden input fields? It seems a bit silly to load all that info a second time just so we can log what was deleted, but I don't know enough about createList to know if there's an easy way to do the hidden fields.

**Comment by emanuele45** [comment]
The problem with passing through an hidden field is that then you have to rely on the validity of the data sent by the user...
I wouldn't rely on that.

And BTW, what you have to load is just the data of the trigger...1 query, not so much I think.

**Comment by Oldiesmann** [comment]
It is just one query, but it just seemed silly to reload everything. If that's the best way though, I'll go that route.
