### ISSUE TITLE
Find and repair any errors page redirects with Token verification failed.

### ISSUE THREAD

**Issue by FearThe1337** [SimpleMachines/SMF#2876]
E.g. when having polls which do not have a valid post, you will receive a link or automated redirect to recount statistics. Clicking this results in a "Token verification failed.".

**Comment by MissAllSunday** [comment]
@FearThe1337  Are you still able to reproduce this error?

**Comment by illori** [comment]
if you manually in the database alter a topic to be in an invalid board or no board, then run the repair when the option comes up to recount statistics and click that button you end up on the token validation failed error. so yes it still happens.

**Comment by MissAllSunday** [comment]
I cannot replicate this issue.

Token issue will be extremely hard to track down or even repair as it largely depends on how a page is accessed and when.

RepairBoards should have its own token and not depend on validateToken('admin-maint');  but then again, every page/action that calls RepairBoards(); needs to create that token first.

**Comment by illori** [comment]
did you follow the steps i provided?

**Comment by MissAllSunday** [comment]
Yes, that should be already implied.

Anyway, try changing Sources/ManageMaintenance::256 

from this:

validateToken('admin-maint');

to this:

validateToken('admin-maint', 'request');

Thats pretty much all there is to do here.

**Comment by illori** [comment]
that did not make the error go away.

maybe the token is missing from the template?

```
                        <form action="', $scripturl, '?action=admin;area=maintain;sa=routine;activity=recount" id="recount_form" method="post">
                            <input type="hidden" name="', $context['session_var'], '" value="', $context['session_id'], '">
                            <input type="submit" name="recount" id="recount_now" value="', $txt['errors_recount_now'], '">
                        </form>';
```

i am just not sure which token is actually missing to add it.

**Comment by MissAllSunday** [comment]
Tokens are different than the session var 2.0 uses, they aren't added to template files but are always created server side and always checked on server side.

A problem with tokens is that you cannot do things like follow an url to an admin action that has a check on a token since that token was never created in the first place.  Same for some ajax actions.

Something like that happens here, an admin page creates a token and then it send you to another page (fix board errors action).

Sadly, I wasn't really around by the time tokens were applied to fully know their extent and limitations. I can only speculate.

**Comment by illori** [comment]
Token are defined in the templates. Look around and you will see them. I
believe sleepy created them so maybe he can help here.

**Comment by MissAllSunday** [comment]
ugh, thats weird then, tokens shouldn't be added to template files.

**Comment by jdarwood007** [comment]
Token get added just the same way that we add session var and value into templates for all forms.

If a place has a bad link due to a token, we should adjust the code to create the valid token.

I attempted to create it in a simple way, a create function and a validate function.  The information still needs to be added into the template, which is why when you create a token, it adds it into the context under the variable you specified when creating (i.e. createToken('admin') creates a $context['admin_token_var'] and $context['admin_token_value']).  On createToken you can specify as a second argument 'post', 'get', or 'request' to tell it where the token is valid for, by default only valid for post.  validateToken is the same way you need to tell it where the token should be and if it can't find it and validate the token matches, you get the token match error.
