### ISSUE TITLE
Disallow at symbols (@) in username?

### ISSUE THREAD

**Issue by FearThe1337** [SimpleMachines/SMF#2880]
I am noticing that over time there have been quiet a few users who have filled in their email instead of a nickname, and show up at the memberlist as name@domain.tld

I would say that this is bad for the following reasons:
- Spam bots might find the email adresses from the memberlist or from google if the memberlist is public
- Privacy, there is an option to not allow emails from other forum members for a reason
- Might block e-mail recovery. [1]

I would suggest disallowing at symbols to prevent users from making this mistake.

[1] When doing password recovery the user either fills in their username or password to recover their account.
The recovery first checks if there is a matching username, if not, then it attempts an email match. If a user would exist with the email address of an other user, then it would pick the username with that email address. Effectively breaking the recover by email feature.

**Comment by illori** [comment]
the first 2 options IMO are up to the admin and user. if they want to be stupid then that is their problem. if it really does break the email recovery feature then we need to consider options or a way to allow it and not break that feature.

**Comment by FearThe1337** [comment]
Third option would only be an issue if the user has forgotten their username.
Although you mention if the user wants to be stupid, on a forum with 5963 users, 18 registered with as username their email. In statistics this is 0.3% of the users.
Even though it is small, it made me wonder if it should not be disallowed by default.

The only way to fix option 3 would be to add a selection between email and username on the initial form.

**Comment by illori** [comment]
what would you do with users that have already registered with their email address as username?

**Comment by FearThe1337** [comment]
I would personally prefer leaving those alone. I guess the best way would be to block the @ symbol in new registrations and name changes.
In the case that someone would indeed have the above mentioned issue 3, I think they should contact the admin of those forums.

**Comment by illori** [comment]
if the admin does not have an email address visible somewhere on the forum, how would those users contact the admin to get a reset?

**Comment by FearThe1337** [comment]
In that case the only way would be to make the user specify that they are entering the email or username in the recovery form.

BTW: "the first 2 options IMO are up to the admin and user. if they want to be stupid then that is their problem."
I do hope you realize http://www.simplemachines.org/community/ has around 40 pages of results when searching the memberlist for name '@'.
The first 5 pages has 28 email adresses in them (so, x8 = 224 emails)

**Comment by LiroyvH** [comment]
Note that in SMF 2.0, using the e-mail address as the username actually stops the pre-hashing we have in place to more securely transmit the password. So if e-mail address used as username == e-mail address on account, it won't pre-hash. (The password will still be stored perfectly safe, but the login features "send as hash" thingy won't function. I forgot why that is the case.)
The same occurs when people login with their e-mail address instead of username, which is allowed; and why this happens.  

At least, that's how I remember how it functions. Might be incorrect by the way, don't take me for an authority on SMF code. ;) The devs will know better and I could be completely wrong. :)

I'm not sure how this is in 2.1 and whether or not this has been improved, but if it's still the same scenario: I'd say it might indeed a be a good idea to block the use of e-mail addresses for new registrations, unless SSL is active. (Existing registrations should naturally not be affected)

**Comment by margarett** [comment]
IIRC, with 2.1 and bcrypt, the password is not hashed client-side anymore.
