### ISSUE TITLE
Load popup doesn't load

### ISSUE THREAD

**Issue by ncoelho** [SimpleMachines/SMF#2908]
Fresh install, when you click in the username. Didn't find this reported.

Database Error 
Unknown column 'mem.tfa_secret' in 'field list'
File: /home/.../public_html/.../Sources/Load.php
Line: 1170

**Comment by MissAllSunday** [comment]
You are either running an old SMF 2.1 version or a SMF 2.0 database.

If you are running a test enviroment then simply start over with the latest code from the release-2.1 branch, if not you will have to manually add the tfa tables to your database.

I was in a hurry, let me expand on this.

This issue happens because you are using recent files with an outdated database, the code is looking for tables your database do not have.

There are two options, if you are running a test site, then simply start over again, delete both your DB and your files and install the forum again.

If not, then manually add the tfa column in the members table, you can find some sql code in the upgrade files, that would give yon an idea about what to add.

**Comment by live627** [comment]
Seems like updated the files but forgot to run the upgrader.

On Sat, Jun 27, 2015 at 10:26 AM, Jessica González <notifications@github.com

**Comment by ncoelho** [comment]
I was able to solve by run the upgrade.php

But I was running the last code from master on a fresh install just to test :/ I'm pretty sure I was...
