### ISSUE TITLE
constructBanQueryIp() will return wrong query

### ISSUE THREAD

**Issue by Elsensee** [SimpleMachines/SMF#2968]
I'm talking about this: https://github.com/SimpleMachines/SMF2.1/blob/939347d4bfdba0194744996d34f9d29abe6544ec/Sources/Security.php#L1273

Let's say you got the range 123.241.98.29-129.23.53.100 in the database and the IP you want to check against that is: 124.10.89.211
The comparison for block1 will be: `124 BETWEEN 123 AND 129` which is true, of course.
For block2 it will be: `10 BETWEEN 241 AND 23` which is false, although the IP is in that range.

Just stumbled across this issue when trying to test the performance of various solutions for IP banning and just wanted to see if you got the same issue. ;)

**Comment by joshuaadickerson** [comment]
This issue comes up every now and then. The issue with fixing it is pretty much just resources.

Besides documentation, which I think is needed, I think the next easiest step is to create rows in the database for the range. So, if your first block is 123 and the last is 129, you would have 7 rows dedicated to this range. The first would have all of its "low"s matching the start and the high would be 255. The last would have all of its "high"s matching the end and the low would be 0. Every row between those (the 5 others) would be 0-255 for all parts. If you have something like 123.23.53.100 - 123.241.98.29 then all of the rows would have the first part's high and low equal to 123.

This is a hack but it works well. It only adds a few rows per range. I would say to make it less hacky the ban system should make it a group.

Not necessarily directed at you, @Elsensee, but if you have thousands of bans, you probably should look in to what you are doing. If you are trying to block a range, you should talk to your host and get it blocked at a lower level in your stack. If you are trying to block someone that keeps on evading your bans, what makes you think adding more IPs is going to stop them? Once again, maybe get your host involved. There are lists of public proxies out there. You could have your host ban those. There are services that do this too. 

If it is spammers I would recommend making it harder for them. Check their IP extensively in the registration process. If it is one of a known spammer from any of the SPAM lists out there, make them jump through hoops to register or just don't let them at all. If they do register, make their posts require some sort of human verification and then make them approval only. Make it cost them time which equals money. For the first 10 unapproved posts, make them take 1 minute between each. For the next 10 make it 30 seconds. That is 15 minutes that it takes for them to post. They won't want to waste that much time on your site.

Sorry for the OT discussion. I should bring that to the forum.

**Comment by wintstar** [comment]
//OT// Only times for information. Elsensee is a developer in the phpBB forum system.

**Comment by joshuaadickerson** [comment]
@wintstar, I don't understand what you mean.

**Comment by Elsensee** [comment]
I totally agree, @joshuaadickerson.
Still, if there are admins who want to have thousand of bans, they should get them. (And with nice performance as well)
But besides that, I agree.

**Comment by jdarwood007** [comment]
@joshuaadickerson, He is saying Elsensee is a phpBB developer.  He is in our IRC and I chatted with him on the ban system the other day as he was looking at it.

I do see the problem and it really does come to how we handle ranges.  The reason I could find/tell we used this system was because it was very efficient.  MySQL (and other databases) could easily compare these numbers and return a result if you had a ban.  I believe at the time the MySQL based functions for IP addresses had flaws (I would have to dig around and find those reasons again).  Topping it off, I don't know if its all cross database safe (i.e. does PostgreSQL have a function to handle IP comparisons?)

Obviously pulling down the entire ban system and comparing with PHP would mean more accurate results, but a very heavy burden on the system.  Our current ban system can process tens of thousands because of database indexing those numbers.

If we wanted to solve it, we should look at a different ban system in the first place, as the ban system was just extended if you will to handle IPv6 and it will exhibit the same flaws.  IP banning is practically worthless with how easy it is for anyone to get new addresses (I've got a /64 IPv6 and can get a new one with a couple clicks and router config update).  Users will not want to be without IP based banning so it must remain, but doing it in a way that ensures a very fast system seems like a tricky solution.  I love the fact that we could use MySQL/PostgreSQL indexes to process a IP ban in microseconds against thousands of rows of ban entries.  I fear a similar solution that resolves this wouldn't offer that, but I can honestly say I haven't research ban management solutions in forever and have no idea what is out there today.

**Comment by joshuaadickerson** [comment]
@wintstar, I don't see how that changes anything

@Elsensee, glad to see a fellow forum developer noting issues. It better serves the entire community. I don't disagree that we should strive to make the ban system better. If we can make it better, it will make the web better. We should also help admins by educating them of better ways. I am very interested in hearing about your findings in other systems.

@jdarwood007, I think if the entire table was loaded in to memory by its indices it could process thousands and thousands of rows very easily in very little time. Though, as you mentioned, IPv6 kind of makes it pointless. Proxies also make it pointless. Database indexing would be no different from loading it in to a PHP variable though, so that's moot.

That being said, we can make it smarter. It can search for ranges to reduce the amount of rows. Maybe it can make suggestions when ranges aren't consecutive. If you have thousands upon thousands of rows, you should have the hardware to support searching that quickly.

Is caching via the session the best way to cache it? Don't know.

**Comment by Oldiesmann** [comment]
In response to the question about PostgreSQL - yes it does allow you to compare IP addresses. See http://www.postgresql.org/docs/9.4/static/functions-net.html for more info.

**Comment by jdarwood007** [comment]
@joshuaadickerson There is no way pulling in 10 thousand rows from the database and parsing each one would be as efficient as a properly indexed database. The time alone to process 10 thousand rows would take significantly more than having sql return pull those rows raw.  A index shouldn't add any noticeable time

We are caching the ban lookup in session.  No need to hammer system resources for something we can check every x minutes instead.

**Comment by live627** [comment]
Perhaps we could store ip_low and ip_high  both encoded in hexadecimal and use MySQL to determine if thew user's IP is within that range.

**Comment by Elsensee** [comment]
@live627
I know that Mediawiki does it that way. (btw, don't look into their code - I find it hard to read ^^)
and I was wondering: can you really compare hexadecimal values which exceed 32/64 bits? and could you do that in all database systems or just MySQL?
I tried to find something about that but I obviously was to dumb to give Google that right question ^^

**Comment by live627** [comment]
Well, I did find https://gist.github.com/Golpha/1a79868b6598f2c6a531

**Comment by jdarwood007** [comment]
@live627 It looks like the IPv6 safe function only supports MySQL 5.6+  I forget our current version requirements, but this would present a problem otherwise.  It sounds like a solution but only if we are bumping the min requirements up to 5.6.3.  In addition it seems MariaDB has support but Percona I can't find anything on.

@Oldiesmann It looks like PostgreSQL supports it as of 9.0, what is our min PostgreSQL version for 2.1?

**Comment by live627** [comment]
Since we still have many users on MySQL 5.1, I'd rather not take the draconian move and require 5.6. So it seems that we can  use PHP to convert the IP addresses to hexadecimal and store them in varbinary(16) fields.

```
SELECT * FROM `smf_ban_items` WHERE binary 'c19b426f' between `ip_low` and `ip_high`
```

> what is our min PostgreSQL version for 2.1?

8.0, according to the installer.

**Comment by joshuaadickerson** [comment]
@live627, I was thinking along the same lines - you don't need to worry about the database, just use PHP. 

Storing them as varbinary(16) will not work though. That is storomg the full IP in a single column. If you want to keep wildcard ranges such as 123.456.* or 123.456.*.789 you will have to store the octet/hextets as separate columns. 

I know this might be crazy, but I wonder if anyone bans using a wildcard with a concrete number after it. I don't think there are many (any?) people that are jumping around on the 3rd octet while maintaining the 4th. If there are, why wouldn't you just ban the entire /24? If that "feature" were to disappear, the start-end range would be much easier to figure out.

Actually, if someone wanted to do something ridiculous like that, you could just have it fake it on the back-end like I mentioned earlier by creating more rows. Of course, that would be 255 rows, but that's what you get for doing something weird heh. Then again, that would be 65k rows for something equally as weird in IPv6.

**Comment by joshuaadickerson** [comment]
Sorry for the multiple posts. I am trying to think about this more.

What if we did only have two columns? We could store it as binary(32). It would require padding to make it 32 characters (4 for each hextet). The trick would be that the wildcard would be different for high and low. The low would just need anything lower than 0 and the high would need something higher than f. I would go with * and z respectively. If I had an IP range like 0000:0000:0000:0000:0000:ffff:455*:5d20 (removing the colons) the high column would just replace * with z.

This requires a *much* larger storage requirement per ban. It is now 64 bytes. We can't pack two hexadecimal characters as 1 byte because of the wildcard requirement. 

Even though it is a much larger size, that shouldn't really matter. There are less comparisons to take place (1 as opposed to 8). 64 bytes in terms of disk storage is nothing for a forum. That is a normal post. 64 bytes in memory for MySQL is nothing. You don't need extra rows which wastes space for the ban id. 1000 rows is still only 64KB (plus the ban id). If you have 10k bans you get to 64MB which is nothing for an index. Though, one must realize that it is checking every row in the database.

**Comment by Oldiesmann** [comment]
@jdarwood007 8.0, but it appears those functions are still supported in that version as well. http://www.postgresql.org/docs/8.0/static/functions-net.html

**Comment by live627** [comment]
@joshuaadickerson your recent comments disappeared... not sure if I should reply to them.

**Comment by joshuaadickerson** [comment]
No, I realized I shouldn't be trying to think past 2 AM and saw how stupid I was. I deleted them.

**Comment by Elsensee** [comment]
Sorry, I was busy lately (and also not able to have good ideas about this).

So after I asked in the sql irc channel a few weeks ago where I didn't get a satisfying response, I asked in the ##php irc channel. Much better. (Except bashing the bad bad code style of old phpBB code... :D)

```
<Bittarman> Elsensee, normalize them to their integer values on the way in, and then you can query based on that...
```

I guess that seems to be the easiest and best solution. I think I read something about the special and fast connection between a DBMS and integers as values. (Indexes might be involved.. not quite sure, though)

So, uh, yeah. I'll implement it and if the performance is waaay to bad, ... I probably have to think about that again or implement it in a better way.

**Comment by joshuaadickerson** [comment]
That's besides the point. You need to account for each group. I think the
only way to do it is the way I mentioned, with more rows. Then a lot of
caching.

**Comment by Dragooon** [comment]
Do we store simple IP addresses or things such as wildcards and subnets as well? If we store simple IPs, wouldn't it be possible to check the IP using simple if/else? If first part is between low and high and if first part is equal to low, then check second part. Otherwise if it's not equal to low and high then it's in range anyway..so on so forth for the four or eight parts.

**Comment by albertlast** [comment]
From postgresql point of view exist different aproache:
1. work with range type inet (need pg 9.2) https://wiki.postgresql.org/images/7/73/Range-types-pgopen-2012.pdf
   easiest syntax + index(gist) + posibility to prohibited overlapping ban range (when wanted)
   Syntax "where $user_ip <@ bi.ban_ip_range"
2. work with two inet(datatype in pg for ipv4 AND ipv6) columns (need pg 8.0)
   easy syntax + index(betree)
   Syntax "where $user_ip between bi.ip_low and bi.ip_high"

The subnet think works with both aproache too.

I did a litte research about mysql,
the solution would be to use in mysql varbinary field for the low and high ip addres fields.
To support mysql 5.0+ you need to implement the mysql function in php: http://stackoverflow.com/questions/1120371/how-to-convert-ipv6-from-binary-for-storage-in-mysql

My recomandation is not to use this methode for postgresql, you should use there the nativ version.

**Comment by live627** [comment]
https://github.com/SimpleMachines/SMF2.1/commit/a96192b99465a245ebd1c54357de9c827e06fc1d
