### ISSUE TITLE
Good option, I think ...

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#2983]
.. to add a option to disable the quick edit box in the topic view.
Not every one need this.
Also the box don't have a option to "cancel"  what you have do in the box.

**Comment by MissAllSunday** [comment]
There has always been an option for that, the only thing that changed is setting the box to be always open rather than always closed and it was changed due to massive popular demand.

What does a "cancel" button will do? cancel the actual posting? or just clean up the textarea?

Cancel the actual posting might be difficult if not impossible to implement.
Cleaning the textarea?, nope nope and nope, this article sums it up pretty nicely: http://www.nngroup.com/articles/reset-and-cancel-buttons/

**Comment by PortaMx** [comment]
Well .. it's very simple the hide the qick edit box ..
put this in a div and set these div to hidden and all works as well .. ;-)

**Comment by live627** [comment]
quick edit already HAS a cancel button.

**Comment by Oldiesmann** [comment]
If you're referring to the quick edit on the message index (double-clicking on a topic to change its subject), you can disregard changes made by hitting the escape key, and you can use the standard "undo" feature on your computer as well (CTRL+Z). I'm not sure if it's possible to disregard/undo things on mobile, but I couldn't trigger that option on my phone anyway (if I double-tap on something the browser zooms in or out). We can look into adding a cancel button there as well.

I'm not sure about adding an option to disable it though. If we added an option to disable everything simply because some people won't need it, we'd have a ridiculous number of settings, which would in turn make things more confusing for people.

**Comment by Kindred-999** [comment]
We are looking to simplify the options....  Not add more, especially not in spots that don't need a configuration

**Comment by PortaMx** [comment]
You have the option "Use full editor in Quick Reply" in the Theme settings,
Why not rename this option and give him 3 options;

"Editor for Quick Reply"
Not show
Show
Show as Full editor

By the way ,,
If you go to these Settings, it's not show the settings as you made ..
As example .. in Germany the first day of week is Monday (as I have set), but in the screen always "Sunday" is shown. So I can't see, if my settings correct ,,,
That is -so I think- a havy bug ..

**Comment by Oldiesmann** [comment]
What would be the difference between "show" and "show as full editor"? The current option simply determines whether the editor is shown on the quick reply. I'm not sure how there can be an "in between" option.

What problem are you having with the "first day of the week" setting? The profile option is working fine on both of my test boards (one using the Beta 2 release and the other using the latest files from github).

**Comment by PortaMx** [comment]
Go to:
Admin - Themes and Layout Settings - Member Options - Change current options for all members using this theme

First day of the week on the calendar ...  [ Sunday ]

I have set that to Monday !!

I use the released Beta 2 - cache set to file level 1

**Comment by illori** [comment]
i have caching at level 1 and the change to the first day of the week showed up just fine.

**Comment by Oldiesmann** [comment]
Works fine on my board as well both when I change it in my profile myself and when I reset the option for all members.

**Comment by wintstar** [comment]
@Oldiesmann I can confirm.
