### ISSUE TITLE
Unable to install themes... (beta2)

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#2995]
I have tried several of the themes linked from the main Simplemachines.org site...

Using /index.php?action=admin;area=theme (upload option)

Every single one gives me the response: An error occurred while installing the theme.

this suggests that there is a problem with the code, not every theme...

edit...
I have confirmed that installing a theme by uploading/extracting and the using the "indicate directory" option works - as does the "create a copy of the default theme"

found this in the error log:
...../index.php?action=admin;area=theme;sa=install;do=file 
2: mkdir() [<a href='function.mkdir'>function.mkdir</a>]: File exists
File: /home/turtleshell/www/test2/Sources/Themes.php
Line: 1294

**Comment by illori** [comment]
i bet it is related to #2929

**Comment by Oldiesmann** [comment]
The initial error you got indicates something failed during the extraction of the files, but there are a number of issues that could cause this (corrupted file, not a valid tar.gz or zip archive, failure to get the data or write it...). I'll do some testing on my own board later and see if I can figure out exactly where it's failing.

The other error is related to the first one. When you go to install a theme, SMF tries to create a "temp" directory in your Themes directory. The files are then extracted to this directory, and it's renamed after the installation is successful. Because things failed, the directory already existed. We already tell the extraction function to overwrite any files in that directory, but we should probably drop it and recreate it if it already exists to avoid ending up with extra files that aren't necessary.

**Comment by Oldiesmann** [comment]
Figured out what's going on... We're using PharData to handle zip archives. The PharData class expects the file that we pass to it to have a valid extension, but the file was just getting uploaded without an extension, so it fails. Adding code there to rename the file to have ".zip" and telling PharData to expect it that way fixes the problem (I then get an error saying the theme isn't compatible with my version of SMF, which is what I expected).

I'll commit a fix shortly.
