### ISSUE TITLE
[Idea] Implement HTML5-Sortable in 'manage boards' list + Easier moderator changing

### ISSUE THREAD

**Issue by IstuntmanI** [SimpleMachines/SMF#3023]
Today while I was stalking live627's profile ( joking, haha :P ) I saw that he starred "html5-sortable" repository ( https://github.com/taylorhakes/html5-sortable ), I saw the demo and I thought that it would be great to have it implemented in SMF to move boards way easier, directly from "Manage Boards and Categories" . If we move a board, there should appear be a "Save" button.

And because I am at it, there should also be a way to modify moderators faster for a board and all of its child-boards, without editing board-by-board. We could have check marks in "Manage Boards and Categories", and if we check at one, there should appear a pop-up in which we could specify the moderators for all of its child-boards including itself. I changed moderators lots and lots of times, and I am tired of doing that, especially when there is a board with a lot of child boards.

**Comment by BitFros7y** [comment]
+1

**Comment by Oldiesmann** [comment]
As far as the moderator issue goes - in 2.1 you can assign entire membergroups to moderate boards. Create a group and assign it as moderator of the boards in question. Then you only have to add users to the group to have them assigned as moderator of multiple boards instead of having to do it separately for each board.

**Comment by Rupurudu** [comment]
+1
