### ISSUE TITLE
$modSettings['guest_post_no_email']

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3051]
```
if (empty($modSettings['guest_post_no_email']))
            echo '
                        <dt>
                            <span', isset($context['post_error']['no_email']) || isset($context['post_error']['bad_email']) ? ' class="error"' : '', ' id="caption_email">', $txt['email'], ':</span>
                        </dt>
                        <dd>
                            <input type="email" name="email" size="25" value="', $context['email'], '" tabindex="', $context['tabindex']++, '" class="input_text" required>
                        </dd>';
```

where is $modSettings['guest_post_no_email'] defined in the admin panel?

do we really need this if there is no setting to turn it on? or should we add a setting to turn it on.... i doubt many even allow guest posting so this may be a tad useless.

**Comment by MissAllSunday** [comment]
Its not defined anywhere and thats by design, what guest_post_no_email does it to prevent guest for having to enter an email address when they post. If that setting is set to true, no checks are ever performed on whatever email a guest used or even if the guest used an email.

The code is wrote in an inverse approach, meaning that changing the code to a more "natural" approach is somehow redundant.

**Comment by illori** [comment]
So when would this ever be enabled?

**Comment by MissAllSunday** [comment]
It is enable, like I said, the code uses an inverse logic, it performs all the checks unless you explicitly told it not to.
