### ISSUE TITLE
I found a lot of undeclared or unneed Globals in Sources and Themes ..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3059]
Today I scan the SMF files with the Tool Globye .. (you fond this on my Github repository) .. and found many unused or unneed globals ..

I think, now is a good time to fix that ..

**Comment by margarett** [comment]
Actually I think that this a good idea. I'll try to give it a spin.

BTW:

```
Unused global in Globye.php:156 (find_global_problems) -- $root
```

:tongue:

**Comment by MissAllSunday** [comment]
I cleaned up the unused and a few undeclared ones the rest are all false positives, IE when using a global var in a closure  function() use($txt).  Thats preferable over declaring globals inside the closure itself but the tool cannot catch this behavior.

Template files gives a lot of unused results but thats to be expected, those globals are there to help mod authors and avoid them adding those globals vars themselves.

Theres also a lot of local vars been named after globals, things like $topic and $board are recurrent names due to the very own nature of the software itself, although we can named them differently, I dunno if it will be worth it, none of them directly interfere with their global counterparts and renaming vars can lead to unexpected results, I did rename a few of them but stopped after a few files because its really not worth the hassle.
