### ISSUE TITLE
Visiting /index.php?action=stats;xml triggers an error

### ISSUE THREAD

**Issue by wodim** [SimpleMachines/SMF#3066]
If you visit `/index.php?action=stats;xml` (yes, I made the URL up, it's not linked from anywhere) the following three errors are generated:

> 8: Undefined variable: year
> File: /srv/http/smf/Sources/Stats.php
> Line: 72
> 
> 8: Undefined variable: month
> File: /srv/http/smf/Sources/Stats.php
> Line: 72
> 
> The database value you're trying to insert does not exist: year
> File: /srv/http/smf/Sources/Stats.php
> Line: 652

**Comment by Oldiesmann** [comment]
Actually that is a real URL, sort of. That's used to handle expanding/collapsing individual sections for yearly/monthly stats (eg if you click the "+" next to a year or month, that section is expanded, if you click "-" it's collapsed). The `$year` and `$month` variables aren't getting defined here because those are set from either `$_REQUEST['expand']` or `$_REQUEST['collapse']` (it's expecting those to have the month and year in YYYYMM format).

While it is relatively easy to fix this, I'm not entirely sure it's worth fixing since it's highly unlikely anyone will ever encounter this issue.
