### ISSUE TITLE
Change localhost to 127.0.0.1 by default for installer

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#3069]
I just saw my times on my sites go from 1 second done to 100ms in most cases where I was using localhost
Check out the first answer for the reason why
http://stackoverflow.com/questions/17815604/very-slow-1-second-connections

It boils down to the default config mysql is not optimized well but we can optimize it for users and make their forums perform better

**Comment by Rupurudu** [comment]
No. 

localhost means "Unix domain sockets" which is not supported by Windows. What's happening is mysqli tries to connect with unix domain sockets, fails. Then tries to resolve localhost on DNS, then connecting to 127.0.0.1 with TCP/IP.

On windows systems localhost needs to be replaced with "." (dot) This actually means "Windows named pipes" and fastest method of connecting the database on Windows.

**Comment by VBGAMER45** [comment]
I have done changed about 8 of my windows servers so the speed boost is insanse.
More on this
http://www.borngeek.com/2011/04/05/mysql-performance-and-localhost-performance/
http://stackoverflow.com/questions/11310564/php-to-easyphp-mysql-server-1-second-connection-delay/15436435#15436435

**Comment by Rupurudu** [comment]
Okay, I know that it actually boosts speed. But changing this will slow down Unix servers.

Try `.` It's better than `127.0.0.1`

Edit: Let me explain this a bit better.

`localhost` does not mean `127.0.0.1` It has a special meaning.

PHP have 3 ways to connect the database.
1. Unix domain sockets (`localhost`)
2. Windows named pipes (`.`)
3. TCP/IP (`127.0.0.1`)

Domain sockets and Named pipes are always faster than TCP/IP, becasue they skip the networking stack.

But Domain sockets are exclusive to Linux and Named pipes are exclusive to Windows.

To use Domain sockets, you need to type in `localhost` to the host field.
To use Named pipes you need to type `.` in the host field.
TCP/IP is should be used as last resort, because it's noticably slower than other 2.

**Comment by VBGAMER45** [comment]
The . didn't work for me. But probably have to alter the mysql config? And maybe skip networking? But that might interfere with some remote tools that use to manage the databases.

**Comment by Rupurudu** [comment]
Hmm... Try adding `enable-named-pipe` to my.ini

**Comment by live627** [comment]
Can this be closed?

**Comment by frandominguezl** [comment]
I think this can be closed... @live627 @Oldiesmann

**Comment by colinschoen** [comment]
Yes, thanks.
