### ISSUE TITLE
Errors on install language ..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3071]
A lot of error came up on install a language (see image)
I use Latest github release ..
![langinstall_fail](https://cloud.githubusercontent.com/assets/2270223/9956603/5b15abfe-5dfa-11e5-801a-15bda3f0790d.png)

**Comment by illori** [comment]
which pack did you install? i just installed one on my 2.1 test forum and i got no errors.

**Comment by PortaMx** [comment]
I install the english utf-8

**Comment by Rupurudu** [comment]
SMF is already english? Why are you installing a language?

**Comment by illori** [comment]
Some people want the utf-8 version anyway. If the database is converted
there is no problem with it.

**Comment by Oldiesmann** [comment]
That error is from old code that handled the existence of language-specific image files (which we no longer have in 2.1). It assumed there would always be at least one such file in the package (since even in 2.0 we still had one), but because there aren't any, $context['files']['images'] is never set, which of course causes the errors.

At this point I think we can safely remove that code.

**Comment by Oldiesmann** [comment]
Looking at this further, it seems that code is still used for languages that have a "Themes/default/languages/index.php" file and/or an agreement.{language}.txt file included in the package. We should still at least rewrite that code to handle situations where there might not be any of those files, and maybe change the interface some (since technically an agreement file isn't theme-related). Will commit a fix in a bit.

**Comment by margarett** [comment]
https://github.com/SimpleMachines/SMF2.1/commit/2c1cc495818b0ca7abb5e3d814a0a2aed30e8c2c#commitcomment-14686420
