### ISSUE TITLE
Error while searching only in subjects.

### ISSUE THREAD

**Issue by smguy9** [SimpleMachines/SMF#310]
> Unknown column 'm.id_msg' in 'field list'
> File: D:\xampp\htdocs\smf21\Sources\Search.php
> Line: 1129
> 
> INSERT IGNORE INTO smf_log_search_results
> (id_search, id_topic, relevance, id_msg, num_matches)
> SELECT
> 4,
> t.id_topic,
> 1000 \* (30 \* COUNT(*) / (MAX(t.num_replies) + 1) + 25 \* CASE WHEN MAX(m.id_msg) < 2 THEN 0 ELSE (MAX(m.id_msg) - 2) / 1 END + 20 \* CASE WHEN MAX(t.num_replies) < 200 THEN MAX(t.num_replies) / 200 ELSE 1 END + 15 + 10 \* CASE WHEN MIN(m.id_msg) = MAX(t.id_first_msg) THEN 1 ELSE 0 END + 0 \* MAX(t.is_sticky)) / 100 AS relevance,
> t.id_first_msg,
> 1
> FROM smf_topics AS t
> INNER JOIN smf_log_search_subjects AS subj1 ON (subj1.id_topic = t.id_topic)
> WHERE t.approved = 1
> AND subj1.word LIKE '%welc%'
> LIMIT 1200

And sometimes there is no error, and also no result.

**Comment by emanuele45** [comment]
Do you have any particular setting for the search?( I mean custom index, or something like that)

**Comment by smguy9** [comment]
Nope, default settings. @Antes told me he could also reproduce.

**Comment by emanuele45** [comment]
Okay...I think @Spuds is the search master! :smile_cat:

**Comment by emanuele45** [comment]
Adding a bit: from debugging if `$search_params['subject_only']` is true, `$userQuery` is set to empty, and at line 1063 the check to `INNER JOIN` messages is skipped because is done only if `$userQuery`.

Not sure if inverting this check would break something else...I would even remove it... :angel:

**Comment by Spuds** [comment]
@emanuele45 
I'm relatively certain that is because its using the wrong relevance factors in that area of the query .....

```
if (!empty($value['search']))
$relevance .= ' * ' . $value['search'];
$relevance .= ' + ';
```

those 'search' terms should be instead 'results'  ... ignore for a moment that those are not the greatest names for the weight array keys ... there may be other issues with subject only search though ... the use of the weight array, to provide modifications the ability to impact search results, carried a few difficulties with it. 

In that loop, be sure to check for $value['results'] being set as well before concatenation it in to the relevance string

**Comment by emanuele45** [comment]
Changing that (there are two instances, I changed both) seems to fix the issue! :D

If there is anything else...beta is for that. :P

Thanks!

**Comment by Spuds** [comment]
If by second instance you mean the one after the comment

```
// Did we either get some indexed results, or otherwise did not do an indexed query?
```

That one needs to stay as 'search', only the one inside the subject conditional section needs to change
