### ISSUE TITLE
Install database error for missing db_last_error.php

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3114]
Warning: file_put_contents(/smf/db_last_error.php): failed to open stream: Permission denied in /smf/Settings.php on line 195
1. We should include this file (empty) by default in our installer.
2. We should make sure on install/upgrade that this file exists and is writable.

**Comment by albertlast** [comment]
is this issue existing?

**Comment by jdarwood007** [comment]
I believe it is as I don't recall any checks being added into the installer to check this nor is it a default file.

Issues like this would occur on sites where permissions are not 777 on the smf folder and thus the system will fail to create this file.

**Comment by tinoest** [comment]
It is still a issue, why isn't it included in the package? 

Also should be detected during the install/upgrade process as a file which needs to be writable

**Comment by albertlast** [comment]
It's fine that the file is not in package.
It will created when it's needed.

And because the file is not in package the file access issue can not happen.
When this issue rised up,
than someone created this file by his own -> this issue is created by the user him self.

**Comment by tinoest** [comment]
At no point do we inform the user that they need to make the root directory writable, which I'd argue is bad practise anyway. 

We say about Settings.php but not db_last_error.php. It's even not shown in the SMF error log for me only my lighttpd error log. 

Either we need to inform the user better or we create it at the start. I prefer the latter as it removes the chance or the db having a failure and it failing to write it due to permissions.
