### ISSUE TITLE
Subs-editor.php action=loadeditorlocale - 404 Error

### ISSUE THREAD

**Issue by Mavn** [SimpleMachines/SMF#3131]
Issue in this code
// editor language file
        if (!empty($txt['lang_locale']) && $txt['lang_locale'] != 'en_US')
            loadJavascriptFile($scripturl . '?action=loadeditorlocale', array(), 'sceditor_language');

result http://localhost/Themes/default/scripts/http://localhost/index.php?action=loadeditorlocale?beta21

**Comment by margarett** [comment]
This is actually weird. There is an action in index.php --> action=loadeditorlocale

But the associated function seems to be called only in that specific line, so it should be possible to just call the function and remove the action in index.php. The idea was probably be to call all JS files at once (through loadJavascriptFile --> $context['javascript_files']). If the call to loadLocale is executed there, the respective JS will be immediately dumped.

I hate JS :tongue:

**Comment by margarett** [comment]
No, if loadLocale is executed instead of the broken loadJavaScript file, then all we get is the dumped JS on the screen ehehehehe

**Comment by MissAllSunday** [comment]
It seems I forgot to update this when I changed the behavior of loadJavascriptFile

This commit should fix this issue. https://github.com/MissAllSunday/SMF2.1/commit/04372e54cbcc53472bbd15c6643e7ee72470af9d

@margarett that action is suppose to mimic a js file, it was done like this because its easier to dump all language strings in a dynamic file than having to "print" all of them directly in the HTML.  For all purposes the browser "sees" index.php?action=loadeditorlocale as an url to a normal plain js file who will be loaded by the browser.

**Comment by margarett** [comment]
Yes, that fixes it :)
