### ISSUE TITLE
Call to undefined function AddMailQueue()

### ISSUE THREAD

**Issue by Mavn** [SimpleMachines/SMF#3132]
PHP Fatal error:  Call to undefined function AddMailQueue() /Sources/tasks/Birthday-Notify.php on line 113

**Comment by margarett** [comment]
Confirmed. It happens when none of the "birthday members" have the selected preference to receive email on their birthday. In that case Subs-Post isn't required and, when the code reaches AddMailQueue, the function is undefined. If there are no birthdays _or_ at least one of them has chosen to receive an email on its birthday, all works fine.

It's an easy fix, I'm submitting a PR shortly
