### ISSUE TITLE
Login.english.php Undefined index: forum_name_html_safe

### ISSUE THREAD

**Issue by Mavn** [SimpleMachines/SMF#3137]
Themes/default/languages/Login.english.php line 125 /122 /112

I think $context variable($context['forum_name_html_safe']) doesn't work in this file

**Comment by margarett** [comment]
Can't reproduce this, the variable is correctly filled when the language file is loaded.

$context['forum_name_html_safe'] is defined in Load.php (loadTheme) which is executed by index.php before the call to the register/register2/coppa action so it must exist...
Are you using the most up-to-date code from this repo? Do you have installed MODs which migt mess with this?

**Comment by MissAllSunday** [comment]
I can :tongue:   my site has been logging this error for some time now but I always thought it was one of my mods.

In my case it has to do with guests (bots) trying to "see" an attachment, somehow they get redirected to the login page or something like that, I haven't fully investigated this. Looks like the login language file is been called before that vars is set, the inline attachments has a way to see attachments without loading the entire forum structure, thus its highly possible that this bug is related to that.

**Comment by margarett** [comment]
I still can't ehehehe. I just tried that here, eg, a guest accessing
index.php?action=dlattach;topic=3.0;attach=1
is redirected to the login screen, no errors. And if a guest sees a post with inline attachments, it gets the "You cannot see attachments on this board." message instead of the attachment.

@Mavn: What is the URL of the error in your log?

**Comment by Mavn** [comment]
1. Yes I use latest files from this repo + path for attachments https://github.com/MissAllSunday/SMF2.1/commit/5590fec577a4b0e108bc7026d46da18c4580e81a
2. URL of the error as in you post 
   http://***/index.php?action=dlattach;topic=1779.0;attach=13520;image
   and this error only from guest
3. I have some mods for code highlighting, payments, redirect links but they are not using $context['forum_name_html_safe']

**Comment by MissAllSunday** [comment]
It must be something unique to our boards, I just tried to replicate this on a clean install and there is no errors been logged, maybe some weird permissions been mixed up, dunno.

**Comment by Oldiesmann** [comment]
Looking through the code, I'm not sure how this could happen.

dlattach calls the Download function in Display.php
Within that function, we have `isAllowedTo('view_attachments');` (line 1487, Display.php)
That function will call is_not_guest if they're a guest and they don't have that permission (line 999, Security.php)
The is_not_guest function will call loadTheme if the theme isn't already loaded (line 113, Security.php)
$context['forum_name_html_safe'] is set in loadTheme, which is called before the Login language file is loaded

Unless the is_not_guest function has been modified on your forum, there's no way this should ever happen.

**Comment by MissAllSunday** [comment]
@Mavn Did you have a corrupted or a non-existent attachment?  the error I got only appeared in a corrupted attachment, for some reason bots loved that specific topic and continually hit that attachment.

I deleted the attachment and tried to replicate the same issue with a few other ones but no luck so far.

**Comment by Mavn** [comment]
@MissAllSunday sorry for long response ...
I have new installed forum and I can't replicate this error, above I provide link from existing topic and attachment. Right now I can't test on real forum(where I have problem), I have some problem with converting serialize to json data(attachments doesn't work), After fix this problem, I'll can test

**Comment by Mavn** [comment]
@MissAllSunday
my forum is working and now I can test this again :)
ok... I have latest files, performed maintenance attachments, fix all errors,
I have attachment in topic, and if guest call this attachment(or any in another topics) I'll have error something like that

```
8: Undefined index: forum_name_html_safe
/index.php?action=dlattach;topic=44.0;attach=12520
/Themes/default/languages/Login.english.php
Line:124;121;125;124;122
```

**Comment by margarett** [comment]
That's really odd...
What's the rest of your URL? PM me at sm.org if you don't want to post it in public ;)

**Comment by Mavn** [comment]
www.simplemachines.ru

**Comment by margarett** [comment]
OK so, I'm redirected to the login page. This is pretty much what I tested here and got no errors...

Maybe it's caused by the file name or forum language? I'm lost :(

**Comment by margarett** [comment]
Some more juice to try to understand the tests we need to do, in order to reproduce this.

If I go to your site and try to access the following link
http://www.simplemachines.ru/index.php?action=dlattach;topic=44.0;attach=12520
I'm redirected to http://www.simplemachines.ru/index.php?action=login

In my test forum, if I try to access
http://localhost/smf21_clean/index.php?action=dlattach;topic=1.0;attach=2
I also see the login page _BUT_ I am NOT redirected to action=login. The difference is that I see the message

> "It seems that you are not allowed to download or view attachments on this board. Please login below or sign up for an account with My Community"

And I don't see it in yours.

![img1](https://cloud.githubusercontent.com/assets/5584935/11489750/0cb00612-97ca-11e5-8480-50902db083a8.png)

**Comment by margarett** [comment]
Still looking at this, I still think that something has to be messed in your setup (messed or in any other way working differently :tongue: )...

Looking at FF's developer tools, when I request
http://www.simplemachines.ru/index.php?action=dlattach;topic=44.0;attach=12520
Your server replies with 302 Found which usually indicates a redirect through redirectexit. And after that, we get a call to action=login with the "normal" code 200.

In my test forum
http://localhost/smf21_clean/index.php?action=dlattach;topic=1.0;attach=1
Gets directly a reply with code 200. So I'm NOT redirected and I get the usual "not allowed to do this, please login" screen.

Searching through the code, the only time SMF redirects you to action=login is in Security.php, part of the "is_not_guest" function:

```
    // Apparently we're not in a position to handle this now. Let's go to a safer location for now.
    if (empty($context['template_layers']))
    {
        $_SESSION['login_url'] = $scripturl . '?' . $_SERVER['QUERY_STRING'];
        redirectexit('action=login');
    }
    else
```

Why does it happen in your forum and not in mine? Absolutely no idea :open_mouth:

**Comment by MissAllSunday** [comment]
Justo saw the error losg at my forum and the error is back, the attachment is missed and the forum shows a weird 404 error... I gotta do some more checks

**Comment by margarett** [comment]
Friendly bump here ;)

**Comment by Yariksat** [comment]
Guests try to download an attachment

Гость
 Сегодня в 19:55:19
 86.105.56.106  
 66754ae38468dd1e3e9b4caa98632478
 Тип ошибки: Неопределенные  8: Undefined index: forum_name_html_safe
    https://yarik-sat.ru/index.php?action=dlattach;topic=715.0;attach=6561

 Файл: /home/admin/web/yarik-sat.ru/public_html/Themes/default/languages/Login.russian-utf8.php
 Строка: 124  
 Гость
 Сегодня в 19:55:19
 86.105.56.106  
 66754ae38468dd1e3e9b4caa98632478
 Тип ошибки: Неопределенные  8: Undefined index: forum_name_html_safe
    https://yarik-sat.ru/index.php?action=dlattach;topic=715.0;attach=6561

 Файл: /home/admin/web/yarik-sat.ru/public_html/Themes/default/languages/Login.russian-utf8.php
 Строка: 121  
 Гость
 Сегодня в 19:55:19
 86.105.56.106  
 66754ae38468dd1e3e9b4caa98632478
 Тип ошибки: Неопределенные  8: Undefined index: forum_name_html_safe
    https://yarik-sat.ru/index.php?action=dlattach;topic=715.0;attach=6561

 Файл: /home/admin/web/yarik-sat.ru/public_html/Themes/default/languages/Login.russian-utf8.php
 Строка: 112  
 Гость
 Сегодня в 19:55:19
 86.105.56.106  
 66754ae38468dd1e3e9b4caa98632478
 Тип ошибки: Неопределенные  8: Undefined index: forum_name_html_safe
    https://yarik-sat.ru/index.php?action=dlattach;topic=715.0;attach=6561

 Файл: /home/admin/web/yarik-sat.ru/public_html/Themes/default/languages/Login.english.php
 Строка: 125  
 Гость
 Сегодня в 19:55:19
 86.105.56.106  
 66754ae38468dd1e3e9b4caa98632478
 Тип ошибки: Неопределенные  8: Undefined index: forum_name_html_safe
    https://yarik-sat.ru/index.php?action=dlattach;topic=715.0;attach=6561

 Файл: /home/admin/web/yarik-sat.ru/public_html/Themes/default/languages/Login.english.php
 Строка: 122  
 Гость
 Сегодня в 19:55:19
 86.105.56.106  
 66754ae38468dd1e3e9b4caa98632478
 Тип ошибки: Неопределенные  8: Undefined index: forum_name_html_safe
    https://yarik-sat.ru/index.php?action=dlattach;topic=715.0;attach=6561

 Файл: /home/admin/web/yarik-sat.ru/public_html/Themes/default/languages/Login.english.php
 Строка: 112

**Comment by Yariksat** [comment]
Raising the issue in the log a lot of these errors

**Comment by MissAllSunday** [comment]
I believe I got a solution for this. Turns out there was a few extra params when checking for attachments, this caused the check to fail and to delegate the attachment displaying to Display::Download()

The undefined errors happens because theres a check to prevent theme related stuff from loading when viewing an attachment BUT since the other check fails, the attachment end up being serve by Display.php which does require the theme to be loaded.
