### ISSUE TITLE
smf2.1 to 2.1 Convert serialized strings to JSON doesn't work

### ISSUE THREAD

**Issue by Mavn** [SimpleMachines/SMF#3155]
I tested upgrade 2.1 old to 2.1 latest and have problem in Step 6: Convert serialized strings to JSON
![serial_to_json](https://cloud.githubusercontent.com/assets/2140726/11458430/cf63b384-96d0-11e5-8d3c-e1780cb83e84.jpg)

upgrade script stop and do nothing.
I am trying upgrade two various forums with diferent 2.1 version's, but it doesn't work

**Comment by wintstar** [comment]
I can confirm.

**Comment by Oldiesmann** [comment]
I believe this is because I rewrote the code to use substeps (to prevent it from timing out) but didn't add appropriate templates as well. If you run it from the shell (cd to your forum directory the "php upgrade.php" without the quotes) it should work fine. I'll look into this in the coming days and see if I can fix it.

**Comment by Mavn** [comment]
Thank you @Oldiesmann, I forgot about this feature of upgrade.php
I find another:
1. spelling error

```
*  +++  Altering mil_queue table... done.
 Successful.
```
1. In two forums have this error

```
 - Failed to unserialize the 'attachmentUploadDir' setting. Skipping. done.
```

and after upgrade -> path('s) to attachments directory is empty

**Comment by Oldiesmann** [comment]
The attachmentUploadDir thing is a known issue - in many cases it's a string rather than a serialized array. I'll fix that in a bit.

**Comment by margarett** [comment]
@Oldiesmann I just performed a test upgrade and my step 6 still has no template...
