### ISSUE TITLE
a new index to add

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#317]
log_actions => index('id_topic', 'id_log')

Easy to do, big improvement (in a forum I'm following the query (list_getModLogEntries) went from ~1.0 sec (from 0.7 to 1.7) to less than 0.1 (approx. 0.004) in phpMyAdmin, SMF is usually a bit slower).

It may be worth considering also an index('id_board', 'id_log') I think (it should improve the query for board moderators).

@Spuds that's for you too! :P

**Comment by Spuds** [comment]
Must have a substantial number items in the log action table?  Curious what the explain showed before and after.  

I can see where adding that index would help since it is the where part of the query thats being tested.... Also how large did that index come out?

**Comment by emanuele45** [comment]
> Must have a substantial number items in the log action table?

Indeed, we are talking about 700k entries.

> Curious what the explain showed before and after.

Before:
![screen_95](https://f.cloud.github.com/assets/1095308/271835/0e36af82-8ff2-11e2-975c-77f2c28823ba.png)
After:
![screen_94](https://f.cloud.github.com/assets/1095308/271831/fdcd4624-8ff1-11e2-9fd8-a9c2c0546a0b.png)

> Also how large did that index come out?

It should be about 10 MB where the data are 260 MB

**Comment by ghost** [comment]
Anything further on this?

**Comment by jdarwood007** [comment]
Only problem with this is you are dropping into a filesort as your explain shows.  Although we have now better hit the target and brought our rows down to 2, so this seems like a good improvement.  So at any rate while it does filesort, it filesorts very few results.

Have you tried with just a index on id_topic for that table?

Also the filesort is possibly because of the order by (usually is).  Indexing that is sometimes worth it, other times not because you have to index all columns that are sortable.

**Comment by butch2k** [comment]
It is profile you shall use not just explain, while explain will tell you about the execution plan profile will tell you about the actual cost. If you need to filesort and create a sorting file on disk then this is an issue as cost could be high.   

## 

Olivier Lefebvre
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by Arantor** [comment]
Any chance someone can perform more thorough profiling on the site in question? I know I can generate 700k rows of moderation log but it's not going to be as accurate as the site's log above.

**Comment by Arantor** [comment]
@emanuele45 Any chance of getting profiling?

@butch2k Do note that while profiling was not yet obtained, the time for this query was reduced significantly in so doing as noted earlier... creating a filesort is not necessarily terribly bad if you only have a tiny number of records to filesort, as opposed to non-filesorting through thousands of records.

**Comment by emanuele45** [comment]
It's on the todo list... but the list is getting bigger and bigger... lol
Anyway I suppose this is not something that could/should hold a release.

**Comment by butch2k** [comment]
@Arantor 
In this case indeed, filesort is in fact just a kind of quicksort which has nothing to do with it being done on disk, BUT if the number of rows to be sorted is high it might require a temporary file on disk which would be costly. It might be interesting to check the impact on other queries using this table in case the new index change the usual execution plan (e.g. change it to filesort on disk rather than scan).

**Comment by Arantor** [comment]
I am well aware of what a filesort is, thanks.

But if you look at the actual explains given, we were dealing with thousands of rows being sorted purely in memory, versus a much smaller list (2 items) being sorted via a filesort.

**Comment by butch2k** [comment]
We do agree on this, what i want to be sure is the impact on other queries, some choices being made by the MySQL optimizer are far from being the most effective.
What i'm missing here is the query which was actually used to get that result. Exemple: what will happen if rather than an equality we match against an array of values ? etc... I do not know if it could happen, but it's the kind of things i would like to check.

Based on the results before i would add the index but i want to be sure it's not just an edge case (ok 700k rows is an edge case anyway...).

As far as the explanation of what the filesort is, do not take this personnaly,i wanted to make it clear for everyone reading it.

**Comment by Arantor** [comment]
It's actually stated where this is coming from, list_getModLogEntries().

**Comment by butch2k** [comment]
It's not a MySQL query it's the PHP function, and yes i know what it is, thanks. 

And there are a few parametrized queries in there... what i need is the actual query which was run, i.e: which parameters where used. Given there are both $query_params and $query_string variables in use within this function the whole query might change a bit from call to call...
