### ISSUE TITLE
I thought yall fixed this? Upgrade hangs

### ISSUE THREAD

**Issue by bperry921** [SimpleMachines/SMF#3228]
Latest version i tried to upgrade just minutes ago hangs on updating attachments, i thought someone fixed that last go round?
![githelpsnip01](https://cloud.githubusercontent.com/assets/4441576/12060062/605dcf42-af35-11e5-9bc9-20f8e80a9e89.PNG)

Also, my chat utility pluggin and certain stat functions do not seem to recognize when guests are logged in or viewing boards/topics??

**Comment by illori** [comment]
seems oldies added a bug instead of fixed it.
-  +++  Converting legacy attachments.
  Parse error: syntax error, unexpected 'attachmentUploadDir' (T_STRING), expecting ']' in D:\wamp\www\github2.1\upgrade.php(2655) : eval()'d code on line 43

Call Stack:
    0.0156    1441728   1. {main}() D:\wamp\www\github2.1\upgrade.php:0
    1.3098    3533000   2. DatabaseChanges() D:\wamp\www\github2.1\upgrade.php:669
    1.3098    3537624   3. parse_sql() D:\wamp\www\github2.1\upgrade.php:1700

Error in upgrade script upgrade_2-1_mysql.sql on line 357!
