### ISSUE TITLE
css too general bulleted lists

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3255]
```
ul, ol {
    list-style: none;
}
```

with this css it means that any mod that allows the use of html to create pages etc you cant have a list with bullets as you can in SMF 2.0. i think this css should be a bit more specific so that you can use bullets as you can in SMF 2.0.

**Comment by MissAllSunday** [comment]
Or the other way around, mod authors that does want to use bullets on their lists can apply their own css styles.  If they are already adding a page then it would be easy to use addCss or loadCss functions to load their own.

It doesn't make sense to apply a rule to 99% of all lists just so the 1% left doesn't have to.

**Comment by illori** [comment]
I am talking about the end user that end user that is creating html
pages/articles. They don't know that by default they can't have the bullets
show up.

**Comment by XinYenFon** [comment]
Still pretty much same, instead user gonna type `<ul class="bullet">...`

**Comment by illori** [comment]
Only if we educate them. Thought it would be easier if it could be fixed in
SMF.

**Comment by MissAllSunday** [comment]
Theres nothing to fix.

**Comment by illori** [comment]
i am still seeing this issue popping up with mods that allow html pages. IMO we should not have to teach the end user [not the admin] how to add the css to fix this. cant we just target certain elements instead of killing all the style on lists like we are now? we did not have this issue in SMF 2.0 and we have this now in SMF 2.1.

**Comment by lurkalot** [comment]
I agree with you illori.  It should target the elements it really needs to rather than breaking other stuff along the way.

**Comment by Gwenwyfar** [comment]
This is not as simple as you think. We use lists in a lot of places. This is a very normal default to have in css because 99% of the time, they won't be displayed as lists. This would mean we would have to go on every single list used everywhere (and make sure we get them all) and remove their list styles individually. So instead of removing it once, and adding it back on the few that are actually simple lists with bullets, we'd be removing it dozens of times in every single place. And this is not just smf, most sites doing any sane css will add this as the default.

If someone is trying to meddle with html/css this should be a very simple issue if they know anything at all. And if it's in a mod it should be extremely simple for them to handle as well.

**Comment by illori** [comment]
then how would you expect a mod to handle this if they allow the end user to post html and not always know the level of html knowledge that the user has?

**Comment by XinYenFon** [comment]
with educating them properly?

If you don't know something in basic level you don't use it... What you are saying is illogical.

**Comment by Gwenwyfar** [comment]
> then how would you expect a mod to handle this if they allow the end user to post html and not always know the level of html knowledge that the user has?

There are also mods that allow you to use custom php. Not all mods or features are meant for everyone to easily understand. If they don't know how to use it, they have two choices: Learn how or don't use it.

If someone comes asking for support because they want to learn how, I don't see what's wrong with that.
