### ISSUE TITLE
Separate multiple types out of smf_log_comments

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#328]
2.0.4 uses this table for:
- storing the Q&A
- storing notes in the moderation centre
- comments to reported posts
- warnings sent to users
- custom warning templates that users make

IMO, these should each have their own table, they should not be shoehorned into a single table.

This is especially important  if we ever plan to add multiple language support for the new user Q&A

**Comment by matthew-kerle** [comment]
Nothing wrong with adding more tables for those things, but I'm pretty sure the reason they were put into one is probably because it's expected that there'll be so few rows that it's not necessary to add more tables (not that I agree with this practice, just my speculation on the methodology used for this table).

**Comment by Kindred-999** [comment]
it might have been expected at one point, but 
- Q&A needs to move if we're going to make it possible to support multiple languages
- moderations notes are used heavily on some sotes
- coments to reports are used VERY heavily
- Warnings are also used very heavily
- custom warning templates... Ok, this one probably only has a few records.

So, 4 of the 5 things are deinfietly not "just a few rows" whatrever the original reaosning may have been. :P

**Comment by matthew-kerle** [comment]
Right, that was my point...it was probably designed this way back when the rows being added were fairly minimal. Are we going to support multiple languages in SMF 2.1? I wouldn't be against this by any means, but it's one more thing to do, and someone has to do it.

**Comment by Arantor** [comment]
Q&A has already been moved. Probably should update the upgrader to move old Q&As or at least dump them or something.

The rest, though, would be nice to move.

**Comment by Arantor** [comment]
Thinking about it, do we actually gain anything by moving them at this stage? Q&A had to move, we needed the space for extra information that wasn't going to fit in the existing schema but I'm wary of having to not only update the upgrade code (multiple times, once per background) but retesting everything works as expected.

**Comment by jdarwood007** [comment]
I think it is something we leave for 2.1, unless there is a good consensus to change this at this point when we are wanting to get to beta testing stage for 2.1

**Comment by Oldiesmann** [comment]
I think this is something that should be changed at least by the time 2.1 goes final (not necessarily before the first beta, but at some point in the beta stage). It doesn't make a lot of sense to store a bunch of unrelated stuff in a table that was originally designed to handle comments on reported posts.

On a related note at some point we might also want to look into moving custom profile field data out of the themes table, but that might require a lot more than just a few query changes and such.

**Comment by Arantor** [comment]
If we change it post-beta, we have to then re-test everything that's changed, including re-testing the upgrader each time we change it, and frankly I don't want to do that multiple times since it took ages last time for the Q&A table.

There are other benefits to having the custom profile data in the themes; that really can't just change in 2.1. Had we done this months ago, there wouldn't be a problem because we could fix everything up.

**Comment by emanuele45** [comment]
> I think this is something that should be changed at least by the time
> 2.1 goes final (not necessarily before the first beta, but at some
> point in the beta stage). It doesn't make a lot of sense to store a
> bunch of unrelated stuff in a table that was originally designed to
> handle comments on reported posts.
> 
> If it doesn't make sense and you want to have it in "final", do it.
> There is no reason to wait until a beta is out except to make the
> beta/RC stages last longer (and have more troubles while upgrading
> because you may or may not have data migrated depending on which exact
> version of a beta you are on, etc.).

**Comment by Arantor** [comment]
OK, I'm going to close this issue for now because while we do need to do it, it's not something we should be doing in 2.1 at this late stage, not if we want to ship something in the next couple of months (writing the same code 3-5 times for each thing is not a lot of fun!)

When we tackle 3.0 we'll be going over everything from the ground up and we can easily fix it then.
