### ISSUE TITLE
Missing index

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#3288]
Lots or queries search `variable` in `smf_themes`; shouldn't that column be indexed?

**Comment by albertlast** [comment]
On a fresh install version we got 22 entries,
this amount is two low.
But what is the average amount of rows in this table?

**Comment by live627** [comment]
multi[ly that  by number of themes installed
all theme specific preferences are stored there, sometimes for  individual members (thus the `id_member` column)
values of custom fields are stored there

 I don't know an average. @MissAllSunday?

**Comment by albertlast** [comment]
On the other hand,
when this multiplied by themes,
than you need the in where condition not only variable,
additionaly the id_theme and id_member.

And then the index is not needed any more,
because the this three fields are the pk fields -> pk got everytime a index.

We could change the order of the pk col,
when some col are less often used.

**Comment by albertlast** [comment]
Is there a need to keep this open?
When the issue is relevant should be the definition of pk changed like i write in the post before.
