### ISSUE TITLE
INET_ATON only handles IPv4

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#3291]
Per http://www.simplemachines.org/community/index.php?topic=543417 - the INET_ATON function in MySQL only handles IPv4 addresses. The equivalent function for IPv6 is INET6_ATON, but this function is only available in MySQL 5.6 and up.

**Comment by Oldiesmann** [comment]
Looking into this a bit more, this issue will also affect PostgreSQL since our custom INET functions in Postgres only handle IPv4 as well. It might be better to just use PHP's functions instead (inet_pton and inet_ntop), though even then it's possible to disable IPv6 support in PHP (although I have no idea why anyone would want to do that).

**Comment by albertlast** [comment]
The needed core function for this are done in the pr https://github.com/SimpleMachines/SMF2.1/pull/3222
from my pov is the biggest problem the upgrade script,
because we had to change the datatype of this and similiar col to varbinary in mysql and in pg to inet.

Effected fields are: log_actions.ip, log_banned.ip, log_errors.ip,
log_floodcontrol.ip, log_online.ip, log_reported_comments.ip,
member_logins.ip, member_logins.ip2,members.member_ip,
members.member_ip2, messages.poster_ip, spiders.ip_info

Some are varchar(255) which could safe ipv4 and 6 but it's bad design decision to handle the ip address as varchar

Tracking of the field status:
Waiting: 
log_floodcontrol.ip, log_online.ip, log_reported_comments.ip,
member_logins.ip, member_logins.ip2, spiders.ip_info

pr: https://github.com/SimpleMachines/SMF2.1/pull/3373
log_actions.ip 
log_banned.ip 
log_errors.ip,members.member_ip, members.member_ip2 
messages.poster_ip 

done:

@Sesquipedalian you ask in forum for work, here you finde some :)

**Comment by Oldiesmann** [comment]
At this point I think our only option is to convert every IP field to varbinary and run each IP address through PHP's inet_pton function before inserting the data into the database. It's not as user-friendly as storing the raw IP, but I have yet to find a better solution that still allows for easy sorting of IP addresses (at least in MySQL - I would assume PostgreSQL's inet type can handle proper sorting).

**Comment by jdarwood007** [comment]
Need to do some testing to verify we can do comparisons still in SQL.

**Comment by albertlast** [comment]
I tested for the ban ip pr:
- comparsion like <, >  or = 
- sorting(desc,asc on ip) in mysql(varbinary) and pg(inet)

and both works, but feel free to test on your own

> At this point I think our only option is to convert every IP field to varbinary and run each IP address through PHP's inet_pton function before inserting the data into the database.

That is not the challenge here (I allready build a internal mysql upgrade path in the ban pr),
the problem is that we need to old and new col at the same time.
The old col as source and the new as target for the converting

**Comment by jdarwood007** [comment]
Was that using the varbinary solution?

**Comment by albertlast** [comment]
Here a playfield: http://sqlfiddle.com/#!9/bf591/1/0 (mysql)
http://sqlfiddle.com/#!15/cde34/1/0 (pg)
i noticed that mysql result is unexpected...
i was expected that the amount rows should be two...

Feel free to play with the sqlfiddle,
maybe exists some more unexpected there.

**Comment by jdarwood007** [comment]
INET6_ATON for MySQL was added in 5.6.  I haven't checked at what the status for hosting is, but I have a feeling that most hosts are not there.

The current solution being discussed is we use PHP and its support for IPv6 to store the varbinary field and create it for comparisons.  I think it still works as SQL should still compare the varbinary properly.

**Comment by Oldiesmann** [comment]
The majority of the WordPress sites reporting their server info to WP are still on MySQL 5.5: https://wordpress.org/about/stats/

I do think the binary version would be best. Also, the issue of adding the new column "at the same time" isn't a big deal - we add a new column, copy the converted data to it, drop the old column and rename the new one.

**Comment by albertlast** [comment]
Postgresql would be affected by this change too.
The pg/db label should be added.

**Comment by albertlast** [comment]
I thinks this can be closed

**Comment by live627** [comment]
@Oldiesmann this can be closed
