### ISSUE TITLE
Convert instances of htmlspecialchars

### ISSUE THREAD

**Issue by matthew-kerle** [SimpleMachines/SMF#330]
As per the topic on SMF (http://www.simplemachines.org/community/index.php?topic=497179.0) there are still remaining instances of the raw htmlspecialchars(); without a character set being passed as an additional argument. $smcFunc['htmlspecialchars'](); was designed to take into account character sets and therefore _most_ instances of htmlspecialchars(); should be replaced with $smcFunc['htmlspecialchars']();.

**Comment by Oldiesmann** [comment]
@Garthi - have you finished working on this on your end? If so, could you shoot us a PR so we can merge your changes in?

**Comment by MissAllSunday** [comment]
OK, before I tackle this, what about Subs::un_htmlspecialchars() ?  Is there a particular reason why this is an independent function rather than a $smcFunc lambda?

**Comment by Arantor** [comment]
Partly historical, most of what was $func in SMF 1.1.x became $smcFunc in 2.0, and partly it's situational. Pretty much everything in $smcFunc is dependent on current situation, be it aware of the current character set (i.e. able to effectively be htmlspecialchars without having to explicitly remember to declare the character set every time), or based on database backend (e.g. different in MySQL to PostgreSQL)

The other twist about it being a lambda function is that you can effectively have two separate implementations of the same thing without any pain in terms of implementation, whichever version is appropriate for the current execution is the one that is declared, something you can't readily do so easily with more conventional functions (short of going around and having if() branches at the start of each function to work out what it should do, or dynamically loading the right class out of several with the otherwise-same name)

**Comment by MissAllSunday** [comment]
OK, those are all instance of htmlspecialchars, theres another one in Index.template which sets a custom class on <body>

I applied it to the places where it gets defined and remove it from the template but I don't know if that would be enough.
