### ISSUE TITLE
who is target by the upgrade_2-1* script?

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#3309]
I got the question in my mind,
for which version this upgrade script is targeting.

i ask oldiesmann in the irc, he sayed smf 2.0+,
this mean 2.1 beta version too.

Personaly i don't like this idea,
because this get fast messy,
let's take the ban ip topic.

There many different stats there could be the user:
- how came from 2.0, needs ip_low field as varbinary and convert the existing information into this and get rid off ip_low1-4
- early adopter of 2.1, got ip_low1-8 so they need convert the ipv4 and 6 to new ip_low varbinary field and get ride off ip_low1-8
- new one, which allready got ip_low varbinary -> no need to anything

When I update the upgrade script,
than i do this with a smf 2.0 in mind not 2.1

Maybe another solution would be,
a own upgrade script for 2.1 to 2.1.

Feel free to comment.

**Comment by MissAllSunday** [comment]
We don't support betas in the upgrade process.

This is one of the main reasons why we don't encourage people to use betas in production because if there are any DB changes running the upgrade won't add them, you must manually add then.

This isn't a problem in test forums, since you can always start fresh, however, if you have an old beta install and there are DB changes, merely updating the files isn't enough, you need to manually add the new DB changes.

The upgrade script only has to take into account any 2.0.x forums.

**Comment by Oldiesmann** [comment]
We do support betas in the upgrade process. Alpha versions are a different story, but we do typically support beta versions. It's also harder to test things if we don't.

**Comment by MissAllSunday** [comment]
Do you mean actual support in the upgrade process? As in be able to upgrade from beta 1 to beta 2 and beta 3 via the upgrade. Php file? 

I think it will be a lot more easier if the upgrade just take 2.0 as reference and nothing more,  there's a lot of changes in the last beta and it will be quite complicated to cover them all

**Comment by Kindred-999** [comment]
hmmm... I always thought that we did support beta to beta updates (but only using the full upgrader, no patches)

It will be MUCH more difficult to test beta if I have to blow away my test site every time I put a new beta version in (sometimes weekly, depending on push/pulls)

**Comment by MissAllSunday** [comment]
The issue here are DB changes, I want to think that by the time we hit an RC there aren't going to be any more DB changes.

I find it way more easier to apply those DB changes manually than having to include and cover every possible change in the upgrade.

So, add support for RC versions sure but for betas, not so much, specially considering that we discourage installing betas on production, thus, there aren't that many users out there who really need support for this.

**Comment by Oldiesmann** [comment]
Yes, we do support upgrading between beta versions. It is extra code, but it makes it far easier for us to test things.

**Comment by MissAllSunday** [comment]
I would be inclined to not offer upgrade support in betas, its extra code for little to no benefit, I mean everyone participating in this discussion can perfectly add manual edits on their test sites or create a sql/php file to add the changes or run a command line, there are a lot of ways someone can add manual changes to an old beta installation.

But anyway, I hope this IP thing is the last DB change we are going to make.

**Comment by albertlast** [comment]
I'm not sure,
because there exists some fields how are not able to safe ipv6:
https://github.com/SimpleMachines/SMF2.1/issues/3291#issuecomment-189595915

**Comment by smfbigguy** [comment]
I would be inclined to say let beta versions be upgraded. If it has always been this way for testing purposes because it makes it easier to test, why take that away from people who want to test. That doesn't make a lot of sense. To me anyway. People like me can not add manual edits to code unless it is shown to us and works by copy paste, let alone manual database edits. I think by not allowing beta versions to be upgraded you are going to have a lot of people asking how this should be done manually, which takes time away from real support issues. Just my thoughts anyway.

**Comment by MissAllSunday** [comment]
En Wed, 02 Mar 2016 16:02:50 -0600, Bigguy notifications@github.com  
escribió:

> I would be inclined to say let beta versions be upgraded. If it has  
> always been this way for testing purposes because it makes it easier to  
> test, why take >that away from people who want to test. That doesn't  
> make a lot of sense. To me anyway. People like me can not add manual  
> edits to code unless it is >shown to us and works by copy paste, let  
> alone manual database edits. I think by not allowing beta versions to be  
> upgraded you are going to have a lot >of people asking how this should  
> be done manually, which takes time away from real support issues. Just  
> my thoughts anyway.
> 
> —
> Reply to this email directly or view it on GitHub.

ugh.... I don't want to "take away" anything.....

It just seems illogical to me to add more code into an already convulsed  
process just so a couple of people can upgrade their test  
installations.... it doesn't make any sense. Manually upgrading its pretty  
easy. If you have problems or cant upgrade then just ask and I'm sure  
anyone will assists you.   And no, I assure you there arent

What DO make sense is having an error free upgrade process from 2.0 to 2.1  
as thats what the 99% of our userbase is going to do.

Seriously, just how many users do actually benefit from adding support for  
betas in the upgrade? I'll dare to say less than 10 users.

Remember, you shouldn't use betas in production, you only should use betas  
in tests forums.

It doesn't seems logical to me to potentially affect a very critical  
process (upgrade from 2.0 to 2.1) that hundreds of people are going to do  
just to support upgrading a bunch of test installations.

So nope, sorry, between a clean and error free upgrade from 2.0 to 2.1 and  
adding support for test forums I will always chose having a clean upgrade  
process.

**Comment by smfbigguy** [comment]
Well, a clean upgrade process is more important for sure. I agree with that. I guess I just don't like change to much, lol. I like the old adage that if it ain't broke don't fix it type of thing. If it's always been like that then leave it. I get your point though for sure.

**Comment by XinYenFon** [comment]
I don't think any support needed for Alpha to Beta / or Beta to Beta etc...

**Comment by smfbigguy** [comment]
That would be good but what about beta to RC. ? Are all database changes made final now or will there be more between builds. ??

**Comment by XinYenFon** [comment]
@smfbigguy in an ideal world, people shouldn't be using beta product (unless they are capable of doing manual sql runs etc...) in their sites. So they should easily wipe their test site and reinstall. So quick answer is no Beta > RC or Beta > Gold upgrade option would be less painful as well. Still last word comes from devs/pm.

**Comment by smfbigguy** [comment]
If there is a sql query to run I can manually run it but I can not write it is what I mean. If it is available for people to run then cool but if I had to make it or something than I'm lost.
