### ISSUE TITLE
Upgrade Problems

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#331]
First of all my db is very small (1,5mb) my all modifications uninstalled and I'm using i5 2.5Ghz (3.1 Ghz Boosted) CPU with 4gb ram.

First problem:

The upgrader found some old or outdated files.

Please make certain you uploaded the new versions of all the files included in the package. 

with little hackish method I passed this then second problem pops (I'm not sure this is a problem everyone gets) : Need to type admin pass twice (first time says wrong pass).

Third problem :

Executing: "Changing column names." (1 of 42 - of this script) -- Upgrade script returns with 

Error!
Server has not responded for 30 seconds. It may be worth waiting a little longer or otherwise please click here to try this step again

**Comment by XinYenFon** [comment]
Problematic code can be;

```
// Need legacy scripts?
if (!isset($modSettings['smfVersion']) || $modSettings['smfVersion'] < 2.1)
    $check &= @file_exists(dirname(__FILE__) . '/upgrade_2-0_' . $db_type . '.sql');
if (!isset($modSettings['smfVersion']) || $modSettings['smfVersion'] < 2.0)
    $check &= @file_exists(dirname(__FILE__) . '/upgrade_1-1.sql');
if (!isset($modSettings['smfVersion']) || $modSettings['smfVersion'] < 1.1)
    $check &= @file_exists(dirname(__FILE__) . '/upgrade_1-0.sql');

if (!$check)
    // Don't tell them what files exactly because it's a spot check - just like teachers don't tell which problems they are spot checking, that's dumb.
    return throw_error('The upgrader was unable to find some crucial files.<br /><br />Please make sure you uploaded all of the files included in the package, including the Themes, Sources, and other directories.');
```

Probably Upgrade script not getting SMF 2.1 Alpha 1 as SMF 2.1 branch and treating it like older version and running upgrade_2-0... or even others

**Comment by gevv** [comment]
@Antes  hocam  bu hatayı wamp serverde  2.0.15 den beta 4 e geçiş yaparken almıştım bir kaç defa ""click here""  linkine tıklayıp geçtim  güncelleme yapıldı  ama asıl sunucuda  işe yaramadı 


"""""14% Overall Progress
0.2%Step Progress

Database Changes
Executing database changes
Please be patient - this may take some time on large forums. The time elapsed increments from the server to show progress is being made!
Executing upgrade script 1 of 2.
Executing: "Changing column names." (1 of 41 - of this script)

Error!
Server has not responded for 30 seconds. It may be worth waiting a little longer or otherwise please click here to try this step again"""""


coğu sunucuda ""max_execution_time""  30 olarak  ayarlı ve kullanıcıların bunu değiştirme imkanı yok  

acaba  bu ""Database Changes""  işlemini  forum bakımında olduğu gibi sunucuya yüklenmemek için kesintili olarak yapmak daha iyi olmazmı

**Comment by XinYenFon** [comment]
Use English, and please do not tag me.
