### ISSUE TITLE
incomplete regex

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#3320]
It seems the regex added to remove empty BBC tags has flaws, it catches the following:

[b]Description[/b]

And completely removes it.

On the other hand, it doesn't catch this:

[color=purple][/color]

The regex itself relies on the closing tag having the exact match the first tag has which of course not all tags behaves that way.

Will take a look and see if I can modify it.  A possible solution is catch whatever word before the first = symbol and use that for the closing tag.

**Comment by Sesquipedalian** [comment]
Looks like you and I have both tried to address this recently, @MissAllSunday. My fix has been submitted as pull request #3331.

Looking at your latest version, I'm not really sure why you've set it up that way. The `(?>(?R))*?` bit creates an atomic group containing a recursive test of... nothing... and then lazily repeats it. If I've understood the intention for this regex correctly, a `\s*` would fit the bill much better in this bit.

The first part of this version of regex improves on the earlier version, but it doesn't match for opening tags that contain space separated parameters. Instead, `\[([^\]=\s]+)[^\]]*\]` captures just the first word, breaking off at either a `]`, a `=`, or a whitespace character. After that, anything else that might be in the opening tag can just be slurped up by `[^\]]*`.

I think the version in #3331 pretty much has this solved, except for the more general issue I mention in the comments there. Feel free to check it out and comment/critique it. :)

**Comment by MissAllSunday** [comment]
The atomic group is performing a recursive test of the entire regex.

Your solution won't caught multiple nested instances, for example:

[b][b][/b][/b]

The recursive atomic group takes care of that.

It doens't matter if this regex doesn't caught space separated params, the params are optional, we just need the name of the BBC which is the word before the first =  what happens after the first = and the closing ] is not really important.

**Comment by Sesquipedalian** [comment]
> The atomic group is performing a recursive test of the entire regex.
> 
> Your solution won't caught multiple nested instances, for example:
> 
> [b][b][/b][/b]
> 
> The recursive atomic group takes care of that.

Ah, yes. I see what you mean now. Still, would it not be better to use `(?>\s|(?R))*?` in order to match codes that have nothing but whitespace in them? Or do you only want ones that have absolutely nothing in them?

> It doens't matter if this regex doesn't caught space separated params, the params are optional, we just need the name of the BBC which is the word before the first = what happens after the first = and the closing ] is not really important.

It does if you want to match against, e.g., an empty quote like this:

```
[quote author=Simple Machines link=msg=1 date=1456135470][/quote]
```

`\[([^\]=\s]+)[^\]]*\]` correctly captures `quote` into the first group, whereas `\[([^\]=]+)(?:=[^\]]*)?\]` captures `quote author`.

**Comment by Sesquipedalian** [comment]
I forgot to mention in my previous comment that I have modified the code in #3331 to restore the recursion, along with the possibility to match a pair of tags that contains a string of whitespace. Please check it out, @MissAllSunday, and see what you think of it. I've tried to break this latest version every way I can think of, and so far it hasn't failed.

**Comment by MissAllSunday** [comment]
Its basically the same of what I already wrote but doing a comparison your regex takes 111 steps to complete while mine took only 30.  Use https://regex101.com to make the comparison yourself.

**Comment by Sesquipedalian** [comment]
That's not what I'm seeing.

First, here's yours tested against `[b][b][/b][/b]`

Success after 30 steps

Next here's yours tested against `[quote author=Simple Machines link=msg=1 date=1456135470][/quote]`

Failed after 37 steps

Here's mine tested against `[b][b][/b][/b]`

Success after 31 steps (which would be 28 if you took out my added checks for whitespace between the otherwise empty tags and at the end)

Here's mine tested against `[quote author=Simple Machines link=msg=1 date=1456135470][/quote]`

Success after 13 steps

**Comment by MissAllSunday** [comment]
What exactly are you using to test yours?

When I try your solution on regex101 I got an error, you have an unescaped  
/ char

This is what I got when I try yours: https://regex101.com/r/tY7fD7/1

Can you save your results and pass them in an url so I can see them?

But anyway, I got a couple more bug fixes on the same branch I added that  
commit. you can add the space stuff after I merge it to prevent merge  
conflicts.

**Comment by Sesquipedalian** [comment]
The error is just because you were using `/` as the regex delimiter on regex101.com. In the actual SMF code this regex is using `~` for the delimiter, so there's no need to escape the literal `/` in the regex. You can either add the escape when testing on the website, or just change the delimiter to `~`.

Aside from that, it looks like the version you are testing in that link is missing the `?` to make the `(?>\s|(?R))*` a lazy repeat. That's strange, since it is present in mine.

**Comment by Sesquipedalian** [comment]
... Oh geez. I committed and pushed with unstaged changes. My bad. :)

**Comment by Sesquipedalian** [comment]
Here's the URL you requested. https://regex101.com/r/hB5xB9/1

**Comment by MissAllSunday** [comment]
@Sesquipedalian Can you add the space in param and inside the tags to the regex? I had a few commits on my PR that didn't want to lose, now that those are merged your changes can be applied.

**Comment by Sesquipedalian** [comment]
Will do. :)

**Comment by Sesquipedalian** [comment]
... And done. #3331 is ready to merge.

**Comment by MissAllSunday** [comment]
Thanks!
