### ISSUE TITLE
[minor] Wrong Current SMF version

### ISSUE THREAD

**Issue by iveinsomnia** [SimpleMachines/SMF#334]
Admin page >

_Version Information:
Forum version: SMF 2.1 Alpha 1 
Current SMF version: SMF 1.1.18_

I assume **_Current SMF version: SMF 1.1.18**_ should be at least **_SMF 2.0.x**_ or **_SMF 2.1 xxx**_

**Comment by Oldiesmann** [comment]
The file that specifies the current SMF version (on simplemachines.org) falls back on 1.1.18 if your forum version doesn't have "2.0" in it. This is leftover from when 2.0 was released, as there wasn't anything newer than 2.0 at the time.

It will likely be fixed for the first public beta of 2.1, but I don't think there's really much of a reason to change it now.

**Comment by Oldiesmann** [comment]
Since I had to update the version file for 2.0.5, I went ahead and updated it to show that 2.1 Alpha 1 is the latest version for 2.1 forums. The detailed version check will still be wrong for the time being, as there's more work involved with that (you have to list each file and what version it should be). I'll update that in the coming days as I have time.
