### ISSUE TITLE
smtp mail bug

### ISSUE THREAD

**Issue by abolabo** [SimpleMachines/SMF#3383]
Hello guys!
Please replace $modSettings['smtp_host'] with getenv('SERVER_NAME') in line
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Post.php#L1319
Your code not working with gmail smtp correctly.

**Comment by live627** [comment]
Understand that we cannot just blindly change things around. That causes
bugs.   We don't want that.

On Fri, Apr 8, 2016 at 12:25 PM, Dmitry Suprunenko <notifications@github.com

**Comment by abolabo** [comment]
Yes, i understand it. 
Please read about EHLO and blocking http://faculty.cs.niu.edu/~rickert/cf/bad-ehlo.html
Your code gives smtp-server's URI instead sender host name. it's a bug 100%.

Best wishes from AbanteCart Developers Team. :-)
https://github.com/abantecart

**Comment by jdarwood007** [comment]
The problem is we connect to the specified smtp_host and then issue a ehlo with that stmp_host name.  So gmail appears to be blocking this.  We should be attempting it seems to get the FQDN (which SERVER_NAME should specify) and using that in our EHLO.

Of course incorrectly configured servers that do not setup the SERVER_NAME with their FQDN attribute may either cause this to say localhost or be blank.  Both of which can cause a bad EHLO as well.

**Comment by live627** [comment]
>  Your code gives smtp-server's URI instead sender host name. it's a bug 100%.

It is user-configurable from the admin panel, no?

https://github.com/SimpleMachines/SMF2.1/blob/4a67433f28be2c0c1b63c87fd41f209116046a4f/Sources/ManageMail.php#L313

**Comment by asmith20002** [comment]
@abolabo 
You gotta check SMF error log to see what gmail responded.

I use gmail smtp with SMF 2.1 beta 2 with absolutely no problems. But for the first time, gmail rejects it and you gotta configure some security settings in gmail to allow your website access.

In my case even after setting everything right, gmail was still rejecting me because of my password. Apparently when you get rejected by gmail, it also saves your password on those failed attempts. So even when I fixed all the security checks, it was seeing my password as suspicious. So after changing my password, it began to work.

**Comment by abolabo** [comment]
i guess this issue related to delegated mx-record to google mail-server. We have own web-server in our domain with  SMF 2.0.11 installed. But emails goes to google smtp-server.  Try this case.  Also you can check our mail class. It works similar.. for ex. https://github.com/abantecart/abantecart-src/blob/master/public_html/core/lib/mail.php#L270 and we have no any complaints from our users yet. 

p.s. i spent a lot of time to define a cause. In our case we had no any response from smtp on EHLO command. Only emptiness. ( var_dump of $response showed NULL and error-log contained common 'wrong stmp response' error)

**Comment by asmith20002** [comment]
What are the value in your SMF admin => Maintenance => Mail settings?

**Comment by abolabo** [comment]
Smtp host: ssl:\smtp.gmail.com
Port 465
Username: email from abantecart.com domain
09.04.2016 11:23 пользователь "asmith20002" notifications@github.com
написал:

**Comment by asmith20002** [comment]
Your username is not a gmail account?

Why there's \ in your hotname? It should be //
ssl://smtp.gmail.com

Also it seems that from 29th March, gmail smtp has stopped working. People are looking for solutions. But the SMF code is correct and there's no bug in it.

I changed to mailgun.com for now until gmail's solution.

**Comment by abolabo** [comment]
1. Our username is forum[at]abantecart.com
2. sorry.. answered from phone:) yes.. right slashes:)
3. you are right, it starts from 29th of March. But probably it works on plain gmail accounts (not tested).

**Comment by asmith20002** [comment]
Mine was plain gmail account and it stopped working as well.

**Comment by asmith20002** [comment]
@live627 @jdarwood007 

A solution for this is found:
http://www.simplemachines.org/community/index.php?topic=544856.msg3870010#msg3870010

Basically changing $modSettings['smtp_host'] to 'localhost'. Is that a change that must be done? Won't it break other smtp servers?

**Comment by tinoest** [comment]
"The sender-SMTP MUST ensure that the <domain> parameter in
a HELO command is a valid principal host domain name for the
client host. As a result, the receiver-SMTP will not have to
perform MX resolution on this name in order to validate the
HELO parameter." Is what the RFC states, I believe it also applies to the EHLO command. 

localhost violates that technically, it should be the server host name.
