### ISSUE TITLE
Database upgrade hanging 2.0.11 - > 2.1b3

### ISSUE THREAD

**Issue by PhuriousGeorge** [SimpleMachines/SMF#3387]
After using Firefox and enabling extra debug, I found I'm timing out on database upgrades at:
`Executing: "Messenger fields" (17 of 42)`

According to the extra debug information I was able to get, the following item was the last to be completed:
`Add an order value to each existing cust profile field...done`

**Comment by albertlast** [comment]
Did you a rollback to 2.0.11 of you database before you try this version of the upgrade?
Maybe the upgrade of the beta2 change you database in a version between 2.0.11 and 2.1b2.
And the beta3 upgrade can't handle this.

**Comment by PhuriousGeorge** [comment]
This was attempted on a fresh 2.0.11 conversion. I restored a backup at each attempt.

**Comment by albertlast** [comment]
What is the status of this issue?

**Comment by MissAllSunday** [comment]
@PhuriousGeorge Does this issue still happens to you while using the latest build?

**Comment by dodexahedron** [comment]
This issue is happening for me, too, on the current build.
Upgrading from 2.0.2 to current build (As of now).
It hangs exactly where @PhuriousGeorge said, and doesn't even output the next line in the upgrade_2-1_mysql.sql file, which is:
---# Converting member values

This is on php-fpm 5.6 and nginx 1.10
PHP error logging is turned on and I get nothing at this step to indicate what's going on.

![image](https://cloud.githubusercontent.com/assets/8242181/18418478/325d753a-7815-11e6-8e78-cde4208844ee.png)

**Comment by dodexahedron** [comment]
Still occurring on the most recent beta release.

**Comment by sbulen** [comment]
I believe this is a duplicate of:
Upgrade Issue - Can't get past Step 4 #3833

Which was addressed in this PR:
Fix upgrade migration of fields from members to themes #3842

**Comment by sbulen** [comment]
This should be closed.

**Comment by XinYenFon** [comment]
Can we get feedback from @PhuriousGeorge and/or @dodexahedron while trying with latest build ? Then we can close or move forward with this.

**Comment by PhuriousGeorge** [comment]
Sorry, I'll give the latest a go over the weekend and report back

**Comment by colinschoen** [comment]
@PhuriousGeorge Bump

**Comment by frandominguezl** [comment]
No news from @PhuriousGeorge, maybe we should close this

**Comment by sbulen** [comment]
This one should still be closed...

**Comment by frandominguezl** [comment]
@Sesquipedalian
