### ISSUE TITLE
Minify should not always write to default theme

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#3431]
It looks like the CSS minifier always writes to the default theme folder regardless of which theme's CSS is being used. For sites that intentionally run multiple themes, this is not a good idea because users will switch themes and this won't always pick up correctly, causing older CSS to be served.

While such users could uncheck the 'minify your CSS/JS files' option, that shouldn't really be the solution here.

**Comment by MissAllSunday** [comment]
The idea was to not mess around with any per user per theme per group per page thing as that only causes an infinite amount of permutations, making minify a bit poinless.

If we start making conditionals on what to minify, to whom, when, where and how, we will end up with either a custom css file per user per theme and per group per page or ending up burning cpu cicles everytime a page is displayed.

minify files are global, files should only be minified when served everytime for everyone, everywhere, while is possible to adapt that to custom themes, sooner rather than later we will face issues like different users been using a css file made for another user,etc.

The css creation is based on a one day cache, cleaning up that cache entry whenever an admin changes its theme will ensure updated files will be served.

If you have a better idea then by all means send a PR.

**Comment by Arantor** [comment]
In which case the minifier will have to be turned off if users have multiple themes, thanks for clarifying.

**Comment by MissAllSunday** [comment]
Is not optimal I reckon but theres really no other option.

We will have to offer support for multiple themes, that means the minify file should be saved in the theme folder where the files were taken from.

**Comment by MissAllSunday** [comment]
Been thinking about this but theres simply no way to make this to work with multiple themes.

The most feasible option would be to serve two minify files, one for whatever custom theme is been served and another one for the default theme.

Files with the 'force_current' setting as false will be added to the default one. This is extremely tricky since as far as I can see, not a single file in a vanilla installation has that option to true.

But of course this raises more issues, for example, if the user who happens to trigger the minify action doesn't use a custom theme, the minify file for that custom theme won't be created.

Depending on how the check is made, theres always the posibility that any custom theme will simply not be created or it will be re-created every time an users hits a page.

Also, having two minified files creates redundancy, the check to the cache entry will have to be split into 2 and most likely will have to use the theme ID to be completely sure we are referencing the correct theme, this is problematic because SMF doesn't use an auto increment ID on themes table, it just uses whatever ID after the max ID found in that table.  $id++  yeah yeah we need ot change that too. 

Another option is to check if index.css (or any other file for that matters) is been called from the default theme, if so add it to the minify file, if it comes from a custom theme, ignore it and serve it as usual.

**Comment by MissAllSunday** [comment]
Just thinking about a different way to fix this.

Yes, multi theme support is a must so theres gotta be a way to allow minify for multiple themes.

I was thinking about making the minify function more robust by searching for all installed themes with at least 1 member using them, get all the files marked for minification, see if those files exists on each theme folder, if so, grab the files form there if no grab the file from the default theme.  The usual checks for creating the minified file still applies of course.

Yes, this means an extra query per page request, hopefully the cache will largely mitigate this

**Comment by Arantor** [comment]
For my personal use case it doesn't help me to do it that way but I recognise my use case is non standard.

**Comment by MissAllSunday** [comment]
I'm targeting the most widely used case, an installation with multiple themes for any user to chose from.

**Comment by Arantor** [comment]
Looks good to me though I haven't tested it. Not sure how it would work on 20+ themes installed which is the use case I'm targeting but in that situation I probably should turn minify off anyway.

Thanks :)
