### ISSUE TITLE
Simple Actions, Simple Areas and Simple Sub Actions and ;xml

### ISSUE THREAD

**Issue by Sorck** [SimpleMachines/SMF#3454]
Files:
- Load.php (ending line 1941)

If you head to `/index.php?area=popup` or `/index.php?xml` you'll see the issue. (Loss of index template on unsuspecting actions).

Any simple area/sa/action, or xml, that is supplied in the URL causes the theme to drop the index template whether or not that area/sa/action is truly valid (this probably won't be an issue with actions as they should be in the action array and expect the lack of template, plus they are unique to the mod in a given implementation).

It's quite hard to find a way around this other than some form of asking if the current action expects to display without the index template. Another way would be to have another array containing actions which are able to handle simple actions - however this would then cause the issue that mod A has area "A" and mod B has area "B" but mod A isn't designed to handle area "B" and thus would have to throw an error. Thus you'd need an array specifying actions and which simple area/sa they expect.

Another approach would be to suggest any scripts doing such things pollute the main action array more so you might have `/?action=myMod` and `/?action=myModSimple` with the latter dealing with all simple action/area/sa.

**Comment by MissAllSunday** [comment]
But wouldn't be the expected thing to do?  after all, those are simple actions, if a simple action requires the index template then IMO its not a simple action anymore.

If you're talking about randomly adding an area param to an action that doesn't expect it like /?action=search;area=popup then yes, a check is needed but it woul have to be on a per action basis since we don't know if action X or Y can handle area Z or W.

As per simpleactions, well, those have to be defined in 2 places so if a mod adds a simple action then its implied the mod knows and fully understands that a simple action will not load the index.template.

$simpleAreas has the name of the GET area, we just need to add the main action for those areas and check if we truly are on that action:

```
    $simpleAreas = array(
        'profile' => 'popup',
        'profile' => 'alerts_popup',
    );
```

So, if a random area var is used on an action that cannot handle then the default subaction for that action will be called and no index template will be dropped.

**Comment by Sorck** [comment]
Yes, I did mean adding areas to actions that weren't expecting it. (Not having the index template can cause error information to be outputed and potentially be a security issue).

There's a repeated key issue using that method unfortunately - action=profile;area=popup is overwritten by action=profile;area=alerts_popup

The following could work:

``` php
$simpleAreas = array(
    'profile' => array('popup', 'alerts_popup'),
);
...
$context['simple_action'] = $context['simple_action'] || ( isset($simpleAreas[$context['current_action']]) && in_array($simpleAreas[$context['current_action']], $_REQUEST['area']) );
```

(Similarly for simple sub actions).

And a similar array could be used to make sure requesting an ;xml page doesn't throw an error - `$xmlActions = array();` could be created to list the actions that support XML output (this would need to be added to the integration hook as well).

**Comment by MissAllSunday** [comment]
Yes, I changed the key - values on https://github.com/MissAllSunday/SMF2.1/commit/91e08f0a1fc7a3892d8397e87b05ef6b9bb1da51

**Comment by Sorck** [comment]
Though with the keys the other way around you can still have a conflict problem if two different mods introduce the same simple area - one of their simple areas will stop working unexpectedly as it will be overwritten via duplicate keys.

**Comment by MissAllSunday** [comment]
Highly unlikely but OK...
