### ISSUE TITLE
Ip handling ?!

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3458]
Seams like the IP handling is very different .. if found table-rows with char255, witch char16 and more.
But .. normaly this column is filled with (as example)  **unhex('fe8000000000000010791b8a8d004ac8')**, also a normal ip6 address and is 41 chars long, so the col can set to varchar(50).
More I see that is not handled consequent on all situations .. so this will gives errors or the ip address is not displayed (for a admin, s example).
This need a consequent redesign !!

**Comment by albertlast** [comment]
when your look in the install of different database,
you see that every ip related col is varbinary 16 or inet.

so where is the problem?

**Comment by PortaMx** [comment]
The first problem is that the MySql UNHEX works on MySql release 5.5 and up .. most provider dont have this. So it's better to store the IP in a normal format, I think. And that need not a col with 255 chars (grin)

**Comment by albertlast** [comment]
since 5.5???? let me show your the manuel from myslq 5.0 https://docs.oracle.com/cd/E19078-01/mysql/mysql-refman-5.0/functions.html#string-functions
you should stop to think about this topic.

your idea shows me that your had not idea how specialy ipv6 is working.

here a small example why your idea is bad:
::1 , 0::1, 0:0::1, 0::0:1 this four ipv6 addres are the same your solution would do 4 different.

**Comment by PortaMx** [comment]
Well .. I have installed a version they was ~10 days older as today .. I reinstall again and now it works.

**Comment by albertlast** [comment]
When you find some bugs you are welcome.
But I would like to ask you to close this issue.
