### ISSUE TITLE
Question about developement branch

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#3526]
Sorry I wasn't around for a while. Why the development branch is outdated? (alpha 1)

**Comment by emanuele45** [comment]
Since I'm the responsible for that, I feel I have to answer.
Some years ago, when 2.1 was declared "feature-frozen", few people asked for a way to develop the "next version" after 2.1. In order to let them move SMF forward and let "us" work on finish up 2.1, I decided to act in accordance to the guidelines that we were following (i.e. http://nvie.com/posts/a-successful-git-branching-model/ ) and branched what should have become 2.1 final.
The release-2.1 branch was supposed to receive only bug fixes aimed at releasing 2.1 (and maybe small "cosmetic" features) and the development branch was supposed to keep all the "future development".
Then, the people that wanted to work on the "next version" disappeared and nobody else picked up development, at some point a year or two after the "feature freeze" was released and release-2.1 became the development branch.
