### ISSUE TITLE
double salvaged topics boards

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3594]
when trying to duplicate #2876 i had modified the database to set a topic to not be in a valid board. run the repair task and it was to create a salvage area and a board to contain the topic. 2 salvaged topics boards were created under the category of salvage area, this category did not show up until cache was cleared in the admin panel as well. IMO only one salvaged topics board should show up and the salvage area should show up without needing to clear the cache.

**Comment by XinYenFon** [comment]
I dig up something interesting, Due to description field in cats, its no longer creating salvage cat (which is easy fix), <s>but even ignoring that issue running that maintenance not creating Salvage Board but giving "The database value you're trying to insert does not exist: id_cat". Then I went back to my DB, which it shows category actually created but board not. Re-</s>run the maintenance, creates double salvage board and redirecting you to "recount" but you get token issue in there which mentioned in #2876.

**Comment by jdarwood007** [comment]
I got this as well while testing that bug.  The issue here is we track this via looking for a category named Salvage and a board named Salvage.  Which means if you run this in English you would get one and if you run it in another language, you get another.

Ideally we would correct this by storing this in the settings table.  Which could help prevent this from occurring.

**Comment by jdarwood007** [comment]
Looked into this more.  Its by design.  When fixing topics that are in non existent boards, the process creates a new board just for those and moves all topics in the non existent board to the new board.  By design this is to keep all topics logically sorted into the same board still.

Not going to fix this since this is working as intended.
