### ISSUE TITLE
This table pm_email_notify need ??

### ISSUE THREAD

**Issue by bobrenja** [SimpleMachines/SMF#3724]
TABLE {$db_prefix}members DROP INDEX 'pm_email_notify'   upgrade 2.1 b*
delete Sources/Subs-Members.php
`672  'new_pm', 'pm_prefs', 'show_online', 'pm_email_notify',`

**Comment by albertlast** [comment]
In the database this field didn't exists,
in php code the only entry which i found is this in subs-members and this is only a $knownInts array.

**Comment by bobrenja** [comment]
In the database this field didn't exists 2.1 b *

In install_2-0_mysql.sql exist 2.0.12
CREATE TABLE {$db_prefix}members
`1230   pm_email_notify tinyint(4) NOT NULL default '0',
`

**Comment by albertlast** [comment]
Do it hurt smf more when we remove this col or more when we do nothing?
on pg side the drop of a col only remove the visiblity of the col -> fast operation : http://stackoverflow.com/questions/15699989/dropping-column-in-postgres-on-a-large-dataset
on mysql side the operation take some time because the table is changed (table lock).

**Comment by bobrenja** [comment]
If this field is not needed, when an update 2.0.12 to 2.1 to remove.
