### ISSUE TITLE
Multiple themes and load.php

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#3734]
i'm not able to test,
but this query: https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Load.php#L1279
get scrued when the user got multiple themes with the same variable names.

so someone with enough knowledge should look into this.

**Comment by jdarwood007** [comment]
Yea, I see what you mean.  It should be limiting to id_theme = 0.  I'm not sure of the breakage as we would have to handle that on the user profile as well but still handle theme specific options.

In all I see it as a design flaw as we should be using a member_options table instead and move all those settings over for all user settings not theme specific.  The theme options should be in a theme_options table instead as well and handle all user theme options.  The themes table really should only have the core/admin theme stuff.
The issue behind mashing a but of options in the themes table caused this code to get added due to a security issue in the past: https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Load.php#L1741

**Comment by albertlast** [comment]
One information i would like to add,
the query/database as his own got no problem with situation,
but the code below, how it read the output will get problems.

**Comment by sbulen** [comment]
albertlast pointed to the code in loadMemberData(), which will definitely need changing.  We could do as jdarwood007 suggests & limit it to the default (I think the default id_theme =1).  

Another thought would be to not load the theme data at all in loadMemberData().  I've been looking at the various places it is called, and I cannot find any places that look at the theme options after invoking it.  We would need to carefully review & confirm it's not used.  But if it isn't, why look it up at all.   

(It'd sure be nice to have some 2.1 themes to test with!)
