### ISSUE TITLE
Install a New Theme

### ISSUE THREAD

**Issue by snrj** [SimpleMachines/SMF#3739]
smf 2.1 beta 3 
Install a New Theme
From an archive (e.g. .zip, .tar.gz)
upload test theme http://smf.konusal.com/index.php?action=downloads;sa=view;down=85

An Error Has Occurred
SMF was unable to find any valid information within the package-info.xml file included within the Package. There may be an error with the modification, or the package may be corrupt.

**Comment by live627** [comment]
Confirmed. Zero-byte files are written, even though all packaged files are recognized. Quite the funny bug.

**Comment by jdarwood007** [comment]
I had tracked this down at one point but never was able to resolve it.  Its due to the zip handling in 2.1 versus 2.0 zip handling.  In 2.0 we do it by hand basically and in 2.1 we are using the PharData class.  I couldn't trace back why it didn't like it or a fix but I believe it was due to when your trying to get a single file out or something.

**Comment by jdarwood007** [comment]
Although at this point, not sure why we are using PharData class instead of ziparchive class which meets our 5.3.8 min requirements.

**Comment by Sesquipedalian** [comment]
This may or may not be relevant, but 2.0 has always had trouble handling ZIP archives made using certain `zip` tools, even though the archives are perfectly valid. For example, SMF always chokes on archives made using the Info-ZIP `zip` library, which is fairly common in the *nix world.

**Comment by Sesquipedalian** [comment]
Correction: the last sentence of my previous comment should have said "... the Info-ZIP `zlib` library..."

**Comment by sbulen** [comment]
I don't think PharData is the issue here.  

Reading thru this, this is what I *THINK* is happening...
  -  The read_zip_file() function steps thru all of the files in the .zip & creates empty files with a PHP touch (subs-package line 2723).  I think it does this to ensure it CAN write everything where it wants it (???).
  -  On a subsequent pass, read_zip_data() attempts to move the CONTENTS by opening these files again with an fopen using an r+
  -  This subsequent pass is failing, for some reason it cannot re-open these files writeable (the +)
  -  This causes a fail & the program exits.

So... my theory is that the files are 0 length because the contents haven't been copied over yet.  

There is an accompanying entry in the error log that corresponds with the failed fopen:
> 2: fopen( (path stuff)/Themes/temp/css): failed to open stream: Permission denied   (subs-package:2784 is noted)

During the error exit, it is still cranky - this is also in the error log:

> 512: package_flush_cache(): some files are still not writable   (subs-package:2788 is noted)

It does attempt to make the files writeable with a chmod.  Not sure why this isn't working.  Note that the temp folder being used thru all this is a subfolder of the Themes folder, which is protected.  

Just a theory at this point.  About to read it all again...

**Comment by sbulen** [comment]
Should it even be trying to issue an fopen on the directories themselves?  That's what's failing...
It's the very first thing it tries to do on what I call the 2nd pass above...

After a little research, the answer is NO...   You will ALWAYS get a "permission denied" when issuing an fopen on a directory.  That's the root cause here.   

The solution will be to find a way to iterate thru files only, bypassing directory entries, OR, to use an is_dir before issuing the fopens.

**Comment by sbulen** [comment]
OK...  got it...   

In Subs_Package.php, in package_flush_cache() there are three changes that need to be made.
(1) Fix the comments describing the function...   It doesn't delete anything, it flushes the cache from memory to the filesystem.  
(2) The "acid test" block (with the fopen that fails) shouldn't happen when working on a directory.  Use an is_dir($filename) to bypass.
(3) The fopen/fwrite/fclose at the end should not happen when working on directories.  Enclose in an is_dir($filename) to bypass. 

The themes appear to install fine when this is done!   I'm now using the xenxen example that was used above under 2.1.  

I haven't yet figured out git...   If someone could pick this up & do a PR, I'd appreciate it...

Proposed code for #2 above:
> 		// if we are not doing our test pass, then lets do a full write check
> 		// bypass directories when doing this test
> 		if ((!$trash) && !is_dir($filename))
> 		{
> 			// acid test, can we really open this file for writing?
> 			$fp = ($result) ? fopen($filename, 'r+') : $result;
> 			if (!$fp)
> 			{
> 				// We should have package_chmod()'d them before, no?!
> 				trigger_error('package_flush_cache(): some files are still not writable', E_USER_WARNING);
> 				return;
> 			}
> 			fclose($fp);
> 		}
> 

Proposed code for #3 above:

> // Write the cache to disk here.
> // Bypass directories when doing so - no data to write & the fopen will crash.
> foreach ($package_cache as $filename => $data)
> {
> 	if (!is_dir($filename)) 
> 	{
> 		$fp = fopen($filename, in_array(substr($filename, -3), $text_filetypes) ? 'w' : 'wb');
> 		fwrite($fp, $data);
> 		fclose($fp);
> 	}
> }
>

**Comment by jdarwood007** [comment]
@sbulen ,

As this is your discovery and fix, it would be great if you could setup the PR and get the credit for the work.  I once did a very basic howto with another project in GitHub and it may help you be able to get a PR submitted https://www.simpledesk.net/community/index.php?topic=2184.0

Looking like you are tracking down the issue though

**Comment by sbulen** [comment]
Hold my beer, I got this...

**Comment by colinschoen** [comment]
Holding :beer:

**Comment by sbulen** [comment]
Fix issues with package_flush_cache() that prevented uploading of themes #3770 
Submitted...

Don't know why it listed 4 commits - that includes syncing my repo + 1 failed attempt + reverting the failed attempt + the real fix.

Net net is correct though, only the changed lines are listed.
