### ISSUE TITLE
Drafts - undefinex index: id_member

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#3788]
**The error**
 Undefined index: id_member
Sources/Drafts.php
Line 73

**Steps to reproduce**
1. Create a new topic
2. Click "Save Draft"
3. Click "Cancel" in the alert
4. Click "Save Draft" again
5. Click "OK"

**Comment by albertlast** [comment]
i'm not sure what the correct solution for this is.
On the one hand id_member is missing in select from 326 BUT
on the otherhand the check make no sense because the read function use $user_info['id'].
in the if statement in line 73 will be now checked if $user_info['id'] and id_member is the same...

**Comment by frandominguezl** [comment]
I removed  && $draft_info['id_member'] from the if statement and the issue didn't appear. Is this correct & valid to do a PR?

**Comment by colinschoen** [comment]
Agreed, `ReadDraft` clearly states `Validates that the draft is the user's draft`. That is a valid `PR` and fix @d3vcho. Please submit it and I will merge.

**Comment by colinschoen** [comment]
I'll just go ahead and push this one because I want to get this fixed for release soon.
