### ISSUE TITLE
unapprove first post, not unapprove thread

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#379]
there are times that it would be useful to not have a full thread unapproved when unapproving the first post.

if the whole thread is unapproved the op can not view any replies they made or those that are moderators that reply. each reply would need to manually approved after the first post is unapproved

**Comment by emanuele45** [comment]
That would probably make sense.

Thinking while writing, so I may be wrong.

Though there is to consider that approval acts almost the same way: approving the first message approves the entire topic (including any existing message not yet approved).

Since the two functions are related (code-wise and on how they works) change one would mean change the other too.
In other words (not that I'm against, on the contrary, I think it could even be better since it would match the way other functions (like remove messages/topics) work) it would mean separate the approval of the messages from the approval of the topics and add another button (I'd say in the "moderation bar") to actually approve the topic.
Though such change may create some other issues (even only visual since it would be a bit more difficult to identify an non-approved topic with a first message approved...

**Comment by norv** [comment]
> or those that are moderators that reply.

This makes sense, the poster should be able to see these, otherwise it seems the behavior is inconsistent.

**Comment by Arantor** [comment]
Unless behaviour drastically changed in SMF, moderators who do reply (who, by definition, have approval power because if they didn't, they wouldn't be able to see the topic), their posts should be automatically approved regardless.

There are other issues around this; approved posts even in unapproved topics show up in Recent Items, because that's purely checked at message level, for example.

Sure, we can offer separate unapprove-message and unapprove-topic buttons but unapproving a topic must only unapprove the topic in the topics table, otherwise moderators will find their posts not visible to the topic starter, meanwhile if you unapprove the topic but not touch any of the messages (to leave that other behaviour consistent), messages that are still approved are still accessible in other places.

I'm almost tempted to call this an edge condition of sorts, though I'm not disputing it needs changing, I'm just not sure what to change for the best.

**Comment by illori** [comment]
currently if you unapprove the first post in the topic all posts get unapproved so the op would not be able to view any of them except for new replies that would be already approved.

**Comment by Arantor** [comment]
Ahhhh, I see what you're getting at. Thing is, even if we separate unapprove topic and unapprove post behaviour, we still shouldn't be flagging every single post in a topic as needing to be approved, it should be being handled as the topic flag with each message in the topic remaining approved as it would have been before (and then cleaning up the edge cases)

**Comment by illori** [comment]
i have not tested that much approving a thread that was unapproved to see the behavior, but i know if a thread is unapproved and a user notices that their post count went down it could be an issue :P so i approve the posts in the thread as just the first post should be unapproved not the whole thread.

**Comment by NanoSector** [comment]
Do we still want to change this so late in the game?

**Comment by illori** [comment]
if not a major change i think it should be still done.
