### ISSUE TITLE
Reason for editing and censored words inconsistencies

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#3806]
I was just testing censored words. Will leave you a picture about the issue. "*&ka'!^" is the same word as in the reason for editing (using quick reply), in this case "test".

![](https://i.gyazo.com/2070d557a7a46e365694e9405e72a336.png)

Now, let's quote the message and add some "test" inside & outside the quote tags.
After that, let's go back to our Censored Words settings and remove the actual word and its replacement. This is what happens:

![](https://i.gyazo.com/139354d019e46146925656793a1a90fa.png)

**Comment by Kindred-999** [comment]
I am not sure I understand what you are doing or what the problem is...


Do we have "reason for editing" as a feature in 2.1?   I didn't think that we did...

**Comment by live627** [comment]
we do...

**Comment by frandominguezl** [comment]
We do using quick reply, as stated above.

**Comment by sbulen** [comment]
I think this is expected behavior.  At issue (I think...) is that the quoted text is the quoted text _"as displayed at time of quote"_, not _"as stored in the DB"_.   

Thus, it doesn't honor the removal of the censored word rule.  (In the new message, it is now stored as  '*&ka'!^', not 'test'...)

The quirky inconsistency here is that it did honor the removal of the censored word rule - for the new message text entered inside the quote, but not for the original quote.  But that makes sense, because that is truly new content within the new message, and is stored in the new message as such (stored as 'test', not '*&ka'!^'), thus within the reach of adding/removing censored words.  

To address this slight inconsistency would require some variation of censored word rules within quoted text vs outside of quoted text.   Which, I don't think is smart, it just opens folks up to being able to bypass the rules by quoting themselves...   

OR...  Bringing quoted text over as _stored_ in the original message, not as _displayed_...   Given that we can edit anything inside or outside quote tags (as in the example above), I'm not sure we know exactly which content to query from the original message...  

OR... The simplest & cleanest way to address the quirk would be to NOT honor the censored word rule at quote time, thus displaying the offending words.  Which, I don't think we want to do...     

I suggest leaving it alone...  Mainly because this issue makes my head hurt...

**Comment by frandominguezl** [comment]
Yep, it's a good point. Let's close it, for now ^^

Thanks, sbulen
