### ISSUE TITLE
Upgrader Step 2 - Cannot find database source script! Please check file Subs-Db-mysqli.php is within your forum source directory.

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#3813]
http://www.simplemachines.org/community/index.php?topic=551149

Something related to #3801 ?

**Comment by tinoest** [comment]
Yes, seems that install.php and upgrade.php haven't been fully cleaned up / switched 

#3761 should either contain it or it should be done after that is merged to save people duplicating work.

**Comment by illori** [comment]
running via CLI  i get this
Warning: mysqli_get_server_info() expects parameter 1 to be mysqli, null given in D:\wamp\www\github2.1\upgrade.php(2079) : eval()'d code on line 1

Call Stack:
    0.0180    1403544   1. {main}() D:\wamp\www\github2.1\upgrade.php:0
    0.1800    1882616   2. cmdStep0() D:\wamp\www\github2.1\upgrade.php:303
    0.1810    1866560   3. db_version_check() D:\wamp\www\github2.1\upgrade.php:2958
    0.1810    1868672   4. eval('global $db_connection; return min(mysqli_get_server_info($db_connection), mysqli_get_client_info());') D:\wamp\www\github2.1\upgrade.php:2079
    0.1810    1868872   5. mysqli_get_server_info() D:\wamp\www\github2.1\upgrade.php(2079) : eval()'d code:1

running in browser i get 
Fatal error: Call to undefined function safe_serialize() in D:\wamp\www\github2.1\upgrade.php on line 399
Call Stack
#	Time	Memory	Function	Location
1	0.0190	1420888	{main}( )	..\upgrade.php:0
2	0.1070	1958920	upgradeExit( )	..\upgrade.php:336

**Comment by live627** [comment]
@illori #3761 should fix that

**Comment by illori** [comment]
now a new error 
Fatal error: Call to undefined function throw_error() in D:\wamp\www\github2.1\upgrade.php on line 481

Call Stack:
    0.0120    1162920   1. {main}() D:\wamp\www\github2.1\upgrade.php:0
    0.0360    1182528   2. loadEssentialData() D:\wamp\www\github2.1\upgrade.php:154

**Comment by live627** [comment]
@illori can you apply https://github.com/live627/SMF2.1/commit/fbd4e0a034f8343f772f8d230f44df87898f4cac?

**Comment by illori** [comment]
that gives me via cli 
```
No direct access...
```

nothing else but the above.

**Comment by illori** [comment]
also i see in the other folder upgrade-helper.php does it need to be moved to the main folder like upgrade.php? i did that when i ran the upgrade.

**Comment by XinYenFon** [comment]
@illori can you try with this open your upgrade.php.

Find
```
	// Get the database going!
	if (empty($db_type))
		$db_type = 'mysql';
```

Replace with
```
	// Get the database going!
	if (empty($db_type) || ($db_type = 'mysqli'))
		$db_type = 'mysql';
```

**Comment by illori** [comment]
with the new file from live or the existing file?

**Comment by XinYenFon** [comment]
latest build, and yes you also need upgrade-helper.php in root.

**Comment by illori** [comment]
that does not fix the message i am getting.

**Comment by jdarwood007** [comment]
FYI, #3838 is a fix as well, but checks to make sure the helper exists.  I know sometimes we have issues in support with files not always getting uploaded during upgrades (client side issues).  So the check should prevent a fatal error and give the user some information as to why it fails.

**Comment by jdarwood007** [comment]
Also the proper fix that @Antes meant was:
````
	if (empty($db_type) || $db_type == 'mysqli')
		$db_type = 'mysql';
````

**Comment by illori** [comment]
new error message


Notice: Undefined index: mysqli in D:\wamp\www\github2.1\upgrade.php on line 1554

Call Stack:
    0.0090    1163000   1. {main}() D:\wamp\www\github2.1\upgrade.php:0
    0.3030    3185120   2. cmdStep0() D:\wamp\www\github2.1\upgrade.php:255
    0.3040    3169072   3. db_version_check() D:\wamp\www\github2.1\upgrade.php:2328


Notice: Undefined index: mysqli in D:\wamp\www\github2.1\upgrade.php on line 1557

Call Stack:
    0.0090    1163000   1. {main}() D:\wamp\www\github2.1\upgrade.php:0
    0.3030    3185120   2. cmdStep0() D:\wamp\www\github2.1\upgrade.php:255
    0.3040    3169072   3. db_version_check() D:\wamp\www\github2.1\upgrade.php:2328


Fatal error: Call to undefined function db_extend() in D:\wamp\www\github2.1\upgrade.php on line 2332

Call Stack:
    0.0090    1163000   1. {main}() D:\wamp\www\github2.1\upgrade.php:0
    0.3030    3185120   2. cmdStep0() D:\wamp\www\github2.1\upgrade.php:255

**Comment by illori** [comment]
actually scratch that, a PR that has been merged since 12am eastern fixed that. new error to replace it on one line

+++  Upgrading post notification settingsError: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given File: D:\wamp\www\github2.1\upgrade.php(1777) : eval()'d code Line: 23 done.

IMO we can now close this and open a new bug for the above error.

**Comment by Oldiesmann** [comment]
That latest error means the query on lines 704-713 of upgrade_2-1_mysql.sql failed for some reason (not just that it didn't return any results). What do you get if you run this query in phpMyAdmin?

```sql
SELECT id_member, notify_regularity, notify_send_body, notify_types
FROM smf_members
```

**Comment by Oldiesmann** [comment]
The likely cause is that the query failed because three of the four columns it tries to pull data from are dropped after the upgrader is run the first time. The easiest way to prevent that error from showing is to either check whether $result is `false` or to add a setting like "notifications_done" to the settings table that we can check for and skip that step if that setting exists.

**Comment by illori** [comment]
got a new error message


Parse error: syntax error, unexpected '?>' in D:\wamp\www\github2.1\Settings.php on line 198

Call Stack:
    0.0050    1163056   1. {main}() D:\wamp\www\github2.1\upgrade.php:0


there is only one ?> in the whole file and that is on line 198 the last line of the file.

so then i went and removed the ?> and now i got this error


Parse error: syntax error, unexpected end of file in D:\wamp\www\github2.1\Settings.php on line 198

Call Stack:
    0.0180    1164552   1. {main}() D:\wamp\www\github2.1\upgrade.php:0

so this time i removed $upgradeData = #remove#; from Settings.php and the upgrade ran without issue.

why is the upgrade choking on this line??? after running the upgrade now that line is back, so it will choke on it again if i dont manually remove it. maybe it does not like that there are no quotes of any type around #remove# ?

**Comment by sbulen** [comment]
The # creates a syntax error, since it comments out thru the end of the line, including the semicolon.

It will cause different issues depending on what line is next in Settings.php.  So different folks will see different symptoms.

I have had a PR fix awaiting approval.

IMO, that should never have been put there, even temporarily, due to the syntax error.    Bad things happen if it somehow doesn't complete.

Note that this prevents some folks from loading the app, since settings.php is loaded early.

Again, different symptoms for different people, depending on the arrangements of lines in your Settings.php file.

See:  Upgrader - : unserialize(): Error at offset 0 of 15 bytes in ... upgrade.php on line 125 #3841

And:    Upgrade: forum don't work after upgrade process ended. #3854

I really think this is the proper fix:   Set $upgradeData to null after successful upgrade #3849

**Comment by albertlast** [comment]
@illori  can we close this?

**Comment by illori** [comment]
Yes
