### ISSUE TITLE
News letter progress issue

### ISSUE THREAD

**Issue by siddhartha-gupta** [SimpleMachines/SMF#383]
Stop using Max to get the emails to send. One of the website I was working on has member id's in bit awkward manner.

Just to test the bug, register on 2 members on a test site and give them these respective ids
- Member 1 - 1(id)
- Member 2 - 50000(id)

Now news letter sending code thinks you have 50k members.

ManageNews.php

Line 654

SELECT MAX(id_member)
FROM {db_prefix}members',
array()

**Comment by matthew-kerle** [comment]
Nice catch, thank you! Feel free to submit a PR for it if you have the time :) If not, at least thank you for reporting it.

**Comment by siddhartha-gupta** [comment]
Let me see if I can get the code, as I've already fixed it on a live site :P.

**Comment by emanuele45** [comment]
Just the usual reminder:

```
// Get the smelly people - note we respect the id_member range as it gives us a quicker query.
```

**Comment by Oldiesmann** [comment]
If we're using that to get the total number of emails to send, the best option would be to replace MAX() with COUNT() instead.

**Comment by jdarwood007** [comment]
If we change over remember this:
http://www.mysqlperformanceblog.com/2007/04/10/count-vs-countcol/

mysql> show profiles;
+----------+------------+------------------------------+
| Query_ID | Duration   | Query                        |
+----------+------------+------------------------------+
|        1 | 0.00016525 | SELECT COUNT(*) from fact    |
|        2 | 0.00064675 | SELECT COUNT(i) from fact    |
|        3 | 0.00109800 | SELECT COUNT(val) from fact  |
|        4 | 0.00054625 | SELECT COUNT(val2) from fact |
|        5 | 0.00068875 | SELECT MAX(i) from fact      |
|        6 | 0.00122675 | SELECT MAX(val) from fact    |
|        7 | 0.00195475 | SELECT MAX(val2) from fact   |
+----------+------------+------------------------------+

It is infact faster to use \* when counting rather than specifying a ID.  Even with a index, it is still slower.

This is only with 10k entries in that table.  But already we can see a difference.

**Comment by siddhartha-gupta** [comment]
Hi All,

Placed the fix and sent the PR too #650 but not sure why some other files were also listed as modified, when I haven't even touched them. Might be something to do with line break (CRLF, LF and CR). BTW which one SMF prefers?

**Comment by Arantor** [comment]
The SMF repo uses LF only (and should force it into LF if you try to use CRLF)

Regarding the comment from SleePy above about profiling, those are only entirely valid for MySQL. PostgreSQL and SQLite have different characteristics (where COUNT(id) typically performs better than COUNT(*))

**Comment by siddhartha-gupta** [comment]
Slpeey's suggestion added in the commit. Meh, poor memory of mine.

Moreover these were the files which were shown as changed. Not sure how tff's are shown as changed files.

Themes/default/fonts/AnonymousPro.ttf
Themes/default/fonts/ConsolaMono.ttf
Themes/default/fonts/Pfennig.ttf
Sources/Subs-Charset.php

**Comment by Arantor** [comment]
The ttfs are shown as changed files because of the gitattributes file not being aware of ttfs being binary files. But personally I'd suggest setting your local configuration to have the autocrlf option set to false anyway so you always get the files as they are.

Subs-Charset.php for some reason is a bit special and it may be because of its content, I'm not sure.

**Comment by siddhartha-gupta** [comment]
Well spent some time on this since yesterday and got hold of issue. Thanks for the suggestions.

Do guys want me to make another PR?

**Comment by Arantor** [comment]
If you could, please, that would make it easier to get merged :)

**Comment by siddhartha-gupta** [comment]
Created a PR with only desired files modified ;).
