### ISSUE TITLE
Easy switch between sidebar and dropdown views

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#384]
In SMF2.0, Profile > Look and Layout, there is a setting "Use sidebar menus instead of dropdown menus when possible." When this is enabled it is possible to switch between the two layouts very easily by clicking on the two little arrows, for example next to the section title "Profile Info": 
![easy switch](https://f.cloud.github.com/assets/3731638/593295/1faf926c-ca33-11e2-8251-b09619a92b56.png)

This useful method for quickly switching between the layouts doesn't appear to be in SMF2.1 at the moment.

**Comment by emanuele45** [comment]
TBH you are lucky the double menu is still available... :angel: (It was already on my sight)

Why do you need to switch between the two so frequently? (That's a genuine question, I've never used the side-menu and I don't feel the need to switch between the two)

**Comment by ChainyEO** [comment]
I generally prefer to use the sidebar layout as I find it much easier to navigate. But occasionally I've used that quick switch button when testing things for the translation - some pages are easier to view with a bigger screen area. Still, I suppose this quick switch button is far from an essential feature! But if it's not too difficult to implement, then some users might appreciate it.

I'm not quite sure what you mean by 'double menu', but if you mean the option for the sidebar menu, then I think it would be a terrible shame if that was taken out of future versions of SMF. As I said, I think the sidebar menu works really well - you can quickly scan through the list of features in the sidebar. I find this much more convenient than fumbling around with the drop-down menus where everything is hidden unless you happen to hover the mouse over the right section.

**Comment by emanuele45** [comment]
Then a quite particular case.

I removed it for two reasons:
1) I think it was a "temporary" measure to allow people familiarize with the menu in the switch between 1.x and 2.0,
2) I have always seen very few people realise that to switch back it was necessary to click on the first title of the menu. (Why? Because in Italian the title is long enough to switch on two lines and imagine that the switch is there is just a wild guess or big luck.)

Yeah, I know people may prefer one or the other, though every single variant increases the testing needed to ensure everything works as expected and in many (most) cases requires to accept sub-optimal solutions just because the two variants can't live happily together (and this happened during 2.0 development because many admin pages are not very usable with the sidebar at "low" (1024) resolutions).

ETA: This is the commit https://github.com/SimpleMachines/SMF2.1/commit/d40298396c21ebc0f1090f0a3bb77100128b70ae if anyone wants to restore it, just revert that.

**Comment by illori** [comment]
i think the current option in 2.1 is just fine. most people dont even know they can switch via the double arrows and those that have found the option dont usually switch back to the other menu. if this were to be changed back i dont see the advantage of doing so for most users, they just need to be told where the new option is found and use it.

this is the same idea that most users dont know that you can collapse the header until they do it by accident and complain that things are missing now since they collapsed the header.

**Comment by jdarwood007** [comment]
I think its fine as well, a mod can re-add this feature again if needed for development or translation purposes.

**Comment by Arantor** [comment]
Anyone have anything to add before I close it?
