### ISSUE TITLE
upgrade.php post notification settings error

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3885]
+++  Upgrading post notification settingsError: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given File: D:\wamp\www\github2.1\upgrade.php(1784) : eval()'d code Line: 23 done.

**Comment by sbulen** [comment]
I believe this was resolved late last night.   I was seeing this.

Could you try with a new set of files?

**Comment by illori** [comment]
i just cloned again, this is not resolved.

**Comment by sbulen** [comment]
MySQL or pg?  Do you know which specific DB step it was working on, e.g., "add column to xxxx"?   

Line 1784 doesn't really give anything to work on (all parsed code goes thru that line...).  The eval'd code isn't helping either...

**Comment by illori** [comment]
mysql, that is the complete line it is run via cli and that is from the output.

**Comment by sbulen** [comment]
Thanks.  When you have 'debug' on, it should tell you the exact step it's on as it's running.  (It does on the web version, I've never tried the CLI version, I believe the CLI arg is --debug.)

I didn't get the error on an empty db vanilla 2.0 => vanilla 2.1.    

I'm in the middle of restoring a full 2.0 instance to test the full upgrade with REAL data.

**Comment by illori** [comment]
this not a vanilla upgrade from 2.0 to 2.1. this is an upgrade from 2.1 to 2.1.

see https://github.com/SimpleMachines/SMF2.1/issues/3813#issuecomment-273889880

**Comment by sbulen** [comment]
Hmmm...  There are comments at various places in the 2.1 scripts that say they cannot be run twice.

I think you have to re-do the 2.0 => 2.1 upgrade.  

Or...  

This turns into a request to re-do the upgrader so everything can be rerun safely.   That is likely another significant change to the upgrader.

**Comment by sbulen** [comment]
Next time you run it, could you try the --debug & see if we get more info?  The last message broadcast before it dies.

**Comment by jdarwood007** [comment]
What parts can't be ran twice?  The 2 places that comment that are actually safe.  The first one is doing a replace instead of insert, so it will overwrite things, and the second checks your SMF version to be sure.

**Comment by sbulen** [comment]
In the thread Illori points out above, Oldiesmann referenced steps that remove columns.   And there is a bunch of those.  

I took the comments at face-value.   At the moment, I'd like it to run ONCE cleanly...

**Comment by illori** [comment]
adding --debug did not change the output any.

**Comment by sbulen** [comment]
THAT in itself, I think, is an issue.  Otherwise you're flying blind.  Pointing to the eval() line of code doesn't help...  Plus, I think you might want to watch the progress.  I do, I always have it on...

**Comment by albertlast** [comment]
It's note supported to do an upgrade from 2.1 to 2.1,
so when your find issues here,
than there are no issues because the upgrade is not planed to support this.

**Comment by illori** [comment]
we will still have users that will attempt this over time. even if we tell users they should not be running upgrade.php as they dont need to they will attempt, then come to the support forum stating the errors that were found and worried they broke their forum as a result even if they dont mean much related to that.

if you are running upgrade.php via CLI what exactly do you really want to watch? i send the output to a file so it can be reviewed at a later time. not like it takes that long to run that i want to watch it "live".

**Comment by albertlast** [comment]
and the smf team sayed 1000x times they don't support this.

**Comment by XinYenFon** [comment]
@illori Partial upgrade is not supported, and yet we said this over billions of time, considering that we expect people not to do it or do it with their own risk. If they worry about breaking their forum, they should not be using beta/RC software.

**Comment by illori** [comment]
i know that, but once 2.1 gets to RC stage this issue will still exist. if someone upgrades SMF 2.0 to SMF 2.1 RCx and then needs to upgrade to RCy, they will get this error and think something is wrong. even with SMF 2.1 gold release we will see this issue and have people wonder why they are getting errors running the upgrade when they did not need to as they have the most recent version.

**Comment by albertlast** [comment]
There many upgrade steps which are not safe,
So you may fix this thing but the others keep.
To place for everything the right check would blow up the code.
And this would result in harder management of the code, only for the time period rc to final...


________________________________
Von: Illori <notifications@github.com>
Gesendet: 29.01.2017 5:57 PM
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] upgrade.php post notification settings error (#3885)


i know that, but once 2.1 gets to RC stage this issue will still exist. if someone upgrades SMF 2.0 to SMF 2.1 RCx and then needs to upgrade to RCy, they will get this error and think something is wrong. even with SMF 2.1 gold release we will see this issue and have people wonder why they are getting errors running the upgrade when they did not need to as they have the most recent version.

-

**Comment by jdarwood007** [comment]
@illori Able to test our the PR I just submitted and see if that resolves this error?  It should handle ignoring this since the column doesn't exist anymore.

**Comment by illori** [comment]
this does fix the issue.

**Comment by sbulen** [comment]
I think this is an important discussion.   I still have some questions:  
    (1)  Did we allow for reruns in 2.0?   In other words, is this an expectation that has been set that allows folks to correct errors?
    (2)  If we do *not* want to allow for reruns, should the upgrader test for this & stop?  Or at least bypass some steps?   If so, which steps?  

I'm afraid that if we don't explicitly decide and code with agreement on this question, we may cause database corruption.  

The more bulletproof we make it here, the fewer thorny support issues down the road.

**Comment by albertlast** [comment]
1) nope
2) i already implement the bypass logic but was rejected : https://github.com/SimpleMachines/SMF2.1/pull/3550, the stop logic could be good enough

**Comment by illori** [comment]
yes we did allow reruns in SMF 2.0. upgrade.php ran without issue if it had been run before.

**Comment by jdarwood007** [comment]
In 2.0 and before we had a closed development model consisting of team and beta members testing the code.  The code was unsupported (by the devs) and the general saying was something along the lines of if you don't think you could resolve any issues and broke your live site because you upgraded to a dev edition, then you shouldn't.  We sometimes had issues that broke upgrading and caused other issues, and team members would either need to deal with it or wait for a fix.  If it corrupted data, well you had to have a backup (you backed up right?).

I see no reason why we can't take simple steps such as the PR I pushed that prevents issues like this on reruns with minimal effort.  We shouldn't support any dev/git edition of SMF.  But we should ensure that from one beta/rc to another the upgrader works fine, while anything in-between is a best effort.

The upgrader itself already handles errors from things such as renaming a column that doesn't exist or similar.  The biggest errors are going to occur from the php we do to convert data when we have changed the structure of things.

**Comment by sbulen** [comment]
I seem to recall issues on the support forum where folks were stuck pretty bad & were told to try the upgrader.  Given the state of knowledge of some of the users, we should make it as bulletproof as possible.  Some are gonna run it twice... just... because...

I like jdarwood's suggestion... _if you're already looking under the hood_, and a simple step can be taken, do so.  

But do NOT attempt a significant rewrite.  It is almost stable now...  

I think stability of the upgrader is critically important.   For most users, running this is their first experience of 2.1.  We don't want it to keep breaking.  Any changes going forward should be tested - a LOT...

**Comment by albertlast** [comment]
@jdarwood007  but you didn't done this for postgresql...

**Comment by jdarwood007** [comment]
Oops I did.  I don't have a postgresql forum to test with, but the code is all safe looking for postgresql.
