### ISSUE TITLE
Behaviour of Report to Moderator

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#3908]
- I'm able to report to moderator a post of my own
- I'm able to report it as much times as I want
- Do we really need a preview option for that?
 - In that case, if we don't insert nothing in the field and click on preview, the preview box will be displayed but with no content. Maybe we should change this to show a warning if the body is left empty as well as when submitting it with the body empty

**Comment by illori** [comment]
i dont see an issue with the preview since you cant see the message once you send it.

but since you cant use bbc in the box, it seems a bit useless to actually be able to preview. maybe enable bbc if not a big deal then add the warning if previewing a blank message?

if you submit it empty you see this message "The comment field was left empty." so we can add that to the preview as well.

**Comment by frandominguezl** [comment]
Why'd we need to put BBC inside a report to moderator? It could cause some spam matters IMO

**Comment by illori** [comment]
if they do include working bbc parser and a user provides a link, when the moderator views the report they can just click on the link to view it instead of copy/paste.

i dont think it would cause more spam then we get already. i dont think many would use it but in the case of links it may be useful.

**Comment by XinYenFon** [comment]
1) Can be used in times when edit times limited.
2) Can be used in times when you need to add extra information.
3) No but its ok feature (but surely url/iurl/img bbcode support could be nice in there).
4) No need to. Its doing its job properly :P

**Comment by frandominguezl** [comment]
1. Personal Messages?
2. Maybe a limit? 2-3 times should be enough

**Comment by XinYenFon** [comment]
You mean, you can report the PMs sent by you to others? If that's the case well yea that needs some trimming 😆 no I don't think a limit is required.

**Comment by frandominguezl** [comment]
No, I mean if you can't edit you post anymore, you could contact someone via PM instead of using Report to Mod

**Comment by XinYenFon** [comment]
Not efficient, people actually using that function to do less (write less names) to reach more.

**Comment by frandominguezl** [comment]
I'll close this for now, it's not much necessary
