### ISSUE TITLE
Revert emulation does nothing?

### ISSUE THREAD

**Issue by kat-kta** [SimpleMachines/SMF#3910]
While toying with stuff, i noticed that once you emulate an older version, an update prompt pops up encouraging you to update your emulated smf2.1 beta3 
"Update Available
You're using an outdated version of SMF, which contains some bugs which have since been fixed. It is recommended that you update your forum to the latest version as soon as possible. It only takes a minute!"
Also once you emulate, you canot revert the emulation, since the "revert" button does nothing once you click on it...

**Comment by Oldiesmann** [comment]
The reason you're getting a notification to update is because 2.1 Beta 3 is newer than the official "latest" version of 2.1 (Beta 2). Beta 3 hasn't officially been released yet (it's still in testing). Once it's officially released we'll update the latest version to reflect that.

**Comment by Oldiesmann** [comment]
The "revert" button does nothing because the version you're using (2.1 Beta 3) isn't in the official versions list yet since Beta 3 hasn't officially been released (it's still in testing at this point). Once Beta 3 is officially released, it will work properly. Until then you can fix it by updating the "version_emulate" setting in the settings table in the database to "2.1 Beta 3":
`UPDATE smf_settings SET value='2.1 Beta 3' WHERE variable='version_emulate';`

**Comment by kat-kta** [comment]
Aaa ok makes sense. Thanks didn't see the version_emulate when i breezed through the settings before.. Keep up the good work~ (y)
