### ISSUE TITLE
Bad SEO, bots doing scheduled task.

### ISSUE THREAD

**Issue by sicommnend** [SimpleMachines/SMF#3916]
I seen this in the 2.0 branch and same applies to 2.1.

In Load.php
`		if (isBrowser('possibly_robot'))
		{
			// @todo Maybe move this somewhere better?!
			require_once($sourcedir . '/ScheduledTasks.php');
			// What to do, what to do?!
			if (empty($modSettings['next_task_time']) || $modSettings['next_task_time'] < time())
				AutoTask();
			else
				ReduceMailQueue();
		}`

If the user is a bot then the scheduled task is being called if there is one set. Problem I see with this is that some robots, such as GoogleBot see page speed as a indicator of site rankings. Under the right circumstances this offloading to the bots might hurt a forums web presence.

I suggest in this instance we don't treat the bots any differently.

**Comment by frandominguezl** [comment]
Any thoughts @colinschoen ?

**Comment by sicommnend** [comment]
What I have done in my case is run task on errors and content with no index meta. Only if a task is late then it is ran with indexable content.

**Comment by colinschoen** [comment]
Looking into this...

**Comment by MissAllSunday** [comment]
Since re-captcha is now been used might be good to collect some data from it, "bad bots" or something like that, if  a bot is in the list, hammer it with scheduled tasks.

Oh, NVM its impractical to do so like that as either good or bad bots will fail the test anyway. Still,  some sort of list will be good to have, are you a naughty bot? cool, heres some heavy stuff for you.

That or start to motivate users to use real cronjobs. Even the most basic shared hosting supports them so it might be good to offer a setting to disable "web crons" and create some wiki pages on how to build crons for SMF
