### ISSUE TITLE
Upon new install - all old packages are selectable for installation

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3973]
Upon a new install (overwrite the files method), all of the old packages are still in the packages directory & available for installation.   

Should we clear out the entire packages directory (and corresponding entries in log_packages)?  

If not, should we AT LEAST clear out the old SMF update packages?

![image](https://cloud.githubusercontent.com/assets/23568484/24069570/35e268fa-0b68-11e7-9a64-f9996c6e53e7.png)

**Comment by XinYenFon** [comment]
I think its best to clean up the patches only.

**Comment by illori** [comment]
i dont see any issue leaving them, i dont think we have a good way to just detect the patches and just remove those.

some mod authors may have updated their mods to include support for SMF 2.1 by the time users upgrade and the mods may be able to be installed because of that so they should not be deleted.

the log_packages table should be cleared already in the upgrade process to set all the mods as uninstalled.

**Comment by XinYenFon** [comment]
@illori our patches starts with "smf_patch_*" with a proper regex we can clean up those files.

**Comment by sbulen** [comment]
Since we know 2.0 patches don't work on 2.1, and since it is fairly easy to download new patches, I suggest clearing out the packages table & directory.  

I believe this will prevent support heartaches down the road.  

Yes, the smart ones who know exactly what they're doing will be annoyed at having to spend an extra 2 minutes download & installing, rather than just pressing the install button.  

Even most 2.1-compatible patches will need to be reinstalled, correct?

But YOU KNOW there will be many support cases as folks read the screen above and say "Excellent!  It emulates 2.0" and press all of the install buttons...  _It's what it says it does..._

**Comment by sbulen** [comment]
Versions aren't checked on anything.  Even the SMF packages install out of sequence - below, I installed the 2.0.2 patch in 2.1.   

Yes, you have to click thru the normal warning.  

![image](https://cloud.githubusercontent.com/assets/23568484/24074263/7bf6a810-0bc2-11e7-9a56-47b9494879c8.png)

**Comment by illori** [comment]
yes the versions are checked, but we auto emulate instead of letting you do it manually. so it is easier to try to install mods that were not made for the version you are installing for.

we get a ton of requests on does x mod work with my version, because it does not emulate for them. so this makes it easier and hopefully fewer of those requests.

**Comment by illori** [comment]
really we should be working toward making the code stable rather then adding features like this.

**Comment by sbulen** [comment]
I agree stability is critical.  I am also concerned how many folks will press those buttons.  It sure looks like it's OK to do so in the screenshot above.  

Clearing out packages is a very simple change.  And I do think it will result in many fewer issues upon release.  

(Last try, honest!)

**Comment by illori** [comment]
we never have in the past. people will post asking how to do the upgrade, we tell them to look for mods compatible with their version and they do so. this issue is smaller then you are making it out to be.

**Comment by sbulen** [comment]
OK, I'll close.  No changes.  

If there is notable user confusion down the road, we may wish to reconsider more bulletproofing measures such as this.  I  think that 2.0 => 2.1 is more serious than any of the 2.0.x => 2.0.x upgrades.
