### ISSUE TITLE
Discussion Topic - Beta-to-beta upgrades

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3975]
Not to rub salt in old wounds, but this feels like it is unresolved...  Let me start off by sharing something...  

I believe that **_for the last three years, the upgrader has not run to completion._**  I believe PR #3842  addressed this.  I suspect many of you don't agree, because you've been running it frequently.  But if you look at the code, many updates have been bypassed because that section of code is designed to only execute once.  

_But what about updates to the logic within those sections of code..._

The people who could not run the upgrader to completion for the last three years were those who were working from a freshly restored database.  I.e., exactly like all of the (non-beta) users will do it at production cutover time.  

I'm sure we could find other examples of missed updates.  

If you've been using the beta-to-beta method of upgrading your system, without restoring your 2.0 DB from production first, you have missed out on some set of updates, which means you are not, in fact, running a current version of the beta.

For several years, I was the internal IT release manager for a multi-billion dollar tech company.  I had to oversee scores of post implementation audits of projects big & small.  One major lesson from that activity:
  ** Any test in a test environment that wasn't built replicating the production implementation steps is null and void.  
  
In this context, this includes the beta-to-beta upgrades.  The *ONLY* way to see what the current beta is really like, is to perform a fresh restore of your 2.0 DB from prod & run the upgrader to go to 2.1.  Exactly what will happen for the (non-beta) users at cutover time.

Developers can continue to do the "beta-to-beta" installs, we all agree that the upgrader should run to completion on reruns, but they should be fully aware that at some point, they must save off their commits and do a proper upgrade.  

Feedback welcome.

**Comment by albertlast** [comment]
To be ownest I don't get the point :)

**Comment by jdarwood007** [comment]
To clarify some stuff from back in the day prior to being on git(hub).

- We supported beta to beta upgrades (i.e. 2.0 Beta 1 to 2.0 Beta 2)
- We supported any released version to the latest release (i.e. YabSE to SMF 2.0 RC1)
- We did not support nightlies (i.e. 2.0.13 dev-2017-03-19)
- We did not support svn (i.e. 2.0.13 rev-23492) or cvs.

This made perfect sense.  Those using SVN or nightlies where developers, team members and those with enough knowledge to resolve issues or be able to work with those who can (mostly this feel in the case of team members who where not coders).  We did support team members who beta tested patches (i.e. 2.0.12 to 2.0.13 test patches).

From a software standpoint.  We have people who may upgrade from all sorts of different versions of SMF and we must try to support them with our current upgrade architecture.  I think for 3.0, we could do a cut off and only support upgrades from 2.1, and provide a converter for 2.0, 1.x, and YabSE.

It is expected that we should be testing from random various editions of SMF to the latest one.  From a developers point of view, everything should be the same once they get to X version and there shouldn't be any database mismatches.

We also have to deal with when the upgrader is paused or upgrade status loss.  Because we do local development we don't run into this often.  But what happens if in the middle of the upgrade, the admin who was running it goes offline and for some reason the upgradeData is lost in the Settings.php?  We don't know where to continue off from and have to restart it.

This restart is why we need to be sure things are only done once by testing for them in the appropriate way.  Future versions of the upgrade script could include a test section that if returns true, would perform the upgrade step.

**Comment by albertlast** [comment]
When the key issue "let things run once" why was pr like my rejected?
https://github.com/SimpleMachines/SMF2.1/pull/3550
the main chat is in the board and not in pr messages.

Like i said on topics i would expect that suche system is provided by smf default,
and because this is not i don't understand that the requirement is there without a common solution.

**Comment by jdarwood007** [comment]
Most likely because it would be a feature to add to the upgrader to properly detect what changes have actually been ran and properly testing this.

The best test without breaking things would be to just test things as needed.  For future releases we can add this support and test it, but ignore it the upgrader for 1.x and 2.x.

**Comment by sbulen** [comment]
My point is that the beta-to-beta upgrades don't work.   You may THINK they're working, but they're not.   

If they worked, everyone would have known that 3 years ago a fatal change went in.

**Comment by jdarwood007** [comment]
What fatal change?

**Comment by sbulen** [comment]
I'd rather not point to the specific commit from Feb 2014.  The fix is outlined above:

- Fix upgrade migration of fields from members to themes #3842

The problem is that id_theme has always been unsigned, and trying to stuff a -1 in there using a php upgrader step caused the session to be dropped due to an "Aborted connection 52 to db: 'unconnected' user: host: (Got an error reading communication packets)".   This apparently happens with php that evals php that invokes sql that generates errors of sufficient severity.  

The aborted connection left the upgrader hanging.  

This spawned a # of issues, including:

-    Database upgrade hanging 2.0.11 - > 2.1b3 #3387
-    Upgrade Issue - Can't get past Step 4 #3833

I suspect you will be able to duplicate it if you put the -1s back into upgrade_2.1_mysql.sql (reverse #3842 ), and run the upgrader against a fresh 2.0 restore.  (Note: you must have some of the relevant data - msn, yahoo, location, gender etc. in your source db.)

**Comment by jdarwood007** [comment]
Did it actually convert the data?  SQL should have truncated it to 0 if it got -1 then.

As well if the columns still exist it will try to convert them correctly looking at the code.

**Comment by sbulen** [comment]
Try it!   

I don't think it tried to convert for most people over the last 3 years - once the members columns were removed.  Note there have been a few other tweaks to that logic most people would have missed.  Which was my main point above.  

In my case, no - migrated member location data was not visible until the fix.  Then again, this was when I first tried migrating my forum, and it would not complete...

**Comment by sbulen** [comment]
Related discussion in this PR: Clean up old theme data #3964

**Comment by sbulen** [comment]
Related issue in the support thread: http://www.simplemachines.org/community/index.php?topic=553061.0

(I don't _mean_ to beat a dead horse, but...)

**Comment by jdarwood007** [comment]
That is something we can solve in the code if needed during the loadDatabase stuff.

**Comment by albertlast** [comment]
this is my eye the wrong way,
this is a very special case which is very rar to place here any code make for 99,9% no sense.

**Comment by sbulen** [comment]
I'm going to close this out.  This discussion is out there & folks are aware of the pitfalls.
