### ISSUE TITLE
Installer - "Fatal error: Function name must be a string in install.php on line 971"

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3986]
Installer cannot execute.   

I was attempting to reproduce the issue reported in the support forum - "Error when uploading large files to forum":
http://www.simplemachines.org/community/index.php?topic=552909.msg3919460#msg3919460

**Comment by sbulen** [comment]
This is new code added in this PR: PostgreSQL Check for utf8 database charcode #3977

**Comment by albertlast** [comment]
I don't understand the issue here.
I did the samething like validate_prefix is done and
this is working?!

btw i'm not able to reproduce this.
Which php version you use?

**Comment by Mavn** [comment]
I have the same issue. php7.0-fprm + nginx ubuntu 16.0.4

**Comment by sbulen** [comment]
MySQL 5.7
php 5.6

**Comment by sbulen** [comment]
Line 971 is trying to run a function due to the ():
    if (!$databases[$db_type]['utf8_support']**_()_**)

But that is just a simple boolean flag indicating utf8 support, not a function.

**Comment by albertlast** [comment]
Dammit i changed the wrong Parameter for mysql, well maybe Today or tomorrow.


________________________________
Von: sbulen <notifications@github.com>
Gesendet: 24.03.2017 3:55 nachm.
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] Installer - "Fatal error: Function name must be a string in install.php on line 971" (#3986)


Line 971 is trying to run a function due to the ():
if (!$databases[$db_type]['utf8_support']())

But that is just a simple boolean flag indicating utf8 support, not a function.

**Comment by sbulen** [comment]
I have confirmed it runs to completion if you remove those two characters.

I'm fairly sure this logic is shared with mysql & pg.

**Comment by sbulen** [comment]
The upgrader is not affected, only the installer.  

If you like I can do a PR to get the installer working again.  

Then you can look at the rest of the code closer later.

**Comment by albertlast** [comment]
The removing is the () wrong solution.
That this is a flag and not a function is issue.

________________________________
Von: sbulen <notifications@github.com>
Gesendet: 24.03.2017 4:28 nachm.
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] Installer - "Fatal error: Function name must be a string in install.php on line 971" (#3986)


I have confirmed it runs to completion if you remove those two characters.

**Comment by albertlast** [comment]
Feel free to test the solution from the pr.
