### ISSUE TITLE
Question, Mysql upgrade create myISAM tables

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#3994]
I notice in the pr  #3993 that we create myISAM tables when we upgrade,
and create innodb tables on installation.

Is this behavior good?
I would expect that all new tables are innodb.

**Comment by sbulen** [comment]
@albertlast -

I've raised two variations of this question in the past:
  -  Upgrader - Tables remain MyISAM after upgrade #3867
  -  Upgrader: New tables hard-coded to MyISAM #3899

It was decided at that time to leave the conversion to InnoDB to the admin.   (In part due to your input.  I think I'm wearing you down!  ;^) )

Shawn
