### ISSUE TITLE
language  Not added  there is problem

### ISSUE THREAD

**Issue by replikacep** [SimpleMachines/SMF#4009]
language Unfortunately Admin panel No language  Can not be added ?

Smf installation  Russian  I guess

turkish-utf8 , English-utf8  Not added  Status in

**Comment by frandominguezl** [comment]
Sorry, I can't understand what your problem is. Are you having troubles trying to add a language? Or after adding it you can't enable it?

**Comment by replikacep** [comment]
No language added   It does not appear on the panel

**Comment by XinYenFon** [comment]
This issue is not related to software, as i told you before. Wait for beta3 release, and the pack I also sent you works properly it just has extra -utf8. As the part of new setup, SMF 2.1 only works with UTF8 and we removed requirement of alternative char-sets. So SMF no longer requires index.<language> & index.<language>-utf8 separation.

Take the pack I sent you and remove -utf8 from their ends (or only from index.turkish-utf8) you 'll see its working, this issue requires fix from our server-side.
