### ISSUE TITLE
Package manager: <require-dir> directive fails for packages in archives

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#4031]
If package-info.xml contains the following directions, the package manager fails if the mod is packed in a archive, but not if it is unpacked into a directory structure.

Sample package-info.xml directive:
```
	<install for="2.1 - 2.1.99, 2.1 Beta 3">
		<readme type="file" parsebbc="true">readme.txt</readme>
		<require-file name="SchmoopyNewMod.english.php" destination="$themedir/languages" />
		<require-dir name="SchmoopyNewMod" destination="$sourcedir" />
		<code>install_db.php</code>
		<code>add_remove_hooks.php</code>
	</install>
```

If SchmoopyNewMod is contained in SchmoopyNewMod.tar.gz, the package manager fails and reports the following:

_ | Type | Action | Description
--|------|--------|------------
1.|Extract File|./Themes/default/languages/SchmoopyNewMod.english.php|
2.|Extract Tree|./Sources/SchmoopyNewMod|**File not found**
3.|Execute Code|install_db.php|
4.|Execute Code|add_remove_hooks.php|

But if I unpack SchmoopyNewMod.tar.gz and try again, the package manager is perfectly happy:

_ | Type | Action | Description
--|------|--------|------------
1.|Extract File|./Themes/default/languages/SchmoopyNewMod.english.php|
2.|Extract Tree|./Sources/SchmoopyNewMod|
3.|Execute Code|install_db.php|
4.|Execute Code|add_remove_hooks.php|

It seems like something in the logic for extracting a tree from an archive file is broken, causing the package manager to fail because the directory doesn't already exist somewhere that it thinks it should exist.

Note that I haven't tested with .zip files, only .tar.gz files. For some reason, whenever I try to create a .zip file, SMF chokes on it, so I can't test that archive format.

**Comment by sbulen** [comment]
A couple of questions:  Do you have an example mod that fails?  What does your $packagesdir look like?

I've been able to install tar.gzs and .zips.   But they may not have had that particular directive in them.  

FYI, there have been sporaidic issues in this issues list about directory issues impacting installs over the last couple of years.  (E.g.,: Package upload failed. Works in SMF 2.0.x fails in SMF 2.1 #3337)  I think vbgamer believes that issue was specific to php 5.4.

I have noticed that the method you use to perform a 2.1 install leaves your $packagesdir in different states.  One example, if you copy the install* files without copying the provided settings.php template while performing an install, $packagesdir isn't set at all.   When this happens, you tend to have temp dir issues.  

Also, even if you do install with settings.php properly, $packagesdir is not fully qualified after install.  (Installer - Paths & setting not set #3999)  I think you can get odd behavior until you run repair_settings.php.

**Comment by Sesquipedalian** [comment]
I just tried using repair_settings.php to make sure $packagesdir was properly set, but it didn't help.

Here's a dummy mod that you can use for testing purposes:
[SchmoopyNewMod.tar.gz](https://github.com/SimpleMachines/SMF2.1/files/967423/SchmoopyNewMod.tar.gz)

**Comment by sbulen** [comment]
I believe the require-dir is intended to copy that dir, including all of its contents, from your tar.gz to the filesystem.  It is just like require-file, but for directories.  The reason it is failing in your sample tar.gz is that there is no directory in it with that name.  

I think it is giving you a proper indication of failure.  

If, within the tar.gz, you have a folder called SchmoopyNewMod with contents in it, I have confirmed it works ok.

I think this behavior is consistent with the documentation:
https://wiki.simplemachines.org/smf/Package-info.xml

**Comment by Sesquipedalian** [comment]
Oh, geez. You are right. It was just a problem with the script I have been using to automate the process of creating the archive. 😅
