### ISSUE TITLE
Could not retrieve the file

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4063]
I'm getting this message after an upgrade recently.  It is showing up in the error log:

Could not retrieve the file https://www.simplemachines.org/smf/current-version.js?version=SMF+2.1+Beta+3.

**Comment by illori** [comment]
i ran the scheduled task to fetch the files, and cant duplicate this issue.

**Comment by jdarwood007** [comment]
What version of php and openssl do you have?  does phpinofo show support for https wrappers?

**Comment by sbulen** [comment]
I'm on php 5.6.

My test site is not using https yet.

**Comment by jdarwood007** [comment]
But does PHP show support for it?
In PHP info you should see https in "Registered PHP Streams" and in the curl section "Protocols"

**Comment by sbulen** [comment]
No, it is not in the registered PHP stream list in my test environment.  

This is not surprising, as to-date, I haven't even tried to run TLS/SSL on my test server.  

This is the first time I've seen this error message, however.

**Comment by jdarwood007** [comment]
Since your PHP doesn't have any https support, it can't connect up to sm.org over https.  https://github.com/SimpleMachines/SMF2.1/pull/4016

I was told the http fallback wasn't important at the time.

**Comment by sbulen** [comment]
I bet most hosts support https, so I think that's a fair assessment.  This issue will probably be extremely rare in production.  

This issue is probably restricted to some test environments, like mine, built by noobs such as myself for testing purposes.  

I disabled the scheduled task.  

Should I close this?

**Comment by sbulen** [comment]
I'll answer my own question...

**Comment by illori** [comment]
If it can be duplicated somewhere else then no, as we would need to fix it.
I was testing on my wamp server.

**Comment by sbulen** [comment]
I am getting this error on my wamp server.  

I think the difference is that I have never attempted to enable ssl on my test server.   I bet this is pretty rare - certainly on live sites.

**Comment by illori** [comment]
I don't know if I have ssl enabled or not, it is using localhost.

**Comment by sbulen** [comment]
You can confirm by looking at phpinfo() as jdarwood explained above.  

Run phpinfo() & check if you can see https in "Registered PHP Streams" 

If so, you have it enabled.  That would explain why you are OK & I get the error.  (I'm using localhost as well.)

The next question would be how common my situation is & whether we need to code for it.  My sense is that it would be somewhat common in _local wamp test servers - **ONLY_**.  But I doubt any ISPs would not have SSL enabled.

**Comment by illori** [comment]
php, file, glob, data, http, ftp, zip, compress.zlib, compress.bzip2, https, ftps, phar are listed as the registered php streams, so i guess my wamp server has this covered.

it would not surprise me if some hosts that have not updated their php version beyond php 5.3 may have this issue, but that is another ball of wax.

**Comment by jdarwood007** [comment]
You guys may not like the suggestion.  But what if we implant a $modSettings['fetchData_allowHTTPFallback'] or similar and specifically allow a http fallback only if enabled?
We could then enable that if upon the action where we are loading those file data (in the ACP) that if php doesn't contain https in the list of registered streams (stream_get_wrappers), we enable it.

I wouldn't suggest we use the stream_wrapper_register and building our own https because building our own ssl handshake doesn't sound like fun to me.

**Comment by sbulen** [comment]
I will reopen this issue as the discussion is still ongoing.  

It still feels to me like no further action is required...   I'd rather not increase complexity solely to support a subset of test environments that don't have https even enabled in the environment.  In my view, we're in KISS territory...

But I'll leave this out there for the team to discuss.

**Comment by jdarwood007** [comment]
I would only be interesting in targeting this if we can find a host who doesn't support this.  With the size of testing for 2.1, I don't think we will.  I would hate for this to make it into production because once broken, there is no way for users to know to upgrade their installs as they can't fetch the files.

In my random guess, I suspect we will see this issue on less than 0.001% of installs and that would decrease as hosts continue to use more modern setups.

**Comment by sbulen** [comment]
So close this?
