### ISSUE TITLE
where is $mysql_set_mode setted?

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4067]
i was playing with the idea,
to force the strict mode of mysql.

Than i noticed that we already to some sql mode stuff https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Db-mysql.php#L94
and this is done when $mysql_set_mode is true,
but i found no place where this var is setted.

So the question in the round where is this var setted?

**Comment by jdarwood007** [comment]
It appeared sometime during 1.1 dev cycle between 1.1 Beta 1 and 1.1 Beta 2.  Because it is a global, my guess is it would be set in Settings.php.

**Comment by sbulen** [comment]
If you search for "sql_mode" in the 2.0 codebase, you find a lot of references, including in the changelog.txt.

It's even referenced in comments in the pg files, and also in load.php.  (as mysql_set_mode, not $mysql_set_mode)

It does not appear to be in current usage in 2.0 or 2.1, as far as I can find.  I bet it can be safely removed.  

My 2.0 forum has been patched since 1.1, and there is no reference to it in my settings.php or in my settings table.  So it may not have made it as far as the 1.1 release.

**Comment by jdarwood007** [comment]
@sbulen,
Looking at our old SVN repository, I can see the addition of the code.  But the log message is nothing more than what it stated in the changelog with the addition of the code to the Load.php.  No Settings.php changes.

I think this was a hidden setting that was intended for more testing for MySQL 4.1+ features at the time.  I don't think its relevant today.

**Comment by sbulen** [comment]
Yep.

If albertlast wants to use it, how should it be set?  

I would first experiment with it...   I suspect it would be disruptive, based on the different behavior folks see.  (Remember the issue I raised about the upgrader not running to completion for 3 years?  I bet it ran ok for many folks, depending on the environment...  How many other issues will pop up?)

**Comment by albertlast** [comment]
Maybe it's should used any more.

Like i said the basic idea is to use sql strict mode,
reason for this is mysql 5.7 + is that the default value and
it's less likely that the query doesn't run on pg.

Draw back is that some mod query doesn't work any more.

When this should realy shine than is there no reason make this on or off on the fly.
