### ISSUE TITLE
Newsteller variable issue

### ISSUE THREAD

**Issue by kat-kta** [SimpleMachines/SMF#4116]
Heyo, 

when sending an email with the newsteller, the variable {$member.link} outputs {$member.name} instead of the link. Just sent a bunch of emberrasing emails haha

Cheers, kat

**Comment by Oldiesmann** [comment]
Looking into this, though I can't even get the newsletter to send using the latest code from GitHub. I click "Send" and get redirected to the page where I choose the groups to send it to with a message saying it was successfully added to the mail queue, but I don't actually receive the email at all.

**Comment by Oldiesmann** [comment]
Did some digging in the code and it looks like it only includes a link if you're sending in HTML format (in that case it will include a link to the member's profile with their name as the link text). I agree that it would make far more sense to include just the link instead of the name when you aren't sending it in HTML format. I'll commit a fix for that shortly, though I still need to figure out why newsletters aren't being sent for me.

**Comment by kat-kta** [comment]
Using SMTP with gmail I can send emails just fine with the latest code from GitHub.
