### ISSUE TITLE
Discussion: php minimum?

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4118]
Following up on this thread on the support forum, where a user on 5.4.37 can no longer install the beta:
https://www.simplemachines.org/community/index.php?topic=554352.msg3930876#msg3930876

2 questions:
 - is 5.4.45 too high?
 - the comparison, IIRC, uses a '>', and 5.4.45 is the last 5.4 release.  If it must be > 5.4.45, have we just made the current min version 5.5?

**Comment by sbulen** [comment]
Note also that the upgrader uses '>=' for the comparison, so there is a discrepancy there.

**Comment by Sesquipedalian** [comment]
Hmm. Yes, that is a discrepancy. I'm inclined to think `>=` makes more sense, so that we are saying the value of `$GLOBALS['required_php_version']` is the minimum supported version, rather than the last unsupported version.

As for choosing 5.4.45 as the minimum version, I just suggested that because it is the last released version of 5.4. My thinking was that (1) then we are at least able to rely on whatever bug fixes, etc., went into 5.4 before it was EOL'ed, and (2) usually even crappy hosts will at least update of PHP to the last of the current version, even if they don't upgrade to new versions. But if others think we should do something different (e.g. 5.4.0 or something), I wouldn't make a fuss.

**Comment by XinYenFon** [comment]
Unless there is something horribly bad in that series, minimum requirement should start from x.x.0 (in this case php5.4.0), tracking security patches are not duty of SMF.
