### ISSUE TITLE
reCaptcha guest searches

### ISSUE THREAD

**Issue by kat-kta** [SimpleMachines/SMF#4123]
Heyo,

when "require verification on all guest searches" is enabled and a guest fills in the desired search, solves the captcha and proceeds to click Search, the following error occurs:
"Please enter the verification code below to continue to the results."

Kinda weird, right? Works normal on smf captcha tho.
Regards, kat

**Comment by kat-kta** [comment]
Another reCaptcha issue i just noticed: When a member needs to solve a reCaptcha and does so successfully, if they click "preview" they get the error message **"The letters you typed don't match the letters that were shown in the picture."**, however, if they then proceed to click Post, the message is posted regardless (as it should be since they solved the necesary captcha).

It'd be best to remove the error message as to not cause confusion.

Regards, kat

**Comment by XinYenFon** [comment]
This is very very broken.

At this stage, this issue is a blocker due to blocking ability of guest posting while captcha active.

Edit:

2: file_get_contents(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
2: file_get_contents(https://www.google.com/recaptcha/api/siteverify): failed to open stream: Invalid argument

I'm having those errors I guess they are related to my local setup but can't be sure.

**Comment by frandominguezl** [comment]
How are you getting those errors, @Antes ?

**Comment by Sesquipedalian** [comment]
@live627

**Comment by Oldiesmann** [comment]
@Antes that is a problem with your setup. You need to make sure your PHP setup is compiled with OpenSSL support (--with-openssl or uncomment the appropriate line in php.ini).

**Comment by live627** [comment]
This might have been fixed or at least partially working as of 66b62cdb7e5fae5ee1bf7a8f5b1ae0cff25e2ced - please test.
