### ISSUE TITLE
2.1 upgrade issue Incorrect date value: '0000-00-00' for column 'birthdate'

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#4136]
Occurs on MySQL 5.7
 it seems like MySQL 5.7 doesn't like 0000-00-00 as a date. You'd have to use either an arbitrary date like 1970-01-01 or null.

Report link
https://www.simplemachines.org/community/index.php?topic=554635.0

**Comment by albertlast** [comment]
This error should be not mysql 5.7 related because we force on every mysql,
that NO_ZERO_DATE is enabled https://dev.mysql.com/doc/refman/5.5/en/sql-mode.html#sqlmode_no_zero_date
https://github.com/SimpleMachines/SMF2.1/pull/4068
merged after beta 3 release.

Birthdate is a not null field (stupid smf logic) but the default value 0001-01-01 is a valid value.

**Comment by FDinolfo** [comment]
I can only go by what I'm seeing here. Let me know of any other additional info or log entries you want and I'll bring them over here.

**Comment by albertlast** [comment]
Oldiesmann will look into (he will create the pr),
i already did some changes
maybe he find more stuff and do finish the upgrade part: https://github.com/albertlast/SMF2.1/commit/dc2ce578de957da45d3a06b29bc8a96f56b2a735
