### ISSUE TITLE
Upgrade from Beta 2 MySQLi issue

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#4170]
Upgraded from beta 2 which was using mysql**i** . Upgrade went fine but the $db_type in Settings.php didn't change to mysql. So it was still using the outdated Subs-Db-Mysqli.php, hence tons of errors. everything went fine after I manually changed it from mysqli to mysql.

**Comment by sbulen** [comment]
'mysql' and 'mysqli' all map to 'mysqli' internal calls now, there is no need to differentiate.  

I think your fix was the proper fix.

**Comment by sbulen** [comment]
There is logic in the upgrader that attempts to deal with Beta2 mysqli users, but it doesn't change the settings.php as it goes.  Since we've seen a couple of these, I'll submit a PR to address.

At some point, I think beta testers should do a full 2.0 => 2.1 upgrade, to catch all the other data fixes, etc., that they otherwise miss doing beta-to-beta upgrades.

**Comment by sbulen** [comment]
PR #4172 tested & submitted.
