### ISSUE TITLE
Unknown function: MemberReport

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#4214]
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/ModerationCenter.php#L695

That's not a defined function anywhere. Where should it lead to?

**Comment by Oldiesmann** [comment]
ReportDetails in Sources/ReportedContent.php handles displaying all the info for a report, but it requires $_REQUEST['rid'] to be set. Is $_REQUEST['report'] the report ID?

**Comment by NanoSector** [comment]
I'd guess so, not sure though as we can't check what the function itself would do. Guessing by its name it probably showed details on a specific member report, so it seems likely that $_REQUEST['report'] is the report ID.

**Comment by Oldiesmann** [comment]
I'm wondering if that's just old code that never got removed, as I can't find anything in the moderation center that would have $_REQUEST['report'] somewhere. If you report a topic, it lists it and links to the details for that topic (correct URL). If you report a profile, it lists the user and just links to their profile (we should probably change that to link to the report rather than the profile though).

**Comment by NanoSector** [comment]
Fixed with #4254?

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Archer70** [comment]
@Yoshi2889 The code in question looked dead and unused, so I removed it. Therefore, yes, I'd say it's fixed. :)
