### ISSUE TITLE
"Enable basic HTML" tags not working

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#4224]
Some tags for the "enable basic HTML" feature are not working properly.

Here's a screenshot with the output for the following posts:
```
<b>Bold</b>
<em>Em</em>
<i>i</i>
<u>U</u>
<s>S</s>
<ins>ins</ins>
<del>del</del>
<a href="somelink">Somelink</a>
<img src="/upgrade-ver/Themes/default/images/smflogo.png" alt="Someimage" />
<pre>Pre</pre>
<blockquote>blockquote</blockquote>
<br />
<hr />
```

Second post (`strong` is not on the list, but it should be since `em` is). Both `<br/>` and `<br>` should work. both hrs are working fine.
```
<strong>Strong</strong>
<br>
<hr>
```
![tags](https://user-images.githubusercontent.com/28991853/28870661-83454abc-7757-11e7-991b-167e52a43885.png)

Edit: Adding http:// or https:// to the anchor or image tags works, but shouldn't it still be parsed as HTML on both cases?

**Comment by illori** [comment]
the html has to be valid html 5 or we need to put in more effort to convert it to be valid html 5.

**Comment by Gwenwyfar** [comment]
The html for the image tag is completely valid, and the link could also be valid without http://. Both of them accept relative paths.

**Comment by Gwenwyfar** [comment]
Did a few more tests, and `mailto:` works, but `tel:` doesn't. `#id` also doesn't (but this latter is probably not going to get much use).

**Comment by sbulen** [comment]
I'll start chasing a few of these down.

**Comment by sbulen** [comment]
PR #4230 submitted, fixes hr, br & strong.

I've started looking into relative paths.  Current a & img code works fine on fully qualified URLs at the moment.  

I think tel: would be very valuable in a mobile context.  I'll look into that, too.  

Not sure #id is worth it, though...

**Comment by Gwenwyfar** [comment]
I think for #id as long as it works at the end of a full URL it should be good enough (gave it a try with a full URL with a message ID but it returned another broken tag :P)

**Comment by sbulen** [comment]
In plain link in SMF it work, right?   E.g., the following works in a post:
http://www.vguitarforums.com/smf/index.php?topic=20867.msg154930#msg154930

And in a post in SMF, this works:
`<a href="http://www.vguitarforums.com/smf/index.php?topic=20867.msg154930#msg154930">Link test 2</a>`

**Comment by Gwenwyfar** [comment]
Oh, you're right. I didn't include text inside, so I guess it looks for that too.

**Comment by sbulen** [comment]
It currently supports:
```
<a href="http(s)://somelink">Sometext</a>
<a href="ftp(s)://somelink">Sometext</a>
<a href="mailto:somelink">Sometext</a>
```

to which it is very easy to add:
```
<a href="tel:somelink">Sometext</a>
```

**Comment by sbulen** [comment]
Hmmm...   Interesting for email it applies both an email bbc and html into one mangled string...  Will look further...

**Comment by sbulen** [comment]
OK, 3 more fixes:
(1) Fixed preg_match so you won't get lopsided [url]s (like in the very first "somelink" example above).   Instead of 2 different matches, it's now 1.
(2) fixed html mailto: - there was a conflict between 'auto url' logic and the html logic.  
(3) added tel:.   Works great in mobile.  Points to skype on desktops, if skype is there...   

I don't want to do the relative paths.  First, because I suspect it is a security issue - you may be able to execute stuff you shouldn't.   Second, because there is SO MUCH logic in there to prevent it...  It's a pretty big change.  Note that you CAN do relative paths using the url bbc, but SMF translates them to fully qualified paths for you....  

I'll leave it to Gwenwyfar to decide if this should be closed or not...

**Comment by Gwenwyfar** [comment]
Awesome :)

I think we can leave relative paths alone if they're too problematic to make work safely. It'd be nice to have, but they're not essential.

I'll mark this closed then.
