### ISSUE TITLE
[security] username doesn't exists

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4229]
many sites doesn't tell your what you did wrong,
when you did a mistake in your login form.

smf is here different
![grafik](https://user-images.githubusercontent.com/1782906/29012295-caf1514e-7b3a-11e7-8485-e1816a5c4af1.png)

is this the right behavior?

when this should be changed we to do two "task",
get the same text for both setting (wrong password and wrong username) and
secondly slow down/randomize the login process otherwise you see on the response time of the server,
if the username was not correct or the password.

**Comment by colinschoen** [comment]
The constant battle between usability and security. Yes, it is nice to tell the user that perhaps they forgot a character in their username instead of having them try a different password multiple times. We do already have brute force protection and it is fairly easy (for most forums) to figure out certain usernames that exist. 

I'm in favor of leaving as is, but open to hearing other opinions too.

**Comment by sbulen** [comment]
The bulk of the time, even guests can see user id's.  These are online forums, not corporate systems.  I dont think we gain anything by making it less friendly...   

As-is is ok

**Comment by XinYenFon** [comment]
Very best approach to this situation is giving error output "Username or password is incorrect"

**Comment by albertlast** [comment]
we could decide to take the middle way and provide both options.

**Comment by colinschoen** [comment]
>Very best approach to this situation is giving error output "Username or password is incorrect"

That still is less usable than specifying which is incorrect. The decision really is, do we view this as a valid security concern.

**Comment by XinYenFon** [comment]
@colinschoen Its really a generic output which solves the problem (is it a good solution? debatable). As for second part, I don't think so.

**Comment by Gwenwyfar** [comment]
For what it's worth: I'd rather see it being left as is, for the following reasons: 1) Most users already use the same username as their display name, so it would make no difference for them. 2) Those that do change it, often forget their username so the message is helpful for them (and also for group 1). 3) For the remaining few that could benefit, a hacker would still need to guess their username AND password, the error would not make this process that much easier, would it? I think for the majority of users, changing the message would be for the worse, not better, and over a minor improvement for a few.

**Comment by BitFros7y** [comment]
Most security experts recommend not telling user what he entered wrong, password or username. But then again, when user register's he usually use username as display name so that kind of defeats the purpose of tricky message. 

I would leave it as it is, or chose best of both worlds...add switch in admin panel and leave that decision to forum administrators (should be easy).

By the way, from my perspective days of brute force attack's are over since every decent software has quota for failed logins (including SMF)... Linux even has universal took for that (yeah im looking at you fail2ban...).

**Comment by albertlast** [comment]
So should i closed this issue or create a pr where the admin can decide which behavior he likes?

**Comment by BitFros7y** [comment]
I wouldn't bother with PR for these, by the way Google and Microsoft also tell you your mistake (non existing email, wrong password, etc...)
