### ISSUE TITLE
edit ban page missing token

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4240]
create a new ban save it, move on to another page, go back to the ban page using the back button in your browser change the ban and you can save it without issue. there should be a token on this page so you cannot save it without going back to the page directly like the other pages in the admin panel.

**Comment by XinYenFon** [comment]
Page seems to have proper tokens. Also I can visit an admin page (Anti-Spam) then another one use back button and save without having token-issue.

**Comment by illori** [comment]
then something is not working correctly as you should not be able to save the page after using the back button.

**Comment by Archer70** [comment]
@illori, all the admin pages I'm looking at allow you to go back in your browser and amend previous forms. Could you provide an example of a form that doesn't allow resubmission?

As Antes said, the page does have proper tokens in hidden form fields. When you hit the back button, the token fields are populated with fresh tokens, not reusing old ones. I know enough about CSRF tokens to suspect that this isn't really an issue, but not enough to be positive of that.

@Arantor, mind if I ask for your input on this issue?

**Comment by illori** [comment]
edit a board go on to another page and go back, if you submit the page you will get a session error. this is the expected behavior in SMF 2.1.

if you do the same with the anti-spam page it does not give the session error and you can submit the content after moving on and back. it is not consistent.

**Comment by MissAllSunday** [comment]
SMF tokens are like little demons that likes to play tricks on us. This issue in particular is a symptom of something bigger. Rooted, very rooted inside the token system there is something wrong, I tried to figure it out what it was but failed miserably.

Other symptoms includes random token errors on saving pages or submitting forms.  I remember there was an issue with pages issuing multiple tokens at once, specially in the admin page. Some other times a token issued by X page was validated by Y page and some other times validation was expecting token X but received token Z

**Comment by jdarwood007** [comment]
Just hearing that makes me sad since I was the one who developed the initial groundwork for the tokens in 2.1.  The difficult part is we have a lot of pages that can jump from one form to another form and we need those tokens to be valid.  We also need to allow multi-tab browsing as preferred by our end users.  This came down to trying to make tokens work for us, while keeping it secure in what tokens are meant to do.

A bit of a problem from this is our generic settings pages all generate the same token id, which can mean multi-tab usage on them can cause a token error.  Or at least it was a problem when I first coded it and didn't get around to resolving that in a better way.

**Comment by sbulen** [comment]
Is there any writeup on tokens, how they work, purpose, where to use/not to use, etc.?

**Comment by MissAllSunday** [comment]
@jdarwood007 Yep, thats the main issue I believe, the admin pages are too generic and too interconected or totally disconected from eachother. I toyed with the idea of storing a "known tokens" for each admin pages but that turned out be too cubersome. A single token for all pages will defeat the token purpose. Separate tokens for admin pages and normal pages can also be problematic since a normal page very often send an user to admin actions and viceversa.

@sbulen roughly, a token is a unique val generated on a page, store it in session, send to the client then the client send it back and the server checks it againts the one stored. It should be used whenever there is an interaction with the client (POST, GET, PUT, DELETE, etc) and its a one time only thing, meaning each token is re-generated on each page/action request.

For this to work correctly there has to be a single sender and a single receiver. The issue here is that sometimes theres more than a single receiver or sender.

**Comment by sbulen** [comment]
This is gonna sound really dense...  But - within the SMF context - why?  Why are we using tokens at all?  E.g., is it eliminating a need to retest permissions/credentials each request?  

I'm familiar with the token concept for SSO.  But this isn't an SSO application...  Is it?  Was the token needed/introduced for SSI?  I.e., is it actually being used for SSO purposes, across, for example, WordPress & SMF?

I am not yet clued into the need we're trying to solve with the token...

**Comment by Arantor** [comment]
Tokens for SSO are a totally different concept that happens to use the same name.

Tokens in this context are security related, preventing people from spoofing requests as you. That's the use case being tackled here, things like replay attacks or certain types of reflected CSRF attack.

**Comment by sbulen** [comment]
Upon quick read of the code, the SMF token sounds like the "Synchronizer token" in this article:
https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet

Am I on the right track?

**Comment by jdarwood007** [comment]
sbulen,

Yes that is one of the things that it helps with, session validate in form also helps with this.  Session validation is unique per user for the entire session.  Tokens are unique per user per form and limited to time expiration (in addition to session).  In a general sense, once you visit a page, such as a settings page in the ACP, it generates a unique token for that page.  Visiting that page again would generate a new one rejecting the old one.  Once you submit that form, it destroys that token.  This means you can't use that token again.

In theory and practice it makes it more difficult to trick a administrator into preforming a unwanted action (such as lets say making somebody a admin) as even if you obtained the session info, you would need to have their unique token for that page.  Which those tokens do expire in a short amount of time.

A attacker would have to obtain your session validation info, get you to hit the page you need to visit and scrape your token info and then could attempt to trick you into submitting a hidden request to accomplish the action in a short amount of time.  Not impossible, but more difficult to accomplish.

No secure measure we add will make anything impossible, it just makes it more difficult to achieve.  This doesn't just apply to SMF, but to anything in general.

**Comment by sbulen** [comment]
Thanks for the time & explanation.  Starting to make sense now.

**Comment by albertlast** [comment]
i'm not able to reproduce this:

add a ban,
move to another page,
use back button,
try to save
get "Token verification failed. Please go back and try again."

**Comment by Sesquipedalian** [comment]
> i'm not able to reproduce this:
> 
> add a ban,
> move to another page,
> use back button,
> try to save
> get "Token verification failed. Please go back and try again."

Same happened for me.
