### ISSUE TITLE
 integration hook integrate_admin_areas is gone

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4260]
I notice that the integration_hook 'integrate_admin_areas' is gone,
so i got two question:
Is this with intention or a mistake?
When with intention how should a mod add something to the admin panel?

**Comment by emanuele45** [comment]
Since this is my doing I feel I have to answer.

> Is this with intention or a mistake?
> When with intention how should a mod add something to the admin panel?

Frequently, this kind of questions are answered simply by searching the history of the repository.
In that case, the "worst case scenario" search of "integrate_admin_area" in the patches would lead to the commit:

79a54a7c2558e95dd7ddc8a4e25b8c8027952f5f

That has all the answers. :smiley:

**Comment by albertlast** [comment]
Well i didn't see any hint which value got $menu_context['current_action'] when i like to add something to the admin panel...
