### ISSUE TITLE
Admin - Modification Settings - Integration Hooks

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#430]
If you have selected on of the dropdown and then go back to "---" (show all) it do nothing.
On IE 8 this the dropdown don't work..

**Comment by Oldiesmann** [comment]
Does IE throw any JS errors there? Most of us don't have that version anymore so it's difficult to test this issue.

**Comment by PortaMx** [comment]
Nothing .. it do nothing and now error is shown. I have enabled script debugging and show errors for IE8
Nothing to see, nothing work ...
for the other .. I don't have seen the "reset filter" entry (hohoho), but it was better to reset on "---" or name it "All"

**Comment by emanuele45** [comment]
Probably because "---" is not "show all" and there is a second entry that says "reset filter" that is the one that shows all the hooks again. ;)

**Comment by emanuele45** [comment]
Though I have to admit I don't like that dropdown so much (and anyway the check on existence is broken because it doesn't consider OOP, but don't even know if it is worth (in the sense that the hassle is quite big and not so reliable anyway) considering it), or at least I don't like the way I added it, probably use the placement "above_table_header" would be better... but maybe there is an issue with that because I think I tried but then moved to the other solution...or it was just to have the drop down next to the header filtered?? I don't remember...

**Comment by PortaMx** [comment]
I love dropdowns ... However, I make the somewhat different;
At the top of a [show all].
then follow each entry.
And .. Selected ALWAYS is displayed in the input mask
[View all](selected)
[option 1]
[Option 2]
[option 3]
...
[option n]

Now I choose option2:
[Option 2](selected)
[option 3]
...
[option n]

And this stay in postion, if I (as example) remove a entry from the filtered result set.
You know what I mean?

**Comment by emanuele45** [comment]
You mean in the list of hooks?
Did you by chance enabled/disabled one in the meantime?
That would change the order.

**Comment by Arantor** [comment]
So I began to look at this... it doesn't even seem to do anything in Chrome... onclick for an option is a bad idea, needs rewriting to be an onchange event, I think.
