### ISSUE TITLE
MySQL utf8_general_ci Incorrect string value 

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#4302]
Following pull request #3976

Has this been solved? I'm using MySQL 5.7.18 with Php 7.1 and SMF 2.1 beta 3.

Sometimes I get this in error log:
Incorrect string value: '\xF0\x9F\x92\x99' for column 'body' at row 1
Subs-Posts.php
line 1773

And the message is NOT inserted into db. I changed the body column from utf8_general_ci into utf8mb4_general_ci. Does that fix the problem?

**Comment by albertlast** [comment]
What is the content of the body in your post how create this issue?

**Comment by asmith20002** [comment]
I don't know what unicode character is causing that. I enabled query log today.

But does that matter? Shouldn't the body accept "any" character that the user sends?

**Comment by albertlast** [comment]
the utf-8 decoder say that you using: 💙
for the puropsing of testing you could change for temp https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Db-mysql.php#L60 this to true
and look if the issue raised up again

well github does some conversion:
`💙`
You had to use this here.

**Comment by asmith20002** [comment]
Beside that, shall I convert back the body column from utf8mb4_general_ci to utf8_general_ci?

**Comment by albertlast** [comment]
well this stuff needs to be sync,
you can only use the true ther when the col is mb4,
otherwise you should keep on false.

in my test mysql board(smf 2.1 beta 4/github) i got no issue with this char.
my setting is false and no mb4 charcode.
10.1.21-MariaDB should be something like mysql 5.7...

when i look in the smf_messages table in the body col of mariadb the i see that the entry is:
`&#128153;`
which is the exptected value.
on postgresql where mb4 is supported is see in the col:
`💙`
which means in my test env everything works as designed.

**Comment by asmith20002** [comment]
ok I leave it be for now. Changed it to true. Let's see...

Thanks for the help.

**Comment by albertlast** [comment]
When you keep this on,
You had to change all varchar fields...
In your th from smf

________________________________
Von: asmith20002 <notifications@github.com>
Gesendet: 16.09.2017 08:53
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] MySQL utf8_general_ci Incorrect string value (#4302)


ok I leave it be for now. Changed it to true. Let's see...

Thanks for the help.

**Comment by asmith20002** [comment]
What happens if I don't? Almost all varchar fields don't have incoming 4-bytes utf8 characters.

**Comment by albertlast** [comment]
But all can be filled with this,
This is reason that you should do this only temporary.


________________________________
Von: asmith20002 <notifications@github.com>
Gesendet: 16.09.2017 09:27
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] MySQL utf8_general_ci Incorrect string value (#4302)


What happens if I don't? Almost all varchar fields don't have incoming 4-bytes utf8 characters.

**Comment by albertlast** [comment]
Question:
Which kind of file your got in your source directory in this schema:
Subs-Db-*.php

**Comment by asmith20002** [comment]
Well this was SMF 2.1 beta 2 and then I did a upgrade to beta 3 using SMF site official release.

I have:
Subs-Db-mysql.php
Subs-Db-mysqli.php
Subs-Db-postgresql.php

Worth to note that after the upgrade the Settings.php was using mysqli which was causing problems and I manually changed it to mysql. (issue #4170)

**Comment by albertlast** [comment]
I was aspecting this,
can you please delete mysqli file.

Dunno if it fix your issue but this file shouldn't exists any more.

**Comment by asmith20002** [comment]
It's deleted. I don't think it was getting used anyway. Just an orphan file.

**Comment by albertlast** [comment]
so than please close this issue.
