### ISSUE TITLE
Upgrader - Deleting karma doesn't delete the log_karma table

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4333]
Should it?

**Comment by albertlast** [comment]
Can you please link the place where this happen in the upgrade process?

**Comment by sbulen** [comment]
Here's the prompt:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L3794-L3802

And here's where the cleanup occurs:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L1013-L1049

I'm not sure that table is used, seems to be empty

**Comment by Arantor** [comment]
I would argue that it shouldn't delete it in case people want to re-add the mod for it. Though it's _meant_ to be short lived, there's no guarantee that it is.

**Comment by XinYenFon** [comment]
Upgrader has option to delete karma related data, @sbulen did you select that or not? If not its expected behavior.

**Comment by sbulen** [comment]
@Antes, yes, the option was selected.  The columns were deleted.  The code linked to above does not delete the table.

@Arantor, If you tell the upgrader to delete it, it should delete it.  If you want to keep it around, don't select that option...

I actually don't think that table is used.   There is only one row in it in my forum.   I believe the real data is in the custom columns in members, etc.

**Comment by Arantor** [comment]
I'm sorry, I didn't realise it now had an option. Honestly I wouldn't have the option, I'd just leave the data in there and people who don't care won't care, and people who do care can just use it.

More options is rarely _better_.

The table won't be used in 2.1 since karma was removed... trust me, though, the table is definitely used but it is primarily transient data in typical configuration.

**Comment by sbulen** [comment]
PR #4336 submitted
