### ISSUE TITLE
Missing avatars breaking layout

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#4343]
![image](https://user-images.githubusercontent.com/732116/31048028-faedf870-a5c9-11e7-8ce6-09698312d32a.png)

Can we make that look better when the avatar is missing?

**Comment by Gwenwyfar** [comment]
I'll look into it (unless @Antes wants to do this one)

**Comment by XinYenFon** [comment]
Doesn`t it require to show Default Avatar if user missing avatar ?

**Comment by jdarwood007** [comment]
The files may have been missing or the url bad.  I didn't see why it wasn't loading the avatar, just noticed what the layout looked like when it was.
Its hard to click the link to the PM when its like this as well.

**Comment by sbulen** [comment]
When doing an upgrade, you MUST combine/overwrite the old folders with the new ones, to get the proper default icons.  They are different than in 2.0.

**Comment by illori** [comment]
combine/overwrite which old folders with what new ones?

**Comment by XinYenFon** [comment]
Default avatar introduced in SMF 2.1, so no, overwrite does not required. Its a code related issue. While unread_alerts fetches the default avatar properly (?), unread_messages does not.

**Comment by sbulen** [comment]
Maybe i could have worded that better.  Since the defaults images are new, they must find their way into the existing avatar & custom avatar folders during an upgrade.  I.e., by copying the new folders that have the default images on top of the existing folders (merging the contents).

In addition, the custom avatar folder did not have a fixed/predetermined name in 2.0.  Many (most? all?) users will have custom avatar folders named something other than custom_avatar.  

I found it easiest to rename my "avs" folder to custom_avatar in 2.0, prior to the upgrade.

Upgrade instructions will need to address these needs or we will have lots of "missing" avatars.  This issue would not have happened had a proper upgrade occured.

**Comment by jdarwood007** [comment]
While that fixes it for included avatars, external avatars that are missing could also cause this template issue.

**Comment by sbulen** [comment]
Correct.  The code should be fixed.

Just pointing out that the upgrade process & instructions are an important factor for rollout, or we will see a lot of missing avatars.

**Comment by Gwenwyfar** [comment]
I have submitted a fix, but we may need to expand it to some other places where images/avatars are used that may have the same problem.

**Comment by Gwenwyfar** [comment]
So we have the same alt text displaying on topics, profile and user menu, although the text doesn't break anything on those.

**Comment by Gwenwyfar** [comment]
There seems to have been some confusion on this so just to clarify... I'm only getting a few css "fixes" up that were in the previous PR, someone else should take care of this issue.

**Comment by albertlast** [comment]
When i understand correctly are more than css fixed not needed?!
And second guess would be that this is than enough:
```
.top_menu.scrollable .avatar {
	width: 40px;
	height: 40px;
	object-fit: scale-down;
	margin: 4px;
	display: inline-block;
	color: transparent; /* For broken images */
}
/* This will only show when the image does not load */
.top_menu.scrollable .avatar:before {
	content: "";
	display: block;
	background: url(./avatars/default.png) no-repeat center / 100%;
	opacity: 0.5;
	height: 40px;
}
```
