### ISSUE TITLE
While login a new session id is generated

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4365]
Since revert pr https://github.com/SimpleMachines/SMF2.1/pull/4363
you get a new session id while login process which generate the error
that the session runs out.

**Comment by sbulen** [comment]
This will be addressed by #4356

**Comment by albertlast** [comment]
And where there?

**Comment by sbulen** [comment]
The extra session was created because the cookie state change was not detected. Fixing the preg_match restores the cookie & session cleanup logic that was working in 2.0.

**Comment by albertlast** [comment]
Nope the session keeps changing.
So instead of fixing this,
you didn't check the session id any more which is my eyes a new security issue.

**Comment by sbulen** [comment]
New session IDs are generated upon login on purpose.  This is a security measure:
https://stackoverflow.com/questions/22965067/when-and-why-i-should-use-session-regenerate-id

The code to do so is in setLoginCookie.

The "extra session" bug had to do with logging OUT.   Cleaning up the cookie and session takes place on logout, not login.   

This wasn't working upon cookie state changes.  Properly detecting the cookie state change was required for this to work.  Otherwise, it tried to delete the wrong session ID, and left an extra session record out there.

**Comment by albertlast** [comment]
When you look into the code you solve this issue by not checking the session_var and the sc field from the login form,
which is the security issue.
The reason why you not checking this,
that the new session_id is generated before login process is done.
