### ISSUE TITLE
Weird database issue with new install [PHP 7.1.11]

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#4396]
I downloaded XAMPP with PHP 7.1.11.

Trying to run a new install, I got stuck in the database step. By default, phpMyAdmin does include a database called "test".
If you use anything other than "test" for the database name, I receive the following error:
![](https://i.gyazo.com/923170ebbb2741312747456e19860315.png)

If I use test, the install runs good.

![](https://i.gyazo.com/09f50cf11a2d30765e24ecab7b1dc6fd.png)

**Comment by sbulen** [comment]
I believe this is expected behavior.  In some systems, e.g., my WAMP server, the installer has sufficient privileges to create the DB and it just goes ahead and does so if it doesn't exist.  

In my hosted system, however, the installer does NOT have sufficient privileges.  I am expected to go in cPanel and create an empty DB, and create a DB user with sufficient privileges in order to do an install, & then add that user to that DB.  

This is covered in our installation instructions:
      https://wiki.simplemachines.org/smf/Installing

I believe the message is actually telling you what to do.   The reason "test" works is that it exists.

**Comment by frandominguezl** [comment]
Manually creating the databse doesn't work either (I forgot to mention that above)

**Comment by colinschoen** [comment]
Are you sure the DB user you are using has privileges to the database that you created?

**Comment by frandominguezl** [comment]
Everytime I used XAMPP the username was "localhost". I don't know if this changed for this version... I will going to check later and reply here.

**Comment by wintstar** [comment]
localhost is right under xampp. Did you changed the standart password? Xampp uses "" as initial password =>> https://stackoverflow.com/questions/26757197/i-cant-access-my-database-in-localhost-using-xampp

I have no problems with PHP 7.1.11, neither with xampp nor on the Live Sever.

**Comment by frandominguezl** [comment]
Looks like it was a (weird) phpMyAdmin config issue. I managed to solve it. Thanks for the help :)
