### ISSUE TITLE
Database error when going to different page

### ISSUE THREAD

**Issue by notepaddo** [SimpleMachines/SMF#4431]
SMF 2.1 Beta 3

Steps to reproduce the error:

1) Click on a board index containing so many topics that they need to be listed in more than one page, so that you obtain the list of topics
2) Click on the header “Subject”, so that you will list topics in alphabetical rather then chronological order
3) Go down and click on page 2

You will obtain this message:

Database Error
Unknown column 'mfsubject' in 'order clause'
File: /(folder where the forum is installed)/Sources/MessageIndex.php
Line: 307

**Comment by albertlast** [comment]
Please use the github version.

**Comment by notepaddo** [comment]
I tested the github version and the bug is there.

**Comment by albertlast** [comment]
I test you steps:
open a board with more than one page
order by subject
jump to page 2 -> got no error

Can you please look in your messageIndex.php  Line 233
and compare this with the github version: https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/MessageIndex.php#L233

maybe post you complete MessageIndex on a pastebin side and link this to this issue here,
for furhter analyse when the line are the same.

**Comment by notepaddo** [comment]
I downloaded my messageIndex.php and Line 233 looks identical:
		'subject' => 'mf.subject',

**Comment by notepaddo** [comment]
You can see the error in my forum: https://www.spiritualita.org/forum
The error does not appear if I jump to page 2 without having ordered by subject.

**Comment by albertlast** [comment]
I remember that we got here an issue,
the pr how fix this: https://github.com/SimpleMachines/SMF2.1/commit/ca7b717596887e73d847cf1ef4660d6dcacf2064#diff-04560aac86aa2e2dfa81d1199a933dce
did one change in messageIndex Line 296
and one change in Subs-Db-mysql.php Line 275
also check that the Subs-Db-mysqli.php didn't exists anymore.

Please do the checks and yes i saw that you got the issue in your board.

**Comment by notepaddo** [comment]
Thank you: it solved the bug.
