### ISSUE TITLE
upgrade.php password fail on first attempt?

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#447]
when running the upgrade.php script the first attempt to log in will fail with the password being reported as incorrect. the second attempt to log in works just fine.

**Comment by ghost** [comment]
This looks to be an issue with the hashing of the password, when you login initially from the upgrade.php file there is an `onsubmit="hashLoginPassword(...)` function that's called which populates `$_POST['hash_passwrd']` and wipes `$_POST['passwrd']`.
When you enter your password and submit it, the hash that's generated is different to the hashed password retrieved from the database.

Once the login fails the first time then `$upcontext['disable_login_hashing']` is set to true so `onsubmit="hashLoginPassword(...)` isn't called on login next time which in turn works.

**Comment by emanuele45** [comment]
From IRC:

> [2013-06-19 15:06:03] emanuele> probably upgrade.php doesn't have the tokens code to hash the password...I may have forgot to add it...
> [2013-06-19 15:06:08] \* emanuele whistles innocently
> [2013-06-19 15:06:14] emanuele> (or I added it broken)
> [2013-06-19 15:06:49] emanuele> most of the time if the login works the first time and not the second is a client-side hashing issue

And obviously the last line I wrote is wrong and should be read the other way around: _most of the time if the login doesn't work the first time and works the second is a client-side hashing issue_

So what I suggest is:
1. check if when hashLoginPassword is called has all the three arguments it is supposed to have,
2. if it doesn't have the third then you have found the bug,
3. if it's there, then it may be an issue with the token regenerated too early in the process

The root cause of 2 may be one of:
1. the token is not generated when it should,
2. the token is placed in the wrong array,
maybe something else.

At the moment I don't have a clean install to test an upgrade and before set up any other I really should clean up the mess I have around... :blush: 
/me runs

**Comment by ghost** [comment]
The token is created on line 1001 `$upcontext += createToken('login');` in the `WelcomeLogin()` function and the template is set on line 955 `$upcontext['sub_template'] = 'welcome_message';` of the same function.

**Comment by matthew-kerle** [comment]
onsubmit="" is used? Why not bind an event to the element instead like it should be?

**Comment by emanuele45** [comment]
OMG WE HAZ AN onsubmit!!

There are about:
- 413 onclick
- 112 onchange
- 26 onsubmit
- 12 onkyeup/down
  and only counting those that are evident (i.e. found with a simple search, those that are added somehow in some source file are excluded).

The reason al those are there is simple: nobody changed it up until now.

**Comment by matthew-kerle** [comment]
Oh, I know.

**Comment by ghost** [comment]
`onsubmit="hashLoginPassword(this, \'' . $upcontext['rid'] . '\', \'' . (!empty($upcontext['login_token']) ? $upcontext['login_token'] : '') . '\');"`

So `this` is the password input which should be grand, `$upcontext['rid']` is a random integer between 0 and 5000 and `$upcontext['login_token']` looks to be set correctly with `$upcontext += createToken('login');` on line 1001 in the `WelcomeLogin()` function and `$upcontext['sub_template'] = 'welcome_message';` is set on line 955 of the `WelcomeLogin()` function.

I'm assuming `$upcontext['sub_template'] = 'welcome_message';` just sets the variable in the array and that there's nothing fancy going on here like loading the template function into the array, as if this was the case then the token isn't set.

Can anyone shed any more light on this issue?

**Comment by Oldiesmann** [comment]
I'm looking into this, and figured out what's going on, but the obvious solution doesn't work.

The problem is that hashLoginPassword() includes the login token, but the code to calculate the hash using what's in the database doesn't.

However, adding $upcontext['login_token'] to the check on line 1127 doesn't work either. I'm guessing this value gets changed between the time the form is filled out and the time the check is performed. If I add `<input type="hidden" name="login_token" value="', $upcontext['login_token'], '" />` to the login form, and add $_REQUEST['login_token'] to the check, it works fine.

We need to figure out the most secure solution here. I'd rather not expose the login token in such an obvious way, but storing it in a session variable isn't very secure either.

**Comment by jdarwood007** [comment]
On a related note, I have similar issues with 2.1 on the general login page and it seems to be related to the login hash.  I need to do more checking but it seems completely unstable.  Although I am using SMF with 5.5 right now.

**Comment by Oldiesmann** [comment]
I haven't experienced any issues with the login form, though I usually use the quick login instead of the specific action=login page.

**Comment by illori** [comment]
closing this as #568 should fix it
