### ISSUE TITLE
Persistent connection issue (2.0 & 2.1)

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4516]
This was reported by the forum user nend earlier, but I think it's important enough to put here.   

$db_persist is not declared as a global in smf_db_query, and it is needed to support persistent connections:
```
		// Fall back to the regular username and password if need be
		if (!$db_connection)
		{
			if (empty($db_persist))
				$db_connection = @mysqli_connect($db_server, $db_user, $db_passwd);
			else
				$db_connection = @mysqli_connect('p:' . $db_server, $db_user, $db_passwd);
		}
```

In a related issue, sessionWrite ends up creating new db connections using this logic, since the connection seems to be getting closed before the session is written.  Persistent connections may help reduce the # of db connections.  (I have confirmed this in 2.0, I believe it will be an issue in 2.1 as well.)

**Comment by albertlast** [comment]
The real issue in my eyes is:
~~that Subs-Db-mysql.php didn't support persist connection,
atm only pg does this but with a different var... $db_options['persist']
when you look in the mysql_* version/time ther was also support for persist and the var $db_options['persist'] was used.~~

looks fine to me you need to use the right var ($db_options['persist'] ) and mysqli_*

The whole "reconnect" logic in query and error looks for me broken and should be removed...
i cant imagen how the connection should get be lost and
when it get lost the smf_db_initiate should be get called...

**Comment by sbulen** [comment]
FYI - The setting is in both $db_persist (from settings.php) and in $db_options (it gets copied there in Load.php).  $db_persist is more commonly used; I don't know why it was also copied to $db_options.  

The connection is indeed lost before sessionWrite().  This is easily verified in the debugger in 2.1.   I noticed this researching why 2.0.14 used more resources than 2.0.13.  

I don't know why the connection is lost, but it is.  There is a comment in the code that notes that sometimes the db connection is dropped before the session is written.  In my testing, this ALWAYS happens now, and every sessionWrite() creates its own db connection.  

It'd sure be interesting to know _why_...

**Comment by sbulen** [comment]
This should probably be reopened.

Should we use $db_option as @albertlast suggested?

@albertlast - I am also interested in your take as to why the connections are getting lost.   (Starting with 2.0.14)

**Comment by sbulen** [comment]
Note from jdarwood on the PR I submitted:

> For a default install of SMF with no changes this fix will resolve that problem.
> 
> The problem I see results in when you start using SMF APIs/calls outside of SMF. Such as for example if you use SSI to get SMF going, then use the database setup to initialize a new database connection, to another database. That would mean a different user, password, database and possibly db_persist among other db_options. During a event that would trigger this issue in the first place, the process to reinitialize the connection would fail to reconnect you to the proper database since it would try to use the information from the Settings.php, rather than what it was initially supplied with when we called the process to initialize the connection.
> 

Thanks for the explanation @jdarwood007 .    

I'm still confused though.  Where is the API call that won't work?  

Fixing the performance problem was at the top of my list.  I can't fix code that I can't see...  

I propose that we separate the performance issue from the overwritten connection string issue.  The prior is an easy fix.  The latter, I admit I don't yet see where that takes place.

**Comment by albertlast** [comment]
I will look into this issue (maybe i should it mention early),
because the logic of "reconnection" needs a fix also.


SMF 2.1 session management based on that database flags are setted,
but the reconnection logic doesn't set the right flags -> even when the reconnection solve the lost db connection, 
you will run in the next issue because the connection flags are wrong.

**Comment by jdarwood007** [comment]
If you call smf_db_initiate multiple times for multiple databases, and you trigger this event or lets say trigger a database error that also uses similar code here, then upon it trying to reconnect to that database, this would fail.

Initially I thought this would be easier to solve in 2.0 since the database stuff for mysqli is a object, we could store private vars and recall them as needed.  But this would still fail since all calls to db functions still don't know where they originated from if multiple smf_db_initiate are done.  We don't store the result of the class creation anywhere natively from smf_db_initiate.

In 2.1 this is not using any classes, so I thought it would be harder to fix, but it looks like it will be just as difficult to fix.  The only common variable passed to database functions is the connection resource, which if getting to this point, its null to trigger this occurrence anyways.  Thus I am not sure how the effective solution here is to even fix this properly.

I was wrong about the $ssi_db_* since it appears to be statically handled.  But doesn't change that multiple calls to smf_db_initiate will result in being unable to properly restore a connection.

Your patch could be implanted as a simple fix for the problem you have, while the deeper issue is looked at.  I don't think its worth trying to fix it for 2.0, since this most likely in my mind is looking like a good sized change.  I don't even know if the change could make 2.1.  I'm trying to wrap my mind around how to fix it, but coming up with nothing since we are only tracking multiple connections via the connection resource which is null in this case.

**Comment by sbulen** [comment]
Thanks, @albertlast .

For the record, I must admit I'm more concerned with 2.0.14/2.0.15.  My CPU increased & became more erratic after upgrading to 2.0.14.  I'm still trying to stabilize my production website.  The doubling of db connections is one of the most significant changes I can identify.  

And I really do mean doubling - every page has a db connection for the page and a 2nd one for sessionWrite().  This started with 2.0.14/mysqli.  

This logic is shared with 2.1.  A proper fix is important.  

I may need to go back to 2.0.13, and start telling others who experience http500 to do likewise.

**Comment by sbulen** [comment]
Thanks @jdarwood007 .  Our posts crossed.  My note above to albertlast still applies.

**Comment by albertlast** [comment]
Since i don't care about smf 2.0.x i only interested if this issue exists in 2.1 too or not.
Maybe a mod or something else close the connection before session write is done...

**Comment by sbulen** [comment]
The session is closing even on a pure vanilla 2.0.14/15 & 2.1 prior to sessionWrite().  

A second connection is opened during sessionWrite, even just viewing the simple "welcome" post.  No mods, nothing special.  Not even a post.  Just viewing the initial install post.

2.0 & 2.1 have the same problem - and it's pretty bad on large forums during recrawls by search engines, since they hit EVERYTHING as rapidly as possible.  And now we have 2x the number of DB connections.

**Comment by jdarwood007** [comment]
@sbulen Ok.  I would be fine with this fix for 2.0.  Its a simple fix and I can not foresee it breaking anything for OOB users.  Those of us making use of smf_db_initiate would have problems with this, but at this point since the logic is already flawed, would be used to seeing its side effects.

**Comment by albertlast** [comment]
in 2.1 this issue which you describe can't exists,
because the postgresql didn't got this reconnect logic and
i didn't got any issue.

**Comment by sbulen** [comment]
I don't use pg.  And neither do 99+% of SMF users.  I'm talking about mysqli.

**Comment by sbulen** [comment]
And you won't see any issue until your site gets many thousands of hits in an hour - e.g., by a web crawler like Google.  I started looking into this after upgrading to 2.0.14/15 & getting re-crawled by Google.  

Everything I see says the number of DB connections has doubled with 2.0.14 / 2.1.  **_Doubled._**  

You can see the multiple connections in this profile on the left.  The test after applying my 2.1 PR is on the right (persistent connections used for both; as an FYI, 2.0.13 only has one connection in this scenario):
![smf21_persist_compare](https://user-images.githubusercontent.com/23568484/35479272-2996adfc-03a8-11e8-856f-dcacce04f165.JPG)

**Comment by albertlast** [comment]
In my eyes i found the real issue in smf 2.1:
https://github.com/SimpleMachines/SMF2.1/blob/be71e66309af5d54726b96159f9ce4544a0a338e/Sources/Subs-Db-mysql.php#L77-L80
Needs to be (see $db_name):
```
	if ($connection) {
		if (!empty($db_options['port']))
			$success = mysqli_real_connect($connection, $db_server, $db_user, $db_passwd, $db_name, $db_options['port'], null, $flags);
		else
			$success = mysqli_real_connect($connection, $db_server, $db_user, $db_passwd, $db_name, 0, null, $flags);
```
In short the intial db connection method got an issue ->
reason why everytime the reconnection logic is called.

**Comment by sbulen** [comment]
$db_name is declared as a global about 6 lines above what you just showed.

**Comment by sbulen** [comment]
What you've got to ask yourself:  Why are $connection & $db_connection null/unset here?   But only during sessionWrite()?

**Comment by albertlast** [comment]
Yeah but not used in the mysqli_real_connect() call,
in my test env create this the issue that the connection is not created and the reconnection logic got in place.
So maybe is that the issue also in smf 2.0.x that the intial db connection call got an error like this,
so that the db call (maybe session write is the first call) needs to run the reconnect logic ->
the real issue would be than again that the intial db call got some error.

**Comment by sbulen** [comment]
If you continue the trace in 2.1, what happens is that upon first smf_db_query, a connection is made.  

So, in 2.1, there is a mysqli_real_connect followed by a mysqli_connect.  (These are shown in my profiles above.)   

On very complex pages, this is sufficient, and no further connects are requested.  

Until sessionWrite()....   That's when the 2nd mysqli_connect occurs (as shown in the image above).

**Comment by albertlast** [comment]
jeah this follow up is another bug which needs to be fixed:
https://github.com/SimpleMachines/SMF2.1/blob/be71e66309af5d54726b96159f9ce4544a0a338e/Sources/Subs-Db-mysql.php#L96-L99
Needs to be:
```
mysqli_query($connection, 'SET SESSION sql_mode = \'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION\'');
```

**Comment by albertlast** [comment]
In smf 2.0.x the issue could be this (maybe more exists):
```
		// This makes it possible to have SMF automatically change the sql_mode and autocommit if needed.
		if (isset($mysql_set_mode) && $mysql_set_mode === true)
			$smcFunc['db_query']('', 'SET sql_mode = \'\', AUTOCOMMIT = 1',
			array(),
			false
		);
```

Since the sql_mode exists since 2.0.14 i believe that will cover your description.

**Comment by jdarwood007** [comment]
https://secure.php.net/manual/en/mysqli.configuration.php#ini.mysqli.reconnect
https://secure.php.net/mysqli_ping

How about we make sure reconnect is enabled and then have mysqli_ping attempt a reconnection?  Seems all we need to supply is $(db_)?connection.
However since mysqlnd is becoming default, this won't work well on them.

The best solution would be to move over to using object based setup here and then this becomes easier to fix.

But as far as 2.1 is along in its development process.  Do we want to do this?  Theoretically if this is done, it should cause no breakage as all calls go through the $smcFunc[db_*] handlers.
I would propose a that smf_db_initiate return the db_connection, but if db_options['return'] = 'instance' is called, the class itself is returned.

This leaves the resulting issue up to the code developer to handle but still easier for them to handle.

**Comment by albertlast** [comment]
Ther is no general changed needed,
first fix the issues (see my pr).
Secondly centralize the connection code for intial and reconnect than we done.

Since the issues exists partly also in smf 2.0.x shows that the object attempt make no different here,
the implementation of smf 2.0.x is garbage in my eyes.

**Comment by tinoest** [comment]
You can always call mysqli_ping and if that fails then reconnect. It’s not to hard to have a reconnect function, your variables are all in scope still.

**Comment by albertlast** [comment]
When you like to slow down the mysql db version of smf feel free to do so.
So long you don't do such stuff on pg side i'm fine.

The "hard" part is that the logic should work, in the same when you connect intial or reconnect.
In existing solution this doesn't is the case,
also i would like to point out that the howl reconnect logic didn't exists in postgres AND mysql_\*.
The stuff was intial introduce by the intial commit of mysqli_\*. --> For ssi and co. that not realy need
otherwise the mysql_\* version would never work with ssi.

**Comment by sbulen** [comment]
This issue is still open.   (The global variable is still not declared. )

I think that after albertlast's other fixes,  it is quite possible that the remaining fix is to simply remove all the reconnect logic entirely.   That fix, I think,  got to the root cause that the author was trying to fix when adding the new connect logic.

We should fix or remove that logic.
