### ISSUE TITLE
Get Browser ID's and Mobile detection before all other ..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#454]
It's a problem, if a mod must detect is a browser a mobile device or what browser is used.
This can a modification they is loaded via "integrate_pre_include" or "integrate_pre_load" not checked, because the functions "detect browser" is not executed at this time.
Also must the result from this stored in $modSettings, because all other not exist at this time.
What did you think about this feature ?

**Comment by emanuele45** [comment]
`integrate_pre_include` is not meant to "execute" anything (just to include files and anyway it should be deprecated IMO because any hook in 2.1 can load its own file, so any integrate_*_include is a sort of duplication, but that's another point).
`integrate_pre_load` ... dunno, any example of actual need to detect the browser so early in the process?

**Comment by PortaMx** [comment]
It's not abolute exactly what you say (I think)
pre_include can load additional files and can check other thinks to check is't need to load additional files.
So at this point WE detect the browser and if that a mobile device, the need settings a modificated and additional files are load (because HERE IS the point to do that ;-)
But it's you right to see that other as my person ...

**Comment by jdarwood007** [comment]
We are supposed to be doing our best to remove browser logic from sources.  Thats supposed to be left up to our templates and in reality css to handle.

As well, nothing would prevent you or should break anything by calling the detectBrowser function early.  As well when you call it from the sources (I guess even templates), you should use the isBrowser() function.

**Comment by Arantor** [comment]
I'm not sure it should be loaded that early at all. I can't actually think of a use case where it would be important to have it that early. I know the argument of 'but we can load things on demand'... sure, you're going to be implementing other logic before the page ends and after it is otherwise detected.

I think I'm going to have to close this but if someone provides a realistic use case, we'll revisit it.
