### ISSUE TITLE
banned user trying to login

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4603]
if you use the login popup while you are banned, it just shows "error" and nothing else where the rest of the page shows your banned message. i think the popup should show the same error if you are not allowed to log in.

**Comment by albertlast** [comment]
Stacktrace:
https://github.com/SimpleMachines/SMF2.1/blob/93f0e142c2f606fe1cdc45b0a9956a65b4e0c153/index.php#L150
https://github.com/SimpleMachines/SMF2.1/blob/93f0e142c2f606fe1cdc45b0a9956a65b4e0c153/index.php#L192
https://github.com/SimpleMachines/SMF2.1/blob/93f0e142c2f606fe1cdc45b0a9956a65b4e0c153/Sources/Security.php#L343

What happen?
ajax call the "login form" and get as response a html status code 500 and a complete html side instead of html snipe for the login form.
the "error" message came from jquery not from smf,
you get a endless loop when you switch the html code to 200

It's central logic issue in the core,
i see many issue if we try to fix this.
My recommandation keep it like it is. -> close this issue @illori @colinschoen @Sesquipedalian

**Comment by albertlast** [comment]
Can we close this issue?
Like i mention the issue hit the core of smf,
i see less chance to do changes here without open many other issues.

**Comment by illori** [comment]
i dont think this should be closed.

**Comment by albertlast** [comment]
Can you please add more as "no" to this reason?
When you look in effort which I spend this doesn't fit

________________________________
Von: Illori <notifications@github.com>
Gesendet: Samstag, 28. April 2018 12:03
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] banned user trying to login (#4603)


i dont think this should be closed.

**Comment by illori** [comment]
lets let someone on the dev team look it over. IMO it is looks bad to the user that they cant even view the login form.
