### ISSUE TITLE
modify profile -> fatal error

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4658]
Fatal error: Class 'TrueBV\Exception\LabelOutOfBoundsException' not found in D:\wamp\www\github2.1\Sources\punycode\Punycode.php on line 84

Call Stack
--

1 | 0.0000 | 341920 | {main}(  ) | ..\index.php:0
2 | 0.0468 | 4784064 | call_user_func:{D:\wamp\www\github2.1\index.php:150} (  ) | ..\index.php:150
3 | 0.0468 | 4784600 | ModifyProfile(  ) | ..\index.php:150
4 | 0.0780 | 7002336 | saveProfileFields(  ) | ..\Profile.php:646
5 | 0.1560 | 8995176 | {closure:D:\wamp\www\github2.1\Sources\Profile-Modify.php:585-593}(  ) | ..\Profile-Modify.php:761
6 | 0.1560 | 8995336 | validate_iri(  ) | ..\Profile-Modify.php:591
7 | 0.1560 | 8995488 | iri_to_url(  ) | ..\Subs.php:6443
8 | 0.1560 | 9092088 | TrueBV\Punycode->encode(  ) | ..\Subs.php:6498

i was modifying my profile, changed the gender option, saved the page and the above error came up.

**Comment by illori** [comment]
i was doing this as the admin user, i tried as global moderator and could not duplicate the error.

**Comment by Sesquipedalian** [comment]
What was in the website URL field at the time?

**Comment by illori** [comment]
since it is just for testing, http://sghjhhggff..com

**Comment by Sesquipedalian** [comment]
The immediate error was due to the fact that I was just including the main Punycode.php file rather than setting up a proper autoload for it (my bad). But once I fixed that, I realized that throwing the exceptions was not something we wanted to happen for our purposes in the first place. So in #4665 I've removed the unwanted and problematic code and thereby simplified everything involved with this stuff.
