### ISSUE TITLE
request to join a group alert

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4661]
my admin user is not the moderator of the group, why should the admin by default get an alert that someone wants to join a group that they are not moderator of? IMO only the moderator should get the alert that someone wants to join the group.

**Comment by albertlast** [comment]
Two reason
1) he is the admin
2) it's simple from authorization pov  and simple is part of the smf

**Comment by illori** [comment]
just because you can, does not really mean you should be doing it.

**Comment by albertlast** [comment]
The name of the board is not complex maschine forum,
keep it simple when possible and here i see no need (can be done by a mod i guess)

**Comment by frandominguezl** [comment]
I do agree that it should only send alert to the moderator(s) of the group

**Comment by albertlast** [comment]
This message is not send to any one,
the solution which is here used based on the authority and
everyone how got the rights, see the stuff.
Admin got the right todo everthing -> he see the stuff.

**Comment by illori** [comment]
in SMF 2.0 only those that are the group moderator get an email if they op in to get it. so the admin does not get alerted that someone wants to join a group unless they go digging to find the list. unless i am missing a setting somewhere i have never gotten an email about an invite pending.

i think the same should apply to SMF 2.1.

**Comment by equinoxmatt** [comment]
I agree with illori on this. 

Just because it is called 'Simple Machines Forum' does not mean bugs/incorrect implementation should be acceptable.  Poor reasoning.  AFAIK the name has nothing to do with the forum code being complex/simple. It is about being easy to use.

Plus if you have a large forum, with several groups and a team of moderators, why on earth should an admin get all the alerts?  It is unnecessary noise.

I would agree, if the group has no moderator, it should fallback to admin.

**Comment by smfbigguy** [comment]
Why not allow the admin the choice of opting into emails or not. If they want to know they shouldbe allowed to know. If not then they don't have to opt in for emails.

**Comment by albertlast** [comment]
I'm not sure if the admin got a mail by a request,
this part was never looked in my eyes.

**Comment by MissAllSunday** [comment]
Historically, SMF has always allowed the admins to see and do everything, this follows the same principle.
