### ISSUE TITLE
Memberlist Smartphone view

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4673]
HUAWEI Mate 9
Browser Firefox and Chrome

Microsoft Lumia 950
Browser Edge

Gender icon is not in the column Gender in portrait format.

![memberlist_potrait](https://user-images.githubusercontent.com/2753863/37949977-2ead6a34-3197-11e8-8f22-672c5b452cdf.jpg)

![memberlist_landscape](https://user-images.githubusercontent.com/2753863/37949985-349a72d4-3197-11e8-8606-3830183a74c1.jpg)

**Comment by Gwenwyfar** [comment]
The adaptive version is not complete, so it is best that you wait until the revision for it comes in before spending time testing. If you want to test the theme, for now test the desktop view.

I am closing this, feel free to open new issues after the mobile revision has been done.

**Comment by wintstar** [comment]
I would leave the issue open anyway. By closing it the problem is forgotten.

**Comment by Gwenwyfar** [comment]
It will not be forgotten because **all** pages need to be tested, this is not an isolated problem. The responsive.css file will also be heavily modified. Tracking each of those little problems individually will take more time than simply testing all of them.

If you like you can create a issue with a checklist of all problems instead, but they may still become obsolete once the revision is done.
