### ISSUE TITLE
like any content

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4696]
in permissions we have "Can like any content", currently we only have likes in posts, i think this should be changed to "Can like any posts" since this better reflects how this feature works. we would need to update the help text as well if this is changed.

**Comment by albertlast** [comment]
Why you don't open a pr with this changes?

**Comment by illori** [comment]
If I had time I would have.

**Comment by albertlast** [comment]
To create a pr with this changes would be faster than create many issue and write a wall of text and
important you would not cover important issue with issue like that.

**Comment by illori** [comment]
Can't hurt to also get some feedback to see if others agree before putting
in the effort. Also you could have already fixed it in the time you are
complaining about this.

**Comment by albertlast** [comment]
To ask for every small step make the project slower is already is,
when you create a pr guys can vote/comment like a issue and
the stuff keep together,
now the draft topic is spread around in ~5 issues without the possibility to get the big pic since,
the missing linking.
When you want realy a feedback than ask the user and the user didn't look here,
they look at sm.org.

When you did my task where i try to implement more advanced stuff in travis,
than i take you task.

**Comment by MissAllSunday** [comment]
Actually, the likes system can be extended by mods and will use the same general permission. "any content" reflects this more accurately.
