### ISSUE TITLE
Enable automatic saving of drafts

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4697]
in the profile under look and layout there is the option to "Enable automatic saving of drafts", there are permissions to grant saving of drafts for posts and PM's, if this permission is not granted you can still see the option in look and layout. to a point i can understand why it is permission based but i think it should be a default feature that is enabled for all or none not permission based. either way if it is kept permission based the option should not show in the profile if you dont have permission to use it.

**Comment by frandominguezl** [comment]
I've just checked it and it works as expected.

**Comment by illori** [comment]
why not just remove the option in the profile and if drafts are enabled have them enabled by default for everyone? since the saving of drafts in the profile is not enabled by default, most will not know to enable it and as a result will not use the feature.

**Comment by frandominguezl** [comment]
That'd be something to discuss with the devs but I'm in favour of leaving that option available for users. Someone who posts a lot would have a lot of drafts saved automatically and they may not want to.

**Comment by illori** [comment]
then we need to tweak the feature, if they have posted the post, the draft should be deleted. so IMO this is not an issue.

**Comment by frandominguezl** [comment]
So yes, I believe it'd be better to get rid of the auto draft saving option and just make it that way by default, but I don't know if there's someone available to do that. I'll try to have a look on that but I think it's out of my scope.

**Comment by Sesquipedalian** [comment]
> either way if it is kept permission based the option should not show in the profile if you dont have permission to use it.

This is the right solution.

**Comment by SychO9** [comment]
I don't think there is anything to fix here,

If you disable drafts, the option in the look and layout page is hidden, we can't hide it when the user doesn't have permission, because the permission is board based, the other permission which isn't board based is for PM drafts only. So there's nothing to do about this.

The only issue I did notice was if you disable [**Enable the selection of drafts from the posting screen**] but the user has already enabled it in their options, it will still show for them even though the admin completely disabled it)
