### ISSUE TITLE
Undefined index:

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#4895]
The new Smiley code is causing an "Undefined index: " error on every page load.

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs.php#L2872

It seems that $matches[1] isn't defined.

**Comment by albertlast** [comment]
I guess the issue got introduce by the pr #4776

**Comment by frandominguezl** [comment]
Can you post steps to reproduce?

**Comment by sbulen** [comment]
Oldiesmann - did you run the upgrader after loading the latest?

**Comment by wintstar** [comment]
I have updated per upgrade.php to today's pull request and have no error messages in the error log.

**Comment by sbulen** [comment]
I'll look at this more closely after work.  

Running the upgrader is required in this instance, to correct problems in the smiley folder structure & corresponding settings.

**Comment by Oldiesmann** [comment]
I did run upgrade.php after loading the latest files from GitHub. I didn't experience this issue until after I had done so.

**Comment by sbulen** [comment]
I can't duplicate this.   I am, however, having pretty serious issues running the upgrader on a large forum.  It won't run to completion.  Will log a new issue for that.  

Oldiesmann, a couple questions:

- What folders do you see under your Smileys folder?
- How big is this forum?   Did the upgrader run to completion?
- What is the default smiley set?
- Can you change the default smiley set?

**Comment by sbulen** [comment]
I have confirmed that you get those exact symptoms if the upgrader does not run to completion & the folders were not cleaned up (per #4776).  

Symptoms should go away if you select a different smiley set or if the upgrader completes successfully.  There are currently problems with the upgrader completing successfully (#4896).

**Comment by Oldiesmann** [comment]
Something must have gone wrong during the upgrade... I ran it from the shell (``php upgrade.php``), so it did run to completion.

To answer the questions in your previous comment:
* The only folder under the Smileys folder is alienine
* The forum is very small since it's just a test board. 5 posts, 1 topic, 4 members
* The default smiley set is fugue, but the errors did go away when I changed to alienine (though this is labeled as "Akhyne's set" rather than Alienine's)

**Comment by sbulen** [comment]
These symptoms are from the original issue, eg. settings out of sync with the folder.  I think you'll have to fix those manually.    Don't know why you don't have a fugue folder - a new copy will get you that.

**Comment by sbulen** [comment]
The misalignment in folder/set name was caused by a prior upgrade - see #4773.  You'll see identical issues there.  Further complicating, it appears the new Smileys folders weren't copied over as part of your upgrade.  

To fix, I would:  
 - Empty smiley_sets_known & smiley_sets_names fields in the settings table
 - Delete the old smiley sets folders
 - Copy the new smiley sets folders from the 2.1 code tree (make sure they have .pngs in them!)
 - Rerun the upgrade to reset the settings table entries

Or just reinstall.

**Comment by jdarwood007** [comment]
Can we ensure that this doesn't occur for other upgrades?  Any way to fix it from the upgrader?

**Comment by sbulen** [comment]
Two problems here...

(1) I believe that root cause of the undefined index issue above is the fact that the new fugue folder wasn't copied over prior to upgrade.  It's not there at all, & the upgrader wasn't expecting that (...and set the default to fugue).  

We could theoretically make it smarter & not use 'fugue' if the folder doesn't exist.  But...  Set it to what then?  First folder found?  My thinking here is that not copying the new smiley folders over is a broken upgrade.  I think it should be fair to assume fugue will be there.  

(2)  Mis-mapping the name & folder (Akhyne to Alienine) was done at some point in the past.  I was concerned about 2.0 custom smiley sets, & did not want to make assumptions about what is wrong vs right and overwrite any existing mappings.  

A PR could be made to hard-code all 2.0 & 2.1 default smileyset folder names.   I.e., throw out suspicious associations, e.g., the akhyne to alienine association.  The benefit there would be specifically for beta-to-beta upgrades for folks like Oldiesmann who had their settings corrupted by the prior problem.

**Comment by Oldiesmann** [comment]
Doing a git pull got me the Fugue set again and all is well after clearing smiley_sets_known and smiley_sets_names then running upgrade.php again.

**Comment by sbulen** [comment]
Thanks @Oldiesmann .   

@jdarwood007 - I did take a quick stab at a smarter version that tries to repair issues with the smiley settings, at least for the 2.0 & 2.1 default sets.  Yes, it will even default to the first one if fugue ain't around.  

I'll test over the next couple of days.  It would look something like this:
https://github.com/sbulen/SMF2.1/commit/6ed3b16b9563f76f6aac54f6c270d468f714a1e6
