### ISSUE TITLE
[suggestion] Minor Alerts & Messages Suggestion

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#4950]
While browsing I noticed that when I receive a notification, I find myself clicking on the member's link instead of the reply to the topic/post itself (or other kinds on alerts such as reports) 

I'm thinking either having the first link be the important one, or have the entire box of each item take to the subject notified about, I do believe small details like this matter and make a difference.

**Comment by Gwenwyfar** [comment]
Making the whole area take to the subject sounds good. I also noticed some kinds of notifications don't have any link other than a profile link.

Do you want to do it?

**Comment by SychO9** [comment]
Sure, I'll do so & post an PR as soon as my current PR is closed (whether it be merged or not)
cause I didn't branch (stupid I know, was my first time, I know my way around now, literally took a git course)

**Comment by Gwenwyfar** [comment]
Alright :)

hehe, beginner's mistake, I did the same. You get used to it xD

**Comment by SychO9** [comment]
I'm unable to produce a calendar event alert, can anyone check if they can ?

**Comment by MissAllSunday** [comment]
I would be against this change since on my mods I add more stuff in the notification than a simple link, if the whole area gets converted to a link, mods won't be able to emit this kind of more robust notifications.

**Comment by Gwenwyfar** [comment]
I'm sorry but I think good default behavior is more important than how it will affect mods. As it stands you need to manually find links to many notifications and that's far from ideal. You can always just change your mod to work with this (and if possible this can be made in a way easy to change).

Or maybe another way this could be done is change the avatar to a user link, and make a good portion of the main message link to the subject (the first phrase on most of them), removing user links there.

**Comment by SychO9** [comment]
making this does require a lot of additional code in the fetch_alerts() function and Alerts language file since that's where most of the links which have to be removed for this are, but I don't think It's a problem for mods, 
Why trying to do this I had to add a condition to either use a global link or not, because the alerts list in the profile section needs those links contrary to the dynamic alert box, 
So the way I see it, mod creators can add a bool variable to the "extra" array, say globalLink for example, and tests are made to determine if that one alert will use a global link or not

Otherwise I suppose @Gwenwyfar last suggestion is better than nothing.

**Comment by MissAllSunday** [comment]
Yeah... the point is, notifications aren't limited to a single action, just because SMF doesn't do this by default (It should BTW) doesn't mean the notification feature needs to be limited.

A lot of effort has been put to make the notification system as extensible and customizable as possible, limiting the actual notification to a single link kinda defeats this purpose.

**Comment by SychO9** [comment]
if the main purpose is to have many links, then I guess it is what it is, 
I only tried to look at this from a simple user's perspective, cause I personally find it inconvenient this way, but I guess it's just a matter of getting used to it.

**Comment by Gwenwyfar** [comment]
The main purpose of a notification shouldn't be about multiple links, but the main subject (to know about it, use it, go to it). Anything else is an extra. While the extras is nice to have, the main function should work well.

So making a more usable link for it is the minimum we should do (and add one where there isn't any at all).

@MissAllSunday what do you think about the idea of being able to just change the format easily (with a bool or otherwise)?

**Comment by MissAllSunday** [comment]
Sure, a way to specify what kind of notification you want to show would be great.
