### ISSUE TITLE
moderation center latest news

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#505]
why do moderators need to know the latest news from smf? i think it would be more useful to add a block for unapproved posts/attachments instead, or even membership requests for those that can approve the requests

**Comment by Oldiesmann** [comment]
I don't see a problem with leaving it there. You can turn it off in the mod center settings if you don't want to see it.

**Comment by illori** [comment]
right you can turn it off but why does a moderator need that information? if it is to be left why not add the unapproved posts/attachments as an option? [membergroup requests exists already]

**Comment by jdarwood007** [comment]
Seems like something that might have been a oversight, or possibly it was too complex to pull what boards that user could moderate and show unapproved posts/attachments at the time.

**Comment by Arantor** [comment]
The only argument I can make for it being there is that an admin is (marginally) more likely to notice it than being in the admin panel, purely because I'd assume an admin will see the moderation panel more frequently.

Personally, I'd rather turn on moderator notes by default and have that in place of the current news.

Anyone got any objections to doing that? Seems to me like the moderation notes will be more useful for more admins than not.

**Comment by illori** [comment]
sounds good to me, while you are at it maybe taking a look at http://www.simplemachines.org/community/index.php?topic=511645.0 ?

**Comment by Oldiesmann** [comment]
I don't have any objections to that either. Sounds good to me.

**Comment by Arantor** [comment]
See also the comments in http://www.simplemachines.org/community/index.php?topic=511645.msg3616106#msg3616106 namely making the moderator notes on permanently (not just on by default) and giving it the ability to take up full width rather than half width, to give it room to display times.
