### ISSUE TITLE
Memberlist empty $request['sa']

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#5051]
#### Description
$request['sa'] is undefined here:
https://github.com/SimpleMachines/SMF2.1/blob/af31e402a6d5172304dae403b8268ebd8ccff75d/Sources/ManageMembers.php#L131-L136

sm.org: https://www.simplemachines.org/community/index.php?topic=562617.0

The Code line very old so i guess the issue came from a different newer on,
see below.

### Steps to reproduce
1.  admin
2.  members

### Environment (complete as necessary)
- Version/Git revision: newest
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references
Error message: 8: Undefined index: sa

    #0: smf_error_handler()
    Called from F:\github\SMF2.1\Sources\ManageMembers.php on line 136
    #1: ViewMemberlist()
    Called from F:\github\SMF2.1\Sources\Subs.php on line 4966
    #2: call_helper()
    Called from F:\github\SMF2.1\Sources\ManageMembers.php on line 119
    #3: ViewMembers()
    Called from F:\github\SMF2.1\Sources\Admin.php on line 497
    #4: AdminMain()
    Called from F:\github\SMF2.1\index.php on line 150

Possible introduce by pr #4995 by @jdarwood007 i guess

**Comment by Sesquipedalian** [comment]
We should just remove [line 136](https://github.com/SimpleMachines/SMF2.1/blob/af31e402a6d5172304dae403b8268ebd8ccff75d/Sources/ManageMembers.php#L136) and then replace `$context['current_subaction']` with `$context['sub_action']` in [line 41](https://github.com/SimpleMachines/SMF2.1/blob/af31e402a6d5172304dae403b8268ebd8ccff75d/Sources/ManageMembers.php#L41) and everywhere else in that file.

While we are at it, we should also move [line 41](https://github.com/SimpleMachines/SMF2.1/blob/af31e402a6d5172304dae403b8268ebd8ccff75d/Sources/ManageMembers.php#L41) down to a point immediately after [line 103](https://github.com/SimpleMachines/SMF2.1/blob/af31e402a6d5172304dae403b8268ebd8ccff75d/Sources/ManageMembers.php#L103) in order to avoid other potential problems.
