### ISSUE TITLE
"Minimize CSS and JavaScript files" add very high page creation time and loading time

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#5067]
#### Description
When the option is enabled page creation get doubled or more.

Question should be this realy be default enabled?

Should be the help text warn about the issue of higher page creation time?
### Steps to reproduce
1. Admin
2. Gereral setting

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

For $reason i got actualy a unstable/small internet connection
with minimized the page loading (measured by ff) 3.84 sec
without minimized page loading takes 1.92 sec

**Comment by MissAllSunday** [comment]
By design yes, when the files are generated theres a lag in page creation since the files are actually being generated, however, this should only happen once every time they are created.

Theres also a browser lag since it has to download the new files but again this should only happen once.

Yeah,  the help page should indicate this clearly.

**Comment by albertlast** [comment]
Look like that this run everytime.

**Comment by Sesquipedalian** [comment]
Perhaps instead of waiting for the minimized files to be generated, we could assign that to a background process and send the unminimized files in the meantime.

**Comment by MissAllSunday** [comment]
The issue with sending it to a background task is that it might get triggered by an user  or, since it depends on users hitting the server, it might take too long to run that process and the admin might get confused as to why nothing happens.

I prefer to let the admin know about the lag as well as preferring to be the admin the one who will "suffer" the lag.

**Comment by albertlast** [comment]
So could we change the default setting for this feature to be off?
I don't want to take out this feature only that the default value,
when you setup smf 2.1 that this feature is disabled.

**Comment by albertlast** [comment]
Enabled:
![grafik](https://user-images.githubusercontent.com/1782906/47606703-21255d80-da17-11e8-97b3-01f781708cb0.png)

Disabled:
![grafik](https://user-images.githubusercontent.com/1782906/47606694-094dd980-da17-11e8-9063-dd51533edff1.png)

I disabled for this test cronjob.

**Comment by MissAllSunday** [comment]
Thanks.

So the minimized files aren't the ones being taking too long to respond, they actually take the about same amount of time vs a non-minimized and browser cached file which is the intended behavior (loading time should be faster after the browser caches the minimized files).

The REAL issue is in the request to index.php, which takes a significant amount of time, again this is the intended behavior when the minimized files are being created and should only happens once.

If you say that ALL your request are taking this long to create then it only means the minimized files are being generated on each request, THIS is the real issue and it is what needs to be fixed.

A simple way to verify this is to enable the feature, do some hard-refresh (Ctrl + F5) and take a look at the minimized files names, if they are different, IE they have a different salt after the minified_ part then it means your setup is generating them on each request, that or just go to your css folder and you should see a bunch of minimized files.

A vague guest would be you don't have any forum cache enable or something else is telling the minimized to create them on each request, either way, this setting should be completely separated from the forum's cache system or add some other (better) ways to detect a minimized file.


As for the feature being disabled by default, I propose adding a call to this process on upgrading, the upgrade process already takes some time so adding the lad this causes shouldn't be an issue.

**Comment by albertlast** [comment]
when you enable minimized files, you notice on every call the page creation time takes longer,
in comparsion to the disabled version.

You see based on the text color and "Übertragung" col that the minimized files got not cached on browser side,
so they get transed everytime.
The result is when you enable minimized you transfer 316kb and
when you disable minimized the call transfer 253kb (because of cached filed).

when you look at actual status of the minimized implementation:
it take more cpu
it take more page creation
it create a longer page loading
the page size get higher
--> complet useless

**Comment by MissAllSunday** [comment]
Yes.... I already understood that part, no need to repeat it anymore. Thats NOT the REAL issue. Its just a side effect.

Now, if you care to answer some simple questions that would be great:

- Do you use any forum cache type and if so, which one.
- Which browser are you using?
- Does this happens on other browsers?
- Does the minimized files ever get cached by your browser?
- Did you did a compare on the minimized files and see if their names are different every time you do a hard-refresh?
- Do you have more than once minimized files in your css and js folders?

Please answer each and everyone of the questions.

**Comment by albertlast** [comment]
nope
ff
yes
the http header of the cache forced not be cached (based on the reaction of the browser)
they are the same always
three js and three css in total 6 files

**Comment by Sesquipedalian** [comment]
> Do you use any forum cache type and if so, which one.

> nope

That's the issue. If there is no cache enabled, then [this chunk](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs.php#L3914-L3924) of code will always conclude that we need to make new minimized files. We could probably fix this by adding a fallback to check if the file exists on disk when no cache is enabled.

**Comment by albertlast** [comment]
Or disable the minimized when cache not avaible.
Some cache solution like the default file cache smf does hurt smf more as it help.

Any way the actual logic make no sense like you mention,
a function which is actualy default enabled got a dependency to a function which is default disabled and
can only activated after install.
