### ISSUE TITLE
Naming consistency

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#5122]
We have multiple names (variables, css classes and so on) that have sneaked in as camelcase or other format. These should be changed to match everything else.

Note: This doesn't apply to some widely used ones by mod/theme authors that were brought over from 2.0, like $modSettings. It would probably cause too much confusion to rename those now.

**Comment by Sesquipedalian** [comment]
If you can put together a PR addressing this in time to include it in RC1, go for it. But once RC1 goes out, I won't want to change them unless absolutely necessary for some reason. Most mod and theme authors have been waiting for RC1 so that they can use it as a base on which to develop their code. If we were to change a bunch of variable and function names after that, they would have legitimate reason to be annoyed by that.

**Comment by Gwenwyfar** [comment]
Fair enough. I'll add what I can do until then to the formatting PR (#5125), which would also be good to merge before RC1 as it might alter some install calls for mods.

I already have a few css ones done, I'm keeping a list of changes so anyone that has been following up the beta doesn't get confused.
