### ISSUE TITLE
Do not embed external libraries into SMF files

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#5136]
We really shouldn't be adding/embedding external libraries into SMF files. Doing it just calls for a maintaniance nightmare.

I'm talking about: https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Compat.php#L461 I prefer to use composer for managing ext libraries we might user but we're too far into an RC release to do that besides, we already add ext librarie son their own folder inside Sources so we should add random_compat() inside its own folder too, not the best way to handle ext libraries but its still better than hardcoding it into SMF files.

**Comment by albertlast** [comment]
Since you only pro point is "i like",
let spice up this issue with some more con points:

* Composer doesn't work well with windows
* Debugging of issue get more complex because we don't know which lib version the user got
* build process get more complex
* Contributer how do a small amount of pr, are already overwhelmed by singed of and don't add wrong end of file char and now get the composer work would be another barrier for them

Many pain point and nothing gains -> i don't liked

**Comment by MissAllSunday** [comment]
>but we're too far into an RC release to do that besides, we already add ext librarie son their own folder inside Sources so we should add random_compat() inside its own folder too

Lets add some reading into that spices ;)

**Comment by albertlast** [comment]
And how would this change/affect the cons? (i notice this part already in the first reading)

**Comment by jdarwood007** [comment]
I suggested we embed it as it seems to me this library shouldn't need updated often enough to warrant its own files.  It should also not be needed for php7 sites, which I suspect are becoming way more common place.  The combat file can handle this nicely.

**Comment by Sesquipedalian** [comment]
I can see the argument, @jdarwood007. Heck, I even took the time to edit and compile all the functions from the random_compat library into a single block of code so that we could do that. But on further consideration, I think @MissAllSunday is correct. It will be easier in the long term if we simply drop the library into the Source directory and use it that way.

**Comment by MissAllSunday** [comment]
I know PHP 7 is here and 7.2 is around the corner but as we recently discovered with SMF 1.1, users do tend to just keep using whatever it works for them so I foresee a lot of users still using 5.x PHP versions as long as their host allow them to use those versions.

**Comment by albertlast** [comment]
For this they can keep using 1.1 or can upgrade to 2.0,
so nothing what the 2.1 setup should care about.

**Comment by MissAllSunday** [comment]
The SMF 1.1 mention is just a reference... we still have a significant amount of 1.1 installations, I used that as reference to make a point about users still using PHP 5.x
