### ISSUE TITLE
Can't create tables with prefix indexes using $smcFunc

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#5137]
#### Description
$smcFunc provides a DB agnostic way to create tables. Unfortunately one of the things it can't do (at least in MySQL) is provide for prefix indexes, e.g. a column of VARCHAR(255) with a (non-unique) index over the first 15 characters, e.g. for email addresses where 15 characters will usually give you enough of an index to be useful without being too big.

### Steps to reproduce
When calling $smcFunc['db_create_table'] there is a parameter for indexes which accepts them in SMF's usual format - an array with columns and type entries. There's no real filtering here so you could conceivably define an index based on `array('email(15)')` for example.

But this would trip up later on because this will be concatenated into the new name of index which won't support the (15) without being appropriately quoted. (And even though it would be supported by quoting, not sure I'd suggest encouraging that anyway.)

### Environment (complete as necessary)
- Version/Git revision: cfce05c
- Database Type: MySQL, probably Postgres too
- Database Version: n/a (MySQL 5.x, 8.x both have the same related rules)
- PHP Version: n/a

### Additional information/references

**Comment by albertlast** [comment]
Thanks for introduce to me a new topic,
reason why i like this project.

I read something about this https://stackoverflow.com/questions/31526618/mysql-prefix-index-vs-index/31529672#31529672 and
ask guys how had more knowledg as me about this topic.

From pg side this would be a function index (you can in pg create a index for "any" function call).
Downside is, since this is a function call you need a function on you sql query like
``substr(col,1,10) like ('asdf%)``
beside this the guys mention that the field is to small in general that the prefix index make sense,
addiontional like you see in stackoverflow comment the prefix index got limitation about order,
index only scan etc.

So instead of using a prefix index a normal index would be for the case of a email addresse the right call,
since they say 255 varchar field is to small for a prefix index.

In my personal eyes is the not supported index only scan a big draw back,
a ``select email from smf_members where email like 'asdf%'`` would be cheaper/faster when you got a normal index instead of a prefix index because of possibility to use index only scan.

**Comment by Sesquipedalian** [comment]
Closing because this is not the sort of change that ought to be introduced once we've reached the RC stage.
