### ISSUE TITLE
normal member can see an unapproved message

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#5159]
#### Description
Hi,

member (not moderator, not permission)
can see an unapproved message
only in his own topic

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by live627** [comment]
Is it their own message?

**Comment by SychO9** [comment]
Own topic, not own post

**Comment by SychO9** [comment]
Before anything is done about this, you should know it is intended behavior and not a bug
See more here #2841

**Comment by albertlast** [comment]
So it's a bug or a feature?  @Sesquipedalian

**Comment by Sesquipedalian** [comment]
Thanks, @SychO9. I will take a look at that in order to see what changes were made and why. I don't think the behaviour described in this report is what ought to happen. Non-moderators should never be able to see unapproved posts of other members. If this was the intended effect of the changes in that PR, we'll need to reverse them. If this is an unintended effect, we'll need to fix it.

**Comment by SychO9** [comment]
Well to save you even more time
https://github.com/SimpleMachines/SMF2.1/blob/29f7e16d1c69c62f709c8ba3b5e1e35c19dcf3ca/Sources/Display.php#L202-L203

**Comment by Sesquipedalian** [comment]
Ugh. It seems that there have been a number of incomplete attempts to fix issues with unapproved messages and unapproved topics, with the result that all of this logic has become quite convoluted.
