### ISSUE TITLE
User Likes Count

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5161]
Nowhere do I see an option to show the user's number of received likes on topic view, nor is it shown on the user's profile, or his stats page, I think this needs to be added. Or did I perhaps not see where the setting is ?

**Comment by Oldiesmann** [comment]
I'm guessing that's something that got overlooked. @Arantor are we missing something?

**Comment by illori** [comment]
the likes are not per person, they are related to a post by default.

**Comment by smfbigguy** [comment]
There should still be a way to show that though...

**Comment by illori** [comment]
since the likes are not based on users but the content they post, i dont see how you can.

**Comment by smfbigguy** [comment]
Could you not show a page to members of their most liked posts. ???

**Comment by illori** [comment]
to me sounds like a lot of work for little output. also on large forums could put a lot of load on it. honestly i think this should be mod material and not in the core.

**Comment by Arantor** [comment]
I very consciously didn’t add it originally because otherwise it does the same thing karma does: disproportionately favours cliques and not good content.

It’s also not super cheap to calculate so bad idea to put on topic view (and caching doesn’t help because it’s a potentially fluid number)

**Comment by albertlast** [comment]
We talk yesterday about this in the irc,
result is that the database design is not designed to support this.

**Comment by smfbigguy** [comment]
Those all sound like good reasons to me. :)

**Comment by Arantor** [comment]
> We talk yesterday about this in the irc,
> result is that the database design is not designed to support this.

I know, right?

**Comment by albertlast** [comment]
Arantor maybe your are not used to, but i supported you here.

**Comment by illori** [comment]
i am going ahead and closing this. if a dev feels otherwise they can reopen.

**Comment by Arantor** [comment]
> Arantor maybe your are not used to, but i supported you here.

I know! My point was that the design may have been intentional on some level 😉

**Comment by vort7u** [comment]
Hi everyone, since we can see the likes in the statistics 
![like](https://user-images.githubusercontent.com/1554203/50602272-32776400-0eb7-11e9-980e-2de3ead56f1a.jpg)

Could not be added only in the user profile?
In this way it does not weigh too much and is easy to add.
![like2](https://user-images.githubusercontent.com/1554203/50602246-1ecbfd80-0eb7-11e9-9640-8c1101b5c3cc.png)

Thanks

**Comment by Gwenwyfar** [comment]
It seems to me it should not be in the statistics instead...

**Comment by vort7u** [comment]
Why not?
If the counter does not even put in the statistics page "Like" really makes little sense to exist...

**Comment by Gwenwyfar** [comment]
Likes was not meant to be a contest of "who has more likes", which is what this is bound to become. It doesn't do any good to a community and is not something we should have as default. 

Having a total in your own profile on the other hand wouldn't be too bad because you'd need users to openly share it to know who has what, and would involve trusting someone is not joking/lying about their numbers. Could still happen in some communities but it would not really be forced by the system.

**Comment by Arantor** [comment]
On the contrary, global is much easier to calculate than a single user’s likes. MUCH easier for the server.

In any case, likes are about promoting the content, not about promoting the user (which is what karma always had the effect of doing, which is why I removed it and replaced it with likes)

**Comment by Gwenwyfar** [comment]
Exactly. And having a leaderboard for it does exactly that...
