### ISSUE TITLE
mentions of old themes in upgrade

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#518]
in upgrade_1-1.sql there are mentions of core and babylon themes, these are no longer included with 2.1, should those lines be removed?

in upgrade_2-0_mysql.sql there are lines talking about core and curve theme, should those be removed? these are also in the other 2-0 upgrade files.

**Comment by ghost** [comment]
I think there is a bigger issue here, there shouldn't be specific lines for certain themes, there should be a abstract method of checking what themes exist on an install instead of looking for specific ones and then doing the relevant updates as some installs will still have the older themes if they came from an old version of SMF and they could still use it other installs will have gotten rid of those themes a long time ago..

**Comment by Arantor** [comment]
I have no idea why the installer so much as bothers; no theme from 1.1.x is going to work properly on 2.0, no 2.0 theme is going to work entirely properly on 2.1.
