### ISSUE TITLE
JavaScript error: new_replies is not defined

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#5200]
### Steps to reproduce
1. Preview a post (new topic or reply to existing one)
2. Check the console in your browser's development tools (CTRL+SHIFT+I on Chrome)

```
Uncaught ReferenceError: new_replies is not defined
    at smc_preview_post.onDocSent (script.js?beta21:1835)
    at Object.success (script.js?beta21:90)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at A (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
```
Relevant code:
```js
	// Remove the new image from old-new replies!
	for (i = 0; i < new_replies.length; i++)
		document.getElementById(this.opts.sNewImageContainerID.replace('%ID%', new_replies[i])).style.display = 'none';
```

### Additional information/references
This code is meant to remove the "new" icon from any new replies made while you're posting, but new_replies is never defined anywhere.

**Comment by frandominguezl** [comment]
I'm not much into JavaScript. It outputs an error because new_replies is defined as a new Array right below the for loop, which doesn't makes too much sense. A solution would be to declare the array before the loop, but then it will iterate over an empty array.

If we have a look at:
https://github.com/SimpleMachines/SMF2.1/blob/29559c8787971aeff5779da79ce2efedde004a6b/Themes/default/scripts/script.js#L1848

Makes more sense to define the array inside that if condition, change that line to:
`new_replies[i] = newPosts[i].getAttribute("id");`

And then call the for loop right after that one. Something like this:

```
if (numNewPosts != 0)
	{
		var newPostsHTML = '<span id="new_replies"><' + '/span>';
		var tempHTML;
		var new_replies = new Array();
		for (var i = 0; i < numNewPosts; i++)
		{
			new_replies[i] = newPosts[i].getAttribute("id");

			ignoring = false;
			if (newPosts[i].getElementsByTagName("is_ignored")[0].firstChild.nodeValue != 0)
				ignored_replies[ignored_replies.length] = ignoring = newPosts[i].getAttribute("id");

tempHTML = this.opts.newPostsTemplate.replaceAll('%PostID%', newPosts[i].getAttribute("id")).replaceAll('%PosterName%', newPosts[i].getElementsByTagName("poster")[0].firstChild.nodeValue).replaceAll('%PostTime%', newPosts[i].getElementsByTagName("time")[0].firstChild.nodeValue).replaceAll('%PostBody%', newPosts[i].getElementsByTagName("message")[0].firstChild.nodeValue).replaceAll('%IgnoredStyle%', ignoring ?  'display: none' : '');

			newPostsHTML += tempHTML;
		}

		// Remove the new image from old-new replies!
		for (i = 0; i < new_replies.length; i++)
		{
			document.getElementById(this.opts.sNewImageContainerID.replace('%ID%', new_replies[i])).style.display = 'none';
		}

		setOuterHTML(document.getElementById('new_replies'), newPostsHTML);
	}
```

I'm not sure how to test this but the logic makes sense. Previous logic was senseless since you'll always be iterating over and empty array.
