### ISSUE TITLE
Float does not work properly on board description

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#5271]
#### Description
As I understand how this works, you should be able to add/remove tags to `$context['description_allowed_tags']`, however it seems float is being processed differently than other tags I tested. 

I haven't seen if there are others that do the same, but if you allow it, and use [float] in the description, upon saving the tag will be removed from the description text, and float code will be added both to the description and the title. 

### Steps to reproduce
1. Add float to allowed list of bbc, then save any board description with float in it.

**Comment by SychO9** [comment]
Actually, the problem here is that the description is inside a **P** tag, and the float converts to an html **DIV** tag, and <div tags can't go inside <p tags, so things go wild.

**Comment by Gwenwyfar** [comment]
Hmm. Maybe it should be a span instead due to nesting possibilities then. But something is still awry with how it applies it. Also, tags that are not allowed are not removed from the description as happens here.

**Comment by SychO9** [comment]
> But something is still awry with how it applies it

hmm you're right, I just noticed while trying to edit the description that the float bbcode was gone (even though it's set as allowed)

> Also, tags that are not allowed are not removed from the description as happens here.

well if they're not allowed, they're just interpreted as normal text so I don't think they should be removed, just not parsed

However we definitely need to change the description to a div element instead of paragraph, just tested a bunch of allowed bbc and it's gone really wild.

**Comment by Gwenwyfar** [comment]
There's at least three (or more) issues here then.

1 - Description should be a div (we also allow divs in the description so there's that too)
2 - Float should be a span
3 - Float bbc gets edited out of the description
4 - Float bbc is applied twice where it shouldn't

**Comment by SychO9** [comment]
> 4 - Float bbc is applied twice where it shouldn't

if by twice you mean it going in the title & the description, this commit of PR #5003 fixes that
https://github.com/SimpleMachines/SMF2.1/pull/5003/commits/8101d65cc8eb9e7d9642c22f8595f3fc42b0b8ce

**Comment by Sesquipedalian** [comment]
>1 - Description should be a div (we also allow divs in the description so there's that too)

Yes. The same can be said of quite a few other places cases a `<p>` appears in our templates. Not only can using `<p>` in such cases introduce problems like this, but moreover in most of them `<p>` is semantically incorrect.

>2 - Float should be a span

No. Floats can contain other block level elements, so that's not an option.

**Comment by Gwenwyfar** [comment]
2 - Ah yes, you're right. I'm slow today :P

**Comment by Sesquipedalian** [comment]
No worries. That's why we help each other out, right?
