### ISSUE TITLE
Christmas (and other holidays) don't show up in the calendar (fresh install)

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#5282]
#### Description
Christmas and other annual holidays are defined in the database in a default install - but they don't show up on the calendar.

![image](https://user-images.githubusercontent.com/1156911/50427492-b7ec8a00-08a1-11e9-9e1b-98a028919d85.png)

![image](https://user-images.githubusercontent.com/1156911/50427495-c470e280-08a1-11e9-9f91-9e3391353b96.png)

They still have a year 4 in them as far as I can see, rather than the new default of 1004. If added via the admin panel, they correctly get the year of 1004 and thus show up as 'every year' as they should.

**Comment by albertlast** [comment]
To fixing an mysql issue all event got moved from year 0004 to 1004.
But this changed look like was to forgotten also update the sql stuff for holydays.

@frandominguez03  since you already touche the table with you pr,
could you please 0004 entries and move them to 1004 and
update the upgrade in this direction too (don't forget to extend the delete command).
