### ISSUE TITLE
Upgrader should show warning, not error, when the server is slow to respond

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#5303]
#### Description
When the server is slow to respond, the upgrader currently shows an .errorbox message, like this:

![](https://i.imgur.com/nLS1VVV.jpg)

We should probably show a .noticebox message instead, since this isn't an error.

### Steps to reproduce
1. Run the upgrader on a really show server.
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by sbulen** [comment]
I'm not sure we know in advance if it's coming back or not...

I only see that message upon total failure; if I see it, it ain't coming back.  Even on my old pc.

**Comment by Sesquipedalian** [comment]
But even if it doesn't come back, that's not an error per se. Nothing actually went wrong in the upgrade process; it just stalled. That's why we show a link to manually continue.

**Comment by sbulen** [comment]
Due in part to the indirect way the ".sql" files are invoked, in chunks, with code being eval'd and many errors deliberately ignored, the truth is that errors arent trapped well at all during the database updates.  

"Pauses" are indistinguishable from errors. 
 Even parse errors.

I've never seen that continue button work...   It just attempts to restart the current step, and freezes in the same spot again.  Guess what happens when you do the same thing?  You get the same result...

I'm not so sure there is a way to enhance it to distinguish real errors/aborts from slowness.  

We might get clever and increase the execution intervals on slower systems...   That might achieve the desired result...

**Comment by Sesquipedalian** [comment]
Fair point.
