### ISSUE TITLE
Most liked messages display empty rows

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#5313]
If you don't have enough liked messages to fill the top 10 in the stats page, it picks multiple messages with a value of "0".

**Comment by albertlast** [comment]
Sounds correct to me.

**Comment by live627** [comment]
uhh that's correct? Shouldn't it skip those?

**Comment by albertlast** [comment]
Why should it?
I mean the point is known as "Top 10" when you skip it's more liky that you don' t show 10 entries.

**Comment by live627** [comment]
do all other "top ten" blocks not skip rows when the value is zero?

**Comment by albertlast** [comment]
Look like so:
![grafik](https://user-images.githubusercontent.com/1782906/50629327-60eb5280-0f3c-11e9-96f1-218459ed9f80.png)

![grafik](https://user-images.githubusercontent.com/1782906/50629315-5335cd00-0f3c-11e9-84d8-86ff1f199ad0.png)

**Comment by albertlast** [comment]
Conclusion:
- Posters, Topic Starter, Liked users don't show 0 values
- Boards, Topics, Replies, Time Online, likes messages, view show 0 values

5 vs 3 -> the most show 0 values

**Comment by Gwenwyfar** [comment]
Then it's all those 5 that should be fixed.

**Comment by albertlast** [comment]
Since it create a very dynamic height,
which create a disturbing view.

So for me are the 5 rights.

The likes user static is by the way wrong,
I guess and should be removed.


________________________________
Von: Gwenwyfar <notifications@github.com>
Gesendet: Donnerstag, 3. Januar 2019 12:52
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] Most liked messages display empty rows (#5313)


Then it's all those 5 that should be fixed.

**Comment by Gwenwyfar** [comment]
The height can be uneven by other factors as well, it doesn't make much difference. I don't think we should display irrelevant information.

> The likes user static is by the way wrong, I guess and should be removed.

I agree on that. Also because it will become a leaderboard to see who has more likes. Not a good thing to have as default. Let people add that as a mod if they really want to.
