### ISSUE TITLE
After installing the new 2.1 forum, the administrator has an incorrect time

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#5315]
After installing the new forum 2.1 as admin I have an incorrect time after logging in to my account. It should not be like that. Every new user after login in has an automatically placed correct time on the forum. Let anybody fix this mistake.

https://github.com/SimpleMachines/SMF2.1/issues/5309#issuecomment-451245661

**Comment by Arantor** [comment]
Well, fix it in your profile... it’s no different to how you can’t set your avatar or signature during installation (and no, that should not be an option)

Not a bug as far as I’m concerned.

**Comment by jsqx** [comment]
But in SMF 2.0, after installing the forum, the administrator account has the correct time. If the time runs correctly in 2.0 after creating the forum, why can not it work correctly in 2.1. If it can be fixed, let it be repaired, after all it is probably not a big difficult mistake.

**Comment by LexArma** [comment]
It's not necessarily a mistake, the timezones work a bit differently in 2.0 and 2.1

**Comment by Sesquipedalian** [comment]
Bleh, I had a glitch posting a reply here. 

The short version is that this appears to be a user error, not a bug. Nevertheless, thanks for filing a report with us. Even if this one turned out not to be a bug, we still appreciate that you took the time to report a potential issue to us and we will be glad to receive any reports about other issues from you in the future. 🙂
