### ISSUE TITLE
Add new smiley interface should be better

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#5329]
It does not let you know that the "code" field is required, nor that all of the files for each set are required, making you go back to fill it again if you miss any.

It should also not require you to select files for each set manually. There should be some way to make it use the same file for all.

The list of sets in the upload new smiley page is also in the opposite order than the default list of smileys in the main page, which is confusing.

**Comment by sbulen** [comment]
You cannot use the same file for all - your sets may have different extensions.

**Comment by Gwenwyfar** [comment]
I was actually meaning to test this while I found these issues. So we are not allowing different extensions in each set, are we? That is another problem by itself if so.

And either way, even if we are only allowing extensions per set, and all sets are .png, we should allow you to mark it the same for all. #5328 could be related to this because of different extensions in each set.

**Comment by sbulen** [comment]
Some clues as to what is required would definitely help here.  The UI is definitely clunky...  

Adding an 'apply to all with the same ext' flag would be a nice enhancement.  Tricky though, because what if you do have mixed extensions, how would you want the UI to look/behave?  In the meanwhile, it remembers what you last selected, so doing this manually only takes a couple clicks.  It's functional, if clunky, which may be OK for such a low-volume function.  

The one-ext-per-set rule is basically baked in without DB changes, which I don't think we should be considering at this point.

**Comment by sbulen** [comment]
This one might be able to be closed now?
