### ISSUE TITLE
Smiley list doesn't use correct sorting

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#5330]
The first sort type says "Default", but all it does is sort by the IDs. Clicking it does nothing.

**Comment by sbulen** [comment]
All the sort columns sort by the content underneath.   Clicking on "Default" sorts by the default flag, where set > not set, so sorting by "Default" pushes your default set to the bottom.  So sorting by "default" is working.  

What is a little different is that clicking it AGAIN doesn't do the reverse sort, like all the other sort buttons.  I would expect a 2nd press to push the default set to the top.  

EDIT:  It would be a minor change to provide both ASC & DESC sorting to the Default column, which sorts by the "selected as default" flag.  For some reason, it has never had that.

**Comment by sbulen** [comment]
I had been testing on my WAMP server earlier.  Oddly, on my Linux server, the sort is not correct...   So there is something amiss here.

**Comment by Gwenwyfar** [comment]
My default flag is in the middle. It does not change position either way. It is indeed a linux server.

**Comment by Sesquipedalian** [comment]
Once #5342 is merged:

1. The list of smiley sets will sort by "Name" by default, rather than by "Default" by default. (That's a weird sentence to type.)
2. Sorting by "Default" actually will sort by whether the set is the default for the forum or not, rather than by ID.
3. Sorting by ascending or descending will work as expected for the "Default" column.
