### ISSUE TITLE
Improve custom smiley handling & upgrading

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5336]
#### Description
This discussion is spawned from #5331 , where @Gwenwyfar pointed out that multi-extension support exists in 2.0 - but for custom smileys only.  Only the default smileys are stuck on .gif in 2.0.  

And...  Given the current 2.1 design assumes one extension per set, this can pose a problem upon 2.1 upgrade:
![image](https://user-images.githubusercontent.com/23568484/50814245-dc972780-12cd-11e9-80e3-e055ffe6dcfa.png)

In effect, 2.0 operates in a "hybrid" mode, where the default smileys are stuck at .gifs across all sets, but custom smileys can be in other formats, jpg, png, gif, etc.  

### Proposal
Use a "hybrid" approach in 2.1, treating custom & default smileys differently...   Do this by:
 - Stripping extensions for _default smileys only_ throughout the app, including the upgrader
 - Dynamically applying extensions to the _default smileys only_
 - Storing full filenames, _extensions included,_ for custom smileys; the same name & extension must be used across sets

This will be complex, but doable.  

Benefits:
 - Fixes the upgrade bug noted above
 - We can restore the quirky but functional 2.0 "copy this file across sets" function
 - No DB changes needed

### Steps to reproduce the bug above
1. Use a custom smiley with a non-.gif image in a 2.0 environment
2. Upgrade to 2.1

### Additional information/references
_If we agree on this "hybrid" approach, we likely need to revert #5324 , or early RC adopters will lose the extensions on their custom smileys._  

Thoughts, @Sesquipedalian ?

**Comment by Sesquipedalian** [comment]
![](https://media1.tenor.com/images/e87d01bb8fcc8c506a0449dfdc3366a0/tenor.gif?itemid=4613605)

I think I wish everything to do with smilies would just go away so I could release RC1 already...

Anyway, no, I’m afraid I don’t like that plan. We need a single, consistent system to handle all smilies in all sets.

If we were starting from scratch, I’d add a separate table to track every combination of `id_smiley`, `set`, and `extension`, and then use a query to get the right extension for each smiley in the user’s chosen set. But since we are not starting from scratch, here's what I want us to do instead:

1. Get rid of `$modSettings[‘smiley_sets_exts’]` entirely.
2. Add an `extensions` column to the smileys table.
3. For each smiley, populate the `extensions` column with a JSON encoded array identifying the file extension to use for each smiley set. The keys for this array should be the names of the smiley sets as used in `$modSettings[‘smiley_sets_names’]`, and the values should be the file extension for this particular smiley in each of those sets. So for example, this is how the array might look in my local install for one of the smilies:  

```
array(
	'aaron' => '.gif',
	'akyhne' => '.gif',
	'fugue' => '.png',
	'alienine' => '.png',
):
```
4. When retrieving information about smilies from the database, add `extensions` to the list of columns to retrieve, then decode the JSON value and grab the correct extension for the user's selected smiley set.
5. When adding or changing a smiley via the admin area, simply update the `extensions` array with the new info.

Obviously, we'll need to update the UI in the admin area a bit to reflect this change, and we'll need to adjust the installer and upgrader to fit the new method.

**Comment by Gwenwyfar** [comment]
:laughing: Sorry, Sesq, couldn't ignore this one, only noticed from the other bug report ;P

Sesq's solution also seems better for me, for whatever that is worth. 

Thank you both for looking into it :)

**Comment by albertlast** [comment]
From json pov would it not make more sense to save this data in this way:
```
array(
	'aaron' => ['extension' => '.gif'],
	'akyhne' => ['extension' => '.gif'],
	'fugue' => ['extension' => '.png'],
	'alienine' => ['extension' => '.png'],
);
```
json would be then
```
{"aaron":{"extension":".gif"},"akyhne":{"extension":".gif"},"fugue":{"extension":".png"},"alienine":{"extension":".png"}}
```

**Comment by Gwenwyfar** [comment]
Also, since I'm still not completely sure I understand: These changes will allow multiple extensions inside the same set, correct? That's the entire problem here.

**Comment by albertlast** [comment]
no,
it's provice a format which is enable to be extendable.

**Comment by Gwenwyfar** [comment]
May I ask what exactly is the reasoning to do it per set?

Locking sets to a single extension is far too limiting and problematic in many ways. The only reason I'm not personally so bothered is that I'd already be using all pngs with apng, but your average user will use gifs and other formats mixed in, and we can't require them to do otherwise. Just imagine a situation where someone adds an animated gif to an existing default set, for example.

**Comment by Sesquipedalian** [comment]
My proposal would allow multiple extensions in the same set, yes. The smileys table would look like this:

id_smiley|code|filename|extensions|description|smiley_row|smiley_order|hidden
---------|----|--------|----------|-----------|----------|------------|------
1|:)|smiley|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Smiley|0|0|0
2|;)|wink|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Wink|0|1|0
3|:D|cheesy|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Cheesy|0|2|0
4|;D|grin|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Grin|0|3|0
5|>:(|angry|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Angry|0|4|0
6|:(|sad|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Sad|0|5|0
7|:o|shocked|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Shocked|0|6|0
8|8)|cool|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Cool|0|7|0
9|???|huh|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Huh?|0|8|0
10|::)|rolleyes|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Roll Eyes|0|9|0
11|:P|tongue|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Tongue|0|10|0
12|:-[|embarrassed|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Embarrassed|0|11|0
13|:-X|lipsrsealed|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Lips Sealed|0|12|0
14|:-\\ |undecided|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Undecided|0|13|0
15|:-*|kiss|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Kiss|0|14|0
16|:'(|cry|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Cry|0|15|0
17|>:D|evil|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Evil|0|16|1
18|^-^|azn|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Azn|0|17|1
19|O0|afro|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Afro|0|18|1
20|:))|laugh|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Laugh|0|19|1
21|C:-)|police|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Police|0|20|1
22|O:-)|angel|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Angel|0|21|1

If someone decided to replace the standard wink PNG image in the Fugue set with an animated GIF, then the JSON in the extensions column would end up like this:

id_smiley|code|filename|extensions|description|smiley_row|smiley_order|hidden
---------|----|--------|----------|-----------|----------|------------|------
1|:)|smiley|{"aaron":".gif","akyhne":".gif","fugue":".png","alienine":".png"}|Smiley|0|0|0
2|;)|wink|{"aaron":".gif","akyhne":".gif","fugue":".gif","alienine":".png"}|Wink|0|1|0
...|...|...|...|...|...|...|...

**Comment by Sesquipedalian** [comment]
> From json pov would it not make more sense to save this data in this way:
> 
> ```
> array(
> 	'aaron' => ['extension' => '.gif'],
> 	'akyhne' => ['extension' => '.gif'],
> 	'fugue' => ['extension' => '.png'],
> 	'alienine' => ['extension' => '.png'],
> );
> ```
> json would be then
> 
> ```
> {"aaron":{"extension":".gif"},"akyhne":{"extension":".gif"},"fugue":{"extension":".png"},"alienine":{"extension":".png"}}
> ```

I don't think that will be necessary. The data in this column is doing a single job, so I can't imagine any reason to make it extensible.

**Comment by albertlast** [comment]
the datastructur is a nightmare,
the extension column is here very destructiv.

From my eyes the problem is not high enough to keep rc1 holding back more time.

To save more infomation about the smikeys set, like version, date, author etc.

**Comment by Gwenwyfar** [comment]
Oh, alright. Thanks for the explanation.

**Comment by Sesquipedalian** [comment]
> the datastructur is a nightmare,

Oh, I don't like it very much either. As I said in my first comment, "If we were starting from scratch, I’d add a separate table to track every combination of id_smiley, set, and extension, and then use a query to get the right extension for each smiley in the user’s chosen set." But its the eleventh hour and I just want the wretched thing finished.

> From my eyes the problem is not high enough to keep rc1 holding back more time.
 
Unfortunately, anything involving changes to the database structure needs to be settled before RC1.

> To save more infomation about the smikeys set, like version, date, author etc.

That could be interesting information to track somewhere else sometime, I suppose. But that's definitely outside the scope of this issue.

**Comment by albertlast** [comment]
the json which i meantion would be saved into $modSettings[‘smiley_sets_names’]

 
>>From my eyes the problem is not high enough to keep rc1 holding back more time.

>Unfortunately, anything involving changes to the database structure needs to be settled before RC1.

Then drop this feature request.

**Comment by Sesquipedalian** [comment]
This isn't a feature request. This making sure that upgrading to 2.1 doesn't break stuff.

**Comment by Sesquipedalian** [comment]
I'll tell you what, @albertlast. If you want to put together a PR to add a smiley_extensions table like the following to track the data without using JSON, go for it. If we have to make changes to the database to fix this, I suppose inserting a table vs. inserting a column doesn't make that big a difference.

id_smiley|set|extension
---------|---|---------
1|aaron|.gif
1|akyhne|.gif
1|fugue|.png
1|alienine|.png
2|aaron|.gif
2|akyhne|.gif
2|fugue|.png
2|alienine|.png
3|aaron|.gif
3|akyhne|.gif
3|fugue|.png
3|alienine|.png
4|aaron|.gif
4|akyhne|.gif
4|fugue|.png
4|alienine|.png
5|aaron|.gif
5|akyhne|.gif
5|fugue|.png
5|alienine|.png
6|aaron|.gif
6|akyhne|.gif
6|fugue|.png
6|alienine|.png
7|aaron|.gif
7|akyhne|.gif
7|fugue|.png
7|alienine|.png
8|aaron|.gif
8|akyhne|.gif
8|fugue|.png
8|alienine|.png
9|aaron|.gif
9|akyhne|.gif
9|fugue|.png
9|alienine|.png
10|aaron|.gif
10|akyhne|.gif
10|fugue|.png
10|alienine|.png
11|aaron|.gif
11|akyhne|.gif
11|fugue|.png
11|alienine|.png
12|aaron|.gif
12|akyhne|.gif
12|fugue|.png
12|alienine|.png
13|aaron|.gif
13|akyhne|.gif
13|fugue|.png
13|alienine|.png
14|aaron|.gif
14|akyhne|.gif
14|fugue|.png
14|alienine|.png
15|aaron|.gif
15|akyhne|.gif
15|fugue|.png
15|alienine|.png
16|aaron|.gif
16|akyhne|.gif
16|fugue|.png
16|alienine|.png
17|aaron|.gif
17|akyhne|.gif
17|fugue|.png
17|alienine|.png
18|aaron|.gif
18|akyhne|.gif
18|fugue|.png
18|alienine|.png
19|aaron|.gif
19|akyhne|.gif
19|fugue|.png
19|alienine|.png
20|aaron|.gif
20|akyhne|.gif
20|fugue|.png
20|alienine|.png
21|aaron|.gif
21|akyhne|.gif
21|fugue|.png
21|alienine|.png
22|aaron|.gif
22|akyhne|.gif
22|fugue|.png
22|alienine|.png

**Comment by albertlast** [comment]
Sure it's a feature request,
when you look into the 58 smiley sets: https://custom.simplemachines.org/mods/index.php?action=search;type=12
you find none how use more than one exentsion.

**Comment by Sesquipedalian** [comment]
Sorry, but I simply do not have time to argue about this today. If you would like to put together a PR to handle this in a way that you like, @albertlast, feel free to do so. Otherwise, I am going to ask @sbulen to implement the changes I've suggested ASAP. Now I need to go and deal with other pending work.

**Comment by albertlast** [comment]
I will not release any pr because i'm interested to see the rc1 release and
this will not happen when we add every day new stuff.

The table structure without json allow to use index,
so it's better and you don't read the table to insert stuff.

What i don't understand why you guy only try to handle the extension.

 | id_smiley | code | description | smiley_row |smiley_order | hidden
|---|---|---|---|---|---|
| 1 |	:) |  		Smiley 	| 0 	| 0 | 	0| 
|  2 	| ;) 	| 	Wink 	| 0 	| 1|  	0| 
|  3 	| :D 	| Cheesy 	| 0 	| 2 	| 0| 
 | 4 	| ;D 	| Grin 	| 0 	| 3 	| 0| 
 | 5 	| >:( 	| Angry 	| 0 	| 4 	| 0| 
 | 6 	| :( 	| Sad 	| 0 	| 5 	| 0| 
 | 7 	| :o 	| Shocked 	| 0 	| 6 	| 0| 
 | 8 	| 8) 	| Cool 	| 0 	| 7 	| 0| 
 | 9 	| ??? 	| Huh? 	| 0 	| 8 	| 0| 
 | 10 | 	::) 	| Roll Eyes 	| 0 	| 9 	| 0| 
 | 11 | 	:P 	| Tongue 	| 0 	| 10 	| 0| 
 | 12 	| :-[ 	| Embarrassed 	| 0 	| 11 	| 0| 
 | 13 	| :-X 	| Lips Sealed 	| 0 	| 12 	| 0| 
 | 14 	| :-\ 	| Undecided 	| 14|  	13| 0| 
 | 16 	| :'( 	| Cry 	| 0 	| 15 	| 0| 
 | 17 	| >:D 	| Evil 	| 0 	| 16 	| 1| 
 | 18 	| ^-^ 	| Azn 	| 0 	| 17|  	1| 
 | 19 	| O0 	| Afro 	| 0 	| 18 	| 1| 
 | 20 	| :)) 	| Laugh 	| 0 	| 19 	| 1| 
|  21 	| C:-) 	| Police 	| 0 	| 20 | 	1| 
|  22 	| O:-) 	| Angel 	| 0|  	21 	| 1| 



id_smiley | set | filename
-- | -- | --
1 | aaron | smiley.gif
1 | akyhne | smiley.gif
1 | fugue | smiley.png
1 | alienine | smiley.png
2 | aaron | wink.gif
2 | akyhne | wink.gif
2 | fugue | wink.png
2 | alienine | wink.png
3 | aaron | cheesy.gif
3 | akyhne | cheesy.gif
3 | fugue | cheesy.png
3 | alienine | cheesy.png

With filename stuff get so mutch easier.

**Comment by Sesquipedalian** [comment]
... Hm. Actually, @albertlast is right that we don't need to separate the filename from the extension at all. 

That also means that if we go with the JSON method, we can fix this problem without making database changes besides lengthening the allowed number of characters in the `filename` column. Since the filename info for smileys doesn't relate to anything else in other tables and we don't index the `filename` column because we never look smileys up by filename, there's actually very little harm in storing an encoded array in that column. So if we simply do the following, we can have complete flexibility with filenames:

id_smiley|code|filename|description|smiley_row|smiley_order|hidden
---------|----|--------|-----------|----------|------------|------
1|:)|{"aaron":"smiley.gif","akyhne":"smiley.gif","fugue":"smiley.png","alienine":"smiley.png"}|Smiley|0|0|0
2|;)|{"aaron":"wink.gif","akyhne":"wink.gif","fugue":"wink.png","alienine":"wink.png"}|Wink|0|1|0
3|:D|{"aaron":"cheesy.gif","akyhne":"cheesy.gif","fugue":"cheesy.png","alienine":"cheesy.png"}|Cheesy|0|2|0
4|;D|{"aaron":"grin.gif","akyhne":"grin.gif","fugue":"grin.png","alienine":"grin.png"}|Grin|0|3|0
5|>:(|{"aaron":"angry.gif","akyhne":"angry.gif","fugue":"angry.png","alienine":"angry.png"}|Angry|0|4|0
6|:(|{"aaron":"sad.gif","akyhne":"sad.gif","fugue":"sad.png","alienine":"sad.png"}|Sad|0|5|0
7|:o|{"aaron":"shocked.gif","akyhne":"shocked.gif","fugue":"shocked.png","alienine":"shocked.png"}|Shocked|0|6|0
8|8)|{"aaron":"cool.gif","akyhne":"cool.gif","fugue":"cool.png","alienine":"cool.png"}|Cool|0|7|0
9|???|{"aaron":"huh.gif","akyhne":"huh.gif","fugue":"huh.png","alienine":"huh.png"}|Huh?|0|8|0
10|::)|{"aaron":"rolleyes.gif","akyhne":"rolleyes.gif","fugue":"rolleyes.png","alienine":"rolleyes.png"}|Roll Eyes|0|9|0
11|:P|{"aaron":"tongue.gif","akyhne":"tongue.gif","fugue":"tongue.png","alienine":"tongue.png"}|Tongue|0|10|0
12|:-[|{"aaron":"embarrassed.gif","akyhne":"embarrassed.gif","fugue":"embarrassed.png","alienine":"embarrassed.png"}|Embarrassed|0|11|0
13|:-X|{"aaron":"lipsrsealed.gif","akyhne":"lipsrsealed.gif","fugue":"lipsrsealed.png","alienine":"lipsrsealed.png"}|Lips Sealed|0|12|0
14|:-\\ |{"aaron":"undecided.gif","akyhne":"undecided.gif","fugue":"undecided.png","alienine":"undecided.png"}|Undecided|0|13|0
15|:-*|{"aaron":"kiss.gif","akyhne":"kiss.gif","fugue":"kiss.png","alienine":"kiss.png"}|Kiss|0|14|0
16|:'(|{"aaron":"cry.gif","akyhne":"cry.gif","fugue":"cry.png","alienine":"cry.png"}|Cry|0|15|0
17|>:D|{"aaron":"evil.gif","akyhne":"evil.gif","fugue":"evil.png","alienine":"evil.png"}|Evil|0|16|1
18|^-^|{"aaron":"azn.gif","akyhne":"azn.gif","fugue":"azn.png","alienine":"azn.png"}|Azn|0|17|1
19|O0|{"aaron":"afro.gif","akyhne":"afro.gif","fugue":"afro.png","alienine":"afro.png"}|Afro|0|18|1
20|:))|{"aaron":"laugh.gif","akyhne":"laugh.gif","fugue":"laugh.png","alienine":"laugh.png"}|Laugh|0|19|1
21|C:-)|{"aaron":"police.gif","akyhne":"police.gif","fugue":"police.png","alienine":"police.png"}|Police|0|20|1
22|O:-)|{"aaron":"angel.gif","akyhne":"angel.gif","fugue":"angel.png","alienine":"angel.png"}|Angel|0|21|1

Not only with this allow mixed image types within a smiley set, but it will allow arbitrary filenames for any smiley in any set. Problem more than solved.

Now all we need is a PR to accomplish it, and we'll be ready to roll again.

**Comment by sbulen** [comment]
Great discussion on the ideal structure!   My personal thought is we overuse JSON to compensate for not doing proper DB design...  IMO, the proper, 3.0, design would be to have 3 records, a smileys record (with the code & placement attributes), a sets record (with the path & friendly set name) and a junction that connects the two & basically holds the filenames (with extensions).   Perfect flexibility.  No JSON kludges...   

In terms of what to do right now...  I'd be game to attempt Sesquipedalian's alternate design, but I think I work too slow at these things & would take too long.  To be honest, I'm not too fond of introducing a DB design this late before RC.  And we have a whole new rewritten subsection of code.  _I'm very, very leery of the ripple effects of such a rewrite..._  

I do think I can do my proposal above in a couple days, mainly because I'm very familiar with the current structure & code at this point.  That's still my recommended Plan A.  For a few reasons:  It's the only solution I'm confident I can implement in a couple days, no DB changes, no significant rewrite, and having me do it frees up Sesquipedalian to do other things...  

Sorry for the late response, very long days at work these days...

**Comment by sbulen** [comment]
One last attempt...

I really think to fix this we simply need to change the logic where extensions are applied.  Which is in 3 places.  And allow storage/keeping of extensions for custom smileys.  

Fixing this within the current environment is actually pretty simple.  

A rewrite seems a bit drastic and risky.   Really not something we should do this close to RC.  We should save that for 3.0...

**Comment by albertlast** [comment]
how is the state?
