### ISSUE TITLE
UI improvements needed for smiley editor

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5368]
Add smiley to a single set, example = Image for the Fugue's Set set:  
upload the smiley and it gives the error:  All smiley sets must have an image

If you check the box for, Same image for all sets: then the smiley gets added without problem.

Also does it really need to say set twice when we know it's a set 
Image for the Alienine's Set set:
Image for the Fugue's Set set: 
Image for the Aaron's Set set:
Image for the Akyhne's Set set: 

https://github.com/SimpleMachines/SMF2.1/compare/a31952a...release-2.1

**Comment by sbulen** [comment]
The idea when adding a smiley code is to add it across all sets, so no matter which set you have chosen to use (either as administrator setting the default or as a user if selection is allowed), all smileys can be depicted.   You don't define a smiley that only works for one set, you define a set of codes/smileys you want supported, & then need to associate images to round out each set.  

It will work when you select same image for all sets, because it copies that image to all of the smiley set folders.  

It's the same way in 2.0, & hasn't changed. 

"Alienine's Set", "Fugue's Set", etc, are set names.   Adding your own set, you could add "Penguin", and it would say "Image for the **Penguin** set:"  You don't want to remove "set:" from the prompt, because then it would say "Image for the **Penguin**:"...

**Comment by lurkalot** [comment]
Not meaning to be rude here, but this has to be one of the most confusing admin pages yet.

Add smiley to me say I can add a new smiley = upload a new smiley.   When you click add smiley you're taken to a page where you can use an existing smiley, or upload a new one.   You're presented with a checkbox to add to all sets, but leaving this unchecked you'll see four browse buttons, one for each set.  

That tells me I can browse and upload a image to that set.

Check the Same image for all sets: box, then you're presented with a single browse button which obviously will add the image to all the sets. 

What's the point of the "Same image for all sets:" checkbox if that's the only way you can upload a smiley? 
![adsmil1](https://user-images.githubusercontent.com/6047983/51799237-19907300-2217-11e9-8485-0c3a7547b2f3.png)

**Comment by Bopske** [comment]
It actually allows you to upload different files to different sets: a png to set 1, a gif to set 2 and so on. Makes sense that it allows to load specific files per set, otherwise there is no point to having multiple sets...

What could be better is a clear note stating that you will need to assign a file to each set when uploading...

**Comment by Gwenwyfar** [comment]
Yep, maybe a help tooltip for that.

**Comment by lurkalot** [comment]
I do understand that, but I maintain the UI is extremely confusing, it suggests to me when looking at it, that you can leave the same image for all sets unchecked and upload your smiley to a chosen set from the multiple browse buttons.

Clicking the add to all sets gives you a single browse button, which makes perfect sense.   To me the way it's laid out is just very confusing. 

Also I believe in 2.0.15 the "Same image for all sets:" is checked by default which it isn't in 2.1

**Comment by Bopske** [comment]
I am afraid it's been a bit confusing for years, so not specific to 2.1 tbh. Room for improvement, though once I got my head around the logic: it does make sense, the way it is laid out. 

A tooltip describing the basics to users with less experience would help. 

What may also be helpful is a way to upload a (new) smiley file to only ONE set to replace one uploaded before in that set. ATM this can only be done using ftp or by uploading a smiley with new files to all sets to overwrite the previous file in one.... see also: https://www.simplemachines.org/community/index.php?topic=564355.msg4004270#msg4004270

**Comment by wintstar** [comment]
It would be better to add smileys independently from other sets. What is this logic to have different sets and everywhere the same smiley is available? I have a smiley set with Yahoo. There are 167 pieces. The standard is 24. Now 143 are equal to smilies in the e.g. alienine inserted. Why do you need the different Smilie sets if the smilies are the same?

It would be useful to have Smilie sets where different smilies are included. And also with custom smilies much easier if they do not have to be added to the other sets.

Please remove this function => **Smiley not found in set(s): fugue, alienine**

![yahhoo](https://user-images.githubusercontent.com/2753863/51800046-2b2f4600-222a-11e9-8a58-9abf9e4bed15.jpg)


![alienine](https://user-images.githubusercontent.com/2753863/51800050-36827180-222a-11e9-98d1-078846035059.jpg)

**Comment by Bopske** [comment]
I think the idea is to allow users to choose a smiley set to display the forum. With these choices it is important that each set has all smileys! Removing that warning would take away the visibility what smileys are not in all sets.

**Comment by wintstar** [comment]
> I think the idea is to allow users to choose a smiley set to display the forum. With these choices it is important that each set has all smileys! Removing that warning would take away the visibility what smileys are not in all sets.

It is not in the warning text but the complete function that a uploaded Smilie in all other sets should be inserted. This function should be removed.

**Comment by Bopske** [comment]
Let’s hear what the devs think...

**Comment by sbulen** [comment]
I am still trying to understand why someone would want "uneven" smiley sets...   Where one set has 30 and another has 22....  

Just making sure we're on the same page...  Smiley images are not _embedded_ in posts, they are evaluated & displayed when _viewing_ posts.  When a post is displayed, the smiley codes are evaluated & the smileys are displayed depending on the set chosen by the user/admin.  If enabled, different users can choose different sets.  That choice is reflected throughout the forum to that user.  The same post can look different to different users, depending on which smiley set they chose.  

So...

Let's assume the large set with 30 had `:smirk:` defined to display 😏 , where the small set with 22 did not have an image associated with `:smirk:`.  

If a user selects the small set, that didn't have a link for `:smirk:`, s/he will see a lot of `:smirk:` texts - as a broken link: 
![image](https://user-images.githubusercontent.com/23568484/51807777-558bfe00-2240-11e9-9f02-e6fe29fbdb59.png)
Where a different user, who chose the large set, viewing _the exact same post_,  would see 😏 ...

Is that the desired behavior ?  That is exactly what would happen in 2.0 & 2.1...   

The UI is attempting to make sure that images are available for _all_ the codes in _all_ the sets, so that no matter which set is chosen, users won't have broken links or unevaluated codes like `:smirk:`.

**Comment by wintstar** [comment]
Who says, as in my example above, that the administrator would then activate all Smilie sets for the users. It is obvious that it would come to broken pictures.  It is utterly illogical for me to have the same smilies, as in my example above, in every smiley set. Where is the difference?

One should not always assume that the users of SMF always use only 24 different smilies that differ slightly in shape and color but nevertheless resemble each other. 

Just because it is always the case in 2.0. *, It does not have to stay that way in 2.1 *.

2.1 already has many new features compared to 2.0. *, Why not a new Smilie feature?

**Comment by Sesquipedalian** [comment]
The term "smiley" refers to a text string like `:)`.  This should not be confused with "smiley image," which refers to an image that replaces a textual smiley in the displayed output. A "smiley set" is essentially just a folder containing smiley images, so choosing between different sets is simply choosing which folder to get smiley images from when generating the output.

Smileys, therefore, do not belong to any one smiley set. They are just text strings that users can type into their posts. When those text strings are converted into images in the output, the parser simply retrieves the correct image from the selected smiley set. If the necessary image is missing from the smiley set, the result will be a broken `<img>` element in the output.

So, asking for smileys that only belong to some sets and not others doesn't make sense. To think that it does make sense is to be confused about how smileys, smiley sets, and smiley images work.

**Comment by Sesquipedalian** [comment]
Regarding the UI, I see two needs here:

1. More help text and descriptions to guide the admin about what is required and how things work.
2. A way to upload new files to use for existing smileys. Right now the only way to upload a new file is to create a whole new smiley so the file can be uploaded, then delete the new smiley and assign the image to the existing smiley that one actually wanted to use it for.

**Comment by sbulen** [comment]
I think defaulting to the same image for all sets would eliminate 80% of the confusion.

**Comment by Bopske** [comment]
I fully agree with Sesquepedalian... (sorry about the spelling )
