### ISSUE TITLE
pm_ignore_list new data type is too small

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#5446]
#### Description
From: https://www.simplemachines.org/community/index.php?topic=565144.0

> ```
> ---# Updating members pm_ignore_list
> ALTER TABLE {$db_prefix}members
> MODIFY COLUMN pm_ignore_list VARCHAR(255) NOT NULL DEFAULT '';
> ```
> I have a lot of members where they have an ignore list that contains sigificantly more that 255 chars,

**Comment by albertlast** [comment]
Well on postgres we could change all varchar(255) fields to text,
for mysql would be this step more hurt.
https://github.com/SimpleMachines/SMF2.1/compare/release-2.1...albertlast:RemovedMax?expand=1

**Comment by Oldiesmann** [comment]
The only "proper" way to fix this would be to move the ignore list to its own table, but that would require rewriting a lot of code so that's probably too much work at this point in development

**Comment by sbulen** [comment]
I guess the question is how broad this is.  Throughout 2.0 & 2.1, this has been set to varchar(255).  

Either this was set to a different value manually, or, it's some holdover from 1.x.   

If we do anything, we could just delete those few lines, in case others have manually changed their DB.

**Comment by Sesquipedalian** [comment]
It looks to me like the reporting user must have changed this value sometime in the past and has simply forgotten that he did so. All the way back in upgrade_1-0.sql, when this column was named `im_ignore_list`, its max length was 255 characters. (FYI, the column name was changed in 1.1, and the column type was changed from `tinytext` to `varchar(255)` in 2.0.)

Now, perhaps this column *should* have a max length greater than 255 characters, but changing that would be a feature enhancement rather than a bug fix. Although this would be a database change, and we don't normally want to make database changes in the RC phase, this particular one would be harmless. So if someone wants to submit a PR to make that change for RC2, I won't object.
