### ISSUE TITLE
BBCode authorization groups selection not visible

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#5454]
#### Description

> https://github.com/SimpleMachines/SMF2.1/pull/5351
> Sesquipedalian write to use Permissions for BBCode
> * To impose permissions restrictions for a given BBC, the BBC tag simply needs to be appended to the $context['restricted_bbc'] array via the integrate_pre_load hook.
> * **The admin panel UI will show options to grant permission to use the restricted BBC on the main permissions page for each membergroup, as well as showing an inline permissions form for each restricted BBC at the bottom of the BBC settings page.**
> * The permission to use a restricted BBC is saved in the permissions table as `bbc_*`, where `*` is the tag for the BBC. For example, permission to use SMF's standard [html] BBC is stored as `bbc_html`.
> * Mods adding their own restricted BBC do not need to add language strings for use on the permissions forms. Basic strings for that task are taken care of automatically. However, if a mod wants to add a $helptxt string for an individual BBC, it is free to do so.

With the fix https://github.com/SimpleMachines/SMF2.1/issues/5417 and the pull request 5432 the group selection for BBCode permissions is not visible.

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1 RC1 / Request 5432
- Database Type:  MariaDB 
- Database Version: 10.1.29-MariaDB
- PHP Version:  7.1.11 

### Additional information/references
When I apply live627 suggested solution from https://github.com/SimpleMachines/SMF2.1/issues/5417, the group selection is visible

```
		WHERE id_group != 1 AND id_group NOT IN (
			SELECT DISTINCT id_group
			FROM {db_prefix}permissions
			WHERE permission IN ({array_string:permissions})
				AND add_deny = {int:add}
		)',
```

change to

```
		WHERE id_group NOT IN (1, (
			SELECT DISTINCT id_group
			FROM {db_prefix}permissions
			WHERE permission IN ({array_string:permissions})
				AND add_deny = {int:add}
		))',
```

![not_see_bbc_berm_groups_select](https://user-images.githubusercontent.com/2753863/53036967-441dc680-3479-11e9-893e-7d28c1f42d43.jpg)

**Comment by Sesquipedalian** [comment]
This code is working as intended. The reason that you don't see any inline permissions for the html BBCode on a default install is that the html BBCode has special restrictions above and beyond even the normal restrictions. Specifically, permission to use [html] can only be granted to membergroups who have at least one of the following three permissions:
https://github.com/SimpleMachines/SMF2.1/blob/ab9852e5282137361238de4078010f9d281d872a/Sources/ManagePermissions.php#L2374
If no membergroups have any of those permissions, then the inline permission form for [html] will not appear. Since SMF's default permission settings do not grant any membergroups those permissions, that inline permissions form won't appear until you grant at least one of those permissions to at least one membergroup.

To demonstrate, I changed the content of `$context['restricted_bbc']` to this in my source files:
```
	// Define a list of BBC tags that require permissions to use
	$context['restricted_bbc'] = array(
		'html', 'youtube', 'color', 'attach',
	);
```

If all of the membergroups have their default permissions, then the BBC settings page will show this:
![screen shot 2019-02-19 at 11 30 43 pm](https://user-images.githubusercontent.com/191731/53071163-a937e300-349e-11e9-87e2-feb546ef8fe4.png)

However, if I grant the Global Moderator group the manage_membergroups permission, then the BBC settings page will show this instead:
![screen shot 2019-02-19 at 11 35 13 pm](https://user-images.githubusercontent.com/191731/53071289-059b0280-349f-11e9-998a-34dc79f0b12a.png)

As you can see, only Global Moderator is available in the "Membergroups allowed to use [html]" form in the second image, because that is the only membergroup who has the necessary permissions to become eligible for permission to use [html].

**Comment by wintstar** [comment]
Now I have understood it too. Everything works. Also with the hook.
