### ISSUE TITLE
Incorrect unsubscribe link for topic notifications

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#5480]
#### Description
See https://www.simplemachines.org/community/index.php?topic=565371.0

### Additional information/references
I'm not sure if we can provide a valid link, because the "notifytopic" action requires a valid session ID.

**Comment by Sesquipedalian** [comment]
I think it will be possible to fix this once I port over to 2.1 the GDPR-compliant unsubscribe code that I wrote for 2.0.16. That code implements a system based on tokens instead of sessions so that people can unsubscribe from stuff without logging in (yet without compromising security) as the GDPR requires.

**Comment by Sesquipedalian** [comment]
Cross-reference: #5106.  Not the same issue, but integrally related.
