### ISSUE TITLE
Default cache settings upon install

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#5520]
They could be disabled for new installs. It is very confusing to have your fresh installed forum and the settings take long to be saved. And it won't be a needed option for most users until their forums are big enough to need it.

**Comment by sbulen** [comment]
Some thoughts on this...

It defaults to OFF on install today.  Try it.  

The premise that settings changes don't take effect for 90 seconds when cache is enabled is in error.  When making _most_ settings changes, cache is reset and they take effect immediately.  (~~There is a small # of settings changes (e.g., 'set once & forget' settings, like SMTP), where cache is not reset and you must wait up to 90 seconds.~~  Edit: Our standard updateSettings() call invalidates the cache in 2.0 & in 2.1.)

Also, I think the default of level 1 is a very good default, even for new & small forums.  Caching benefits small forums.  I don't think it should be disabled by default.  

_What really does need fixing:_  The cache setting is in both Settings.php (where it is set to OFF on a new install) and in the settings table (where it is set to ON on a new install).  Updates in the ACP change both.  The Settings.php entry seems to override the settings table entry, which is why it is OFF in new installs. 

I am not sure if this were done on purpose?  I doubt it...  I recommend having ONE setting...  

When cleaning this up, my recommendation is to restore our old default - level 1.  

If there is a specific setting not taking place immediately, then we should log that & discuss whether to reset the cache for it to take effect immediately.  Fix the specific problem.

**Comment by sbulen** [comment]
Related to this, & also needs to be fixed:  _Upon upgrade, your cache settings are lost._  They are overridden by the new Settings.php entries, which default to OFF...

**Comment by Arantor** [comment]
No, it really should default to off on a new install.

It is highly disconcerting for new users to install the forum, make a topic and be surprised that their topic takes a couple of minutes to show up. It makes them think the forum doesn't work properly.

Regularly appears as a support issue in the forums.

**Comment by qcybb** [comment]
Arantor is right, is should be defaulted to off for those reasons.
