### ISSUE TITLE
view own warnings permission

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#553]
there may be cases where an admin does not want users to view their prior warnings. the admin should have the right to assign permissions to who can view their own warnings.

**Comment by Arantor** [comment]
I'd argue the opposite, though. A user should be able to look at their warning history to see what warnings they've had.

**Comment by Oldiesmann** [comment]
I don't see why an admin would want to prevent users from viewing their warnings either.

**Comment by illori** [comment]
in case not so nice message comments were left when the warning was issued for example.

**Comment by Oldiesmann** [comment]
So basically to allow admins to cover up potentially stupid/embarrassing moments? Not a good reason in my opinion.

**Comment by illori** [comment]
have you looked at some of the comments used on sm.org at times they are not exactly friendly.

we will upgrade and without warning admin will have this extra access given to their users if they do allow users to see their own warning status and no way to disable it but not let them view that they have any warning. i just think that any admin that knows that users will see their own warning history may not be too happy.

**Comment by jdarwood007** [comment]
If the default action in 2.0 was to not show the user those, then the default in 2.1 should be the same.  We shouldn't up and change this for no reason.  I can't see a clear reason why we should show them to the user by default.  Let the administrator decide that option after upgrading to 2.1.

**Comment by illori** [comment]
correct in 2.0 the user could only view the status of if they were warned but not the list of their prior warnings. but now in 2.1 without a permission to view the list of prior warnings anyone that has their forum set to allow the user to know they are warned will now be allowing them to view all the warnings.

**Comment by Oldiesmann** [comment]
So what changed in 2.1 to allow all users to see their warnings regardless of warning status? Was this related to the bug that allowed you to see the option to issue a warning when viewing your own profile?

I still don't think a permission is necessary though - a simple "allow users to view their warning history" checkbox should be enough.

**Comment by illori** [comment]
if you give the users the ability to view their warning status in 2.0 they could only view if they were watched/warned etc, but in 2.1 they can fully see all the warnings issued and WHO issued them and what was said.

no this is not related to any bug, it is a new feature.

IMO since in 2.0 no one could view their own warnings that were issued and who issued them, i think in the future we should not unless the admin has full control over allowing or disallowing it per group or even user.

**Comment by illori** [comment]
you know i just checked in 2.0 and in admin panel it says... "Users who can see warning status" but i just double checked in the profile of the user with the warning they can view their warnings. this is not clear anywhere at all that the users can view all their old warnings or any warnings beyond the status they currently have.

so maybe we need some language strings changed as well.

**Comment by Oldiesmann** [comment]
Profile-View.php limits who can view the user's warnings

``` php
if (!allowedTo('issue_warning') && (empty($modSettings['warning_show']) || ($modSettings['warning_show'] == 1 && !$context['user']['is_owner'])))
        fatal_lang_error('no_access', false);
```

If "Users who can view warning status" is "Moderator Only", a user should not be able to view their own warnings unless they have permission to issue warnings.

**Comment by illori** [comment]
then 2.1 has an issue. i did not think about that my 2.0 test user can issue warnings but 2.1 can not but in 2.1 can view the warnings on http://localhost:8080/clean2/index.php?action=profile;area=viewwarning;u=2

**Comment by emanuele45** [comment]
Works as expected on my 2.0 and 2.1:
- warned user cannot access if set to "moderators only"
- warned user can access viewwarning if "moderators and warned users"

**Comment by illori** [comment]
then my issue would be the wording in the admin panel as it does not say that the user if you select "moderators and warned users" would be able to view prior warnings.

**Comment by Arantor** [comment]
Seems like what came out of #473 would cover this? Thinking this should be closed then as a duplicate and we can add both under 473?

**Comment by illori** [comment]
this is in the profile and the other is in the moderation center

**Comment by Arantor** [comment]
Sure but the same permission would still cover both, no?

**Comment by illori** [comment]
i guess so, but then one would give access to the moderation center if the user does not?

**Comment by Arantor** [comment]
I don't see why it would; the whole issue of 'who can access the mod center' has been an issue for literally years because the permission doesn't properly control it, some other people have access because of other permissions.

**Comment by illori** [comment]
if it would not then i cant object to this as a way to fix the issue.

**Comment by Oldiesmann** [comment]
Here's how I was planning to handle this. Any objections @illori?
1. Add a new permission that replaces the current "who can view a user's warning status" setting.
2. Add a new section to "track user" in the profile to list a user's warning history if you can view any user's warning status, but can't actually issue warnings (since warning history is currently shown on the issue page as well).
3. Anyone who can view any user's warning status would also have access to view the warning log in the moderation center.
4. Anyone with moderate_forum will be able to view the new warning history area of the profile and also see a user's warning status.

The "view any user's warning status" permission will essentially be a moderator-level permission, much like most of the other "any" permissions (except of course things like view profile, reply to topics, etc.). I don't see a reason why we'd need to show non-moderators whether or not a user has been warned.

**Comment by illori** [comment]
... i had replied to this...

you are not considering the existing ?action=profile;area=viewwarning;u=## page

also you are not considering the warning status in the mini profile

**Comment by Oldiesmann** [comment]
I didn't realize there was an existing "area=viewwarning" page since that's based on the setting that these permissions would replace and again requires the issue_warning permission. We can just move that to a sub-section of track users instead.

I forgot about the warning status in the mini profile, but that would be based on the same permissions - if you can view any warnings or issue warnings, it'll show; if you can't, but can view own warnings, it will show for your posts.

**Comment by illori** [comment]
If users can view their warnings they can on that page, go check it again

**Comment by illori** [comment]
Did you fix it in the pm view too?
