### ISSUE TITLE
Searching in SMF Admin gives error in log

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5558]
RC2 

Searching in SMF Admin gives me a error in log, but the search still works.

Type of error: Critical 							
The selected search API the forum is using is out of date - falling back to standard search. Please check file SearchAPI-Standard.php.							 http://localhost/testrc2/index.php?action=admin;area=search
--

**Comment by albertlast** [comment]
Which fulltext search you use?
None
Custom
Fulltext

Did you rebuild it after upgrade?

**Comment by vort7u** [comment]
I also have same error, I'm using "None".

**Comment by SychO9** [comment]
it's just the version number in the search api files hasn't been changed from RC1 to RC2

**Comment by albertlast** [comment]
Class-CacheAPI got some rc1 too:
https://github.com/SimpleMachines/SMF2.1/blob/bce556af30c4118a7f2baf4c4841c486c46b2714/Sources/Class-CacheAPI.php#L168-L173

SearchAPI:
https://github.com/SimpleMachines/SMF2.1/blob/bce556af30c4118a7f2baf4c4841c486c46b2714/Sources/Class-SearchAPI.php#L148-L153

@Sesquipedalian

**Comment by lurkalot** [comment]
Apologies for my loud text in the above report,  It was a simple copy and paste, not idea why it did that.

Thanks for finding the cause of the error.

**Comment by Sesquipedalian** [comment]
I find myself wondering why we even have those minimum version checks for the search and cache APIs.

**Comment by albertlast** [comment]
I guess for mods,
so when they add addtional search and cache stuff,
that smf is able to check if the api (class interface) is the same.

The problem when you want realy to do this,
than is the way correct here,
because the min and current version be different between this two topics.

**Comment by illori** [comment]
> I find myself wondering why we even have those minimum version checks for the search and cache APIs.

it is just more locations to forget to update when we do releases and patches. if they are not necessary i think it would good to remove them, or document somewhere that they do exist so we dont forget to update them in the future.

**Comment by vort7u** [comment]
Class-SearchAPI.php will be updated for RC2 or do we have to wait for RC3?
Thanks

**Comment by Sesquipedalian** [comment]
Okay, I've had a chance to look at the relevant code, and my conclusion is that we should just set `$version_compatible` to `2.1.999` and be done with it. 

Performing a min/max version compatibility check is not completely useless, because (1) one day we may need to check for SMF 2.1 vs. SMF 3.0 versions of the search and cache APIs, and (2) third party plugins might need to declare min/max version compatibility ranges for different versions of said plugins. But since our own included plugins and the API itself can and should remain consistent across all versions of 2.1.x, setting the min/max version compatibility range to reflect that is the only move that makes any sense.

**Comment by Sesquipedalian** [comment]
> Class-SearchAPI.php will be updated for RC2 or do we have to wait for RC3?
> Thanks

It'll be fixed in RC3. In the meantime, you can manually edit Class-SearchAPI.php to make the change shown in #5559.
