### ISSUE TITLE
Enabling TFA error

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5577]
#### Description
When you type a wrong password on the tfa enable screen you get this error
```
Type of error: Undefined 
8: Undefined index: oldpasswrd
SMF21/index.php?action=profile;area=tfasetup
SMF21/Sources/Profile.php (Line 627)
```

**Comment by Sesquipedalian** [comment]
Are you certain that this was from an unmodified copy of the latest version of the release-2.1 branch? Because if `$_POST['oldpasswrd']` were undefined, I'd expect the error to come from line 623, not line 627.
https://github.com/SimpleMachines/SMF2.1/blob/2eafeb3b490bc3bc134ac1d7538b27d943655ff3/Sources/Profile.php#L622-L627

**Comment by live627** [comment]
I get errors on both lines
