### ISSUE TITLE
wolf avatar

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#558]
Something to consider: the wolf avatar is [Amarok's](http://amarok.kde.org/) logo.

It may be fine to use it, it may be not. I would seek for an alternative, but that's just my opinion.

Alternatives always from the Oxygen pack) may be the following:
![applications-toys](https://f.cloud.github.com/assets/1095308/910110/a2d1fad0-fdd3-11e2-99ac-4021089797dc.png) ![applications-education-university](https://f.cloud.github.com/assets/1095308/910112/a94fee80-fdd3-11e2-9d74-f3689a67955b.png) ![meeting-chair](https://f.cloud.github.com/assets/1095308/910114/b16599f8-fdd3-11e2-9156-f054f2b369b7.png)

Or:
![view-conversation-balloon](https://f.cloud.github.com/assets/1095308/910121/c5157d42-fdd3-11e2-83a5-2967ec58a874.png)
but in a lighter shade.

**Comment by Oldiesmann** [comment]
I like the 3rd one. Can we add a "default avatar" feature and use that for those who haven't set one? :stuck_out_tongue:

**Comment by matthew-kerle** [comment]
I actually had a graphic artist design a male, female and unspecified avatar set for SMF 2.1. My plan was to implement them so even those that hadn't specified an avatar had an image. Maybe with some settings too.

I would vote the first one out of those four. Or the third.

**Comment by Kindred-999** [comment]
I agree that either a generic male/female (determined at registration, if gender is turned on?) or the man in a bowler from above.
Either way, this does need ot be addressed and I agree - either implement the default avatar mod or our own variation so that a user who has not chosen an avatar gets one.
That being said: For a good UX, this needs to be switchable and settable...   some sites may not want the default avatar or may want to easily specfiy their own default (without overwriting files). So, an interface, like the default avatar mod would be helpful
(if no custom default is used, and default avatar is turned on, use the predefined defaultavatar.png)

**Comment by Arantor** [comment]
So am I right in thinking that there are two separate matters here? One: we need to remove one of the existing avatars, two: default avatars for users without avatars.

The first seems easy enough, the second... hmm.

**Comment by Kindred-999** [comment]
yes. Two separate matters. :P

**Comment by Arantor** [comment]
I'm going to close this issue and start a new one about default icons.
