### ISSUE TITLE
More attributes option in loadCSSFile() and loadJavaScriptFile()

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5604]
You should be able to load an external files with extra attributes like "crossorigin" and/or "integrity"

**Comment by Sesquipedalian** [comment]
Actually, you'll want to look at `template_css()` and `template_javascript()` in Subs.php if you want to add support for those. 

The `loadCSSFile()` and `loadJavaScriptFile()` functions will simply copy any arbitrary key-value pairs in the `$params` array into `$context['javascript_files'][$id]['options']` (or `$context['css_files']` as the case may be), so there's nothing more to be done there. But `template_css()` and `template_javascript()` currently only process expected key-value pairs in the `options` array for each file. 

You'll either way to add explicit support for the attributes you want to support, or else abstract the system in order to support any arbitrary attribute. If you decide to take the latter approach, you might want to look at the handling of `$context['meta']` in index.template.php for inspiration.

**Comment by dragomano** [comment]
I now use this trick:
`loadJavaScriptFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous', array('external' => true));`
