### ISSUE TITLE
Changing the language redirects to index.php

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#5625]
#### Description
Changing the language from the top-right dropdown menu redirects to `index.php?language=foo`. Is there a technical reason for this? Could it be changed to redirect to `<current deeplink>?language=foo`?
Currently, I either have to re-click my way back into the maze that is, for example, the admin center, or use my browsers back button and reload to see the language change.

### Steps to reproduce
1. Install another language in your forum
2. While n clicks deep into some random forum function, change the language
3. Find yourself being redirected to the forum front page

### Environment (complete as necessary)
- Version/Git revision: HEAD

**Comment by albertlast** [comment]
For ther deeplink maybe some addional information are needed like the post stuff or the anker information,
both would create mutch complexity with less gain.

**Comment by Sesquipedalian** [comment]
We do maintain a note of the user's current URL during their session<sup>1</sup> so that we can redirect the user back to it after certain actions (e.g. login). Redirecting after changing languages should be possible if we extend that system to include the action of changing languages.

-----

<sup>1</sup> A note for any privacy conscious readers: This is an ephemeral record only of the current URL you are visiting at the moment, not a record of where you have been. Whenever you go to a new page, the previous URL is forgotten, and the record is deleted entirely after you leave the site.
