### ISSUE TITLE
Deleting Alerts

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5743]
On bigguy's forum after his last update I suddenly 

have 3437 alerts which amounts to 375 pages.  I noticed while trying to delete them, Which I have to say is going to take me days to do.  there's a box that the webpage throws up which says,

Message from webpage
Are you sure you want to do this.  
And a checkbox so you can tell it to stop asking, "Don't let this page create more messages"

If I check that box, the page refreshes then it won't let me delete any more alerts until I close my browser and reload the site. 

This happens in IE11, and Edge, I haven't checked to see if it does it in other browsers yet.

![pitaalerts](https://user-images.githubusercontent.com/6047983/61588560-a3514580-ab95-11e9-9370-25d67bcd09db.png)

**Comment by sbulen** [comment]
What browser is this?

Edge?   https://answers.microsoft.com/en-us/edge/forum/all/dont-let-this-page-create-more-messages/f7a749f9-2ef2-421c-8c44-b888f054e181

More info on the alerts would be helpful.  Were they valid?  Dupes?  Bugs?

**Comment by smfbigguy** [comment]
I had just used a fix for the alerts on my site a few days ago from GH here. It fixed alerts but gave everyone a crap load of them. So they are real alerts and not bugs.

**Comment by lurkalot** [comment]
Thanks BG.  Yep real alerts as you said.   Browsers, as in my report above, only tried it in IE11 and Edge, no idea if it happens with other browsers.  

The Edge issue you linked to is a slightly different one to what I'm getting.  After checking the box the page message will go away as expected, but when the page refreshes you the delete alerts button becomes unresponsive.   Only way to get it back is close the browser, and reload the page, then it'll work again until you tick the box.

**Comment by albertlast** [comment]
I don't see the issue.

You try to delete the alerts,
a message box appears with the question "are your sure?" when you "ok" stuff gets deleted,
"cancel" nothing happen,
when you click "don't let this page.." nothing happen.
Since you block with the last step this message box you can't any more say "ok",
without this alerts don't get deleted.

**Comment by sbulen** [comment]
I believe this is an IE/Edge quirk.  I believe that 'no more popups' checkbox is unique to them.   And, when checked, the form doesn't work anymore...  Pretty easy to verify.

**Comment by albertlast** [comment]
To my eyes i would drop the message box thing,
i mean we talk here about alerts,
why you want the user ask again if here realy sure is?

**Comment by SychO9** [comment]
> i mean we talk here about alerts,
why you want the user ask again if here realy sure is?

Yes, I feel like it'd be best to just drop the confirmation alert in this case.
Otherwise we can tweak the Js code to check for the timing, so that even if the browser disables the alert box, action would still be taken.
https://github.com/SimpleMachines/SMF2.1/blob/e0848c82fbbc912b51789a2fefded6b6830f086f/Themes/default/scripts/script.js#L1671-L1676

**Comment by sbulen** [comment]
A "delete all" option would be helpful.

**Comment by SychO9** [comment]
> A "delete all" option would be helpful.

Well that's planned here https://github.com/SimpleMachines/SMF2.1/issues/5071
