### ISSUE TITLE
Manage boards conflicts

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5830]
#### Description
If you add 'manage boards and categories' to a group, BUT, that group did not have access to all boards prior, you create an illogical situation.  You are disallowed from modifying board permissions to correct.   

Workaround is to remove 'manage boards and categories' from that group, alter board permissions, then add it back...  

The problem is that 'manage boards and categories' is intended to be a global setting (as in all boards), but you can assign it to groups that don't have all boards...   

Possible solutions?  Disallow selection of that permission if the group doesn't have access to all boards?  Propagate to all boards upon selection (feels a little dangerous...)?

### Steps to reproduce
1. Remove global moderators access from BOARD A
2. Add 'manage boards and categories' to global moderators
3. Now attempt to modify board permissions for BOARD A; you cannot add global moderators because it is grayed out & protected.

### Environment (complete as necessary)
- Version/Git revision: current
- Database Type: mysql
- Database Version: 5.7
- PHP Version: 7.2

### Additional information/references
This is from the support forum:
https://www.simplemachines.org/community/index.php?topic=569994.msg4034683#msg4034683

I've confirmed in my local WAMP with the latest from GH - it's not just an RC2 issue.

**Comment by albertlast** [comment]
How it's beahvior in 2.0?

**Comment by illori** [comment]
in SMF 2.0 there is no grayed out/protected section for allowed groups when that group has the permission manage boards and categories. this issue cannot exist in SMF 2.0 due to this.

so in SMF 2.0 you can actually hide boards from those that can manage boards and categories and they can only see them in the admin panel. in SMF 2.1, it sounds like they should be able to view all boards but it does not actually work that way. the boards are grayed out and if it was not checked already they cannot view the board.

**Comment by sbulen** [comment]
I am going to close this, because I cannot reproduce it recently.

Also, this particular writeup focused on certain symptoms (greyed out fields), not the core problem from the forum discussion (see link above).  The core issue was that enabling board managers _actually locked them out..._  

If I can reproduce in the future, I'll do a better writeup.
