### ISSUE TITLE
Installer/upgrader should check for fileinfo

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5913]
#### Description
From: https://www.simplemachines.org/community/index.php?topic=571155.0

> This "undefined function dl()" error has cropped up previously in the past couple of days.
> 
> The dl() function seems to be called by PHP when a required extension has not been nominated in the php.ini file to handle an operation (eg, a file interrogation operation). Some code, somewhere, is trying to circumvent that missing object by doing a dynamic load of the required extension. The dl() function has been deprecated for quite some time as extensions in the php.ini file are the way forward.
> 
> The right answer here is to ensure the minimum extension set has been entered in the php.ini file, including (but not limited to)
> 
> [code=Windows NT]extension=php_fileinfo.dll[/code]
> 
> - or (I think) -
> 
> [code=Linux]extension=php72-fileinfo[/code]
> 

I think the extension is just fileinfo, but the notion is correct.

**Comment by MissAllSunday** [comment]
It looks like the only place file info is used is the proxy and only for checking the mime type. The code should check for that function and fallback to whatever SMF code is using, or just use whatever SMF core is using since I'm sure we already have code for getting the mime type.

**Comment by MissAllSunday** [comment]
Meh, unfortunately, the few places where we got the mime type all depend on file info.

Also, it seems only a very few specific users will face this issue, namely user using windows and without the ext enable on their .ini file.

TBH I don't like adding conditionals for such niche cases 😞

**Comment by sbulen** [comment]
I think finfo is used by all users - unix & win.

Is there s fallback if fileinfo is not available?

**Comment by sbulen** [comment]
Installer & upgrader have the option to issue warnings when components aren't found.  You can provide a "some features may not work" message.  (See #4114 )

**Comment by MissAllSunday** [comment]
Yeah, it works for both, the issue is, on windows it isn't enabled by default which means in some crappy servers it won't be available :/

Yep, working on a generic function with fallbacks for those cases.

**Comment by MissAllSunday** [comment]
NVM, each solution I check needs Windows users to have their libraries installed.... damn windows...

So yeah, having the check on upgrade is the sanest option here.

**Comment by Sesquipedalian** [comment]
I’ve found a partial fallback solution for checking the mime type without the FileInfo extension. It uses the Exif extension, so it only really works for images (anything else will have a null mime type) and could fail if that is also not installed, but it is better than nothing. I’m on my phone at the moment, so I’ll have to share it later. 

But at any rate, I think it will be better to rewrite our code that uses the finfo functions to try that fallback (or to just say “Oh well, we tried” if even it fails), rather than to refuse to install. Unless my memory fails me, our use of finfo is limited to functionality that is not mission critical, so I don’t think it should be a showstopper if it isn’t available. Instead, we can warn the admin about the missing extension during install and in the ACP where appropriate (probably in connection with the image proxy settings and the attachments and avatars settings). If I recall correctly, the custom avatar code already refuses anything that isn’t a supported image type, so my fallback will be good enough there. If we also have some checks in proxy.php to refuse anything with a unknown mime type, that will keep the proxy secure even without finfo, albeit at the cost of limiting it to only images. That will only leave attachments as an issue, since we won’t be able to do a full mime type check for non-image files. But since 2.0.x doesn’t use finfo functions for that anyway, the worst that can happen is that we’ll continue to rely on the same checks that we already do in 2.0.x.

**Comment by MissAllSunday** [comment]
Thing is, fileinfo should be pretty available, if not standard, already. The users who will face this issue would be counted with, maybe, both hands :(

I see it the other way around, if its a stopper then sure include a fallback but for cases like this one, adding checks in the code feels unnecessary :/ On the other hand, I see the benefit of adding a check on install as it helps people to get on with the times.

And if SMF is telling you to get on with the times you really need to do so :P

**Comment by MissAllSunday** [comment]
https://github.com/SimpleMachines/SMF2.1/pull/6011
