### ISSUE TITLE
base directory paths for attachments cannot be modified

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#5977]
#### Description
base directory paths for attachments cannot be modified

### Steps to reproduce
1. try to edit a base directory path and save the page

### Environment (complete as necessary)
- Version/Git revision: latest as of 12am this morning
- Database Type: mariaDB
- Database Version:
- PHP Version:

### Additional information/references

https://github.com/SimpleMachines/SMF2.1/issues/899 is related to this issue.

**Comment by MissAllSunday** [comment]
Tested this and was able to edit the current path as well as adding a new path and set it as current.

Can you please verify if you can reproduce this with the current build?

**Comment by illori** [comment]
i still cannot change the base directory paths at the top of the attachment directories page.

i put in the new path and it reverts back to the old after pressing save.

**Comment by illori** [comment]
in attachment settings set method for the management of the attachment directories to  directories to (auto) when either director space limit is reached, save the page, then go to attachment directories and try to edit any base directory path. it does not save the changes.

**Comment by illori** [comment]
seems you can change the folder but not the drive that the folder is located on

for example if your attachments base directory path is

C:\wamp64\www\github2.1new/attachments1

you cannot change it to

D:\wamp64\www\github2.1new/attachments1

but you can change it from

C:\wamp64\www\github2.1new/attachments

to C:\wamp64\www\github2.1new/attachments1

**Comment by MissAllSunday** [comment]
This does seems to be a local install issue as I've been unable to reproduce this on Docker, shared hosting and cloud servers.

Might need someone else to replicate this issue on a server different than localhost

**Comment by illori** [comment]
maybe it is a windows server thing? i dont know how many use a windows server in production.

**Comment by MissAllSunday** [comment]
@VBGAMER45 Can you please help us confirming this behavior?

**Comment by VBGAMER45** [comment]
Will test on windows server with apache

**Comment by VBGAMER45** [comment]
You can change it but you have to add a new path! You can't edit existing @illori @MissAllSunday 
Maybe should remove that option to edit the default path

Example video: https://softwaredemos.tinytake.com/tt/NDQ3MTA1OV8xNDE1NDk2OA

**Comment by MissAllSunday** [comment]
That's a bummer

**Comment by illori** [comment]
the test @VBGAMER45  did was not on the base directory paths. he needs to do the test again but first change in attachment settings set method for the management of the attachment directories to directories to (auto) when either director space limit is reached, save the page

then do the test again but with the base attachment paths

**Comment by sbulen** [comment]
This has been an outstancing issues for many years...  But today, you can fix this within the Admin Control Panel, if you delete the old one & add the new one.  Just as 2.0 has behaved for many years.  

**_I don't think this should be a holdup for RC4._**

@MissAllSunday I think we should remove the RC4 label from this issue.

It is not user-friendly, but, there is a workaround.  And this is a long-standing issue, present in both 2.0 & 2.1.  No reason to hold up 2.1 for it.

**Comment by Sesquipedalian** [comment]
If I understand correctly, the issue here is that base directories for attachments cannot be moved from one drive to another in a single step (e.g. changing `C:\path\to\attachments` to `D:\path\to\attachments` in the admin UI and saving).

Assuming I do understand correctly, this issue is a manifestation of the fundamental structures of file systems, which is not something we can do anything about.

Put simply, it is not possible to move a directory from one drive to another. Instead, a multi-step process is required. First a new directory needs to be created on the new drive. Then all the files within the old directory need to be copied to the new directory. (File managers often elide these first two steps as "copying the directory to the new drive," but it is actually two steps.) After the copy operation is complete, you might choose to delete the original directory and its contents on the old drive, but that is a completely separate operation.

This structural limitation affects SMF just the same way as it affects a file manager. SMF can move things around on the same drive in a single step. "Moving" to a new drive, on the other hand, involves the same multi-step process described above. This is reflected in SMF by the fact that the admin first needs to create the new base directory, then use the "Transfer files between directories" functionality to copy the files from the old directory to the new one, and then remove the old base directory.

We could, I suppose, offer a more descriptive error message and some help text when this situation arises, but the behaviour is correct.

**Comment by illori** [comment]
The issue is you cannot rename the path even if you manually moved the
folder.

**Comment by sbulen** [comment]
Yeah, this can happen if you move a forum, or you are just doing some file maint & want to rearrange/rename them.
