### ISSUE TITLE
why notify all users watching a topic that it has had moderation performed?

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#5998]
#### Description
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/RemoveTopic.php#L75

### Additional information/references

i dont understand why we need to let all users watching a topic know that the topic was removed. what if the topic is an old topic and the admin/moderators are cleaning up, now all those users get emails that the topic was removed.

looks like similar emails get sent for merges as well as locks, unlocks, sticky, moves, splits and deletes.

i think this could lead to a lot of unnecessary emails being sent to users.

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/languages/EmailTemplates.english.php#L684

**Comment by frandominguezl** [comment]
I'd label this as minor as well. While Illori has got a point, I also see the other way around. If I'm watching a topic, I definitely would like to know if that topic has been removed.

**Comment by illori** [comment]
This came up on the forum yesterday. The admin could not clean up due to
all these emails being sent.

**Comment by Sesquipedalian** [comment]
Notifying everyone about splits and merges makes sense, since that changes which topic the user is watching. For the rest, I'd say only notify the original poster.

**Comment by sbulen** [comment]
I think that is a 2.0 thread???  The problem in 2.0 is that the default setting is actually set at the DB level (notify_types on the members table).  In 2.0, users can change their setting, but the admin cannot due to the weird default behavior for that particular setting.   

Related 2.0 topic: https://www.simplemachines.org/community/index.php?topic=569570.0

In 2.1, I am pretty sure that is a user defined option, & the admin can set the default.   
![image](https://user-images.githubusercontent.com/23568484/73888692-f1bced80-4822-11ea-86a7-497d07107e25.png)

**Comment by illori** [comment]
That same setting exists in 2.0.

**Comment by sbulen** [comment]
Where?  My understanding is that was for users only & a default could not be set at the admin level.  

_If you know where an admin can set the default in 2.0, that would be helpful..._  In the thread referenced above, you & I both told the user the admin could not set a default.

In 2.1, admins can set the default & users can override.

**Comment by illori** [comment]
Sorry I read your comment wrong.

**Comment by sbulen** [comment]
No problem!   ;^)

In short:
 - In 2.0, no default setting exists.  You literally need to change the db definition to change the default.  Any user updates would need to be done by sql.  Not impossible, but not friendly.
 - In 2.1, admins can set a default, and users can override.  Which is perfect.

Unless someone has verified a bug with these settings in 2.1, I think this can be closed.  (I haven't checked & I'm looking at other things atm...)

**Comment by sbulen** [comment]
OK... I just tested this in 2.1, and it's the other way around...  Most moderation activity results in NO notifications, even when requested.  

I had 2 users, Bob wanted replies only, & Joe wanted replies & moderation.  Both wanted both emails & alerts.

Replies worked perfectly - both got an alert & an email.  

Split topics also worked perfectly - Joe received the notifications, Bob did not.   All good.  

But...  Reported posts, bans, warnings, deleted posts & _even deleting the topic_ - generated no alerts or emails at all, even for Joe, who had requested 'replies and moderation' for that topic.  So it's not working as expected.

**Comment by illori** [comment]
did Joe open the topic? i believe that the person that started the topic should get a notification of moderation action on the whole topic, like locking the topic or moving it. the person that started the topic should not get a notification if a post was removed if they dont start it, the person that posted it should only if they are being notified of moderation.

i dont know how the actual code is written around this to know if this at all expected.

**Comment by sbulen** [comment]
> did Joe open the topic? i believe that the person that started the topic should get a notification of moderation action on the whole topic, like locking the topic or moving it. the person that started the topic should not get a notification if a post was removed if they dont start it, the person that posted it should only if they are being notified of moderation.

That is totally under Joe's control.  Defaults are set, and he can override the default for any topic.

Defaults are set here, under his profile:
![image](https://user-images.githubusercontent.com/23568484/77593121-e1370400-6eb0-11ea-9dbc-a94687467395.png)

Joe can override that here, at the board & topic level:
![image](https://user-images.githubusercontent.com/23568484/77593219-14799300-6eb1-11ea-8575-e49728b05e5d.png)

The problem here remains the opposite of the original post (which was around a 2.0 discussion; 2.0 is very limited in this regard).  The actual problem here is that when alerts for moderation are requested, they do not appear for most moderation activity at the moment.

**Comment by MissAllSunday** [comment]
This seems like could use input from the team to collectively decide what to do, thus I tagging it for Final to allow some room for discussion.

**Comment by sbulen** [comment]
I really don't think this is a 2.1.0 requirement.  Could we remove or change the milestone?

Also, the title should be changed.  The real issue here in 2.1 is that no moderation activities appear to trigger the notification.  (I.e., the exact opposite of the initial report.)

**Comment by Sesquipedalian** [comment]
> Also, the title should be changed. The real issue here in 2.1 is that no moderation activities appear to trigger the notification. (I.e., the exact opposite of the initial report.)

Instead, @sbulen, could I get you to open a new issue describing the situation as it exists in 2.1? That way we won't have a confusing mix of things to sort through.
