### ISSUE TITLE
?action=helpadmin;help=attachment_manager_settings missing help on recode line endings in textual attachments

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#600]
this help popup is missing the new [to 2.0] feature of recoding line endings.

**Comment by Oldiesmann** [comment]
Do you have any suggested text for that? We definitely need help text for all the options there, but at the same time I can't think of a way to explain the concept of line-endings in a way that wouldn't thoroughly confuse the average (non-techy) user.

**Comment by illori** [comment]
i dont know why we actually need this feature, best i could do when adding it on the wiki was this 

http://wiki.simplemachines.org/smf/index.php?title=Attachments_and_Avatars&action=historysubmit&diff=18173&oldid=18172

**Comment by Arantor** [comment]
The reason for it is because back in the day, SMF would just do the conversion of a text file to whatever the user's line endings were - except we'd see all kinds of mangling of PHP files when attached to sm.org where there were double (or worse) line endings.

Personally I'd be inclined to drop it because I can't see a reason why people should really leave it on.
