### ISSUE TITLE
Language Timezones.english global $txt  missing 

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#6002]
#### Description
This function "Custom descriptions for individual locations" does not work.

https://github.com/SimpleMachines/SMF2.1/blob/e2bd570713b4bbde0c720ca68a72aa5a391c5b43/Themes/default/languages/Timezones.english.php#L50
`global $tztxt;`

Here the global "$txt" is missing.

**Fix**
`global $tztxt;`
change to
`global $tztxt, $txt;`

**Comment by frandominguezl** [comment]
Do you want to submit the fix?

**Comment by wintstar** [comment]
I'm not so good with Github. Could you please do this for me.

**Comment by live627** [comment]
Is there an error somewhere? None of the other language files do this.

**Comment by Sesquipedalian** [comment]
I just tested locally using French. I was successfully able to change one of the custom time zone descriptions, and the new description was correctly used in all locations after that. From what I can tell, everything is working as it should.

In general, it is not necessary to declare `$txt` as a global in the individual language files. `$txt` is already in global scope long before any of the language files are loaded. In contrast, `$tztxt` does need to be declared as a global at the top of this file because it is not automatically declared as a global during SMF's startup sequence.
