### ISSUE TITLE
Minor alignment issue - should get date & time on one line

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6044]
#### Description
![image](https://user-images.githubusercontent.com/23568484/76913475-52086b80-6874-11ea-92bc-db2a14eac2cb.png)

Also feels like replies/views got nudged over, too.

**Comment by XinYenFon** [comment]
this is because other elements in the same container either using absolute values of width (like we give icons 60px space so they don't get ... squeezed in), but lastpost using EX values which makes things interesting... I don't think ex values should be used as a width, instead it should be used as spacing factors (margin/padding).
