### ISSUE TITLE
karma applaud/smite hidden

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#607]
if a user wants to give karma to a user as currently in 2.0 they can easily click a link in the mini-profile that is on the left side of the post under the users name.

in 2.1 it is completely hidden, do you expect users to even be able to tell karma is enabled if the option is not in their face?

needing to use the drop down menu from the users name to view the options to give or remove karma is not in a good location for it to be actually found and used.

**Comment by Arantor** [comment]
Given that they can't see the current karma value(s) until they go to the popup, it makes sense that the applaud/smite option is listed with that.

This question is ultimately the larger one of: should we have the popup and should we be hiding 'non essential information' in it? If so, what is the definition of 'non essential information' that should be hidden?

**Comment by illori** [comment]
i dont know if anyone still uses karma, so i cant comment if it is essential.

i would say it is useful to see a users post count without using the popup

maybe an option to show a custom (advanced) profile field either in the popup or in the mini-profile could be useful 

also i would say moving the post count group title out of the popup would be a good idea.

**Comment by Arantor** [comment]
See, I know other forum systems that don't display this stuff without clicking on the user's avatar to bring up a popup of details - and that's pretty popular (XenForo, IPB may do something similar)

As far as post count group, interesting, I hadn't actually directly noticed that, but I'd be inclined to leave it there for now. I really don't know what's for the best because for every argument I can make for not doing it, I can make another for doing it.

I've said before the underlying theme of Curve II is minimalism, I'd be inclined to leave things as such, at least until we've had more widespread feedback about these things.

**Comment by illori** [comment]
waiting on this seems ok, as long as it is not forgotten

**Comment by Arantor** [comment]
This relates to #638 and whether we include it or not. If we do, then this issue goes away. If we don't, we need to make a decision about it.

**Comment by emanuele45** [comment]
Technically my question here would: is there anyone using karma nowadays?

**Comment by illori** [comment]
i know i dont, but i dont know how many do.

**Comment by Arantor** [comment]
Most of the sites that use karma use one or more mods to make it less useless.

**Comment by Arantor** [comment]
Fairly sure this isn't an issue now that 'everything's back'.
