### ISSUE TITLE
`loadMemberContext` no longer returns a bool  while various codes expect it to

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#6111]
See theses search results https://github.com/SimpleMachines/SMF2.1/search?q=loadMemberContext&unscoped_q=loadMemberContext

Can we agree to stop changing the API?

ref #6049 
ref #6079

I recommend a revert.

**Comment by Sesquipedalian** [comment]
Agreed. The justification for the change appears to have been to "[minimize global usage](https://github.com/SimpleMachines/SMF2.1/pull/6049)." That's a nice idea in theory, but realistically it's not going to happen in 2.1, so it's not worthwhile to break a bunch of existing code merely in order to make a fairly minor gesture in that direction.

Care to put together a PR to revert the change, @live627?

**Comment by sexwarrior** [comment]
Given that this fix has been [immediately undone with no documentation](https://github.com/SimpleMachines/SMF2.1/commit/95388c999ab6e3c85070987960c925c27e112b8e), does this issue need re-opening?
