### ISSUE TITLE
Safari doesn't support @media (min-resolution...

### ISSUE THREAD

**Issue by StealthWombat** [SimpleMachines/SMF#6162]
index.css - Lines 1727-1732

```
/* Load better icons for higher resolution screens */
@media screen and (min-resolution: 160dpi) {
	.main_icons::before {
		background-image: url(../images/icons/main_icons_sprite_hd.png);
	}
}
```
Problem: Safari, either on desktop or on iOS, doesn't support min-resolution.
See: [https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution](url)

This means no nifty hi-res icons on Safari. Workaround for iThingz could be:

```
@supports (-webkit-overflow-scrolling: touch)
```
That will nail any cases of Safari on mobile, but still wouldn't deal with Safari on hi-res desktop. I assume there will be something else that can be used for hi-res desktop (Apple are always inventing heaps of Apple-specific properties) but I haven't looked into that yet.

ETA: This one looks promising.
[https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-attachment](url)

Only supported by Safari, either on desktop or on iOS. Would result in hi-res icons being served even to Safari on lower res desktop, but that's probably not a significant issue. It'd still look fine, and the extra overhead isn't much in the scheme of things.

**Comment by Sesquipedalian** [comment]
A better workaround would be to use `-webkit-min-device-pixel-ratio`/`-webkit-max-device-pixel-ratio`, since all our supported browsers will treat it as an alias of the standard `min-resolution`/`max-resolution`. (See https://compat.spec.whatwg.org/#css-media-queries-webkit-device-pixel-ratio, https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-webkit-device-pixel-ratio, and https://caniuse.com/?search=-webkit-device-pixel-ratio.)

Edit: An even better solution might be the one given [here](https://www.w3.org/blog/CSS/2012/06/14/unprefix-webkit-device-pixel-ratio/).

**Comment by MissAllSunday** [comment]
Trimmed RC4 issues, moved to Final.
