### ISSUE TITLE
Non functioning and probably superfluous code to set height of code blocks

### ISSUE THREAD

**Issue by KolyaKorruptis** [SimpleMachines/SMF#6252]
I just came across this in **theme.js**:
```javascript
if (is_webkit && $(tag).height() < 20)
			$(tag).css({height: ($(tag).height + 20) + 'px'});
```
This doesn't do anything, because `$(tag).height` is a function in jQuery.  So `$(tag).height + 20) + 'px'}` never evaluates to anything useful. I could fix it:  `$(tag).height() + 20) + 'px'}` 
And you can review the effect of this fix here: https://jsfiddle.net/KolyaKorruptis/40otp8jr/6/

But in reality Safari of course doesn't need help dealing with _overflow: auto blocks_ these days.  (I actually tested this.) 
Now if browser-support is determined by jQuery [as MissAllSunday said](https://github.com/SimpleMachines/SMF2.1/issues/6245#issuecomment-687156251), then [we're talking about the current Safari version - 1](https://jquery.com/upgrade-guide/3.0/#browser-support). Consequently this code could be removed. But I'd like to hear your opinions.

As a sidenote, I noticed that Chrome gets caught in "is_webkit".

**Comment by MissAllSunday** [comment]
Yes, you will encounter some legacy/not used code on js files as those haven't really be modified unless it was needed to do so.

You will also encounter code that is not  suitable for modern times due to the long dev cycle 2.1 had.  But please feel free to make changes where you see fit, we aren't aiming for a complete re-write this late in the process but small focused issues will certainly help us.

**Comment by live627** [comment]
Fortunately no one went all crazy with rewriting     all the code to require jquery.

**Comment by KolyaKorruptis** [comment]
The code is useless today, jquery or not, because browsers don't need help with overflow:auto. 
So  the main problem really is legacy code here, as @MissAllSunday pointed out.
