### ISSUE TITLE
Double string 

### ISSUE THREAD

**Issue by Dzonny** [SimpleMachines/SMF#6297]
https://github.com/SimpleMachines/SMF2.1/blob/b9674508df9874c6d356e1b99fc95b553c2e1e6d/Themes/default/languages/Admin.english.php#L72

"privacy_policy" string can be found in both Admin.english and Agreement.english files.

Ref:
https://www.simplemachines.org/community/index.php?topic=575231.0

**Comment by live627** [comment]
is this really an issue though? dup strings are everywhere though..

**Comment by Dzonny** [comment]
Well it's not a big of a deal, but I guess we should remove duplicates where we can?

**Comment by Oldiesmann** [comment]
Probably a good idea to do a language file cleanup at some point, but I'm not sure it's a good idea to do it this late in the release cycle.

In this case it's likely done to limit how many language files are loaded - Admin.english.php will take care of every instance in the admin center while Agreement.english.php will handle it for user-facing areas. Moving it out of both files to the index language file should fix this instance though (since the index language file is loaded on every page)

**Comment by MissAllSunday** [comment]
A full clean up at this late stage shouldn't happen but if there are well defined cases of duplication spotted then yes we could solve them.

Now on this specific example, Admin and Agreement are files that are only loaded on specific and seldom visited parts of the forum, meaning moving the txt string to index will not really get us a benefit since most of the times that txt will not be used.

A case where duplication can be mitigated would be if the txt string is used on more active parts of a forum or if its sufficiently general for a modification to use it
