### ISSUE TITLE
function get_current_settings Throwable only works in PHP 7.0+ 

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#6298]
In sources/Subs-Admin.php

the function get_current_settings
Uses catch (Throwable $e)

Which is only part of PHP 7.0+

**Comment by live627** [comment]
Does it actually error out, though? Static analysis only gives half the
story...

**Comment by VBGAMER45** [comment]
Haven't been able to get that error. I mainly run PHP 7.3. Just noticed that as an error warning.

**Comment by albertlast** [comment]
no one is running the the lowest supported php from smf,
reason why it make no sense to support sutch low version.

**Comment by Sesquipedalian** [comment]
Not an issue. The error handling in that function is specially designed to handle the difference in the way PHP 5 and 7 handle `eval()` errors. If running on PHP 7, an eval error will immediately throw a ParseError exception, which will be caught by the `catch (Throwable $e) {}` statement. On PHP 5, `eval()` simply returns false on error, so we manually throw our own ErrorException and catch it with `catch (ErrorException $e) {}`. It looks weird, but it works.

> no one is running the the lowest supported php from smf,
> 
> reason why it make no sense to support sutch low version.

As a matter of fact, I carefully tested this code on PHP 5.3–5.6 and 7.0–7.3 in order to make sure it worked for them all.

**Comment by Sesquipedalian** [comment]
... Of course, if anyone finds some circumstances under which this code breaks, this issue can be reopened.
