### ISSUE TITLE
img html in group name and admin log

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#642]
put something similar to `html
<img src="http://localhost:8080/clean2/Themes/default/images/helptopics.gif">test` as the name of a group

go to the admin log and check what the log says, it should show the helptopic.gif next to the group name where it is no longer accepting the html outright, it should not show the image in the admin log

[the image is linked from a 2.0 install]

**Comment by Arantor** [comment]
Group names have accepted HTML for a long time, as do board names and board descriptions. It should be saved with htmlspecialchars so this sort of thing should never be occurring.

This is a behaviour I have never been fond of. However because of the way this has occurred, breaking it would be a backwards-incompatible change for forums that rely on this sort of sketchy behaviour for given purposes.

Certainly for 3.0 this will not be permitted, but for 2.1 I'm not sure what exactly we should do. Sure, we can fix the way it's displayed, but that doesn't change the fact it's still accepting raw content without proper sanitisation.

**Comment by illori** [comment]
html is not parsed in 2.1 any longer, it is only parsed in the admin log.
