### ISSUE TITLE
RC3, URL parsing oddity

### ISSUE THREAD

**Issue by LexArma** [SimpleMachines/SMF#6497]
#### Description
Originally opened a topic about this at https://www.simplemachines.org/community/index.php?topic=576638 
This works correctly on 2.0, and is linked automatically

https://puheenvuoro.uusisuomi.fi/jukka-savorinen/olen-selvittanyt-miten-maailmankaikkeus-toimii-%f0%9f%98%83/

On my RC test install though, for some reason it doesn't. It does work, if I manually add URL tags.
I don't really know what else to say, except that I could assume this is something to do with the encoded emoji in the URL.

**Comment by sbulen** [comment]
Confirmed bug.  Thanks Lex!

**Comment by BrickOzp** [comment]
The problem is in Subs.php sanitize_iri() where it gets decoded into the utf-8 characters. And since the url is not the same before and after the sanitize call, it will not be autolinked.
If posting the url with the smiley instead, it works.
I do not find the reason for this behaviour, and the commit message does not give any clues.
