### ISSUE TITLE
Common support and issues

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#652]
on the support and credits page there is this block. it seems to be another news block. currently it suggests trying 2.0.5 [even if you have 1.1.\* it suggests that 2.0.5 is out and try it]

why do we need this block? can we put in version specific reply from sm.org or get rid of this?

**Comment by Oldiesmann** [comment]
It looks like it was intended to be used to list common support issues relating to your configuration. If you click the help button in the upper left-hand corner it says this:

> This panel shows you some of the most common problems and questions on your server configuration. Don't
> worry, this information isn't logged or anything.
> 
> If this stays as "Retrieving support information...", your computer probably cannot connect to www.simplemachines.org.

I'm not sure why it's recommending 2.0.5 for 1.1.18 users though.

**Comment by Arantor** [comment]
I'd personally rather get rid of it, can't see what use it has especially when most users don't even see it anyway.

**Comment by illori** [comment]
i agree with Arantor we should remove it.

also for the issue in 1.1.\* check out http://www.simplemachines.org/smf/latest-support.js it just has one entry for the Common support and issues

also what is the deal with the kupo part in that file? [the js file]

**Comment by Arantor** [comment]
The kupo part os that file is an easter egg that seems to no longer work in 2.x and should die anyway.

**Comment by Arantor** [comment]
@Oldiesmann What are your thoughts about removing this part entirely from 2.1?

**Comment by Arantor** [comment]
OK, the reason it's recommending 2.0 for 1.1.x users is because both use the same file, sm.org/smf/latest-support.js though 2.0 does supply a version number so we could supply a 1.1.x version for users who don't offer a version and 2.0 for users who do.

However, I'm really not convinced this is helpful for users; users don't go into that screen before coming to the forum for help and most of them wouldn't upgrade unless the ACP told them to as it does. So to be honest, while we can fix it for 2.0 and below, I'd rather just remove it entirely from 2.1 and spare the servers a little (otherwise it's another request per day that needs to be made)

And in the spirit of 'just doing it', I'm working on that right now.
