### ISSUE TITLE
Resized images cause distortion

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#6541]
#### Description
.bbc.resized on phone sized devices seem to cause a distortion and look bad

See this sample image
<img width="632" alt="Screen Shot 2021-02-26 at 10 16 44 AM" src="https://user-images.githubusercontent.com/732116/109340729-3b0d2000-781e-11eb-9cc8-8ce8b03c0849.png">

The fix I have found that works is to instead of setting max height/width.  I set the height/width to auto.  This seems to scale the image properly so it doesn't look distorted.

Any unforeseen issues with this fix?

**Comment by sbulen** [comment]
I think we should keep 'Final' for bug fixes for RC4 only.  This is a rare case I'd actually prefer either an RC4 tag or a post-go-live tag.

**Comment by BrickOzp** [comment]
Did you attach the correct image?

**Comment by live627** [comment]
https://www.simplemachines.org/community/index.php?topic=505050.0 — an old tip that is probably applicable here

**Comment by BrickOzp** [comment]
Here is my interpretation of this problem.

* If an attached image don't have width or height specified resizing works.
* If the image have only width specified resizing works.
* If the image have only height specified, resizing does not work since the height is preserved but the width is altered.
* If the image have both width and height specified. This works the same as if only the height is specified. On RC3, if specifying auto for width and height, the width and height was read from the file and specified in the html. This has sinced changed to not specifiying width and height when using auto.

The resizing problem when height is specified could be fixed by setting height: auto. This would though not work if the width and height is set in such a way that the aspect ratio is changed. In this case the height is ignored and reset to match the width keeping the aspect ratio.

Height could in this case be removed from the input form since it will make no difference.

I have also found a problem on mobile devices.

responsive.css

@media screen and (max-width: 720px)
.bbc_img.resized {
		max-width: 250px;
		max-height: 300px;
	}

This will make resized images be very small and with incorrect aspect ratio.
If no one have a good reason for it to be kept I would recommend it to be removed.

@DiegoAndresCortes

**Comment by jdarwood007** [comment]
Thanks, thats more detailed than what I dug into, but looks like we may have located the source of the problem.  Just need to source the right solution.  I'm fine with removing it if height/width gets set to auto, which seems to work for me.

**Comment by DiegoAndresCortes** [comment]
> 
> 
> Thanks, thats more detailed than what I dug into, but looks like we may have located the source of the problem. Just need to source the right solution. I'm fine with removing it if height/width gets set to auto, which seems to work for me.

This breaks previously resized images as I explained in the pr
To accomplish this, a min-height is required so images stay somewhat squared, changing width/height will display resized images in full size.

> 
> 
> @media screen and (max-width: 720px)
> .bbc_img.resized {
> max-width: 250px;
> max-height: 300px;
> }
> 
> This will make resized images be very small and with incorrect aspect ratio.
> If no one have a good reason for it to be kept I would recommend it to be removed.


I agree with this solution.

**Comment by XinYenFon** [comment]
```
	.bbc_img.resized {
		max-width: 250px;
		max-height: 300px;
	}
```
Replace with
```
	.bbc_img.resized,
	.postarea .bbc_img {
		max-width: 100% !important;
		max-height: 100% !important;
	}
```

this enforces limits on images when smol screen is in play... Since we cannot really ... do "if/else" to respect the limits when its applicable.

**Comment by jdarwood007** [comment]
@XinYenFon Fix does fix it.
