### ISSUE TITLE
loadMemberData(), $set, integration hook problem

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#6566]
Load.php, function loadMemberData(), this block:

```
	// We add or replace according the the set
	switch ($set)
	{
		case 'normal':
			$select_columns .= ', mem.buddy_list,  mem.additional_groups';
			break;
		case 'profile':
			$select_columns .= ', mem.additional_groups, mem.id_theme, mem.pm_ignore_list, mem.pm_receive_from,
			mem.time_format, mem.timezone, mem.secret_question, mem.smiley_set, mem.tfa_secret,
			mem.total_time_logged_in, lo.url, mem.ignore_boards, mem.password_salt, mem.pm_prefs, mem.buddy_list, mem.alerts';
			break;
		case 'minimal':
			$select_columns = '
			mem.id_member, mem.member_name, mem.real_name, mem.email_address, mem.date_registered,
			mem.posts, mem.last_login, mem.member_ip, mem.member_ip2, mem.lngfile, mem.id_group';
			$select_tables = '';
			break;
		default:
		{
			loadLanguage('Errors');
			trigger_error(sprintf($txt['invalid_member_data_set'], $set), E_USER_WARNING);
		}
	}

	// Allow mods to easily add to the selected member data
	call_integration_hook('integrate_load_member_data', array(&$select_columns, &$select_tables, &$set));
```

Say I want to make a custom $set called "my_set".  I can use the integration hook but the "default" statement of switch won't allow the function to move forward to the integration point.

So this one will fail:
`loadMemberData($users, false, 'my_set')`

I guess this is design to allow a mod to modify the predefined sets only not to allow them to define their own.

**Comment by DiegoAndresCortes** [comment]
I understand but I don't see why anyone would add a new set.
Could be changed a bit just for it but don't see the benefit

**Comment by Oldiesmann** [comment]
The hook is designed to allow mods to add additional data to loadMemberData. The set info is passed so mods can determine what, if anything, to load based on which set is being loaded.

**Comment by asmith20002** [comment]
I have a big website with various tables for members. I could define my own set to target those tables. In the current code design, I have to expand one of the 3 pre-defined sets for the custom tables which will result SMF to also query those tables for cases when they are not needed.

**Comment by MissAllSunday** [comment]
Indeed the sets are predefined since loadMemberData() is called by SMF on several places as well as modifications, the hook provides those aprams so anybody who uses the mod can add their own columns and tables according to the $set being used at that time.

If you want to load data only on specific places/actions then loadMemberData() isn't the function to use, however if you want your data to be available at the same time as the data loaded by loadMemberData() then use it and append your custom tables and columns to the variables, it doesn't really matter if you aren't going to use the rest of the tables/columns, someone else will.

If you need to load member data from several tables I would recommend doing it on your own queries where you can fetch what you need when you need it.
