### ISSUE TITLE
new lines and variables in text string

### ISSUE THREAD

**Issue by Dzonny** [SimpleMachines/SMF#6597]
https://github.com/SimpleMachines/SMF2.1/blob/f03f6efd1b9d3b0cd1bef571389bfbefbba5af3a/Themes/default/languages/index.english.php#L150

Issue reported here:
https://www.simplemachines.org/community/index.php?topic=572767.msg4084946#msg4084946

We should change this string to be compatible with Crowdin, as this will cause bug when translated through it.

**Comment by BrickOzp** [comment]
These string also has the same problem

index
$txt['movetopic_default']

Admin
$txt['security_wrong']

Profile
$txt['profile_warning_notify_template_outline']
$txt['profile_warning_notify_template_outline_post']

**Comment by BrickOzp** [comment]
Why was the $ escaped in the source string in the first place?

The error message in Crowin when removing escaping of $ seems to point to that the english input string is erroneous.

_Source text contains variables "%1" that is missing in the translation. Instead, the translation contains "%1$s" that is not found in source text.
Source text contains a variable "$s" that is missing in the translation._

**Comment by asmith20002** [comment]
On the side note, what if the forum title already starts with "The"?

**Comment by jdarwood007** [comment]
@BrickOzp The $ needs escaped because its using double quotes and otherwise would try to parse $1 as a variable.  Its using double quotes I assume to have \n parsed as well.

@asmith20002 Thats a rare edge case I would assume and could be corrected by editing the language files as needed or by not using "The" in the forum name.

**Comment by BrickOzp** [comment]
Could we change to single quoted strings and add a real new line?
Like
$txt['regards_team'] = 'Regards
The $1%s team';

**Comment by jdarwood007** [comment]
I would suggest you do some testing.  @sbulen has a test repo with crowdin that may be useful or you can use your own.

**Comment by sbulen** [comment]
I'd prefer not to use real new lines in the source - mainly for readability.

I've confirmed though that the rest works - only enclose the newlines in double quotes, put the rest in single quotes & the variables don't need to be escaped.

The good news is there are only a few of them, I think they're all identified here.  I'll confirm.

I do think this is a bug in CrowdIn - they should know the difference between single & double quotes.

**Comment by sbulen** [comment]
PR #6607 submitted.  

These new strings have been loaded in the CrowdIn test project, in the SMF_2-1_NEXT branch.

I did go with real new lines, because it was the cleanest in CrowdIn.  Other alternatives worked, but split the text string into multiple substrings in CI. Other alternatives considered (& how they looked in CI) are doc'd in the PR.
