### ISSUE TITLE
bbcode param mismatch—specific order required

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#6654]
```
1) PHPTDD\BBCTest::testBBC with data set #22 ('img', '[img alt=some text width=150 ...[/img]', '<img src="http://adomain.tld/...lazy">')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<img src="http://adomain.tld/an_image.png" alt="some text" title="" width="150" height="100" class="bbc_img" loading="lazy">'
+'<img src="http://adomain.tld/an_image.png" alt="some text width=150 height=100" title="" class="bbc_img" loading="lazy">'
```
This is the bbcodfe in question
https://github.com/SimpleMachines/SMF2.1/blob/8eae9deee9fb0c69571d6654dfac2ecba5c65c2d/Sources/Subs.php#L1746-L1766

And my est inputs are

			array(
				'img',
				'[img alt=some text width=150 height=100]http://adomain.tld/an_image.png[/img]',
				'<img src="http://adomain.tld/an_image.png" alt="some text" title="" width="150" height="100" class="bbc_img resized" loading="lazy">',
			),

This is phpunit. The test method is

	/**
	 * @dataProvider bbcProvider
	 *
	 * @return void
	 */
	public function testBBC($tag, string $test, string $expected): void
	{
		$result = parse_bbc($test);
		$this->assertEquals($expected, $result);

		$this->assertContains($tag, array_column(parse_bbc(false), 'tag'));
	}

https://github.com/live627/SMF2.1/blob/1fdf397dbabc1088b95f03a309a2e4a2939d0465/tests/BBCTest.php#L475-L486

A small debugging session revealed that it matched to the wrong code  it seems like
https://github.com/SimpleMachines/SMF2.1/blob/8eae9deee9fb0c69571d6654dfac2ecba5c65c2d/Sources/Subs.php#L1727-L1745

				if (isset($possible['parameters']['alt']))
				var_dump($matches, $possible['parameters']); 

https://github.com/live627/SMF2.1/blob/7c9a29eef594fb2118d2cf1cfbb76cd4fc57447b/Sources/Subs.php#L2782-L2783

The relevant dump is
```
/home/travis/build/live627/SMF2.1/Sources/Subs.php:2783:
array(3) {
  [0] =>
  string(35) " alt=some text width=150 height=100"
  [1] =>
  string(35) " alt=some text width=150 height=100"
  [2] =>
  string(30) "some text width=150 height=100"
}
```

Expected dump
```
/home/travis/build/live627/SMF2.1/Sources/Subs.php:2783:
array(4) {
  'alt' =>
  array(1) {
    'optional' =>
    bool(true)
  }
  'height' =>
  array(3) {
    'optional' =>
    bool(true)
    'value' =>
    string(12) " height="$1""
    'match' =>
    string(5) "(\d+)"
  }
  'title' =>
  array(1) {
    'optional' =>
    bool(true)
  }
  'width' =>
  array(3) {
    'optional' =>
    bool(true)
    'value' =>
    string(11) " width="$1""
    'match' =>
    string(5) "(\d+)"
  }
}
```
Build log
https://travis-ci.com/github/live627/SMF2.1/builds/221014049

**Comment by jdarwood007** [comment]
The alt needs wrapped in quotes.  How is the parser supposed to know its a param or text?

**Comment by Sesquipedalian** [comment]
> The alt needs wrapped in quotes. How is the parser supposed to know its a param or text?

[The parameter extraction code](https://github.com/SimpleMachines/SMF2.1/blob/505450e24f590b3ba1ef1bfbbd8b0bd27178228c/Sources/Subs.php#L2758-L2777) is capable of finding unquoted parameters that are followed by other parameters, so I don't think that's the problem.

Instead, I suspect the root problem is that we have two versions of the img BBCode that (a) both have the unparsed_content type and (b) both have optional parameters and _only_ optional parameters. That means the match conditions are ambiguous between the two versions: there are no conditions where a string could successfully match one version but fail to match the other. (For comparison, in SMF 2.0, we had a version of the img BBCode with some optional parameters and a version with no parameters. That difference meant that there were no ambiguous match conditions between them.)

Because of this ambiguity, the result just comes down to which version of the BBCode we test first. Since we test them in the order in which they are defined [here](https://github.com/SimpleMachines/SMF2.1/blob/505450e24f590b3ba1ef1bfbbd8b0bd27178228c/Sources/Subs.php#L1727-L1766), we end up testing the simpler version before we test the more complex one. Because that simpler version has no width and height parameters defined, the parameter extraction code doesn't consider "width" and "height" to be possible parameters names while testing against that simpler version—which is correct behaviour on its part—and therefore treats ` width=150 height=100` as plain text.

The solution should be straightforward: delete the simpler version of the BBCode and only use the one that has all the parameters defined. I'll submit a PR shortly.
