### ISSUE TITLE
Security (HTTP Response, Subresource Integrity, CORS) for SMF

### ISSUE THREAD

**Issue by WhistlingDonkey** [SimpleMachines/SMF#6664]
Hoping to get some feedback and perhaps discussion on what I've done so I can formulate a plan forward to contributing some security features for SMF 2.1 which are lacking.

As I had mentioned on the SMF forums, where I was invited to come here to discuss I have written some security features for SMF2.1. I put up a page with some screenshots and better explanations than I can type in here at: http://rptools.pdc.ca/smf/ which I'm allowed to have hosted for a week or so.

Essentially I have written in the major HTTP security related response headers and written in Subresource Integrity for jQuery. To help with the expanded functionality and keep things organised I created a new stand alone security section for this which has resulted in two new files, and potentially moving of jdarwood007's CORS feature to the new security section.

Extra but tied into this I've also added two new jQuery CDN's, removed the Auto jQuery option as it just uses Google CDN anyway and also written DNS prefetch.

I do understand the desire to get SMF out the door and adding functionality delays that but I believe security is important.

**Comment by jdarwood007** [comment]
I have always pushed for more security in our software and have written a few PRs to pull in these security features.

That said, I do agree we could use more security features on top of the recent CORS request.  I was focusing on mostly what was needed to get cross site requests working during my testing with sub domains and the $ssi_theme usage not functioning because CORS was blocking the requests to the login,register and user menus.

I agree with your points.  I had hoped for beyond 2.1 we setup a dedicated section for security with sections for Browser Security, User Security, Mod/Admin Security, and Server Security.  Maybe a section for Integrations Security and Authentication Security (such as allowing old/other password schemas and allowing SAML/other SSO methods for auth).

I was going to propose we introduce SRI into future versions of SMF because we can bake it into the implantation of calling local files and addInlineJavascript calls.

I haven't seen the DNS prefetch before though.  Interesting and would be helpful for the use of CDNs.

If this is determined to be too much to change in RC4, we should leave some hooks in the source code to allow adding these changes in easily as a mod.

**Comment by MissAllSunday** [comment]
Thank you @WhistlingDonkey for your contribution and willingness to openly discuss this matter.

Indeed security has always been a crutial part on SMF development and we are currently thinking about what should be the best approach towards the valid points that you raised. I apologize for the late response but rest assured, we are taking your points into consideration.

If needed, would you like to discuss our approach/share further ideas with us  on a semi private board over at simplemachines.org?

**Comment by WhistlingDonkey** [comment]
@MissAllSunday I'd love to discuss further if needed over at simplemachines.org.

**Comment by Sesquipedalian** [comment]
Between @WhistlingDonkey's own pull requests and @jdarwood007's work on CORS, I believe this can be closed. If there are remaining issues to be addressed here, please open a new issue report.
