### ISSUE TITLE
PHP workflow signoff check

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6666]
#### Description
Workflow ultimately missed the lack of a signoff.  

It initally "passed", but that looks more like an error than anything:
https://github.com/SimpleMachines/SMF2.1/actions/runs/721589909

Then it ultimately failed later:
https://github.com/SimpleMachines/SMF2.1/actions/runs/723493022

@live627 - any clue here?

**Comment by jdarwood007** [comment]
Github has built in checks for signed commits nowadays (they didn't when we initially set this up).   We could just set that on all branches and call it good.

**Comment by sbulen** [comment]
Related Q: How strict are we on the requirement...  Do we need to revert & resubmit?

Feels like overkill for a 4-byte change.

**Comment by jdarwood007** [comment]
In the past we have let it go for something so minor.  We have ensured the signed commits for 2 reasons
1. They are who they say they are.
2. Its a trust model sign the signature that they are sending us code to use in the project and acknowledge this.

As @BrickOzp has sent code up before signed, I believe the second issue isn't an issue as they have sent code before that was signed.  The first isn't a problem here because its a minor change that we are not concerned with malicious intent.

I do recommend that people setup GPG signed commits.  Its easier and you can default your git repo to enforce GPG signing.  I have mine set to enable GPG by default.  My global git config has this, which does this:
```
[commit]
    gpgsign = true
[gpg]
    program = /Applications/SourceTree.app/Contents/Resources/bin/stgpg.sh
```

**Comment by live627** [comment]
> Github has built in checks for signed commits nowadays 

I believe that's for gpg verification only
