### ISSUE TITLE
the message body was left empty

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#6685]
#### Description
created topic with subject test and body https://en.wikipedia.org/wiki/Kotlin_(programming_language)
clicked on post and was greeted with the message "The message body was left empty."

### Steps to reproduce
1. create new topic, subject test, body https://en.wikipedia.org/wiki/Kotlin_(programming_language)
2. click post see message "The message body was left empty."

### Environment (complete as necessary)
- Version/Git revision: as of 12am EDT last night
- Database Type: mariadb
- Database Version: 10.4.10
- PHP Version: 7.3.12

### Additional information/references

**Comment by illori** [comment]
i even tried to edit a message with quick edit and put in that link and got the message "the message body was left empty".

there was already text in the message body, this was added  to it.

**Comment by sbulen** [comment]
Confirmed...

**Comment by WhistlingDonkey** [comment]
It seems the problem is with the autoLinkUrls function. I was able to confirm it happened as posted but didn't happen when:

- The url was put in between [url] tags or
- a trailing slash was added to the non [url] tagged url as posted or
- The brackets were removed from the url or
<s>Some different words were tried inside the brackets</s>

but when I disabled the autoLinkUrls checkbox the posted url no longer caused the error and the post saved successfully.

Update: Further testing indicates the length of the string between the brackets (without a trailing slash) is causing the issue, eg
https://www.example.org/test_(abcdefg_hijklmnop)  = 17 characters = no error.
https://www.example.org/test_(abcdefg_hijklmnopq) = 18 characters = error.
https://www.example.org/test_(abcdefg_hijklmnopq)/ = 18 characters with trailing slash = no error.
