### ISSUE TITLE
Weird wording in string

### ISSUE THREAD

**Issue by Dzonny** [SimpleMachines/SMF#6688]
Just noticed, so posting it here. Is it only me or this is weirdly said ? :D

https://github.com/SimpleMachines/SMF2.1/blob/77c87540ef6f879ca52088a7e781a46678132114/Themes/default/languages/EmailTemplates.english.php#L386-L396

**Comment by Oldiesmann** [comment]
I see a few issues here...
1. "if when you took out the subscription" isn't needed
2. "you need take no action" should be reworded (a bit formal/weirdly worded)
3. The comma before "otherwise" should either be a semicolon or a period. (See the "conjunctive adverb" section at https://study.com/academy/lesson/how-to-use-otherwise-in-a-sentence.html)

**Comment by m4z** [comment]
Soo…

> 1. "[if] when you took out the subscription" isn't needed

`s/If when you took out the subscription you/If you/`?


> 2. "you need take no action" should be reworded (a bit formal/weirdly worded)

`s/you need take no action/you need not take action/`, or
`s/you need take no action/you do not need to take action/`?


> 3. The comma before "otherwise" should either be a semicolon or a period. (See the "conjunctive adverb" section at https://study.com/academy/lesson/how-to-use-otherwise-in-a-sentence.html)

`s/, otherwise you/; otherwise, you/`?

**Comment by Oldiesmann** [comment]
1. Right
2. "You do not need to take action"
3. Yes, that should work
