### ISSUE TITLE
Conflict with minimise files and external theme files

### ISSUE THREAD

**Issue by WhistlingDonkey** [SimpleMachines/SMF#6874]
#### Description
When a theme url is set to an external server or subdomain for serving theme scripts and css as static content, if minimise CSS and JavaScript files is enabled links for the mimimised files will be generated for non existent files, as they can not be created on an external server. No theme scripts and css will be loaded 

### Steps to reproduce
1. Set the theme url to an external server or subdomain that has the scripts and css for the theme being used.
2. Enable minimising scripts and css.

Given that it is possible to have theme scripts and css served externally and we don't want to take that away as it's a good (and requested) feature we should have a check that disables the minimise files setting when the theme url is external.

I'm working on a solution, but may need some guidance.

### Environment (complete as necessary)
- Version/Git revision: Github latest

**Comment by Sesquipedalian** [comment]
Confirmed.

**Comment by Sesquipedalian** [comment]
Please test #6880 to confirm that it solves the issue for you, @WhistlingDonkey.

**Comment by Sesquipedalian** [comment]
Hm. I just realized that there is a problem with the code in #6880. Sometimes admins choose to move a theme's directory outside of the main forum directory. In such cases, the code [here](https://github.com/SimpleMachines/SMF2.1/blob/d517955a5d323c953e9efc64038c788bfbd25beb/Sources/Load.php#L2720-L2728) and [here](https://github.com/SimpleMachines/SMF2.1/blob/d517955a5d323c953e9efc64038c788bfbd25beb/Sources/Load.php#L2845-L2853) will force all their CSS and JavaScript files to be treated as external, even though they are on the same server. That's no good, so I will either have to remove this entirely, or else come up with a different set of criteria.

So let me ask you a clarifying question, @WhistlingDonkey: When you say "an external server or subdomain" in your report above, which one are you actually trying to do?

If you are trying to point to a subdomain hosted on the same server, all you should really need to do is change the theme's directory to the one for the subdomain (or vice versa), so that the minimized files are created in the right location.

If you are trying to load from an external server, can you explain a bit more about the situation and what you are trying to accomplish?

**Comment by jdarwood007** [comment]
We could improve those checks to handle the external check.  Right now even if you pass external = false to the params, then it would still try to do this.  If we have set the param, we shouldn't try to determine the external but still append the theme url if determined its needed.

**Comment by WhistlingDonkey** [comment]
@Sesquipedalian, technically both. I'll try to explain.

This is all to do with my work in providing SMF with modern security (Subresource integrity) when fetching content from a server that is not the host server. For example, forum server: myforum.com , static content server: static.myforum.com .

Many sites serve their static content (scripts/css/images) from a different server (even if it's subdomain and even if it's on the same physical machine) to avoid unnecessary overheads in the server requests (such as avoiding the forum server embedding a php processor in a request for css file).

What is the use case for someone hosting their static content on a different server? apart from myself if I ran a forum I honestly don't know (it has been asked for over at simplemachines.org though) but because it can be done in SMF I'm trying to provide the much needed missing security that goes along with it.

I wish there was an easy way (I haven't learnt git yet) to show you what I've done, it might make understanding easier.

**Comment by Sesquipedalian** [comment]
I see. Well, in that case, essentially what you are trying to do is to manage all the CSS and JavaScript files manually, rather than letting SMF manage it for you. You should just turn off SMF's built-in minimization functionality, because there is no viable way to use it with the kind of setup you are describing. The problematic bit of code I had included in #6880 was basically just trying to automatically detect conditions in which the minimization function should be disabled, but based on this information I now believe it is better to leave it up to you to turn that off manually, since you are trying to manually bypass the entire built-in system anyway.

**Comment by WhistlingDonkey** [comment]
Yes, there is no way to use minimisation with an external server, hence the bug report as there is no safeguard when both conditions are true and some people may not get why their forum doesn't work in that case. I had thought of providing a flag either as a directly checked variable or via a param for the if condition but your auto code worked well, until you found the other issue. I believe your code is fine for the solution and just needs the condition it checks changed to check a themeStaticIsExternal flag, which could be set on the theme settings page.

A couple of examples:
original: if ($themeRef == 'theme' && strpos($settings['theme_url'], $boardurl) !== 0){....}

Alternate1: if ($themeStaticIsExternal){....}

Alternate2: if (empty($params['external'])){....} along with loadCSSFile('xxxxxx.css', array('external' => !empty($modSettings['themeStaticIsExternal']) ? true:false ......);

Alternate 2 requires a lot more code changes, but looks cooler!

**Comment by Sesquipedalian** [comment]
At this point it is safe to say that we will not be adding direct support into SMF for what you are trying to accomplish. However, you should be able to achieve your goals using `integrate_pre_css_output` and `integrate_pre_javascript_output` integration hooks. Those will allow you to capture the list of CSS and JavaScript files that are supposed to be output so that you can do your own thing with them in a custom function in your mod.

**Comment by jdarwood007** [comment]
Are the static files still hosted on the same server, just using a different domain?  If so then this shouldn't be a problem.  But any dynamically generated files will not work on a remote domain under normal conditions.

You could build a 3rd party plugin for the remote systems to load the file from the main domain if a request occurs that it doesn't have a cache for.  But this is something outside of SMF's setup.

FYI, Simplemachines.org uses multiple domains and the secondary domain loads all static content.  However they are internally on the same server, but the static files do not pass beyond the front end nodes, so they can't load any application content (i.e. PHP).  I haven't tested with minimized files on the secondary domain, but it should work as the front end nodes understand how to get to the *.css and *.js files.

**Comment by WhistlingDonkey** [comment]
If I could rename this topic I would (even though it is a correct description). The problem is when the static files are separated from the rest of the themes files (which separating static from the potentially dynamic is a common thing to do) where theme_url and theme_dir ultimately have different directories.

So server A hosts the forum and server B hosts the "static" content and both are on the same machine.

So with the theme directory as /var/www/serverB/Themes/CoolTheme and all of CoolTheme's files located there and theme_url points to server B it's not an issue and the minimised files can be created on server B and will be loaded by the browser but separating the static from the rest of the themes files so server A has the theme php etc at /var/www/serverA/Themes/CoolTheme and theme_dir is set for server A but server B has the scripts and css (the static) at /var/www/serverB/Themes/CoolTheme and theme_url points to server B the minimised files will try to be created on server A because that's where theme_dir points to but the browser will be pointing to server B, where the minimised files don't exist.

This is the same result as if server B was an actual physically separate machine,

Probably the only away around that would be to specify the template dir, script dir and css dir separately in the theme settings so the script dir and css dir could be used in the minify function, and then either treat an empty dir as external or give a "this is external" checkbox as well. or we could just give a "this is external" checkbox so minimising doesn't get called, or we can just hope nobody separates the static from the rest of the theme files and then tries to minimise.

**Comment by Sesquipedalian** [comment]
Please see https://github.com/SimpleMachines/SMF2.1/pull/6882#issuecomment-887792950
