### ISSUE TITLE
function removeMessage - add permission override check

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#6902]
function removeMessage - add permission override check

Was working on a mod and today I realized there is no way to override the permission check. I wanted to use this function to delete auto generated messages inside a topic in a board that the user does not have access to delete messages.
I will need to currently write my own function to do so.

**Comment by Sesquipedalian** [comment]
I don't think we will be adding this to SMF in the foreseeable future.

However, if you want to propose some more integration hooks in convenient locations, that'll be another matter.

**Comment by live627** [comment]
This cannot be solved with integration hooks.

**Comment by Sesquipedalian** [comment]
Why not? A hook at the start of `removeMessage()` (before any of the calls to `boardsAllowedTo()`) could set certain triggering conditions to say that the the current board should be added to the list of boards where the user is allowed to delete other's replies. Then a hook near the end of `boardsAllowedTo()` could manipulate the list of boards that a user has permission to do certain actions on.

**Comment by live627** [comment]
I feel like that's over-engineering a solution to a simple problem, namely, adding a boolean param to override the permissions checks.

**Comment by Sesquipedalian** [comment]
There are a LOT of different calls to `isAllowedTo()` and `boardsAllowedTo()` inside `removeMessage()`. Adding `!empty($perm_override)` checks to bypass them all would be messy, especially since this isn't something that we would ever bypass in normal SMF operation. But simply using a hook to temporarily grant a user the 'delete_replies' permission (or whatever) should allow @VBGAMER45 to do exactly what he needs.
