### ISSUE TITLE
Newicon not always ref to right page

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#6911]
#### Description
the newicon not always referer to right page,
while doing so the "new" id element is not existing.

this icon here:
![grafik](https://user-images.githubusercontent.com/1782906/128120064-c2ce9ed5-edf9-48d1-a9fc-37558ec462e3.png)
got as url something like:
...index.php/topic,123401.msg1194724.html#new

Essential the topic id and the next possible msg id of a new msg and
the #new as jump to an id.
so the program logic is here that a page is selected where a msg higher and near as possible is choosen and
then is use hope that somewhere an element with id new is exists (without testing). 

### Steps to reproduce
lets pretend that 15 post a shown per page
1.  fill a page with 15 posts account A so that we one post miss for open next page
2.  login with account B click on new icon:
![grafik](https://user-images.githubusercontent.com/1782906/128120636-dbc8bee9-2e83-4a2f-9e04-bb51d26441c8.png)
3. use back page function
4. post with A a new post, a new page get added to the post
5. click again with B on newicon (without reloading)

result: B lands on page 1 with no element with id new

alternative to use back page function would be to open nexicon in a new tab close this than and click again on this.

### Additional information/references
this issue got fixed by #6909 but declined

**Comment by sbulen** [comment]
I am not sure this is really an issue.  Navigation using the BACK key will bring you to a stale page.  

Even worse than the above:  What if user A doesn't post in step 4.  But the NEW icon is still there.   But there are no NEW posts at all...  

Even worse than that:  You can hit BACK 20 more times and see a completely different set of NEW buttons - possibly from a day earlier - none of which are current anymore.  Clicking on one might bring you to the middle of a bunch of posts you already read.

Browser BACK/FORWARD buttons yield stale results - on most websites.  I think this is well understood browser behavior.  

Any actual page navigation gets you a current set of NEW icons.  

Make sense?

**Comment by albertlast** [comment]
In my eyes it make no sense,
i don't talk about the issue that the newicon is existing in this case.
i talk about that the url of newicon target the wrong page and
i show in the pr that this behavior can be changed,
also the user get no feedback that he is on the wrong page.

You need to keep in mind that beside of using back key als tab opening by middle mouse button for exp. exists and
when you open a page this way your board index get "stale" without usung back key navigation.

And to force the user always to refresh the index board page only to get to the right side,
is very bad idea of resourcen pov(a rerender of a page cost cpu time and network traffic) only because smf  is lazy programmed here in this case.

Also don't forget between this action can be some time,
so maybe you was between this step afk and forget after being back that the page is stale an click again on the newbutton and
land on the wrong page.

**Comment by sbulen** [comment]
As noted above, and also on #6909 , this is really not an issue.  And we are not going to revisit how the NEW icons work.

**Comment by Sesquipedalian** [comment]
While looking at something else in Display.php, I noticed that we actually already have all the functionality in place to deal with these kind of awkward edge cases, but we just haven't been using it.

Specifically, if `$_REQUEST['start']` is set to `new` when loading a topic in Display.php, this chunk of code looks up the first new reply on the fly:
https://github.com/SimpleMachines/SMF2.1/blob/5356c2da692de9289ff052898743ab9d61a8cd20/Sources/Display.php#L243-L274

That means we already have the ability to use `?topic=123.new#new` instead of `?topic=123.msg456#new` to take the user to the most recent replies. The difference is that when the start is set to `new` we look up the id of the first unread message in `Display()`, rather than specifying one in advance on the message index with `msg456`.

This functionality has been around since before 2.0 was released, and we use it [when the user clicks the Previous/Next Topic links](https://github.com/SimpleMachines/SMF2.1/blob/5356c2da692de9289ff052898743ab9d61a8cd20/Sources/Display.php#L125). It works flawlessly. #6909 was rejected because it introduced a new query, a new `$_REQUEST['start']` value, etc., that would all need to be tested. In contrast, tweaking our "New" links to use `?topic=123.new#new` would be trivial.

**Comment by Sesquipedalian** [comment]
... And after some quick testing, I now see why we don't actually use this. If the URL is `?topic=123.new#new`, then refreshing the browser while viewing a multi-page topic will take you to the next page in the topic rather than refreshing the current page. That's not desired behaviour. 

We could fix that by issuing a `redirectExit()` to `?topic=123.msg456#new` as soon as we know the id_msg of the first unread reply, but that'd push us back into the realm of new behaviour that would need to be tested extensively.
