### ISSUE TITLE
Fix missing values in log_actions timeout protection

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#6946]
#### Description
```
Fix missing values in log_actions
```

This does not have any timeout protection.  Current system has over 100k log_actions.  This step attempts to query through all 100k at once and upgrade them.  From testing it can perform about 500 every 10 seconds.  Most of this delay is the process of unserialize and update commands.

Should add some timeout protection to prevent this from being an issue.

**Comment by sbulen** [comment]
Were there 100k records that met the criteria?  Or 100k records total in log_actions?

The query is:
```
SELECT id_action, extra
		FROM {$db_prefix}log_actions
		WHERE id_member = 0
		AND action IN ('policy_accepted', 'agreement_accepted')");
```
https://github.com/SimpleMachines/SMF2.1/blob/910302afe82cc9cdf3be1dddf703223e52f18c2c/other/upgrade_2-1_mysql.sql#L3658

This should only be the # of folks who accepted the agreements between 2.0.16 & 2.0.18.  The bug was fixed in 2.0.18, and id_member wouldn't be 0 anymore.

**Comment by jdarwood007** [comment]
I don't have that information anymore.  That was the table size.  But it would be an issue for large forums

**Comment by sbulen** [comment]
Do you really still feel this is a 2.1.0 requirement?  This should be extremely rare, and only on truly massive forums.
