### ISSUE TITLE
MOVED Email notification missing links

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#6999]
#### Description
I received a mod notification that a topic has been moved.
It's missing the links and it has different language too?

I'm using english in the forum.
I'm assuming Irisado is using the forum in spanish

![Screenshot_41](https://user-images.githubusercontent.com/3318127/130332454-7bbfe3c4-c1b3-4bcf-8d09-eaa7cf126069.png)

**Comment by Sesquipedalian** [comment]
This appears to be a side effect of changing `$txt['movetopic_default']` to use `sprintf()` instead of manually concatenating it in the language file.

First, here we take steps to ensure that the value of `$txt['movetopic_default']` is always in the forum's default language:
https://github.com/SimpleMachines/SMF2.1/blob/b7e2a4b7f8c0aa21a4ae224e39364914f3cb064a/Sources/MoveTopic.php#L109-L116

Then here we use `sprintf()` to insert the values of `$txt['movetopic_auto_board']` and `$txt['movetopic_auto_topic']` into `$txt['movetopic_default']`:
https://github.com/SimpleMachines/SMF2.1/blob/b7e2a4b7f8c0aa21a4ae224e39364914f3cb064a/Themes/default/MoveTopic.template.php#L103
At this point, `$txt['movetopic_auto_board']` and `$txt['movetopic_auto_topic']` are both in the user's language rather than the forum's default language.

This is different from the behaviour in SMF 2.0, where we did not use `sprintf()`, but instead concatenated the value of `$txt['movetopic_default']` directly in the language file itself, like so:
```
$txt['movetopic_auto_board'] = '[BOARD]';
$txt['movetopic_auto_topic'] = '[TOPIC LINK]';
$txt['movetopic_default'] = 'This topic has been moved to ' . $txt['movetopic_auto_board'] . ".\n\n" . $txt['movetopic_auto_topic'];
```
Because SMF 2.0 concatenated the values, the tokens inserted into `$txt['movetopic_default']` were always in the same language as `$txt['movetopic_default']` itself.

The bug then arises here:
https://github.com/SimpleMachines/SMF2.1/blob/b7e2a4b7f8c0aa21a4ae224e39364914f3cb064a/Sources/MoveTopic.php#L267-L278
Lines 275 to 278 assume that `$txt['movetopic_auto_board']` and `$txt['movetopic_auto_topic']` are in the same language as `$txt['movetopic_default']`. That assumption was always true in SMF 2.0, but may not be true in SMF 2.1.

**Comment by Sesquipedalian** [comment]
I have a fix coming for this soon, but first I want to check to see if this affects similar situations like splitting/merging, etc.
