### ISSUE TITLE
"Enabled BBC tags" for signatures doesn't do anything

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#7050]
#### Description
The "Enabled BBC tags" setting for signatures should in theory allow the admin to choose which BBC are allowed in signatures, which may or may not be the same as the set allowed in posts, etc. In practice, however, it does nothing.

### Steps to reproduce
1. Disable some or all of the BBC in `?action=admin;area=featuresettings;sa=sig`
2. Create a signature using the BBC that are supposedly disabled.
3. Observe that the supposedly disabled BBC work anyway.

### Environment (complete as necessary)
- Version/Git revision: 6776b76
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references
From what I can tell, `profileValidateSignature()` is supposed to make sure that only allowed BBC are used when the user modifies their signature, but it doesn't do so successfully. Meanwhile we don't check for disallowed BBC at all when loading the signature in `loadMemberContext()`.

**Comment by BrickOzp** [comment]
A non admin can not add unsupported bbc tags. An error is shown when the signature is previewed or the profile saved.
However an admin can do it because all checks are bypassed. // Admins can do whatever they hell they want!

If a bbc tag is allowed and a user has used it in the profile. Then the bbc tag is removed from the allowed, the bbc tag is still shown in the signature, but the user can't change his profile unless the bbc tags are removed.
