### ISSUE TITLE
Non graphic characters in member names can allow impersonation

### ISSUE THREAD

**Issue by WhistlingDonkey** [SimpleMachines/SMF#7085]
#### Description
Couldn't think of a better title...

As discussed at https://www.simplemachines.org/community/index.php?topic=578926 , it is possible for a member to insert non graphic characters into their real name and display name which allows them to have what appears to others the same display name as another member .  This can allow, however futile the attempt, impersonation of another member. At the least it can just cause confusion.

### Steps to reproduce
1. Create two members.
2. Using a non graphic character (eg, 0x0F / u+000F) change the display name of one of the members to match the other member.

eg,
Member 1 display name: TestMember
Member 2 display name: Test`[non graphic character]`Member

Member 2's display name will show the same as member 1's display name.

### Version information
Version: Github latest

### Additional information/references
It appears that the symbol for a non graphic character is shown on the Account Settings page where you enter the display name but nowhere else.

**Comment by Sesquipedalian** [comment]
This issue report is timely. I am currently working on PRs to address string input sanitization, normalization, and validation issues.

**Comment by WhistlingDonkey** [comment]
Happy to see you self assign this, I started some basic testing but I think it'd take me too long to come up with a workable solution.

What I do think though, is that instead of stripping out the characters we don't want from the user input for the real name and display name like we do now, we instead just throw the user an error to fix their input if we detect any characters we don't allow.

**Comment by live627** [comment]
possibly related to https://github.com/SimpleMachines/SMF2.1/pull/6786

**Comment by Sesquipedalian** [comment]
> possibly related to https://github.com/SimpleMachines/SMF2.1/pull/6786

Yup. I've cherry-picked the changes from that PR that deal with character sanitization and white space normalization into the new PR I am putting together. 

I haven't (yet?) found it necessary to include the changes related to entity handling from that PR, but we may need to do that eventually anyway. We recently found and fixed some bugs in 2.0.x regarding entity handling, and those bugs are present in 2.1 as well—albeit mostly hidden because all language files in 2.1 use UTF-8.

**Comment by Sesquipedalian** [comment]
Also, just so everyone knows, I don't think we can fully solve the issue of spoofing via invisible characters. We can improve the situation, for sure, but we can't close off the possibility entirely.

This is because there is a class of invisible Unicode characters called formatting characters that are required for various non-European language scripts and for emoji support. If we forbade formatting characters, we'd hobble or break support for those languages (as well as provoking the ire of those who insist that there is a very big difference between ❤️ and 💚). 

I looked into the idea of only permitting formatting characters when they occur in positions where they make a legitimate, visible difference to the string's rendering, but that turned out not to be viable. There is no programmatic, comprehensive way to determine whether a given formatting character is "legitimate" in a given context, and the Unicode Consortium's documentation discourages even trying to do such things.

Still, as I said, we can definitely improve the situation. Even if we can't forbid the formatting characters, there are other invisible characters that we can forbid, and we can check in the middle of strings, not just at the beginning and end. So that will minimize the possibilities, even if it doesn't eliminate them all.

**Comment by Sesquipedalian** [comment]
Because I am too stubborn for my own good, I actually did figure out how to solve this pretty comprehensively in #7102, despite what I said in my previous comment.
