### ISSUE TITLE
IDN Homograph URL spoofing

### ISSUE THREAD

**Issue by WhistlingDonkey** [SimpleMachines/SMF#7095]
#### Description
Another one for discussion. While we are talking about Unicode and name spoofing (#7085), this is another one I was playing around with in the last couple of days. While I don't think I have personally encounted IDN spoofing myself (who really knows but I have no need to go to places like apple.com or adobe.com) it is a very real thing and is used in the wild.

I think a simple mouse over could be introduced that shows the true URL (Punycode), like the attached which is a live test on my test installation. There's a couple of ways this could be done.

1 -  A MouseOver tooltip on the href attribute showing the Punycode URL regardless,
2 -  A MouseOver tooltip on a (?) after the URL showing the Punycode URL if the Punycode URL doesn't match the URL.

I think option 2, as shown in the image would be the better one (which could also potentially open a help box when clicked explaining the alert and to offer caution). This so far has easy to implement with minimal additional code.

![uri_spoof_test1](https://user-images.githubusercontent.com/81920542/134461095-d0329487-b3d0-4389-bd13-19cef6dcb647.png)

### Steps to reproduce
1. Create a post with this link in it: https://www.аррӏе.com/ (note, if the link does not look like apple.com then use a Punycode converter like this one https://www.punycoder.com/ to encode the Punycode link https://www.xn--80ak6aa92e.com/ back to it's IDN)
2. The link should look like it's for apple.com, but it isn't.

### Environment (complete as necessary)
- Version/Git revision: Git Latest

**Comment by m4z** [comment]
I wouldn't "hide" such info in a popup. Display it for everyone to see. (Also, if such spoofing is detected, we should avoid creating the `<a>` tag altogether.)

For example, Gmail detects the GH mail notification of this issue as spam (you can't click links of mails in the spam folder, you have to manually mark them as "not spam" first) and displays a big red warning banner at the top (that is somewhat misleading because of incorrect details):
```
This message seems dangerous
The sender’s email address[sic] uses abnormal characters, which might be used to spoof 
real addresses. Avoid clicking links, downloading attachments, or replying to this message.
```

I don't think the message is about the `/^reply-to: reply+[A-Z0-9]{42}@reply\.github\.com$/` mail address (and definitely not about `from: notifications@github.com`), but rather about your demo links in the message body.

**Comment by WhistlingDonkey** [comment]
Are you really seeing a regex in the reply-to field? That would be weird and GMail would definitely think that's suspicious!

The problem is we can't detect spoofing just by relying on the fact that the url and the punycode url are different and preventing the generation of the <a> tag because that would kill all links for legitimate IDN's as well, which we probably don't want to do.

The mouseover (actually hover) on IDN's in my test is the simplest, though the wording could obviously be improved, but I'm wanting to hear all ideas.

**Comment by m4z** [comment]
> Are you really seeing a regex in the reply-to field? That would be weird and GMail would definitely think that's suspicious!

No, sorry, I just didn't want to share the specific address, so I showed the abstracted pattern. I thought that was obvious, I don't think mail servers would even keep such invalid tags.


> The problem is we can't detect spoofing just by relying on the fact that the url and the punycode url are different and preventing the generation of the tag because that would kill all links for legitimate IDN's as well, which we probably don't want to do. [...] though the wording could obviously be improved, but I'm wanting to hear all ideas.

Agreed. I don't know enough about IDNs to comment if permit- or filter-lists of would be feasible. But I think a simple "(?)" is too subtle, instead I would make the link text something really visible like "(Warning: This link contains international characters, which are sometimes used by scammers to create fake websites. Please be very careful when entering personal data like mail addresses or passwords!)"


> The mouseover (actually hover) on IDN's in my test is the simplest, [...]

I don't know the difference between mouseover and hover (and it probably doesn't matter in this context).

**Comment by Sesquipedalian** [comment]
> I don't know enough about IDNs to comment if permit- or filter-lists of would be feasible. 

It would not be feasible, no. But moreover, it also would not be _appropriate_ for SMF to do this even if it were feasible. 

[Unicode Technical Report #36: Unicode Security Considerations](https://www.unicode.org/reports/tr36) lays out recommended practices regarding IDNs for end users, programmers (like us), user agents (i.e. web browsers, etc.), registries, and registrars in [section 2.11](https://www.unicode.org/reports/tr36/#Visual_Spoofing_Recommendations). In particular, the recommendations in [section 2.11.2.B](https://www.unicode.org/reports/tr36/#Recommendations_General) are the ones that apply for us regarding this situation. Basically, we need to make sure that we sanitize and validate the URL string in order to ensure that it doesn't contain any illegal characters, etc.

 In contrast, the tasks of identifying possible spoofs, alerting the user to them, maintaining whitelists of domain names, etc., are covered in [section 2.11.3](https://www.unicode.org/reports/tr36/#Recommendations_User_Agents), the "Recommendations for User Agents" section. This is because browsers running on users' devices, rather than software running on a server, are in the best position to do these tasks. 

It might _seem_ like a good idea for SMF to add warnings to links that we suspect might have a higher possibility of being a spoofed address, but in reality we are poorly positioned and poorly equipped to make such judgements. Put bluntly, we don't have a clue whether any well-formed URL points to a safe website or a malicious one. If we start slapping warning labels on links merely because they contain IDNs, all we will be doing is spreading [FUD](https://en.wikipedia.org/wiki/Fear,_uncertainty,_and_doubt) on matters where we literally don't know what we are talking about.

... Besides, creating misleadingly labelled links in a forum is trivial even without IDN homographs:
```
[url="https://evil.com"]https://www.apple.com[/url]
```
