### ISSUE TITLE
8: Undefined index: modify_time in CreatePost-Notify.php for cron

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#7108]
#### Description
Cron
Error message
8: Undefined index: modify_time
File
/.../Sources/tasks/CreatePost-Notify.php
Line
227
URL of page causing the error
.../cron.php
	
    #0: smf_error_handler_cron()
    Called from /.../Sources/tasks/CreatePost-Notify.php on line 227
    #1: execute()
    Called from /.../cron.php on line 233
    #2: perform_task()
    Called from /.../cron.php on line 127

**Comment by BrickOzp** [comment]
This probably happens when a user posts a new message with a mention in it. When the background task should send out the notifications, respawns the task. Next time the task is executed this error happens since new posts does not have a modify_time.

**Comment by BrickOzp** [comment]
@Sesquipedalian While investigating this issue I tried to get a task with the type 'edit'.
This is done in Subs-Post.php on line 2350.
But $msgOptions['approved'] seems not to be set so a task is never created. Is this intentionally?

**Comment by Sesquipedalian** [comment]
It was not intentional. Your solution was good. 🙂

**Comment by DebiWebi** [comment]
I'm not a coder, I'm a SMF fan and have this problem on my forum. It began when the site was updated to fix partial quote issues. I'm having a hard time figuring out if this has been fixed in #7113 (above). One thing I don't understand is the error is attributed to "Guest," and guests on my forum are not permitted to post.

> This probably happens when a user posts a new message with a mention in it.

Since the update, members are not getting emails of mentions, only alerts even though both are checked in Notifications. ALSO, I was mentioned in a post today at 2:39 pm and got another Cron error at 2:47 pm so it does seem to be related.

**Comment by BrickOzp** [comment]
Do you have applied the fix from #7113?

**Comment by DebiWebi** [comment]
I have not, @Kindred-999 is going to help me with that. I'll update afterwards.

**Comment by DebiWebi** [comment]
@BrickOzp fix applied, it fixed that issue for us.
