### ISSUE TITLE
I receive notification of more than one reply (but not all)

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#7110]
#### Description
email notification of "new replies to the topic I post in" is turned on
There were 8 new replies
I received email notifications for 3 of them.

I'd expect either 8 notifications or 1 notification of the first reply only (which is the 2.0 standard)

### Environment 
- SMF 2.1 RC4 GitHub from Oct 1
- MySQL
- PHP Version: 7.1

**Comment by Sesquipedalian** [comment]
Is this still happening, @Kindred-999?

**Comment by sbulen** [comment]
A couple notes on this:
1 - #7510 will fix the circumstances where the emails weren't sent when they should be sent.  
2 - A clarification - due to the anti-spam measures in notification processing, you may not get 8 emails for 8 responses.  There is a deliberate built-in delay (the "respawn" logic) that must pass before the notification is sent.  If other replies are posted in that window, only one email is sent.  E.g., if the 8 responses were all within one minute, you would likely only get 1 notification.  
3 - First reply only is still an option, and can be updated under your notification settings.  Pretty sure it's still the default.

I am going to close this out since #7510 was merged.
