### ISSUE TITLE
Issue with avatars from integrated [Oxygen] gallery

### ISSUE THREAD

**Issue by Hatshepsut71** [SimpleMachines/SMF#7139]
#### Description
Hello,
Just upgraded two SMF 2.1 forums with latest build ed0f841
Users with avatars selected from integrated [Oxygen] gallery are displayed with default avatar only.

### Steps to reproduce
1.  Upgrade forum with latest build ed0f841
2.  Open some user profile and select an avatar from integrated [Oxygen] gallery
3.  Open user's post and topics and see avatar displayed

### Environment (complete as necessary)
- Version/Git revision: ed0f841
- Database Type: MariaDB
- Database Version: 10.3.31
- PHP Version: 8.0.11

### Additional information/references

**Comment by Oldiesmann** [comment]
Confirmed. The problem is it's setting the URL to the avatar incorrectly - it's setting it to "Oxygen/<filemane>" rather than the full URL to the image, so SMF determines that the file doesn't exist and displays the default one instead. I'll dig more into it this weekend if nobody beats me to it.

**Comment by Oldiesmann** [comment]
Did some digging and tracked down the issue. It was introduced in #7124, specifically this line of code in the set_avatar_data function:
```php
				$image = parse_iri($data['avatar'], PHP_URL_SCHEME) !== null ? get_proxied_url($data['avatar']) : $modSettings['avatar_url'] . '/' . $data['avatar'];
```
The parse_iri function is a wrapper for PHP's parse_url function that properly handles unicode stuff. The problem is it behaves a bit differently. If the parse_url call doesn't return an array, the URL is passed through PHP's rawurldecode function and the result of that call (a string) is returned, so we're always passing the url through get_proxied_url even if we should be adding the URL to the avatars directory instead.

The best way to handle this in my opinion is to just check whether the result of parse_iri is an array. If it is then we know we've got a valid (external) URL.
