### ISSUE TITLE
Formatting on ban list needs some tlc

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7278]
#### Description
![image](https://user-images.githubusercontent.com/23568484/151674794-be6b96b7-c7c5-493b-8110-b6e4885be949.png)

### Steps to reproduce
1. Enter very long strings with no breaks in ban reason & notes

### Environment (complete as necessary)
- Version/Git revision: Current

Not a massive issue, but should be addressed at some point...

**Comment by XinYenFon** [comment]
Two things,

a) If ban name is too long it gives error and logs it instead of giving SMF handled error;

```
Data too long for column 'name' at row 1
File: C:\xampp\htdocs\smf21\Sources\ManageBans.php
Line: 1565
```

b) We already have word_break as a class... can be added to the following parts to resolve the issue...

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/ManageBans.php#L147
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/ManageBans.php#L161
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/ManageBans.php#L174
