### ISSUE TITLE
Settings not created with all comments during install if file is initially missing

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7296]
#### Description
I blew away my Settings.php and uploaded the installer files to do a fresh install.  I didn't upload a fresh Settings.php.  After the install I realized that the Settings.php is missing comments.  So I tried the recreate Settings.php forum maintenance action.  No change.

### Steps to reproduce
1. See Settings.php example or description.
2. 

### Environment (complete as necessary)
- Version/Git revision: latest
- Database Type: N/a
- Database Version: N/a
- PHP Version: 8.0

### Additional information/references
[Settings-sample.txt](https://github.com/SimpleMachines/SMF2.1/files/8011189/Settings-sample.txt)

**Comment by Sesquipedalian** [comment]
Hm... So far I cannot reproduce this.

I manually substituted my own test forum's values into the Settings-sample.txt that you provided, while being very careful to maintain the exact same layout as in your original. When I ran the "Rebuild Settings.php" maintenance task, all the contents were rearranged and all the comments were inserted as expected.

I haven't yet tested running a fresh install with no preexisting Settings.php file, so I can't say for sure yet whether that makes any difference. Still, my current suspicion is that this might be a file permissions issue.

**Comment by Sesquipedalian** [comment]
Just tested what happens if delete the Settings.php file. Received some error messages during the install about $boarddir, etc., being undefined because the path correction code in Settings.php assumes they have been, but everything proceeded anyway. At the end of the install process, Settings.php was formatted just like in your example, @jdarwood007. However, running the maintenance task afterward did clean it all up and make it pretty.

**Comment by jdarwood007** [comment]
Odd it didn't clean it up on mine.  Maybe that one was permissions.  If so, the maintenance task did not alert that it was unable to write, it said successful.
