### ISSUE TITLE
vsprintf() passed wrong param type when an error occurs uploading attachments

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#7320]
#### Description
Under certain circumstances, if something goes wrong while uploading an attachment, the code that is supposed to report the attachment error itself causes a more severe error by attempting to pass a non-array to the second parameter of the `vsprintf()` function.

Initially reported on the forum at https://www.simplemachines.org/community/index.php?topic=580699.0

### Steps to reproduce
1. According to the original report, attempting to upload a certain PNG file triggered this.
2. 

### Environment (complete as necessary)
- Version/Git revision: 2.1.1
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references
It looks to me like we may have a number of places in the relevant code where `vsprintf()` is passed scalar values where arrays are expected. The fix will probably be to change `vsprintf()` to `sprintf()` in all these cases.

**Comment by d-tol** [comment]
![4](https://user-images.githubusercontent.com/35025445/153810646-db2b0751-f27b-48e7-b8b5-7996a0d9227e.jpg)
This happens with all the images I'm trying to upload, here is one of them.

**Comment by d-tol** [comment]
There's a progress on the error. My forum was running on PHP 8.0 and because of another problem I've downgraded to 7.4 and tested again.

Now, when trying to upload a new photo I'm getting:

> 3.jpg There was a problem during the uploading of 3.jpg.
Your attachment has failed security checks and cannot be uploaded. Please consult the forum administrator. 86.3 KB

Then I removed the security checks on the images and now everything works.
