### ISSUE TITLE
Grammar issue in upgrader's time elapsed

### ISSUE THREAD

**Issue by SugarD-x** [SimpleMachines/SMF#7323]
#### Description
In the upgrader as of 2.1.1, when the time elapsed reaches one minute, it shows "1 mins", which is grammatically incorrect.

### Steps to reproduce
1. Upgrade your forum using the upgrader.
2. Allow the time elapsed to reach one minute.

### Environment (complete as necessary)
- Version/Git revision: 2.1.1 release version
- Database Type: MySQLi
- Database Version: 8.0.27
- PHP Version: 7.4.27

### Additional information/references
This appears to be a similar issue to bug #2020.

![1minssmfupgrader](https://user-images.githubusercontent.com/4693806/153908517-adb4407d-b78d-4a10-b7c8-2c619500a407.png)

**Comment by SugarD-x** [comment]
I just noticed an inconsistency with this too. Seconds are written out completely, but minutes are being abbreviated.

**Comment by jdarwood007** [comment]
I'm fine with fixing "mins" to "minutes", but fixing the plural issue, is not going to be done done.  I understand this doesn't always make sense in other languages, but we have known that plural issues have existed for a while in the code and as linked is a very big discussion on the complications and logistics around it.  Because not all languages conform to the same standardization of "plural" for numbers.

**Comment by SugarD-x** [comment]
Wouldn't it be so easy as to just add another check in the upgrader/installer if the elapsed time is `1` under `$mins`, to use a different language variable, and if not, continue normally? For the languages file, you could add an additional line which contains the corrected text for affected languages, and leave the translation string blank if it doesn't apply to that language. In the upgrader/installer, adding another check if the additional variable is null or not could define whether you even try to use it when 1 is "true".

Theoretically this could also work for the "1 days" issue. I don't see any potential performance losses here either, and other affected languages could also benefit from this type of workaround.

I'm by no means an expert with PHP or SMF's internal workings, but from what I'm seeing in the way translations are handled, this doesn't seem like it'd be very complicated to implement...assuming I managed to explain it properly. 😄 

(Please don't take any of this as demanding or insulting. I don't intend for it to come across that way. I love the work you all have done and I only want to see it continue to improve. This is the best forum software I've ever used, and I appreciate all of you!)

**Comment by jdarwood007** [comment]
The plural issue won't be fixed in 2.1.x.  It requires a lot of underlaying changes to get this done right and thats a thing for the future.  Yes the simple fix for what you see would be adding yet another string.   But I don't see the benefit of fixing it when we can work on fixing this 100% right in a future version by doing the right work to handle all possibilities of handling all languages properly.  Some languages change the wording depending on the last number.

The Mozilla document in the issue no longer exists, but it documented I think the best way we needed to handle this.

**Comment by sbulen** [comment]
Look at the strings...  There are actually many such strings, here's an example:
https://github.com/SimpleMachines/SMF2.1/blob/b9e3b273aa8c1dcdde424dfb751e65bd223f2d4c/Themes/default/languages/Install.english.php#L339

Note that hours, minutes & seconds can all be singular or plural.  So, each one of these strings would need to turn into 2^3, or 8 strings...

And each of those sets of 8 will need translations...  

(Unless we rewrite all such logic...)

For a tool that is hopefully run only once.

I'm with @jdarwood007 - not remotely a priority.  This should be closed.

**Comment by Sesquipedalian** [comment]
Correctly handling pluralization rules in multiple languages is far more complicated than one might imagine. To get a sense of how many rules and variations need to be accounted for, see [this](https://web.archive.org/web/20210216044115/https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals), which still probably doesn't cover everything.

**Comment by SugarD-x** [comment]
I appreciate the explanations on the issues that I wasn't aware of.

As far as changing `mins` to `minutes` to match `seconds`, could that still go forward given the inconsistency for the English translation in the installer/upgrader?
