### ISSUE TITLE
set_time_limit may not work some cloud providers

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#7327]
I have no idea but set_time_limit function wasn't allowed in my cloud provider.

Due to this unmeaningful limitation I have to change set_time_limit functions to comment.

The hard part was upgrade.php and post.php. Also there are some other files.

https://github.com/SimpleMachines/SMF2.1/search?q=set_time_limit

#### Description
set_time_limit function may not be allowed on some cloud providers

### Steps to reproduce
1. You may dissallow set_time_limit function via php.ini
2. Try to send a post via SMF 2.1.1.

### Additional information/references

It's not SMF bug, but providers are so mean.

**Comment by Sesquipedalian** [comment]
I could not reproduce the issue using the steps provided, but I did find this line in the installer that would cause a warning to be issued on hosts that have the `set_time_limit()` function disabled:
https://github.com/SimpleMachines/SMF2.1/blob/a2d261dc6006013272de1fe76ffccdd76aacd783/other/install.php#L1296

In all other cases that I can find, we always prefix the `@` operator when calling that function, which will suppress warnings about the function being disabled.

**Comment by jdarwood007** [comment]
The `@` operator was changed in recent PHP versions.  @libreajans What version of PHP does your host have?

**Comment by sbulen** [comment]
I don't think the installer has an error handler yet.  It would need the same treatment as the upgrader in #7161 to support php8.

**Comment by ghost** [comment]
Thank for the answer.

PHP version is 8.0.15

These functions were disabled by the provider.

```dl, sh2_exec, diskfreespace, disk_free_space, disk_total_space, escapeshellarg, escapeshellcmd, exec, highlight_file, link, lchgrp, lchown, passthru, pclose, popen, proc_close, proc_get_status, proc_nice, proc_open, proc_terminate, set_time_limit, shell_exec, show_source, symlink, system, mail, sendmail```

**Comment by Sesquipedalian** [comment]
> PHP version is 8.0.15

Ah, yes, that makes a difference. Now I see what is going on. The problem isn't the changes to the `@` operator in PHP 8, but rather the changes to the way disabled functions are handled:

> Disabled functions are now treated exactly like non-existent functions. Calling a disabled function will report it as unknown, and redefining a disabled function is now possible.
-- https://www.php.net/manual/en/migration80.incompatible.php 

Under PHP 7, even if an internal function was disabled, it would still be a defined function, and so calling it would merely generate a warning which could be suppressed by the `@` operator. 

Under PHP 8, if an internal function is disabled it is considered to not even be defined, which means calling it (1) causes a fatal error that cannot be suppressed by `@` and (2) halts execution.

Apparently the PHP developers thought this was a worthwhile change because it allows polyfill libraries to provide user-defined functions to replace disabled internal functions, but the side effect appears to be that scripts now *must* include polyfills for missing functions, or else add a whole bunch of `function_exists()` tests all over the place. 

We certainly don't want to insert a gazillion `function_exists()` tests throughout our codebase, so we're going to need to come up with a more clever solution...

**Comment by jdarwood007** [comment]
Looking at that list of disable functions,

- hostname lookups will fail
- emails using PHP mailer will fail
- Exporting profile data won't know free space limits
- Many places where we change the time limits will fail

We can be expected to fix all disabled functions.  But we can expect to fix a few.

We could include Subs-Compat.php and if the function is undefined, define it.  Typically this is used to compat older PHP versions with missing functions we need/call in newer versions.  But in this case, it could be used to correct this logic in PHP.

We could also use a smf_set_time_limit() function that is a wrapper.

**Comment by Sesquipedalian** [comment]
> We could include Subs-Compat.php and if the function is undefined, define it. Typically this is used to compat older PHP versions with missing functions we need/call in newer versions. But in this case, it could be used to correct this logic in PHP.

That's what I am working on now.

**Comment by Oldiesmann** [comment]
I personally would run from a host that has that many functions disabled. Some are harmless (the two "escape" functions and the "disk" functions as well as highlight_file/show_source) and I doubt you could do much with lchown and lchgrp unless permissions are screwed up (which is beyond control of an end user). In addition, there is no "sh2_exec" function...
