### ISSUE TITLE
Also link scaled inline image to full-size image

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#7360]
#### Description
When attaching an image to a post and showing it inline like [here](https://www.simplemachines.org/community/index.php?msg=4101355), the inline image might be scaled down, and it may be hard to make out details. It's quite the oddity to me (like I commented in that thread) that you can't click the inline image to show it in full size anymore (I still have a 2.1 RC 2 install and it behaves like that, at least when "also show the attachment below the post if it is already embedded" is OFF, so the image only shows up once).
With the SMorg settings ("also show the attachment below the post if it is already embedded" is ON) you can still click on the thumbnail below the post to see the image in full size, but I believe many people will not notice. I propose to (again?) also link the inline image to the full-size version.

### Steps to reproduce
1. attach a large image and embed it
2. click on the scaled-down-to-forum-width embedded image, nothing happens
3. click on the thumbnail image, full-size attachment will open in a popup

### Environment (complete as necessary)
- Version/Git revision: Whatever SMorg is using
- Database Type: Whatever SMorg is using
- Database Version: Whatever SMorg is using
- PHP Version: Whatever SMorg is using

### Additional information/references

**Comment by Sesquipedalian** [comment]
The ability to embedded image attachments using the [attach] BBC is meant to function the same way that embedding external images using the [img] BBC does. It is a different use case than a normal attachment. In the provided example, embedding the image was actually not a good fit for the author's purpose regarding it.

**Comment by m4z** [comment]
I'm not sure I understand. My point was that it is confusing to users that they can't increase the size of the "big" inline image and will assume that no bigger resolution is available. It is unexpected and surprising that clicking the smaller version has a different outcome. (AFAICT, even @BrickOzp fell for it in that thread.)

Since you say [attach] and [img] should work the same, I'm assuming that the latter doesn't resize images? Or what are you referring to?

Why was embedding not a good choice in that thread, and why would not embedding (or not attaching at all and using [img] instead?) have been the better choice? I'd say that embedding is always desirable (especially for screenshots) because it gives a bigger preview, and it is only confusing / a bad choice for the users _because_ that bigger preview isn't clickable.

**Comment by Sesquipedalian** [comment]
> Since you say [attach] and [img] should work the same, I'm assuming that the latter doesn't resize images?

Correct.

> Why was embedding not a good choice in that thread [...] ?

The difference between an embedded image vs. an attached image is the difference between content that is integral to the meaning of the post itself vs. content that is related to but distinct from the meaning of the post itself.

The easiest way to see the difference would be to flip the scenario around for moment. Consider the smiley images. It would be stupid to attach those to the bottom of a post. Why? Because it matters _where_ in the post the smiley image appears. The meaning of the image affects and is affected by the surrounding context. Just appending the smiley image to the bottom of the post would not communicate the same thing.

Going back to the uploaded images, the same consideration applies. If the uploaded image needs to appear at a particular point in the text in order to communicate the intended meaning, then it should be embedded at that point. But if the meaning of the image is not integrally tied to any particular piece of the text—or to say the same thing another way, if the meaning of the text doesn't depend on the image appearing at a particular point within it—then the image is a separate piece of communication, and should be attached rather than embedded.

Make sense?

**Comment by m4z** [comment]
Yes, ok.

But even if the example doesn't fit, I think we're confusing our users.
Assume an image had been embedded "correctly", that the location at a point in the post is relevant (whether as an [img] with explicit width and height to make it fit the screen, or as an autoscaled embedded attachment).

1. Why is it not clickable, to show the full size? To me, this is a basic browser feature; every browser I know toggles between full size and fit-to-something when you open an image directly.
2. And why, if resizing the inline image doesn't work, would a user expect something different from the thumbnail below the post than to receive the bigger-than-the-thumbnail-but-still-too-small embedded image?

**Comment by Sesquipedalian** [comment]
> 1. Why is it not clickable, to show the full size? To me, this is a basic browser feature; every browser I know toggles between full size and fit-to-something when you open an image directly.

Embedded image attachments behave exactly like external images embedded using the [img] BBC. If you click on an image embedded using [img], it doesn't resize.

> 2. And why, if resizing the inline image doesn't work, would a user expect something different from the thumbnail below the post than to receive the bigger-than-the-thumbnail-but-still-too-small embedded image?

Why wouldn't they?
