### ISSUE TITLE
Compressed output in PHP 8.0.17 or 8.1.4 breaks attachments

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#7395]
#### Description
Not sure if there's anything we can do about this, but tracking this here so it doesn't get lost. PHP 8.0.17 and 8.1.4 include a fix for a zlib bug, but the fix breaks attachments when compressed output is enabled. See https://github.com/php/php-src/issues/8218 for more and https://github.com/php/php-src/issues/7953 for the original issue that was patched.

### Steps to reproduce
1. Install SMF on a server with PHP 8.0.17 or 8.1.4 and enable compressed output.
2. Attach an image to a post.

### Environment (complete as necessary)
- PHP Version: 8.0.17 or 8.1.4

**Comment by Sesquipedalian** [comment]
Well, doesn't that just suck?

**Comment by jdarwood007** [comment]
I've been meaning to get a env going with this since my current one is following a package maintainer version.

The bad part is these versions are currently the latest versions of their respective branches.  So anyone building from scratch for those branches, will most likely be getting those versions.  I am a bit confused as to why the original issue that caused the output handling issue was not traced back to see if it was from a recent change or not.  The report only said 8.0.10 had the issue, but not if it worked in 8.0.9.  Thus indicating a change occurred that broke the functionality.  Which means this patch while it fixed that issue, caused another and didn't track the root cause. 

From what i can tell in those discussions, a fix may be just to add the call to remove the header in our download attachment logic.  Which while weird, would get it fixed until PHP has released a proper fix that doesn't muck around with headers when it didn't need to before.

**Comment by Sesquipedalian** [comment]
> From what i can tell in those discussions, a fix may be just to add the call to remove the header in our download attachment logic. Which while weird, would get it fixed until PHP has released a proper fix that doesn't muck around with headers when it didn't need to before.

That seems to have worked, but testing by others is needed to confirm: #7400
