### ISSUE TITLE
Permission allowance regarding post based groups

### ISSUE THREAD

**Issue by Underdog-01** [SimpleMachines/SMF#7588]
#### Description
Note: This report may not be limited to this specific scenario & may be a general permission problem.

When using post based groups, members that belong to a membergroup that don't have permission to edit their profile can still do so. This includes everything available in the edit profile template.   

### Steps to reproduce
1. Create a new localhost forum using SMF 2.1.2 stable or current SMF 2.1.3 GitHub.
2. Set it up to use post based membergroup permissions.
3. Rename "Newbie" to something unique (ie. Neophyte)
4. Ensure Neophyte (Newbie) membergroup is set to use unique permissions (this is default)
5. Modify Neophyte (Newbie) permission profile & allow the following:   access to the single default board (General Discussion), View forum statistics, Search for posts and topics, Read personal messages & Select an avatar from the server. (leave everything else unchecked) 
6. Register a new member (manually or use the regular process via localhost url)
7. Log in as that new member
8. Edit profile:  upload an avatar, add a signature with a link, add a website & its link, etc. 

### Environment (complete as necessary)
- SMF Version: SMF 2.1.2 (stable) / SMF 2.1.3 (current GitHub)
- Database Type: MySQL
- Database Version: 8.0.30
- PHP Version: 8.1.3

### Additional information/references
For that post based membergroup only one single permission is given in this scenario to allow the user to pick an avatar from the forum gallery. No other user profile permissions are given for this new user post based membergroup, yet they can still edit all their profile options at any time.

**Comment by DiegoAndresCortes** [comment]
What about 'Regular Members' group? They are always part of it, so you'd need to remove the permissions from there too. Post groups are 'added permissions'.

**Comment by Underdog-01** [comment]
What about this setting:
Inherit permissions:
Select "No" to enable group to have own permission set.

.. it's set to No - Use unique permissions

Regular members pops up in the drop down for its option to inherit permissions but in this scenario it's set not to inherit any permissions.

**Comment by Sesquipedalian** [comment]
You misunderstand how "Inherit permissions" works. It means that the inheriting group uses the exact same set of permissions as the group that is inherited from. It's a convenience feature so that the admin doesn't need to go to each group individually and set the same permissions for each one.

"Inherit permissions" does not affect SMF's additive method of handling permissions. Since all registered members are part of the Regular Members group, all members have whatever permissions have been granted to the Regular Members group—that is, unless you have enabled the option to deny permissions, in which case you can take away permissions from certain groups that they would have otherwise.

It sounds like you are trying to figure out how to give everyone except the Newbie group (or Neophyte or whatever you want to change it to). You should ask for assistance on the SMF 2.1 Support board; someone on the Support team will be happy to help you out.

**Comment by Underdog-01** [comment]
I find it odd that when unique permissions are opted it shows options to disable/enable profile permissions for that group yet from what you just stated it would seem they have no effect. So why are they displayed as options in that scenario?

**Comment by DiegoAndresCortes** [comment]
That's how it's described in the setting: _Enabling permissions for groups based on post count will allow you to attribute permissions to members that have posted a certain amount of messages. The permissions of the post count based groups are **added** to the permissions of the **regular membergroups**._

And users are always in the group of Regular Members (0)

**Comment by Sesquipedalian** [comment]
I think the issue here is simply that the labeling and documentation for the permissions system could be improved. 

In particular, it might be better to use "Granted" and "Not granted" instead of the current "Allowed" and "Disallowed" labels. In normal English usage, to disallow something means to reject or forbid it. If I say that something is disallowed, I am not merely saying that permission has not been explicitly granted; rather, I am saying that permission has been explicitly denied. So if we use a more neutral term like "not granted," people might find it easier to understand how the permissions system works.

**Comment by Underdog-01** [comment]
Thanks for letting me know the specifics and I will post in the forum as suggested next time.

I haven't adjusted my permission settings just yet but I gather the profile permissions have to be denied in the regular members group & then allowed in all other groups less the one I want to deny those permissions. It's too bad there wasn't a "deny" or  "disallow" radio button for each permission in the post count groups.

**Comment by Sesquipedalian** [comment]
> It's too bad there wasn't a "deny" or "disallow" radio button for each permission in the post count groups.

There is if you go to Administration Center ► Permissions ► Settings and turn on the option called "Enable the option to deny permissions." Once you do that, you will see three options for each permission, Allowed, Disallowed, and Denied. The first grants the permission, the second doesn't grant it (but won't take it away if the member is also part of some other group that does grant it), while the third will take it away even if the member would otherwise have it.

**Comment by Underdog-01** [comment]
Doh?!

I suppose I wasn't focused on that checkbox when I opted post based groups.

Thanks!
