### ISSUE TITLE
Defaults are still not what the condition expects?

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#7594]
From #7424

In this case, I was testing with db_change_column function and MySQL.
If you send `default => ''`

This line
https://github.com/SimpleMachines/SMF/blob/aa2f168c69e5286222bae88a11c36edd3ce9368f/Sources/DbPackages-mysql.php#L464

Will return the following: `"''",` which is not the same that is expected below:
https://github.com/SimpleMachines/SMF/blob/aa2f168c69e5286222bae88a11c36edd3ce9368f/Sources/DbPackages-mysql.php#L473

This causes the query to fail when changing a column with a primary key. If the column is **auto**, it doesn't have an empty value, which brings up the same issue as above because it will get that assigned and attempt to set a `DEFAULT ''`, which fails.

**Comment by jdarwood007** [comment]
Maybe we should check that default would not be a empty string?  We can't use empty so it would be a literal check like 

```
$default  = $smcFunc['db_escape_string']($column_info['default']) != '' ? ('\'' . $smcFunc['db_escape_string']($column_info['default']) . '\'') : '';
```
A default with a empty string should be possible though.  So we should be able to produce:
`DEFAULT ''`

**Comment by DiegoAndresCortes** [comment]
Need to also consider if it’s auto (if I recall correctly), that can’t receive any default when using the change function, or it fails.

The additional issue with the change function is that when you didn’t send a default, it will append `'default' => ''`.
Hope that makes sense, I’ll add more details.

**Comment by sbulen** [comment]
You're trying to change a pk to default to ''?  That doesn't make sense to me...  

Can you send example code that's failing so we can reproduce?

I'd want to see the exact code that's failing.

**Comment by DiegoAndresCortes** [comment]
That's exactly the _other_ issue, **I'm not trying to**, but the code adds a default value because I didn't set one.
https://github.com/SimpleMachines/SMF/blob/aa2f168c69e5286222bae88a11c36edd3ce9368f/Sources/DbPackages-mysql.php#L439-L440

And this leads again to `DEFAULT ''`, which is not valid if the column is not supposed to have a default value.

**Comment by sbulen** [comment]
> 
> Can you send example code that's failing so we can reproduce?
> 
> I'd want to see the exact code that's failing.

**Comment by sbulen** [comment]
Or a particular mod install that's failing?

**Comment by DiegoAndresCortes** [comment]
```
$smcFunc['db_change_column'](
					'{db_prefix}postprefixes',
					'id',
					[
						'type' => 'smallint',
						'size' => 5,
						'auto' => true,
						'not_null' => true,
						'unsigned' => true,
					]
				);
```

It's from an upgrade script.
As you can see, no default value, because it's not supposed to have one.

And here:
https://github.com/SimpleMachines/SMF/blob/aa2f168c69e5286222bae88a11c36edd3ce9368f/Sources/DbPackages-mysql.php#L439-L440

It will set the 'supposed' old default value, which is `''`.
And thus, the code below:

https://github.com/SimpleMachines/SMF/blob/aa2f168c69e5286222bae88a11c36edd3ce9368f/Sources/DbPackages-mysql.php#L473
Makes it fail, because of this:
https://github.com/SimpleMachines/SMF/blob/aa2f168c69e5286222bae88a11c36edd3ce9368f/Sources/DbPackages-mysql.php#L464


> Or a particular mod install that's failing?

It always happens.

**Comment by sbulen** [comment]
By "It always happens", are you saying you cannot install any mod in 2.1.3?

Or is this specific to upgrade scripts?

I'm trying to determine scope/seriousness....

**Comment by DiegoAndresCortes** [comment]
No it';s not serious.
I mean it always happens when you run into the specific scenarios using those functions.

This definitely always fails in both functions (4 if we include PG I guess)
https://github.com/SimpleMachines/SMF/blob/aa2f168c69e5286222bae88a11c36edd3ce9368f/Sources/DbPackages-mysql.php#L464
Because that's not actually `DEFAULT ''`, but rather `DEFAULT "''"` as pointed out in the first post.
And so this condition will be false:
https://github.com/SimpleMachines/SMF/blob/aa2f168c69e5286222bae88a11c36edd3ce9368f/Sources/DbPackages-mysql.php#L473

So essentially we have 2 issues in here:
- The condition not returning the correct value
- The change functions always adding a default value even if the column is not supposed to have one.

**Comment by sbulen** [comment]
In the first issue, were you trying to remove an existing default?  Or did it not have one prior?

**Comment by DiegoAndresCortes** [comment]
Didn't have one because it's an auto, and didn't want to add one.

**Comment by jdarwood007** [comment]
Maybe we should ensure that for 'auto', we do not specify any defaults.

**Comment by sbulen** [comment]
I'm getting a completely different error....  😆
`All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead`

Two scripts - one to do the initial setup (which ran perfectly):
```
<?php

global $smcFunc;

if (!isset($smcFunc['db_create_table']))
	db_extend('packages');

$create_tables = array(
	'a_diego_record' => array(
		'columns' => array(
		    array(
				'name' => 'id_atest',
				'type' => 'INT',
				'auto' => true,
			),
		    array(
				'name' => 'atest_col',
				'type' => 'VARCHAR',
				'size' => 25,
				'default' => 'old default',
				'null' => true,
			),
		),
		'indexes' => array(
			array(
				'type' => 'primary',
				'columns' => array('id_atest'),
			),
		),
	),
);

foreach ($create_tables AS $table_name => $data)
	$smcFunc['db_create_table']('{db_prefix}' . $table_name, $data['columns'], $data['indexes']);

```

And one to test Diego's two errors:
```
<?php

global $smcFunc;

if (!isset($smcFunc['db_create_table']))
	db_extend('packages');

$update_tables = array(
	'a_diego_record' => array(
		'id_atest' => array(
			'type' => 'smallint',
			'size' => 5,
			'auto' => true,
			'not_null' => true,
			'unsigned' => true,
		),
		'atest_col' => array(
			'type' => 'VARCHAR',
			'size' => 50,
		),
	),
);

foreach ($update_tables AS $table_name => $column)
	foreach ($column as $col_name => $col_info)
		$smcFunc['db_change_column']('{db_prefix}' . $table_name, $col_name, $col_info);

```

Like it's not honoring the not_null => true?

**Comment by sbulen** [comment]
Diego - are you testing 2.1.3?

What version of mysql?

Amy changes needed in the 2 scripts above?

Trying to reproduce the issues...  Get us all looking at the samebthing....

**Comment by DiegoAndresCortes** [comment]
Oh I got this too
` All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead`

I must've forgotten about it when testing the other outcomes.
I was using 2.1.3/gh with mysql 5.7 and pg 11

**Comment by DiegoAndresCortes** [comment]
In reality,  I think the null issue is not very relevant, it's caused by the function sending a default value regardless of you declaring it

**Comment by jdarwood007** [comment]
An auto can not have a default value.  There should be no default sent at all.

**Comment by sbulen** [comment]
Yes.  This is what is getting generated with the above code, and produces the error noted above:
```
ALTER TABLE smf_a_diego_record
CHANGE COLUMN `id_atest` `id_atest` smallint(5) unsigned NOT NULL DEFAULT NULL auto_increment 
```

**Comment by sbulen** [comment]
Stepping thru the code, my take is a bit different...  

The core problem is that db_list_columns does not distinguish between a default being unspecified, vs a default being NULL.  And those are two extremely different things...  

So...  What happens is you *always* have an entry returned for 'default', even if the column definition did not specify one or if it was set to DEFAULT NULL.  In both instances, the value returned by db_list_columns is null.  

So...  array_key_exists always returns true for the 'default' attribute for pks...  Always,...  So, you will ALWAYS get a 'DEFAULT NULL' set due to this check:
https://github.com/SimpleMachines/SMF/blob/aa2f168c69e5286222bae88a11c36edd3ce9368f/Sources/DbPackages-mysql.php#L459

This explains the DEFAULT NULL being specified on the pk.  

A related issue:  What if you need to remove a default?  That is not supported AT ALL today.  (The syntax is ALTER TABLE x ALTER COLUMN y DROP DEFAULT...).  

As Diego says, the good news is that the scope of the issue here is extremely narrow.  I don't think there is a lot of db_change_column out there.  And this will primarily affect updating pks, which will be a small subset of even that.

**Comment by sbulen** [comment]
Screenshot showing the above, which shows where the DEFAULT NULL came from on the auto column:

![image](https://user-images.githubusercontent.com/23568484/199879312-1f4ab242-4d13-4388-a47c-618a8383c9da.png)

**Comment by sbulen** [comment]
This is the questionable logic in list_columns:
https://github.com/SimpleMachines/SMF/blob/aa2f168c69e5286222bae88a11c36edd3ce9368f/Sources/DbPackages-mysql.php#L775

**Comment by sbulen** [comment]
The biggest question is how to distinguish between "not specified" and NULL going forward?

I see only two options: a text token, or not returning a value at all for the default attribute.

Earlier I had suggested a text token, but that was deemed too cheezy...  It might match someone's mod's actual default value, even if it's something like 'THIS IS UNSPECIFIED!!!!!!!!'....

The most accurate solution would be to not return a default attribute at all.  At that point, an array_key_exists check would actually work....

**Comment by jdarwood007** [comment]
[package-tests.zip](https://github.com/SimpleMachines/SMF/files/9938616/package-tests.zip)
These are the test files I made while testing the PR in question.  Do any of them still fail for you?

I've said it before, PHP has a bad implantation of null handling.  Easiest case to show is
```
$var = null;
var_dump(isset($var));
var_dump(is_null($var));

var_dump(isset($fake));
var_dump(is_null($fake));
```

As expected isset will return false on $var and true on  is_null.  But on the second test is_null will generate a PHP error.

https://3v4l.org/pA65c

**Comment by sbulen** [comment]
The problem here isn't PHP.  The problem here is that our code sets both to null, making them indistinguishable, in the line of code referenced above.  At that point, they are identical, when they shouldn't be.

It's like adding $fake = null; to your test above, then wondering why they both look the same...

**Comment by Sesquipedalian** [comment]
Yeah, PHP is weird on this. But here's a simple workaround:

```
if (compact('var_name') === array())
    echo '$var_name is not a declared variable';
```

**Comment by sbulen** [comment]
Looking at the code & doing some tests, there are a few inconsistencies that bother me.  

In general, it attempts to reuse attributes specified earlier, so you don't have to re-specify them when modifying the column.  E.g., if your column definition initially had a DEFAULT, but your updates do not specify a DEFAULT, the earlier DEFAULT is carried forward.  So your modify column requests do not need to specify all attributes, only what changed.  

But what if you want to remove a default?  It is impossible to do so, because the prior value is always carried forward &, further, there is no logic in there for issuing a DROP default in the mysql code.

OTOH...  On the pg side, if there is no DEFAULT specified, it attempts to detect this & issue a DROP DEFAULT...  So the behavior on mysql vs pg is very different.  It doesn't honor the 'carry forward what's not overridden' rule otherwise followed throughout.  We need to ensure the same requests produce the same results across mysql & pg.

I don't think a lot of changes are needed:
 - Properly distinguish between NULL and not-specified defaults in db_list_columns
 - Honor the 'carry forward what's not overridden' rule consistently
 - Add explicit support for dropping defaults (a new 'drop_default' option)

**Comment by albertlast** [comment]
from my understanding,
smf was never build around to handle null,
so only in special cases like inet fields is null handle correctly.

**Comment by albertlast** [comment]
the mention issue of the start i geuss would be already fix by the pr: https://github.com/SimpleMachines/SMF/pull/5180
