### ISSUE TITLE
3rd level dropdown broken in chrome

### ISSUE THREAD

**Issue by eurich** [SimpleMachines/SMF#76]
the third level dropdown menu is currently broken (FF seems OK, Chrome is broken)..

**Comment by Spuds** [comment]
I know we had a problem in penguin, as well as in an upcoming curve refresh where the 3rd level was getting clipped

That is caused by the global declaration on div elements of  box-sizing: border-box; .  

The current direction will be to only declare the box-sizing on targeted divs  You can also mask the problem by changing the menu animation in superfish from animation : {opacity:'show', height:'show'}  to animation : {opacity:'show'}  ... so its some jQuery animation effect in conjunction with the box-sizing (in chrome/ie/etc ... FF is fine) that causes that issue.

**Comment by emanuele45** [comment]
My fault...I did the merge looking only at the PR title ("remove Penguin") without notice the other two commits...
Sorry... :-[ (and that's also the reason I slowed down merging all the other PRs: I have to manually merge all of them because of the changes to the template...will take a while)

**Comment by Spuds** [comment]
You trusted Ant's first merge request :P

**Comment by eurich** [comment]
btw, penguin wasn't fully removed, the folder named penguin and the index.template.php is still there (at least in my local copy)..
