### ISSUE TITLE
Unlimited attachments causes false warnings to user

### ISSUE THREAD

**Issue by LexArma** [SimpleMachines/SMF#7682]
Admin - Forum - Attachments and Avatars - Attachment Settings

Setting Max number of attachments per post to 0 for unlimited causes an error message "You have reached the maximum number of attachments allowed per post." to show in the attachments -section of post editor. 

Tested on 2.1.3

![Reached the maximum](https://user-images.githubusercontent.com/39050447/216757910-f4e73eb6-1a29-4dfe-b542-31d80290d6a8.png)

**Comment by Sesquipedalian** [comment]
The issue seems to have been introduced in #7498, specifically [here](https://github.com/SimpleMachines/SMF/pull/7498/files#diff-54cf63ea3db0bdae7ddfa518c062b25b45825c2edea5ad441573dbbfbfb3d7cd).

Since I have already been working on the attachments UI in #7676, I'll add a quick fix for this issue in that PR.
