### ISSUE TITLE
Permissions issue creating admin-only boards

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7689]
#### Description
Removing all permissions groups should create an admin-only board.  But the board remains visible on the board index.  Note you cannot access the board, but it is visible.

Note also that if you assign a group permission to that board, and subsequently remove it, it behaves properly & is no longer visible on the board index...  

### Steps to reproduce
1. Remove all permissions for a board, including guests.
2. Logout & access the board index as a guest.  

### Environment (complete as necessary)
- Version/Git revision: Current GH
- Database Type: MySQL
- Database Version: 8.0
- PHP Version: 8.1

### Additional information/references
From the forum:
https://www.simplemachines.org/community/index.php?topic=585181.0

**Comment by DiegoAndresCortes** [comment]
I tested it and whenever the board is saved, it inserts/updates two rows to board_permissions_view 
One of them includes -1 in the id_group, which causes this and shouldn't be happening.

Found the issue here: https://github.com/SimpleMachines/SMF/blob/6060f363db575314b4c59a9a20485a1081439fbb/Sources/Subs-Boards.php#L904

Came from this PR: #4727

**Comment by DiegoAndresCortes** [comment]
Note that modifying the board will update it to -1 when no groups are selected.
This one I couldn't figure out why it happens, yet.

**Comment by DiegoAndresCortes** [comment]
Okay I was able to reproduce both consistently.
 
1. Nothing changes, same as the first comment, adding a new board will trigger it due to the already mentioned PR: #4727 because it includes _-1_ in the groups.
2. Save a board allowing guests to see it, Edit > uncheck guests > It sends back _-1_ again. **Happens only with guests as the single group**

**Comment by DiegoAndresCortes** [comment]
I think **2** might be a different bug.
https://github.com/SimpleMachines/SMF/blob/6060f363db575314b4c59a9a20485a1081439fbb/Sources/Subs-Boards.php#L667

If you had groups selected, and then come back and clear them, they will not be removed from the table because the condition is not met.

**Comment by albertlast** [comment]
The #4727 didn't introduce this,
this logic came from initial commit into github
https://github.com/SimpleMachines/SMF/blob/a18e888838460a816fdbc2703e7e05ce7f626c91/Sources/Subs-Boards.php#L776
