### ISSUE TITLE
Cron check doesn't work properly

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#7696]
#### Description
There is a check, based on `cron_is_real_cron` to verify that cron.php is being triggered by some external trigger, and this check uses the scheduled tasks table to verify if there are any late running tasks (more than 1 day old).

But cron.php doesn't trigger any of the scheduled tasks handling, nor clearing the mail queue that I can see.

### Environment (complete as necessary)
- Version/Git revision: 2.1.3
- Database Type: n/a
- Database Version: n/a
- PHP Version: n/a

### Additional information/references

cron.php probably should explicitly trigger the scheduled tasks routine and the mail queue routine if there is nothing else for it to do in its alloted time period. It's currently only checking the background tasks queue, which is as I intended it to do originally.

**Comment by Sesquipedalian** [comment]
Derp. Yes, you're right. I must have had a brain fart when I wrote that code.

> cron.php probably should explicitly trigger the scheduled tasks routine and the mail queue routine if there is nothing else for it to do in its alloted time period.

That would make sense for many reasons, yes. However, for it to serve as a solution for this issue, we'd need to take it a step farther and make cron.php the _only_ way to trigger scheduled tasks. Otherwise, any way of triggering the AutoTask() function will make it seem like cron is running even if it is not.

**Comment by Sesquipedalian** [comment]
I've developed two alternative solutions for this issue. I think that #7698 is the better one, but I've offered both alternatives for consideration.

**Comment by nc3man** [comment]
With this update, presumably to appear in 2.1.4, does the cron.php update also include flushing the mail queue as Arantor also suggested? Since that seems to be triggered only by page loads, the only way to ensure pages are loaded regularly for low volume forums would be to put a wget or curl call to the smf home page in the crontab.

**Comment by Sesquipedalian** [comment]
#7698 does. #7697 does not.

Also, it is generally better not to presume anything until the dev team assigns this issue to a milestone.

**Comment by Arantor** [comment]
I prefer 7698 as the better solution to this problem, FWIW.
