### ISSUE TITLE
MySQL engine fallback support

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#772]
Right now the installer just shoves everything as MyISAM for MySQL.

What we should be doing is having it able to figure out what engines are available and use the best engine for a given table. Some tables will work best with MEMORY, some with InnoDB, and a few might work better with MyISAM but it's unlikely.

We should be querying for available engine types and setting some variable indicating what we can do, and then using that later on.

This would also be necessary for Mantis issue 3807 (log_floodcontrol table should use MEMORY engine - well of course it should if it is available!)

**Comment by emanuele45** [comment]
Random note: I remember at least one ticket (in the helpdesk) where the user had to convert from InnoDB to MyISAM before the upgrade because otherwise the upgrade was not able to proceed.
No idea why (it may be the upgrade, it may be the specific server configuration, it may be bad luck), just something I've noticed.

I'm also not sure if it is the only case or if there is any other.

**Comment by Arantor** [comment]
I'm not so worried about upgrading; they will have whatever engine types they already have (and I'm not overly enthusiastic about just changing) but new installs should be able to take advantage of this.

**Comment by Oldiesmann** [comment]
The upgrader will still need to take advantage of this to some extent, at least for tables created during the upgrade (I'm fine with leaving existing tables alone).

**Comment by Arantor** [comment]
I'd argue the upgrader should just make it consistent with whatever else is already there.

**Comment by Oldiesmann** [comment]
I'm not following your logic here... If we decide that a table added in SMF 2.1 should have InnoDB by default, then that table should be InnoDB regardless of whether I'm installing 2.1 or upgrading from 2.0.

**Comment by Arantor** [comment]
Well, here's the thing.

2.0 has 60-odd tables, all of which are MyISAM by default.

2.1 has 60-odd tables, most of which will be better as InnoDB. A fresh install will have mostly that.

2.0 -> 2.1 will have 60-odd MyISAM tables and 3-4 InnoDB tables. This is not consistent, nor logical and to users will actually look like it's a bug.

I'm suggesting 2.1 fresh installs should be optimal, and 2.0 -> 2.1 should be whatever the 2.0 installer did originally because if the users haven't made the move to InnoDB themselves yet, it's not for us to pre-empt them. Especially as what you're talking about will force almost every upgrade to completely gut the database (and bearing in mind the 1.1 -> 2.0 installer pretty much does that anyway as it is)

**Comment by Oldiesmann** [comment]
After thinking about this a bit more, I'm thinking the best way to handle this is to modify the DatabasePopulation() function in install.php as follows if db_type is mysql or mysqli:
1. Define a "$table_engines" array (table => preferred engine)
2. Define an array of available engines based on MySQL's "SHOW ENGINES" command.
3. Loop through $table_engines and set `$replaces['${' . $table . '_engine}']` to either the preferred engine or something else depending on what's available.

Then we modify the SQL files and use "ENGINE={$tablename_engine}" in place of "ENGINE=MyISAM" ("tablename" would be the name of the table that query creates since it's easier to do that than to try to pull the table name out of the query).

Do we have a list of which engine is preferred for which tables? Obviously most will be InnoDB, but before we set it up that way it'd be nice to have a good reference in case there are some instances when MEMORY or MyISAM might be best.

**Comment by Oldiesmann** [comment]
One more thing. I see in the "Twenty-four things you can do to make SMF go faster" topic that at the time it was recommended you set innodb_buffer_pool_size to at least 64MB as the default size at the time (8MB) wasn't big enough. According to the MySQL manual, this was increased to 128MB as of 5.1.28. Is this something we should take into consideration, or is 5.1.27 sufficiently old enough that it's not something we should worry about?

**Comment by Oldiesmann** [comment]
Looking back through old issues, this is something I'd like to try and tackle for Beta 2.

Do we have a list of which tables should be InnoDB vs MyISAM, or should I just go from the "24 things" topic mentioned in my last comment?

Also, per my last comment, should we take the innodb_buffer_pool_size into account, or is it safe to assume that most people will be using 5.1.28 or newer by now? Officially, the minimum version for 2.1 is 5.0.3.

**Comment by Arantor** [comment]
The 24 things topic still presumes the old ordering setup for the boards table which ISTR was rewritten.

Most tables can be InnoDB these days; I can't think of any that would make a significant benefit on being MyISAM over being on InnoDB - while I can make a very compelling case for using InnoDB on any table that has more than a trivial write cycle.

**Comment by Oldiesmann** [comment]
Ok. so just assume everything should be InnoDB by default? What about the ones that the topoic suggests making memory instead?

**Comment by Arantor** [comment]
Well... the ones that are suggested to be memory would be good to be memory tables since they're not long term persistent data. Everything else should be safe to move to InnoDB - assuming the ordering issues with custom fields, spider support and board ordering has been dealt with (which ISTR it has now)

As a side note, it would be useful to provide this sort of support in things like MySQL's db_create_table syntax in some fashion since I have encountered cases where I specifically wanted certain types of tables in the past.
