### ISSUE TITLE
Hardcoded string "Salvaged board"

### ISSUE THREAD

**Issue by realdigger** [SimpleMachines/SMF#779]
There is a hardcoded string "Salvaged board" in the RepairBoards.php file.

**Comment by MissAllSunday** [comment]
mmm, interesting, createSalvageArea() uses $txt['salvaged_board_name'] which is "Salvaged Topics" I suppose we could add something for Salvaged board, I'm just confused, theres a comment in createSalvageArea() that suggest $txt['salvaged_board_name'] should be "Salvaged board" but since the board that function is creating is for messages without topics and not topics without boards then is correctly using $txt['salvaged_board_name'] although the key name doesn't really help that much.

**Comment by Oldiesmann** [comment]
Using $txt['salvaged_board_name'] would be best in my opinion.
