### ISSUE TITLE
Should ignore Sources/Unicode/*

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7857]
#### Description
Because files in Sources/Unicode/* can be updated, these should be included in .gitignore.  The files still can be forcefully updated if needed.  If this isn't possible, we should look at another option for this.

**Comment by Sesquipedalian** [comment]
Or we can simply update the Unicode data files in the repository itself. I don't believe they have been updated since Unicode 15.1 was released in September.

**Comment by Sesquipedalian** [comment]
Or both, I suppose.

**Comment by jdarwood007** [comment]
The problem arises if these get included accidentally in PRs.  In multiple PRs it can cause conflicts, devs have to ensure to exclude these files.  We can update them, maybe even automate that if possible to do a PR opening (Does Unicode/CLDR have a dependency workflow on GH?)  This same issue will arise with stable and how we update those files with patches.

**Comment by Sesquipedalian** [comment]
> The problem arises if these get included accidentally in PRs.  In multiple PRs it can cause conflicts, devs have to ensure to exclude these files.  We can update them, maybe even automate that if possible to do a PR opening (Does Unicode/CLDR have a dependency workflow on GH?)  This same issue will arise with stable and how we update those files with patches.

I understand the problem. I've submitted a PR to add the Unicode data files (but not Sources/Unicode/Utf8String.php) to .gitignore.

I'm not sure if there is an existing dependency workflow we could tap into. I'm personally not too stressed about that, though, for two reasons. 

- First, the Unicode Consortium has made it their habit for years now to release annually in September. It's not a hard and fast rule (presumably so that they can make an emergency, off-schedule release if they need to), but they haven't varied from it in a long time. So it's only a concern once per year.

- Second, updating the Unicode data is part of the checklist for the release process for every update, so we will never release an install or upgrade package that is bundled with outdated Unicode data.
