### ISSUE TITLE
Searching causes errors

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#7877]
#### Description
I created a large custom search index on my test board (which currently has all of 3 topics and posts), then tried searching, which in turn led to this error:
![image](https://github.com/SimpleMachines/SMF/assets/89023/c9f53728-4820-4cd5-bda8-6196c1d05e90)

I also got a completely different error while searching for something else:
![image](https://github.com/SimpleMachines/SMF/assets/89023/2f625e5b-174a-4154-b21d-2d16ca6d4aaa)

### Steps to reproduce
1. Create a custom search index
2. Try searching for something

### Environment (complete as necessary)
- Version/Git revision: 3.1 Alpha (current as of sometime yesterday afternoon)
- Database Type: MariaDB
- Database Version: 11.1.2
- PHP Version: 8.2.11

### Additional information/references
I have a topic with the subject of "Poll" (created while debugging the poll issue yesterday), but no posts have that text
Welcome should return the "Welcome to SMF" post. This also generates an error about an undefined array index.

**Comment by Oldiesmann** [comment]
So there are two issues here...

First issue is line 318 of Sources/Search/SearchResult.php:
`		$output = array_merge(SearchApi::$loadedApi->results[$this->id_msg], array(`

There is nothing defining `SearchApi::$loadedApi->results[$this->id_msg]` - the results object is an empty array the first time the function is called. However, I'm not sure why we're using the message ID as the key rather than the topic ID. If you define `SearchApi::$loadedApi->results[$this->id_msg]` as an empty array prior to the function call (or just eliminate the array key in that line), the first error goes away and we get a search result.

The other error is because the post that would be returned by that search was made by a guest, so there is no entry in the members table matching the poster ID, but we don't have any checks in place to handle that.

Also, I discovered a third issue - it says that there were no results even when there are (when I fix the first issue it shows the search result after saying there weren't any).

**Comment by jdarwood007** [comment]
Ran out of time to figure out the first part.

The issue is because SearchResult.php getNumResults() is detecting that `self::$messages_request` is null and thus triggering the 0 return.

The message request is setup in the `intSearchContext` in Search2.php.  Specifically calling `SearchResult::get($this->messages)` should be loading this.  I'm not certain why.  I can't even get it to trigger any debug output unless I remove the yield.  I'm new to yield in PHP, so I may have to let somebody else look more into that.

**Comment by Oldiesmann** [comment]
I can't reproduce it on my server either - only on my local test install in Windows. There are some minor differences between the two environments (different PHP extensions and the server has MariaDB 10.6.12 rather than 11.1.2), but I'm not sure why that would make a difference in how things operate. I've also enabled xdebug on my server so I can at least get nice stack traces there as well (that's what generated the ones shown in the screenshot above)

**Comment by jdarwood007** [comment]
@Sesquipedalian There was a part 2 to this bug I didn't see until after I sent up the initial PR.  Difficult to trigger.  I could only trigger it when I had a search result of 1 post.  But it would throw a error.  My previous comment mentions its coming from getNumResults() encountering a null from self::$messages_request.

**Comment by jdarwood007** [comment]
Thanks.  Are you able to reproduce as well?  I need a course on getters in PHP to figure out if anything can be done.  We call the getter and set it in context, but PHP doesn't do anything yet until we start the looping.  Which means the number of results can not be obtained that early in the logic.  Since the loop occurs in the template, I don't think there is a way to avoid that.

My only logical conclusion then is we need to split the logic up, so we can call and set the `self::$messages_request` earlier.  I was then thinking, why are we getting the number of results this way.  I didn't get into drilling into the logic to understand why, just more concerned that could this give us paginated results or the fact that we only check after if the result is visible to the user.  Which again would change the number of results then once actually computed.  Again, still need to drill into the logic to fully understand it.

**Comment by Sesquipedalian** [comment]
I will need to look into it more deeply myself first.

**Comment by Sesquipedalian** [comment]
> I need a course on getters in PHP to figure out if anything can be done.

Regarding this part, am I correct to assume that you mean generators, of which `SearchResult::get()` is an example? If so, they're not too hard to understand. The PHP manual gives a nice [overview](https://www.php.net/manual/en/language.generators.overview.php) of how they work.

If you remember the `prepareDisplayContext()` function from SMF 2.1, that was basically a poor man's generator. Every time it was called, it would retrieve the data for one post, prepare that data for display, and then return that single post's data. This meant that it didn't have to load all the data for all the posts into memory all at once.

A generator function works quite similarly, and provides similar benefits in terms of keeping memory usage down. It's written as a function, and it is called iteratively in order to get a series of values, but only one of those values exists in memory at a time.

**Comment by jdarwood007** [comment]
Yea I meant generator, I was calling it a getter.  What I mean on a course is even though you called the function directly, it doesn't execute, because of yield.  So the calls to to load and set the query doesn't occur, then we use the number of results for providing page links.  I couldn't find information on how to get it to run everything in the function up to the yield then stop, until you activate the looping (with a foreach for example).  That would be ideal here, so then the logic for number of results works and you can do the paging.  I need a deeper dive to ensure I'm not missing anything else about generators.

**Comment by Sesquipedalian** [comment]
Found the problem.

**Comment by Sesquipedalian** [comment]
> I couldn't find information on how to get it to run everything in the function up to the yield then stop, until you activate the looping (with a foreach for example).

The [Generator class's methods](https://www.php.net/manual/en/class.generator.php) give additional control beyond just looping with a foreach or whatever.
