### ISSUE TITLE
Subs-Compat cleanup

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7893]
#### Description
With 3.0, our min PHP version is 8.0..  Subs-Compat has some old functions that need cleaned up

mb_ord was added in 7.2, no backwards compat needed
mb_chr was added in 7.2, no backwards compat needed
idn_to_ascii was 5.3, but does require the ICU libraries
idn_to_utf8 was 5.3, but does require the ICU libraries
hash_equals was 5.6

I think we could look at removing the mb and hash_equals.  idn ones because they require icu libraries are still ones we may need to compat

**Comment by live627** [comment]
Which Apache does that even work with 🤣

**Comment by Sesquipedalian** [comment]
Yeah, we still need the idn_to_* ones. The others you mentioned can go.

**Comment by jdarwood007** [comment]
Do we need them for a reason?
Our installer/upgrader can report if these libraries are missing and inform them they are are required.
If not, this becomes something we document as a performance increase to ensure these libraries are enabled.

**Comment by Sesquipedalian** [comment]
The idn_to_* functions do need to be handled differently than the hash_equals and mb_* functions. 

The idn_to_* functions come from the intl extension, and a sizeable number of hosts don't have that extension enabled. Because of that, requiring the extension in order to install SMF would result in a sizeable number of potential users aborting the install and choosing different software. Combining that fact with the fact that the idn_to_* functions are only used in a few places means that providing backward compatibility functions is the best solution.

In contrast, the great majority hosts have the mbstring extension enabled (it has no external dependencies, so there's virtually never any reason not to enable it). That means that requiring the mbstring extension in order to install SMF is rarely ever going to be an issue. And since we use mb_* functions all over the place, requiring the extension during install makes sense; we really can't live without it.

**Comment by jdarwood007** [comment]
That is acceptable.  We document this as known to improve performance to include the intl/icu libraries to avoid using user-land functions which run slower than built in functions.
