### ISSUE TITLE
minor twitch - Advanced Profile fields tab selection order

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#803]
When adding a select box item or radio button in the advanced profile fields, tabbing through the selection options bounces to the default selected option radio button, but skips the unselected ones.

**Comment by Oldiesmann** [comment]
That's a browser thing. You can use the arrow keys to move between multiple radio buttons in a group. The tab just selects the first button in a group (a "group" is considered any number of radio buttons with the same "name"). The "checked" status of the button doesn't matter.

For instance:

``` html
<label for="radio1">1</label><input type="radio" name="radiogroup1" id="radio1" /><br />
<label for="radio2">2</label><input type="radio" name="radiogroup1" id="radio2" checked="checked" /><br />
<label for="radio3">3</label><input type="radio" name="radiogroup2" id="radio3" />
```

If you have this code and tab through it, the first "tab" will select the first radio button, while hitting tab again will select the 3rd radio button. Specifying a tabindex doesn't make any difference.

**Comment by Arantor** [comment]
http://stackoverflow.com/questions/14322564/can-you-tab-through-all-raido-buttons may also be useful.

**Comment by Kindred-999** [comment]
my experience with this says differently...

Create a new profile field, tell it radio button.
add 5 new fields (no text yet) and select one 
go back up to a previous field, do some edits, tab through the fields down to the raido button section.
tabbing as I type in the fields brings me to the subsequent text box for the radio button text...  until I hit the one radio button which has been selected...   at that point, the tab skips to the radio button rather than the next text field.

**Comment by Oldiesmann** [comment]
So it's a problem with the interface to create profile fields?

**Comment by Kindred-999** [comment]
yup....   Sorry, I thought that was clear for my original message.
Yes - this is  a minor twitch in the "create" or "edit" aadvanced profile fields.

**Comment by Arantor** [comment]
The tabindex order is really messed up here. Chrome 30 btw.

Switching to radio button first, and then playing around with tab, the tab index order goes:
- field type selectbox
- ? icon next to Options
- first option textbox
- second option textbox
- radio buttons to navigate up and down
- tab then takes you to whichever one is selected
- More link

More interestingly, this is actually not predicated by our code, at least not directly, there aren't any tabindex indicators that I can see - meaning that it's solely going off the order of selectable items. This is of course a smart move because the number of items is not set in stone at any time.

Perhaps this indicates we need to have the updateInputCodes() and addOptions() code also go and reset all the form elements' tabindexes.

**Comment by Arantor** [comment]
After doing some research, I'm not entirely convinced we have this wrong. The whole point of radio buttons is that they are a single entity of joined items, not separate items. That suggests that the tab index order (which we're not forcing anyway) is actually as expected and perhaps even as intended.

**Comment by Arantor** [comment]
Confirmed, this is acting as specification indicates as to how tabindexes are supposed to work. Thus, not actually a bug but as design and that should not be changed.
