### ISSUE TITLE
[2.1,2.0]:  Package Server Browse packages -  Unable to connect to the server. Please try using this URL instead.

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#8140]
### Basic Information

Can't seem to browse packages from the package server from the SMF  Customize Site 
Package Server Browse packages -  Unable to connect to the server. Please try using this URL instead.

### Steps to reproduce

Admin -> Package Server -> Download Packages -> " Simple Machines Third-party Mod Site"

### Expected result

A list of package categories

### Actual result

Error message:  Unable to connect to the server. Please try using this URL instead.

### Version/Git revision

2.1.14

### Database Engine

MySQL

### PHP Version

8,1

**Comment by Oldiesmann** [comment]
Works fine for me on my test site. Latest SMF 2.1 from GitHub, PHP 8.3.
![image](https://github.com/SimpleMachines/SMF/assets/89023/f5bebb54-57cd-41e8-acd9-6718bb370d6e)

**Comment by VBGAMER45** [comment]
Ok Thing I see what is going on. Looks like a cloudflare block/challenge strange it just popped on a few different servers of mine.
I pulled this up doing curl.

[cloudflareblockhtml.txt](https://github.com/SimpleMachines/SMF/files/14705338/cloudflareblockhtml.txt)

**Comment by jdarwood007** [comment]
@VBGAMER45, We set up some CF rules to deal with bot abuse, especially on our contact page.  I wonder if your system is hitting the throttling limit due to shared instances.  Mind sending me a PM or email with the IPs of some of your servers that are seeing this? I can look at the dashboard and see how to relax the rules. 
It also shouldn't send a challenge response for non HTML pages.  I suspect because the filename is missing in the URL, it can't detect that it should be a non html response.

**Comment by jdarwood007** [comment]
Don't need it, I found it.  The text file you provided had enough details to locate it.
Seems your server IP is registered in CF as a 'definite bots'.  Which means it 100% believes your server is malicious.  I added a rule which should fix it.  But you should look into that.

**Comment by VBGAMER45** [comment]
Thanks @jdarwood007 Will have to look at it, to see, don't do any crawling or anything from those servers. So will research.
