### ISSUE TITLE
Letter indicator on memberlist

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#846]

**Comment by Arantor** [comment]
As per http://dev.simplemachines.org/mantis/view.php?id=4532

It's actually inappropriate to highlight the individual letter selected because there's a better than average chance it'll be wrong.

Unless the letter in question takes you directly to a letter that starts at the top of the page, it's not accurate. For example, I went to [P] on sm.org today. The P entries started half way down the page. Since that's the case, I'm seeing half a page of O stuff, not necessarily the P stuff I actually asked for.

Unless we change the functionality of the member list to match, we definitely should not do that.

Now, of course, the argument can be made about the pagination working in an opposite fashion, because the pagination will always tell you what page you are on, but that's because in any case of pagination there is always a reasonable chance of you going through and moving between them.

If we want to leave it as is, that's fine. But if not, I have a proposal that would actually solve it either way. From the example given, I got both O and P items on the same page. Instead of displaying ...N O [P] Q R... on the list, we could always display ...N [O P] Q R... to indicate that we're currently showing part of both O and P.

Thoughts?

**Comment by Oldiesmann** [comment]
The memberlist has been that way since the beginning of SMF, though I never have understood why clicking on a letter doesn't at least jump to the first entry with that letter on the page (eg an anchor). I'm assuming the "don't display the first entry with that letter at the top of the page" thing is done for performance reasons.

I like your idea of showing multiple letters selected though.

**Comment by emanuele45** [comment]
>  though I never have understood why clicking on a letter doesn't at least jump to the first entry with that letter on the page (eg an anchor)

Probably because your browser is broken. :stuck_out_tongue:

**Comment by Arantor** [comment]
It does actually have an anchor. The problem is that the list is physically so short on the page that you never actually get scrolled very far at all.

**Comment by Xarcell** [comment]
I see nothing wrong with the way it is. In my opinion, if it was done any different, if a person clicked "P", it would load only those members that start with "P" and no others. However, it really wouldn't be worth the resource useage to add that. Perhaps in the admin, but not for everyone.

So I say leave as is. The anchor is good enough.

**Comment by Arantor** [comment]
Even though in most cases it won't actually be of any use whatsoever? Unless the names start in the top 1/3 of the list (maybe, depends on browser window size), it's just going to scroll to the bottom of the page which isn't really helpful.

Now, if we did as suggested and added avatars in there, I could see that being useful because the page would easily double in length. Though then I'd perhaps argue about changing up the content in it.

**Comment by Xarcell** [comment]
I've never really gave much thought to the member listing because I rarely use it. It's always full of people I don't know. So I've never really had a good reason to give it much attention.

So I'm thinking about it briefly now....

If I were to do the member listing, I wouldn't list things like contact information. I would list things like: avatar, online status, position, amount of time that the user has been a member(calculated, not just date registered), last seen on date, and current activity. Things such as gender, age/birthday, and contact info is considered personal and should not be shown in the memberlist. In fact, the user should have the option to show this information only to buddies; with the exception of the admin's & GM's of course. 

I would keep the horizontal layout. I wouldn't use boxes or a vertical layout like IPB. It's just a waste of space.

Just my 2 cents...

**Comment by Arantor** [comment]
If you're putting in the avatar you automatically force a larger row size than we have now. So if there's the avatar, we might as well embrace that fact and break away from a table like IPB and XF do since that's really all they're doing.

The privacy stuff is an interesting one and it sort of is covered already in the code. No argument to removing contact details for the most part.

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
