### ISSUE TITLE
WYSIWYG: missing features / bugs

### ISSUE THREAD

**Issue by eurich** [SimpleMachines/SMF#93]
the wysiwyg is nice in general but two features are IMHO important have been wiped out:
1) the button-status isn't updated anymore, thus you don't knwo the current selected formattings..
2) the toggle button to switch between wysiwyg and non-wysiwyg mode

**Comment by emanuele45** [comment]
1) https://github.com/samclarke/SCEditor/issues/25

2) it's there and is the same (and same place) as in SMF...at least here...did I forgot to add something?

**Comment by eurich** [comment]
2) yep, found it :P

**Comment by Trekkie101** [comment]
1. URLs added without http:// screw up.

**Comment by ChainyEO** [comment]
Is an old version of this SCEditor currently being used in SMF2.1? Just that the Button State still appears to be missing in the editor as used in SMF.

**Comment by Oldiesmann** [comment]
Looks like it. The comment at the beginning of jquery.sceditor.js says it's 1.3.7. I'll look into getting that updated soon.

@Spuds, is this something you can help us with?

**Comment by emanuele45** [comment]
The one in the branch master is usually the latest: SCEditor v1.4.3 (rather big on the first page of the repo :P).

That said 85% of the editor would work out of the box just copying the files, some more exotic (like...dunno the [nobbc][ol], [quote], [code][/nobbc]) requires some rewrites of the internals in order to work _properly_.

What I did the first time was to just edito the SCEditor "core" files, though this is not very cleaver because it then requires more maintenance in order to upgrade.

Spuds added another file with Elk/SMF specific code.

The only thing the most likely cannot be added extending the core is the ability to show the buttons on two lines, that requires a change that may not be worth copy just for that, but dunno.
