### ISSUE TITLE
$modSettings['enableErrorLogging'] == 2

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#949]

**Comment by Arantor** [comment]
It's a WTF and no mistake, dating back to 1.1.x... no idea why though.

**Comment by Arantor** [comment]
This is actually an interesting quasi-Easter egg. Forcing it to be 2 would force a stronger logging, every single fatal error as pushed by SMF should be logged even when explicitly marked as false to indicate no logging should be carried out.

That said, I'm not sure how useful it would be for debugging anyway, and I think it would be better to just remove the code in question because it's something that no-one would have known to use, it's not documented anywhere, and there are better ways for debugging anyway.
